const path=require("path");
const { test, expect } = require('../../helpers/isolatedBrowserTest')('attorney-accounts-real');
const { enterSecondaryDocument } = require('../secondary-document-entry');
const start=require(path.resolve(__dirname,"../../../../docs/audits/completion-2026-09-09/accounts/backend-browser-server.cjs"));
test.use({ baseURL: 'http://127.0.0.1:5281', storageState: { cookies: [], origins: [] } });
let server,owner;
test.beforeAll(async()=>{test.setTimeout(120000);server=await start({port:5281});});
test.afterAll(async()=>{await server?.close();});
test.beforeEach(async({context})=>{owner=await server.createUser({phoneNumber:"2125550100",firmWebsite:"https://example.test",languages:[{name:"English",proficiency:"Native"}],publications:["Existing publication"],practiceAreas:["Contracts"]});await context.addCookies([owner.cookie]);});
async function open(page,tab="",secondaryBaseURL){
 const target=`/attorney-v2.html#/settings${tab?`?tab=${tab}`:""}`;
 if(secondaryBaseURL)await enterSecondaryDocument(page,new URL(target,secondaryBaseURL).href);
 else await page.goto(target,{waitUntil:"domcontentloaded"});
 await expect(page.locator("html")).toHaveAttribute("data-attorney-state","ready");await expect(page.locator("[data-account-content]")).toHaveAttribute("aria-busy","false");
}
async function save(page){await page.getByRole("button",{name:"Save changes",exact:true}).click();await expect(page.getByText("Changes saved.",{exact:true})).toBeVisible();}
test("actual profile route persists professional fields and multiline copy without replacing untouched values",async({page})=>{
 await open(page);await page.getByLabel("Bar number",{exact:true}).fill("NY-9876");await page.getByLabel("Time zone",{exact:true}).selectOption("America/New_York");await page.getByLabel("Years of experience",{exact:true}).fill("9");await page.getByLabel("About your practice",{exact:true}).fill("First paragraph.\n\nSecond paragraph.");await page.getByLabel("Firm website",{exact:true}).fill("");await page.getByLabel("Role or position",{exact:true}).fill("Senior attorney");await page.getByLabel("Description",{exact:true}).fill("First responsibility.\nSecond responsibility.");await page.getByLabel("Language",{exact:true}).fill("Spanish");await page.getByLabel("Proficiency",{exact:true}).fill("Fluent");await save(page);
 const stored=await server.inspectUser(owner.id);expect(stored).toMatchObject({barNumber:"NY-9876",timezone:"America/New_York",yearsExperience:9,phoneNumber:"2125550100",bio:"First paragraph.\n\nSecond paragraph.",lawFirm:"Counsel Law"});expect(stored.experience[0]).toMatchObject({title:"Senior attorney",description:"First responsibility.\nSecond responsibility."});expect(stored.languages[0]).toMatchObject({name:"Spanish",proficiency:"Fluent"});
 await page.reload();await expect(page.getByLabel("Bar number",{exact:true})).toHaveValue("NY-9876");await expect(page.getByLabel("Firm website",{exact:true})).toHaveValue("");await expect(page.getByLabel("About your practice",{exact:true})).toHaveValue("First paragraph.\n\nSecond paragraph.");await page.getByRole("link",{name:"View public profile"}).click();await expect(page.getByText("First paragraph.\n\nSecond paragraph.",{exact:true})).toBeVisible();await expect(page.getByText("Senior attorney",{exact:true})).toBeVisible();await expect(page.getByText("NY-9876",{exact:true})).toHaveCount(0);
});
test("two actual sessions merge independent fields and explicitly resolve a stale same-field edit",async({page,context,baseURL})=>{
 await open(page);const second=await context.newPage();await open(second,"",baseURL);await page.getByLabel("Firm",{exact:true}).fill("First session firm");await second.getByLabel("Phone number",{exact:true}).fill("2025550123");await save(page);await save(second);expect(await server.inspectUser(owner.id)).toMatchObject({lawFirm:"First session firm",phoneNumber:"2025550123"});
 await page.getByLabel("About your practice",{exact:true}).fill("First session biography");await second.getByLabel("About your practice",{exact:true}).fill("Second session biography");await save(page);await second.getByRole("button",{name:"Save changes",exact:true}).click();await second.getByRole("button",{name:"Review latest values"}).click();await expect(second.getByText("Latest: First session biography",{exact:true})).toBeVisible();await second.getByLabel("Value to keep for About your practice").selectOption("mine");await second.getByRole("button",{name:"Apply choices"}).click();await save(second);expect((await server.inspectUser(owner.id)).bio).toBe("Second session biography");await second.close();
});
test("actual email mutation stages verification and preserves the active address and next-tab conflict",async({page},info)=>{
 await open(page);const original=(await server.inspectUser(owner.id)).email;await page.getByLabel("Email",{exact:true}).fill("proposed@example.test");await page.getByRole("button",{name:"Save changes",exact:true}).click();await expect(page.getByText("Changes saved. Verify your new email to finish changing it.",{exact:true})).toBeVisible();expect(await server.inspectUser(owner.id)).toMatchObject({email:original,pendingEmail:"proposed@example.test"});expect(server.mailSubjects().length).toBeGreaterThan(0);await page.reload();await expect(page.getByLabel("Email",{exact:true})).toHaveValue(original);await expect(page.getByText(/Confirm proposed@example.test/)).toBeVisible();
 await page.evaluate(()=>document.fonts.ready);await page.getByText("Confirm proposed@example.test to change your email.",{exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:info.outputPath("pending-email-confirmation.png"),fullPage:true});
 await page.getByLabel("Email",{exact:true}).fill("new-request@example.test");await server.updateUser(owner.id,{pendingEmail:"other-tab@example.test"});await page.getByRole("button",{name:"Save changes",exact:true}).click();await page.getByRole("button",{name:"Review latest values"}).click();await expect(page.getByText(/pending: other-tab@example.test/)).toBeVisible();expect((await server.inspectUser(owner.id)).pendingEmail).toBe("other-tab@example.test");
});
test("actual preference routes update only selected leaves and restore each saved result",async({page})=>{
 await open(page,"preferences");await page.getByLabel("Theme",{exact:true}).selectOption("dark");await expect(page.locator("html")).toHaveClass(/theme-dark/);await page.getByLabel("Text size",{exact:true}).selectOption("xl");await page.getByLabel("Email Matter updates",{exact:true}).uncheck();await expect.poll(async()=>{const user=await server.inspectUser(owner.id);return[user.preferences.fontSize,user.notificationPrefs.emailCase];}).toEqual(["xl",false]);const stored=await server.inspectUser(owner.id);expect(stored.preferences.theme).toBe("dark");expect(stored.notificationPrefs.emailMessages).toBe(true);await page.reload();await expect(page.getByLabel("Theme",{exact:true})).toHaveValue("dark");await expect(page.getByLabel("Text size",{exact:true})).toHaveValue("xl");await expect(page.getByLabel("Email Matter updates",{exact:true})).not.toBeChecked();
});
test("photo crop original and removal use actual protected bytes and guarded database state",async({page})=>{
 await open(page);const png=await page.evaluate(()=>{const canvas=document.createElement("canvas");canvas.width=700;canvas.height=450;const ctx=canvas.getContext("2d");ctx.fillStyle="#6495ED";ctx.fillRect(0,0,700,450);ctx.fillStyle="#182033";ctx.fillRect(350,0,350,450);return canvas.toDataURL("image/png").split(",")[1];});await page.getByLabel("Choose profile photo",{exact:true}).setInputFiles({name:"synthetic-portrait.png",mimeType:"image/png",buffer:Buffer.from(png,"base64")});await page.getByLabel("Zoom",{exact:true}).fill("1.5");await page.getByRole("button",{name:"Save photo",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await expect.poll(()=>page.getByRole("img",{name:"Your profile photo",exact:true}).evaluate(image=>image.naturalWidth)).toBe(600);expect((await server.inspectUser(owner.id)).profilePhotoStatus).toBe("approved");expect(server.objectKeys().filter(key=>key.includes(owner.id)).length).toBe(2);
 await page.getByRole("button",{name:"Edit crop",exact:true}).click();await expect(page.getByRole("dialog",{name:"Edit profile photo"})).toBeVisible();await page.getByLabel("Zoom",{exact:true}).fill("2");await page.getByRole("button",{name:"Save photo",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await page.getByRole("button",{name:"Remove photo",exact:true}).click();await page.getByRole("dialog").getByRole("button",{name:"Remove photo",exact:true}).click();await expect(page.getByRole("button",{name:"Add photo",exact:true})).toBeVisible();expect(await server.inspectUser(owner.id)).toMatchObject({profileImage:null,avatarURL:"",profilePhotoStatus:"unsubmitted"});
});
test("invalid and blank required entries remain editable and do not issue a profile mutation",async({page})=>{
 let writes=0;page.on("request",request=>{if(request.method()==="PATCH"&&new URL(request.url()).pathname==="/api/users/me")writes++;});await open(page);await page.getByLabel("First name",{exact:true}).fill("   ");await page.getByRole("button",{name:"Save changes",exact:true}).click();expect(writes).toBe(0);await page.getByLabel("First name",{exact:true}).fill("Avery");await page.getByLabel("Years of experience",{exact:true}).fill("81");await page.getByRole("button",{name:"Save changes",exact:true}).click();expect(writes).toBe(0);await expect(page.getByLabel("Years of experience",{exact:true})).toHaveValue("81");
});
test("changing the actual account after owner preflight cannot save into the replacement",async({page,context})=>{
 await open(page);const replacement=await server.createUser({firstName:"Replacement",lawFirm:"Untouched replacement"});let switched=false;await page.route("**/api/csrf",async route=>{if(!switched){switched=true;await context.addCookies([replacement.cookie]);}await route.continue();});await page.getByLabel("Firm",{exact:true}).fill("Old owner write");await page.getByRole("button",{name:"Save changes",exact:true}).click();await expect(page).toHaveURL(/login\.html|dashboard-attorney\.html/);expect((await server.inspectUser(owner.id)).lawFirm).toBe("Counsel Law");expect((await server.inspectUser(replacement.id)).lawFirm).toBe("Untouched replacement");
});
test("legacy practice description and practice-area aliases can be edited and explicitly cleared",async({page})=>{
 await server.updateUser(owner.id,{bio:"",about:"Legacy description",practiceAreas:[],specialties:["Legacy specialty"]});await open(page);await expect(page.getByLabel("About your practice",{exact:true})).toHaveValue("Legacy description");await expect(page.getByLabel("Practice areas",{exact:true})).toHaveValue("Legacy specialty");await page.getByLabel("Firm",{exact:true}).fill("Unrelated firm edit");await save(page);let profile=await(await page.request.get(`/api/users/me?expectedOwnerId=${owner.id}`)).json();expect(profile.about).toBe("Legacy description");expect(profile.specialties).toEqual(["Legacy specialty"]);
 await page.getByLabel("About your practice",{exact:true}).fill("");await page.getByLabel("Practice areas",{exact:true}).fill("");await save(page);profile=await(await page.request.get(`/api/users/me?expectedOwnerId=${owner.id}`)).json();expect(profile.bio).toBe("");expect(profile.about).toBe("");expect(profile.practiceAreas).toEqual([]);expect(profile.specialties).toEqual([]);await page.reload();await expect(page.getByLabel("About your practice",{exact:true})).toHaveValue("");await expect(page.getByLabel("Practice areas",{exact:true})).toHaveValue("");await page.getByRole("link",{name:"View public profile"}).click();await expect(page.getByText("Legacy description",{exact:true})).toHaveCount(0);await expect(page.getByText("Legacy specialty",{exact:true})).toHaveCount(0);
});
test("an actual committed write with a lost response is read back before another mutation",async({page})=>{
 await open(page);let writes=0;await page.route("**/api/users/me",async route=>{if(route.request().method()!=="PATCH")return route.continue();writes++;await route.fetch();await route.abort("failed");});await page.getByLabel("Firm",{exact:true}).fill("Recovered actual save");await page.getByRole("button",{name:"Save changes",exact:true}).click();await expect(page.getByText("Changes saved.",{exact:true})).toBeVisible();expect(writes).toBe(1);expect((await server.inspectUser(owner.id)).lawFirm).toBe("Recovered actual save");await page.reload();await expect(page.getByLabel("Firm",{exact:true})).toHaveValue("Recovered actual save");
});

async function postWriteFailure(page,pathname,method='PATCH',repeat=false){let writes=0,armed=false;await page.route('**'+pathname,async route=>{if(route.request().method()!==method)return route.continue();writes++;const response=await route.fetch();expect(response.ok()).toBe(true);armed=true;await route.fulfill({response});});await page.route('**/api/auth/me',async route=>{if(armed){if(!repeat)armed=false;return route.fulfill({status:503,contentType:'application/json',body:'{}'});}await route.continue();});return{writes:()=>writes,recover:()=>{armed=false;}};}
async function addRecoveryPhoto(page){const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=640;c.height=480;const x=c.getContext('2d');x.fillStyle='#6495ED';x.fillRect(0,0,640,480);return c.toDataURL('image/png').split(',')[1];});await page.getByLabel('Choose profile photo',{exact:true}).setInputFiles({name:'synthetic-recovery.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.getByRole('button',{name:'Save photo',exact:true}).click();}
test('post-write owner failure confirms actual profile save without replay',async({page})=>{await open(page);const probe=await postWriteFailure(page,'/api/users/me');await page.getByLabel('Firm',{exact:true}).fill('Recovered after owner check');await save(page);expect(probe.writes()).toBe(1);expect((await server.inspectUser(owner.id)).lawFirm).toBe('Recovered after owner check');});
test('post-write owner failure confirms actual preference save without replay',async({page})=>{await open(page,'preferences');const probe=await postWriteFailure(page,'/api/account/preferences','POST');await page.getByLabel('Theme',{exact:true}).selectOption('dark');await expect(page.locator('html')).toHaveClass(/theme-dark/);await expect(page.getByLabel('Theme',{exact:true})).toBeEnabled();expect(probe.writes()).toBe(1);expect((await server.inspectUser(owner.id)).preferences.theme).toBe('dark');});
test('post-write owner failure reviews actual saved photo upload without replay',async({page})=>{await open(page);let attempts=0,failed=false;page.on('request',request=>{if(request.method()==='POST'&&new URL(request.url()).pathname==='/api/uploads/profile-photo')attempts++;});const receipts=()=>server.mutationReceipts().filter(item=>item.ownerId===owner.id&&item.path==='/api/uploads/profile-photo');await page.route('**/api/auth/me',async route=>{if(!failed&&receipts().length){failed=true;return route.fulfill({status:503,contentType:'application/json',body:'{}'});}return route.continue();});const probe={writes:()=>attempts};await addRecoveryPhoto(page);await expect(page.getByText('Your saved photo changed. Close this window to review it before making another change.',{exact:true})).toBeVisible();expect(probe.writes()).toBe(1);expect(receipts()).toHaveLength(1);await expect(page.getByRole('button',{name:'Save photo',exact:true})).toBeHidden();await page.getByRole('button',{name:'Close',exact:true}).click();await expect(page.getByRole('button',{name:'Change photo',exact:true})).toBeVisible();});
test('post-write owner failure confirms actual photo removal without stale repeat',async({page})=>{await open(page);await addRecoveryPhoto(page);await expect(page.getByRole('dialog')).toHaveCount(0);const probe=await postWriteFailure(page,'/api/users/me');await page.getByRole('button',{name:'Remove photo',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Remove photo',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Add photo',exact:true})).toBeVisible();expect(probe.writes()).toBe(1);expect((await server.inspectUser(owner.id)).avatarURL).toBe('');});
test('repeated post-write owner failure leaves photo removal read-only until a later check',async({page},info)=>{await open(page);await addRecoveryPhoto(page);await expect(page.getByRole('dialog')).toHaveCount(0);const probe=await postWriteFailure(page,'/api/users/me','PATCH',true);await page.getByRole('button',{name:'Remove photo',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Remove photo',exact:true}).click();await expect(page.getByRole('button',{name:'Check photo',exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Change photo',exact:true})).toBeDisabled();await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.documentElement.classList.add('theme-dark');document.documentElement.style.fontSize='125%';});await page.getByRole('button',{name:'Check photo',exact:true}).scrollIntoViewIfNeeded();expect(await page.locator('.av2-account-photo').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.screenshot({path:info.outputPath('photo-removal-uncertain-mobile-dark-xl.png')});await page.getByRole('button',{name:'Check photo',exact:true}).click();expect(probe.writes()).toBe(1);probe.recover();await page.getByRole('button',{name:'Check photo',exact:true}).click();await expect(page.getByRole('button',{name:'Add photo',exact:true})).toBeVisible();expect(probe.writes()).toBe(1);});

test('pending photo removal survives a same-owner route return and clears on account replacement',async({page,context})=>{
 await open(page);await addRecoveryPhoto(page);await expect(page.getByRole('dialog')).toHaveCount(0);const probe=await postWriteFailure(page,'/api/users/me','PATCH',true);await page.getByRole('button',{name:'Remove photo',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Remove photo',exact:true}).click();await expect(page.getByRole('button',{name:'Check photo',exact:true})).toBeVisible();await page.getByRole('link',{name:'Preferences',exact:true}).click();await expect(page.getByRole('button',{name:'Try again',exact:true})).toBeVisible();probe.recover();await page.getByRole('link',{name:'Profile',exact:true}).click();await expect(page.getByRole('button',{name:'Add photo',exact:true})).toBeVisible();expect(probe.writes()).toBe(1);
 await page.unroute('**/api/users/me');await addRecoveryPhoto(page);await expect(page.getByRole('dialog')).toHaveCount(0);const second=await postWriteFailure(page,'/api/users/me','PATCH',true);await page.getByRole('button',{name:'Remove photo',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Remove photo',exact:true}).click();await expect(page.getByRole('button',{name:'Check photo',exact:true})).toBeVisible();second.recover();const replacement=await server.createUser({firstName:'Replacement'});await context.addCookies([replacement.cookie]);await page.getByRole('button',{name:'Check photo',exact:true}).click();await expect(page).toHaveURL(/login.html/);await expect(page.getByRole('button',{name:'Check photo',exact:true})).toHaveCount(0);expect(second.writes()).toBe(1);expect((await server.inspectUser(replacement.id)).firstName).toBe('Replacement');
});

for(const held of ['mutation','readback'])test(`pending photo removal settles after navigation during held ${held}`,async({page})=>{
 await open(page);await addRecoveryPhoto(page);await expect(page.getByRole('dialog')).toHaveCount(0);let writes=0,committed=false,paused=false,failAuth=false,release;const hold=new Promise(resolve=>release=resolve);
 await page.route('**/api/users/me',async route=>{if(route.request().method()!=='PATCH')return route.continue();writes++;const response=await route.fetch();expect(response.ok()).toBe(true);committed=true;if(held==='mutation'){paused=true;await hold;}else failAuth=true;await route.fulfill({response}).catch(()=>{});});
 await page.route('**/api/users/me?*',async route=>{if(held!=='readback'||!committed||paused)return route.continue();const response=await route.fetch();paused=true;await hold;await route.fulfill({response}).catch(()=>{});});
 await page.route('**/api/auth/me',async route=>{if(failAuth){failAuth=false;return route.fulfill({status:503,contentType:'application/json',body:'{}'});}return route.continue();});
 try{await page.getByRole('button',{name:'Remove photo',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Remove photo',exact:true}).click();await expect.poll(()=>paused).toBe(true);await page.evaluate(()=>{location.hash='/settings?tab=preferences';});release();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByLabel('Theme',{exact:true})).toBeEnabled();await page.getByRole('link',{name:'Profile',exact:true}).click();await expect(page.getByRole('button',{name:'Add photo',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Check photo',exact:true})).toHaveCount(0);expect(writes).toBe(1);expect((await server.inspectUser(owner.id)).avatarURL).toBe('');}finally{release();}
});
