const {test,expect}=require('../support-session-fixture');
const AxeBuilder=require('@axe-core/playwright').default;
const owner='a'.repeat(24),target='b'.repeat(24),replacement='c'.repeat(24),revision='a'.repeat(64);
const record=(id=target,name='Avery Park')=>({blockedId:id,name,role:'paralegal',createdAt:'2026-09-01T12:00:00Z',reason:'',revision});
const json=(route,value,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});
async function setup(page,overrides={}){
 const model={owner,items:[record()],writes:[],...overrides};
 await page.route('**/api/**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname;
  if(path==='/api/auth/me'&&model.postOwnerFail&&model.writes.length){model.postOwnerFail=false;return json(route,{},503);}
  if(path==='/api/auth/me')return json(route,{user:{id:model.owner,role:'attorney',status:'approved',firstName:'Morgan',lastName:'Counsel',preferences:{theme:'light',fontSize:'md'}}});
  if(path==='/api/csrf'){if(model.switchAfterPreflight)model.owner=replacement;return json(route,{csrfToken:'synthetic-blocks-token'});}
  if(path==='/api/blocks'){if(model.pages)return json(route,model.pages[url.searchParams.get('cursor')||'first']);if(model.listDelay)await model.listDelay;if(model.listFail||url.searchParams.has('cursor')&&model.pageFail)return json(route,{},503);const offset=url.searchParams.has('cursor')?2:0;return json(route,{items:model.items.slice(offset,offset+2),total:model.items.length,nextCursor:offset+2<model.items.length?'later-page':null});}
  if(path.startsWith('/api/blocks/')){const id=path.split('/').at(-1),item=model.items.find(item=>item.blockedId===id);
   if(req.method()==='GET'){if(model.statusDelay)await model.statusDelay;if(model.statusFail)return json(route,{},503);return json(route,{blockedId:id,blocked:Boolean(item),revision:item?.revision||null});}
   const body=req.postDataJSON();model.writes.push(body);if(model.removeDelay)await model.removeDelay;
   if(body.expectedOwnerId!==model.owner)return json(route,{code:'ACCOUNT_CHANGED'},403);
   if(!item||body.expectedBlockRevision!==item.revision)return json(route,{code:'ACCOUNT_CONFLICT'},409);
   if(model.reject)return json(route,{error:'Private server trace'},400);if(model.malformed)return json(route,{});
   model.items=model.items.filter(item=>item.blockedId!==id);if(model.lost)return route.abort('failed');return json(route,{ok:true,blocked:false,blockedId:id});
  }
  if(path==='/api/account/2fa')return json(route,{enabled:false,method:'email',hasBackupCodes:false,sessionManaged:true,securityRevision:revision});
  if(path==='/api/account/passkeys')return json(route,{passkeys:[]});if(path==='/api/account/sessions')return json(route,{sessions:[],currentSession:null,nextCursor:null,total:0});
  if(path==='/api/notifications/stream')return route.fulfill({status:200,contentType:'text/event-stream',body:': ready\n\n'});
  return json(route,path==='/api/notifications/page'?{items:[],hasMore:false,nextCursor:null}:path==='/api/notifications'?[]:path.endsWith('unread-count')?{count:0}:{});
 });return model;
}
async function open(page,url='/attorney-v2.html#/settings?tab=blocked'){
 // Firefox can retain its initial navigation wait after the pane has rendered.
 // Verify native entry through the actual destination and existing readiness.
 const destination=new URL(url,test.info().project.use.baseURL);
 await page.evaluate(value=>{setTimeout(()=>location.assign(value),0);},destination.href);
 await expect.poll(()=>{const current=new URL(page.url());return current.origin+current.pathname;}).toBe(destination.origin+destination.pathname);
 await expect(page.locator('html')).toHaveAttribute('data-attorney-state','ready');
 await expect(page.locator('[data-blocked-list]')).toHaveAttribute('aria-busy','false');
}
async function confirm(page,name='Avery Park'){await page.getByRole('button',{name:`Unblock ${name}`,exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Unblock',exact:true}).click();}

test('list loads honest owner records and does not offer unrestricted creation',async({page})=>{const model=await setup(page);await open(page);await expect(page.getByRole('heading',{name:'Avery Park'})).toBeVisible();await expect(page.getByRole('navigation',{name:'Profile settings'}).getByRole('link',{name:'Blocked users'})).toHaveAttribute('aria-current','page');expect(model.writes).toEqual([]);await expect(page.getByRole('button',{name:/add|block user|new block/i})).toHaveCount(0);});
test('empty and unavailable states stay distinct with deliberate retry',async({page})=>{const model=await setup(page,{listFail:true,items:[]});await open(page);await expect(page.getByText('Blocked users could not be loaded. Try again.',{exact:true})).toBeVisible();await expect(page.getByText('No blocked users.',{exact:true})).toHaveCount(0);model.listFail=false;await page.getByRole('button',{name:'Refresh blocked users'}).click();await expect(page.getByText('No blocked users.',{exact:true})).toBeVisible();});
test('cancel makes no mutation and restores the reviewed row focus',async({page})=>{const model=await setup(page);await open(page);const launcher=page.getByRole('button',{name:'Unblock Avery Park',exact:true});await launcher.click();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(launcher).toBeFocused();expect(model.writes).toEqual([]);});
test('unblocking waits for both server confirmation and authoritative direct-block readback',async({page})=>{let releaseRemove,releaseStatus;const model=await setup(page,{removeDelay:new Promise(resolve=>releaseRemove=resolve),statusDelay:new Promise(resolve=>releaseStatus=resolve)});await open(page);await confirm(page);await expect(page.locator('article[data-blocked-id]')).toHaveCount(1);await expect(page.getByRole('dialog').getByRole('button',{name:'Unblock',exact:true})).toBeDisabled();releaseRemove();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('article[data-blocked-id]')).toHaveCount(1);releaseStatus();await expect(page.getByText('Unblocked Avery Park.',{exact:true})).toBeVisible();await expect(page.locator('article[data-blocked-id]')).toHaveCount(0);expect(model.writes).toEqual([{expectedOwnerId:owner,expectedBlockRevision:revision}]);await expect(page.getByRole('navigation',{name:'Profile settings'}).getByRole('link',{name:'Blocked users',exact:true})).toBeFocused();});
test('lost committed response is confirmed by readback without repeating removal',async({page})=>{const model=await setup(page,{lost:true});await open(page);await confirm(page);await expect(page.getByText('Your block on Avery Park is no longer active.',{exact:true})).toBeVisible();expect(model.writes).toHaveLength(1);await expect(page.getByText('No blocked users.',{exact:true})).toBeVisible();});
test('unavailable outcome readback retains rows and a check action until it can be verified',async({page})=>{const model=await setup(page,{lost:true,statusFail:true});await open(page);await confirm(page);await expect(page.locator('.av2-blocked').getByRole('button',{name:'Check again',exact:true})).toBeVisible();await expect(page.locator('article[data-blocked-id]')).toHaveCount(1);await expect(page.getByRole('button',{name:'Unblock Avery Park',exact:true})).toBeDisabled();model.statusFail=false;await page.locator('.av2-blocked').getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByText('Your block on Avery Park is no longer active.',{exact:true})).toBeVisible();expect(model.writes).toHaveLength(1);});
test('malformed success does not claim removal and requires fresh review',async({page})=>{const model=await setup(page,{malformed:true});await open(page);await confirm(page);await expect(page.getByText('Your block is still active. Review it before trying again.',{exact:true})).toBeVisible();await expect(page.locator('article[data-blocked-id]')).toHaveCount(1);expect(model.writes).toHaveLength(1);});
test('concurrent reactivation preserves the block and replaces the obsolete review',async({page})=>{const model=await setup(page);await open(page);await page.getByRole('button',{name:'Unblock Avery Park',exact:true}).click();model.items[0].revision='b'.repeat(64);await page.getByRole('dialog').getByRole('button',{name:'Unblock',exact:true}).click();await expect(page.getByText('This block changed. Review the current list before trying again.',{exact:true})).toBeVisible();expect(model.items).toHaveLength(1);expect(model.writes[0].expectedBlockRevision).toBe(revision);await confirm(page);await expect(page.getByText('Unblocked Avery Park.',{exact:true})).toBeVisible();expect(model.writes[1].expectedBlockRevision).toBe('b'.repeat(64));});
test('later-page failure retains records and retry exposes all records with visible focus',async({page})=>{const model=await setup(page,{items:[record(),record('d'.repeat(24),'Jordan Lee'),record('e'.repeat(24),'Casey Quinn')],pageFail:true});await open(page);await page.getByRole('button',{name:'Load more',exact:true}).click();await expect(page.getByText('More blocked users could not be loaded. Try again.',{exact:true})).toBeVisible();await expect(page.locator('article[data-blocked-id]')).toHaveCount(2);model.pageFail=false;await page.getByRole('button',{name:'Load more',exact:true}).click();await expect(page.locator('article[data-blocked-id]')).toHaveCount(3);await expect(page.getByRole('button',{name:'Unblock Casey Quinn',exact:true})).toBeFocused();await expect(page.getByRole('button',{name:'Unblock Casey Quinn',exact:true})).toBeInViewport();});
test('failed refresh labels retained records and disables stale actions',async({page})=>{const model=await setup(page);await open(page);model.listFail=true;await page.getByRole('button',{name:'Refresh blocked users'}).click();await expect(page.getByText('Blocked users could not be refreshed. The previous list is shown below.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Unblock Avery Park',exact:true})).toBeDisabled();model.listFail=false;await page.getByRole('button',{name:'Refresh blocked users'}).click();await expect(page.getByRole('button',{name:'Unblock Avery Park',exact:true})).toBeEnabled();});
test('refresh locks existing actions until the current owner read settles',async({page})=>{const model=await setup(page);await open(page);let release;model.listDelay=new Promise(resolve=>release=resolve);await page.getByRole('button',{name:'Refresh blocked users'}).click();await expect(page.getByRole('button',{name:'Unblock Avery Park',exact:true})).toBeDisabled();model.listDelay=null;release();await expect(page.getByRole('button',{name:'Unblock Avery Park',exact:true})).toBeEnabled();});
test('account replacement after preflight cannot unblock the replacement account',async({page})=>{const model=await setup(page,{switchAfterPreflight:true});await open(page);await confirm(page);await expect(page).toHaveURL(/login.html/);expect(model.items).toHaveLength(1);});
test('route return checks uncertain actions without replaying them',async({page})=>{const model=await setup(page,{lost:true,statusFail:true});await open(page);await confirm(page);await expect(page.locator('.av2-blocked').getByRole('button',{name:'Check again',exact:true})).toBeVisible();await page.getByRole('navigation',{name:'Profile settings'}).getByRole('link',{name:'Security',exact:true}).click();await expect(page.getByRole('button',{name:'Change password',exact:true})).toBeVisible();model.statusFail=false;await page.getByRole('navigation',{name:'Profile settings'}).getByRole('link',{name:'Blocked users',exact:true}).click();await expect(page.getByText('Your block on Avery Park is no longer active.',{exact:true})).toBeVisible();expect(model.writes).toHaveLength(1);});
test('blocked deep links use the actual settings pane',async({page})=>{await setup(page);await open(page,'/attorney-v2.html#/settings?panel=security:blocked');await expect(page.getByRole('heading',{name:'Avery Park'})).toBeVisible();});
test('names reasons and confirmation remain accessible in desktop mobile dark and doubled text',async({page},info)=>{await setup(page,{items:[{...record(target,'Alexandria Maximiliana Montgomery-Smith'),reason:'A private reason with a long continuous reference '+ 'x'.repeat(220)}]});await open(page);for(const [width,dark,size] of [[1366,false,'100%'],[390,false,'100%'],[320,true,'200%']]){await page.setViewportSize({width,height:844});await page.evaluate(({dark,size})=>{document.documentElement.classList.toggle('theme-dark',dark);document.documentElement.style.fontSize=size;},{dark,size});await page.getByText('Reason',{exact:true}).click();expect(await page.locator('[data-blocked-list]').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);expect((await new AxeBuilder({page}).include('.av2-blocked').analyze()).violations).toEqual([]);await page.screenshot({path:info.outputPath(`blocked-${width}.png`)});await page.getByText('Reason',{exact:true}).click();}await page.getByRole('button',{name:'Unblock Alexandria Maximiliana Montgomery-Smith',exact:true}).click();expect((await new AxeBuilder({page}).include('dialog').analyze()).violations).toEqual([]);expect(await page.getByRole('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.screenshot({path:info.outputPath('blocked-confirm-mobile-dark-200.png')});});

test('post-write account verification failure checks the committed unblock without replay',async({page})=>{const model=await setup(page,{postOwnerFail:true});await open(page);await confirm(page);await expect(page.getByText('Your block on Avery Park is no longer active.',{exact:true})).toBeVisible();expect(model.writes).toHaveLength(1);await expect(page.getByText('This block could not be removed.',{exact:false})).toHaveCount(0);});
for(const kind of ['repeated','cycle','no-progress'])test(`malformed pagination ${kind} retains loaded rows and requires refresh`,async({page})=>{
 const first=[record(),record('d'.repeat(24),'Jordan Lee')],second=[record('e'.repeat(24),'Casey Quinn')];const pages={first:{items:first,total:6,nextCursor:'one'},one:{items:kind==='no-progress'?first:second,total:6,nextCursor:kind==='repeated'?'one':'two'},two:{items:[record('f'.repeat(24),'Drew Wynn')],total:6,nextCursor:'one'}};const model=await setup(page,{pages});await open(page);await page.getByRole('button',{name:'Load more',exact:true}).click();if(kind==='cycle'){await expect(page.locator('article[data-blocked-id]')).toHaveCount(3);await page.getByRole('button',{name:'Load more',exact:true}).click();}await expect(page.getByText('The next page could not be verified. Refresh blocked users to continue.',{exact:true})).toBeVisible();await expect(page.locator('article[data-blocked-id]')).toHaveCount(kind==='cycle'?3:2);await expect(page.getByRole('button',{name:'Load more',exact:true})).toBeDisabled();model.pages={first:{items:first,total:2,nextCursor:null}};await page.getByRole('button',{name:'Refresh blocked users'}).click();await expect(page.locator('article[data-blocked-id]')).toHaveCount(2);await expect(page.getByRole('button',{name:'Unblock Avery Park',exact:true})).toBeEnabled();
});
