const path=require('path');
const { test, expect } = require('../../helpers/isolatedBrowserTest')('attorney-blocked-real');
const { enterSecondaryDocument } = require('../secondary-document-entry');
const start=require(path.resolve(__dirname,'../../../../docs/audits/completion-2026-09-09/blocks/backend-browser-server.cjs'));
test.use({ baseURL: 'http://localhost:5293', storageState: { cookies: [], origins: [] } });
let server,owner,target;
test.beforeAll(async()=>{test.setTimeout(120000);server=await start({port:5293});});
test.afterAll(async()=>{await server?.close();});
test.beforeEach(async({context})=>{owner=await server.createUser();target=await server.createUser({role:'paralegal',firstName:'Avery',lastName:'Park'});await server.block(owner.id,target.id);await context.addCookies([owner.cookie]);});
async function open(page,secondaryBaseURL){
 const target='/attorney-v2.html#/settings?tab=blocked';
 if(secondaryBaseURL)await enterSecondaryDocument(page,new URL(target,secondaryBaseURL).href,{waitUntil:'load'});
 else await page.goto(target);
 await expect(page.locator('html')).toHaveAttribute('data-attorney-state','ready');await expect(page.locator('[data-blocked-list]')).toHaveAttribute('aria-busy','false');
}
async function confirm(page,name='Avery Park'){await page.getByRole('button',{name:`Unblock ${name}`,exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Unblock',exact:true}).click();}
test('actual deliberate unblock preserves history and reciprocal restrictions without notification',async({page})=>{await server.block(target.id,owner.id,{blockerRole:'paralegal',blockedRole:'attorney'});await open(page);await page.getByRole('button',{name:'Unblock Avery Park',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();expect((await server.inspectBlock(owner.id,target.id)).active).toBe(true);await confirm(page);await expect(page.getByText('Unblocked Avery Park.',{exact:true})).toBeVisible();expect(await server.inspectBlock(owner.id,target.id)).toMatchObject({active:false,deactivatedAt:expect.any(Date)});expect((await server.inspectBlock(target.id,owner.id)).active).toBe(true);expect(server.mailSubjects()).toEqual([]);});
test('an actual missing account remains listed and can be unblocked',async({page})=>{await server.removeUser(target.id);await open(page);await expect(page.getByRole('heading',{name:'Account unavailable',exact:true})).toBeVisible();await confirm(page,'Account unavailable');await expect(page.getByText('Unblocked Account unavailable.',{exact:true})).toBeVisible();expect(await server.activeBlocks(owner.id)).toBe(0);});
test('real pagination presents every blocked record beyond two pages exactly once',async({page})=>{await server.manyMissingBlocks(owner.id,124);await open(page);await expect(page.locator('article[data-blocked-id]')).toHaveCount(50);await page.getByRole('button',{name:'Load more',exact:true}).click();await expect(page.locator('article[data-blocked-id]')).toHaveCount(100);await page.getByRole('button',{name:'Load more',exact:true}).click();await expect(page.locator('article[data-blocked-id]')).toHaveCount(125);await expect(page.getByRole('button',{name:'Load more',exact:true})).toBeHidden();const ids=await page.locator('article[data-blocked-id]').evaluateAll(elements=>elements.map(element=>element.dataset.blockedId));expect(new Set(ids).size).toBe(125);});
test('a real reactivation invalidates the open review and remains active until a new confirmation',async({page})=>{await open(page);await page.getByRole('button',{name:'Unblock Avery Park',exact:true}).click();await server.reactivate(owner.id,target.id);await page.getByRole('dialog').getByRole('button',{name:'Unblock',exact:true}).click();await expect(page.getByText('This block changed. Review the current list before trying again.',{exact:true})).toBeVisible();expect((await server.inspectBlock(owner.id,target.id)).active).toBe(true);await confirm(page);await expect(page.getByText('Unblocked Avery Park.',{exact:true})).toBeVisible();expect((await server.inspectBlock(owner.id,target.id)).active).toBe(false);});
test('two real tabs reconcile another confirmed unblock without a false success',async({page,context,baseURL})=>{await open(page);const second=await context.newPage();await open(second,baseURL);await second.getByRole('button',{name:'Unblock Avery Park',exact:true}).click();await confirm(page);await expect(page.getByText('Unblocked Avery Park.',{exact:true})).toBeVisible();await second.getByRole('dialog').getByRole('button',{name:'Unblock',exact:true}).click();await expect(second.getByText('Your block on Avery Park is no longer active.',{exact:true})).toBeVisible();expect(await server.activeBlocks(owner.id)).toBe(0);await second.close();});
test('actual committed response loss uses direct readback and never repeats the deletion',async({page})=>{await open(page);let writes=0;await page.route(`**/api/blocks/${target.id}`,async route=>{if(route.request().method()==='DELETE'){writes++;await route.fetch();await route.abort('failed');}else await route.continue();});await confirm(page);await expect(page.getByText('Your block on Avery Park is no longer active.',{exact:true})).toBeVisible();expect(writes).toBe(1);expect(await server.activeBlocks(owner.id)).toBe(0);});
test('failed actual outcome readback keeps the row until a deliberate later check',async({page})=>{await open(page);let unavailable=true,writes=0;await page.route(`**/api/blocks/${target.id}*`,async route=>{if(route.request().method()==='DELETE'){writes++;await route.fetch();await route.abort('failed');}else if(unavailable)await route.fulfill({status:503,contentType:'application/json',body:'{}'});else await route.continue();});await confirm(page);await expect(page.locator('.av2-blocked').getByRole('button',{name:'Check again',exact:true})).toBeVisible();await expect(page.locator('article[data-blocked-id]')).toHaveCount(1);expect(await server.activeBlocks(owner.id)).toBe(0);unavailable=false;await page.locator('.av2-blocked').getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByText('Your block on Avery Park is no longer active.',{exact:true})).toBeVisible();expect(writes).toBe(1);});
test('actual cookie replacement after preflight cannot remove either owner block',async({page,context})=>{await open(page);const replacement=await server.createUser();await server.block(replacement.id,target.id);await page.route('**/api/csrf',async route=>{await context.addCookies([replacement.cookie]);await route.continue();});await confirm(page);await expect(page).toHaveURL(/login.html|dashboard-attorney.html/);expect(await server.activeBlocks(owner.id)).toBe(1);expect(await server.activeBlocks(replacement.id)).toBe(1);});
test('actual revoked session leaves the block active and clears protected controls',async({page})=>{await open(page);await server.revoke(owner.cookie);await confirm(page);await expect(page).toHaveURL(/login.html|dashboard-attorney.html/);expect(await server.activeBlocks(owner.id)).toBe(1);await expect(page.getByRole('dialog')).toHaveCount(0);});
test('independent profile edits survive a real guarded unblock',async({page})=>{await open(page);await server.updateUser(owner.id,{lawFirm:'Independent firm','preferences.theme':'dark'});await confirm(page);await expect(page.getByText('Unblocked Avery Park.',{exact:true})).toBeVisible();const saved=await server.inspectUser(owner.id);expect(saved.lawFirm).toBe('Independent firm');expect(saved.preferences.theme).toBe('dark');});

test('actual committed unblock with failed post-write owner check recovers without another deletion',async({page})=>{
 await open(page);let writes=0,fail=false;await page.route('**/api/blocks/'+target.id,async route=>{if(route.request().method()!=='DELETE')return route.continue();writes++;const response=await route.fetch();expect(response.status()).toBe(200);fail=true;await route.fulfill({response});});await page.route('**/api/auth/me',async route=>{if(fail){fail=false;return route.fulfill({status:503,contentType:'application/json',body:'{}'});}return route.continue();});await confirm(page);await expect(page.getByText('Your block on Avery Park is no longer active.',{exact:true})).toBeVisible();expect(writes).toBe(1);expect(await server.activeBlocks(owner.id)).toBe(0);
});
