const {test,expect}=require('../support-session-fixture');
const AxeBuilder=require('@axe-core/playwright').default;
const owner='a'.repeat(24),other='b'.repeat(24),revision='a'.repeat(64),proof='YWJj.'+'b'.repeat(64),key='lpc_account_closure_result';
const json=(route,value,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});
async function setup(page,overrides={}){
 const model={owner,revision,blockers:[],state:'active',writes:[],resultReads:0,...overrides};
 await page.route('**/api/**',async route=>{const req=route.request(),path=new URL(req.url()).pathname;
  if(path==='/api/auth/me'&&model.preflightFailure&&model.preflightArmed)return json(route,{},503);
  if(path==='/api/auth/me')return json(route,{user:{id:model.owner,role:'attorney',status:'approved',firstName:'Morgan',lastName:'Counsel',preferences:{theme:'light',fontSize:'md'}}});
  if(path==='/api/csrf'){if(model.csrfFailure)return json(route,{},503);if(model.switchAfterPreflight)model.owner=other;return json(route,{csrfToken:'fixture'});}
  if(path==='/api/account/deactivate-status'){if(model.reviewFail)return json(route,{},503);return json(route,{ownerId:model.owner,canDeactivate:!model.blockers.length,blockers:model.blockers,closureRevision:model.revision,resultProof:proof,proofExpiresAt:new Date(Date.now()+600000).toISOString()});}
  if(path==='/api/account/deactivate-result'){model.resultReads++;expect(req.method()).toBe('GET');expect(await req.headerValue('x-lpc-closure-proof')).toBe(proof);if(model.resultDelay)await model.resultDelay;if(model.owner!==owner)return json(route,{code:'ACCOUNT_CHANGED'},403);if(model.resultError)return json(route,{code:model.resultErrorCode||''},model.resultError);return json(route,{state:model.state});}
  if(path==='/api/account/deactivate'){
   const body=req.postDataJSON();model.writes.push(body);if(model.removeDelay)await model.removeDelay;
   if(body.expectedOwnerId!==model.owner)return json(route,{code:'ACCOUNT_CHANGED'},403);
   if(body.expectedClosureRevision!==model.revision)return json(route,{code:'ACCOUNT_CLOSURE_CHANGED'},409);
   if(model.reject)return json(route,{},400);if(!model.keepActive)model.state='deactivated';if(model.lost)return route.abort('failed');return json(route,model.malformed?{}:{ok:true,deactivated:true});
  }
  if(path==='/api/notifications/stream')return route.fulfill({status:200,contentType:'text/event-stream',body:': ready\n\n'});
  return json(route,path==='/api/notifications/page'?{items:[],hasMore:false,nextCursor:null}:path==='/api/notifications'?[]:path.endsWith('unread-count')?{count:0}:{});
 });return model;
}
async function open(page,url='/attorney-v2.html#/settings?tab=closure'){
 // Firefox can retain its initial navigation wait after the review has rendered.
 // Keep closure/history assertions separate from this initial document entry.
 const destination=new URL(url,test.info().project.use.baseURL);
 await page.evaluate(value=>{setTimeout(()=>location.assign(value),0);},destination.href);
 await expect.poll(()=>{const current=new URL(page.url());return current.origin+current.pathname;}).toBe(destination.origin+destination.pathname);
 await expect(page.locator('html')).toHaveAttribute('data-attorney-state','ready');
 await expect(page.locator('[data-closure-review]')).toHaveAttribute('aria-busy','false');
}
async function confirm(page){await page.getByRole('button',{name:'Deactivate account',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true}).click();}
const stored=page=>page.evaluate(key=>sessionStorage.getItem(key),key);
test('review presents existing consequences once and all distinct blocking reasons',async({page})=>{const model=await setup(page,{blockers:[{code:'active_matters',message:'Complete active Matters first.',count:2},{code:'open_disputes',message:'Resolve the open dispute.',count:1},{code:'pending_payouts',message:'Wait for the pending payout.',count:1}]});await open(page);await expect(page.locator('[data-closure-blocker]')).toHaveCount(3);await expect(page.getByRole('button',{name:'Deactivate account',exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'View payments',exact:true})).toHaveAttribute('href','#/payments');await expect(page.getByRole('link',{name:'Account closure',exact:true})).toHaveAttribute('aria-current','page');expect(model.writes).toEqual([]);});
test('failed eligibility cannot appear clear and deliberate refresh restores review',async({page})=>{const model=await setup(page,{reviewFail:true});await open(page);await expect(page.getByText('Account closure could not be checked. Refresh to try again.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Deactivate account',exact:true})).toHaveCount(0);model.reviewFail=false;await page.getByRole('button',{name:'Refresh closure review'}).click();await expect(page.getByRole('button',{name:'Deactivate account',exact:true})).toBeEnabled();});
test('cancel and Escape restore visible launch focus without retaining proof or sending a request',async({page})=>{const model=await setup(page);await open(page);const launcher=page.getByRole('button',{name:'Deactivate account',exact:true});await launcher.click();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(launcher).toBeFocused();await expect(launcher).toBeInViewport();expect(model.writes).toEqual([]);expect(await stored(page)).toBeNull();});
test('confirmed closure exits protected session and reads authoritative current state',async({page})=>{const model=await setup(page);await open(page);await confirm(page);await expect(page).toHaveURL(/account-closure.html$/);await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(model.writes).toEqual([{expectedOwnerId:owner,expectedClosureRevision:revision,resultProof:proof}]);expect(model.resultReads).toBe(1);expect(await stored(page)).toBeNull();expect(await page.evaluate(()=>localStorage.getItem('lpc_user'))).toBeNull();});
test('lost committed response checks current state without another mutation',async({page})=>{const model=await setup(page,{lost:true});await open(page);await confirm(page);await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(model.writes).toHaveLength(1);expect(model.resultReads).toBe(1);});
test('unknown result retains proof across refresh and deliberate check then clears only confirmed state',async({page})=>{const model=await setup(page,{lost:true,resultError:503});await open(page);await confirm(page);await expect(page.getByRole('heading',{name:'Account status could not be checked',exact:true})).toBeVisible();expect(await stored(page)).toBe(proof);await page.reload();await expect(page.getByRole('button',{name:'Check again',exact:true})).toBeVisible();expect(await stored(page)).toBe(proof);model.resultError=0;await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeFocused();expect(await stored(page)).toBeNull();expect(model.writes).toHaveLength(1);});
test('active state is current information and retains a check without retrying a pending mutation',async({page})=>{const model=await setup(page,{lost:true,keepActive:true});await open(page);await confirm(page);await expect(page.getByRole('heading',{name:'Your account is currently active',exact:true})).toBeVisible();expect(await stored(page)).toBe(proof);await page.getByRole('button',{name:'Check again',exact:true}).click();expect(model.writes).toHaveLength(1);expect(await stored(page)).toBe(proof);model.state='deactivated';await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();});
test('generic unavailable status retains proof for later checking',async({page})=>{const model=await setup(page,{lost:true,keepActive:true,state:'unavailable'});await open(page);await confirm(page);await expect(page.getByRole('heading',{name:'Account status unavailable',exact:true})).toBeVisible();expect(await stored(page)).toBe(proof);model.state='deactivated';await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();});
test('review conflict preserves current account and requires a new deliberate review',async({page})=>{const model=await setup(page);await open(page);await page.getByRole('button',{name:'Deactivate account',exact:true}).click();model.revision='c'.repeat(64);model.blockers=[{code:'active_matters',message:'Resolve the new active Matter.',count:1}];await page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true}).click();await expect(page.getByText('Resolve the new active Matter.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Refresh closure review'})).toBeFocused();expect(model.state).toBe('active');expect(await stored(page)).toBeNull();expect(model.writes[0].expectedClosureRevision).toBe(revision);});
test('replacement after preflight cannot deactivate or disclose previous account state',async({page})=>{const model=await setup(page,{switchAfterPreflight:true});await open(page);await confirm(page);await expect(page.getByRole('heading',{name:'Session changed',exact:true})).toBeVisible();expect(model.state).toBe('active');expect(await stored(page)).toBeNull();});
test('unavailable tab storage prevents the consequential request',async({page})=>{const model=await setup(page);await open(page);await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new Error('synthetic denied storage');};});await confirm(page);await expect(page.getByRole('alert')).toHaveText('This browser could not retain the account check. Allow session storage and try again.');expect(model.writes).toEqual([]);await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeEnabled();});
test('pending closure survives pagehide and startup reload before normal session bootstrap',async({page})=>{let release;const model=await setup(page,{removeDelay:new Promise(resolve=>release=resolve)});await open(page);await confirm(page);await expect.poll(()=>model.writes.length).toBe(1);page.on('dialog',dialog=>dialog.accept());await page.reload().catch(error=>{if(!/NS_BINDING_ABORTED|Frame load interrupted/.test(String(error.message)))throw error;});await expect(page).toHaveURL(/account-closure.html$/);await expect(page.getByRole('heading',{name:'Your account is currently active',exact:true})).toBeVisible();expect(await stored(page)).toBe(proof);release();await expect.poll(()=>model.state).toBe('deactivated');await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(model.writes).toHaveLength(1);});
test('unverified cross-tab storage signal preserves pending recovery and hides protected controls',async({page})=>{let release;const model=await setup(page,{removeDelay:new Promise(resolve=>release=resolve)});await open(page);await confirm(page);await expect.poll(()=>model.writes.length).toBe(1);await page.evaluate(()=>window.dispatchEvent(new StorageEvent('storage',{key:'lpc_user',newValue:null})));await expect(page).toHaveURL(/account-closure.html$/);await expect(page.getByRole('heading',{name:'Your account is currently active',exact:true})).toBeVisible();expect(await stored(page)).toBe(proof);release();await expect.poll(()=>model.state).toBe('deactivated');await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();});
test('route interruption hands off pending closure before another workspace view is exposed',async({page})=>{let release;const model=await setup(page,{removeDelay:new Promise(resolve=>release=resolve)});await open(page);await confirm(page);await expect.poll(()=>model.writes.length).toBe(1);await page.evaluate(()=>{location.hash='#/settings?tab=blocked';});await expect(page).toHaveURL(/account-closure.html$/);await expect(page.getByRole('heading',{name:'Your account is currently active',exact:true})).toBeVisible();await expect(page.locator('[data-av2-shell]')).toHaveCount(0);release();await expect.poll(()=>model.state).toBe('deactivated');await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(model.writes).toHaveLength(1);});
for(const [status,code,heading] of [[410,'ACCOUNT_CLOSURE_PROOF_EXPIRED','Account check expired'],[400,'ACCOUNT_CLOSURE_PROOF_INVALID','Account check unavailable']])test(`result ${status} clears unusable proof without claiming deactivation`,async({page})=>{await setup(page,{lost:true,resultError:status,resultErrorCode:code});await open(page);await confirm(page);await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible();expect(await stored(page)).toBeNull();});
test('legacy closure deep link resolves the actual review',async({page})=>{await setup(page);await open(page,'/attorney-v2.html#/settings?panel=security:closure');await expect(page.getByRole('button',{name:'Deactivate account',exact:true})).toBeEnabled();});
test('desktop narrow dark and doubled text keep review confirmation and status accessible',async({page},info)=>{await setup(page);await open(page);for(const [width,dark,size] of [[1366,false,'100%'],[390,false,'100%'],[320,true,'200%']]){await page.setViewportSize({width,height:900});await page.evaluate(({dark,size})=>{document.documentElement.classList.toggle('theme-dark',dark);document.documentElement.style.fontSize=size;},{dark,size});expect(await page.locator('.av2-closure').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);expect((await new AxeBuilder({page}).include('.av2-closure').analyze()).violations).toEqual([]);await page.screenshot({path:info.outputPath(`closure-${width}.png`)});}await page.getByRole('button',{name:'Deactivate account',exact:true}).click();expect((await new AxeBuilder({page}).include('dialog').analyze()).violations).toEqual([]);await page.screenshot({path:info.outputPath('closure-confirm-dark-320-200.png')});await page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();await page.emulateMedia({colorScheme:'dark'});await page.evaluate(()=>document.documentElement.style.fontSize='200%');expect(await page.locator('body').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);await page.screenshot({path:info.outputPath('closure-result-dark-320-200.png')});});

for(const kind of ['preflight','csrf'])test(`known undispatched ${kind} failure retains a fresh review without closure handoff`,async({page})=>{const model=await setup(page);await open(page);await page.getByRole('button',{name:'Deactivate account',exact:true}).click();if(kind==='preflight'){model.preflightFailure=true;model.preflightArmed=true;}else model.csrfFailure=true;await page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true}).click();await expect(page).toHaveURL(/attorney-v2.html/);await expect(page.getByText('Account closure could not start. Refresh the review and try again.',{exact:true})).toBeVisible();expect(model.writes).toEqual([]);expect(model.resultReads).toBe(0);expect(await stored(page)).toBeNull();});
test('doubled-text confirmation starts with the entire focused Cancel control visible',async({page})=>{await setup(page);await open(page);await page.setViewportSize({width:320,height:900});await page.evaluate(()=>{document.documentElement.style.fontSize='200%';document.documentElement.classList.add('theme-dark');});await page.getByRole('button',{name:'Deactivate account',exact:true}).click();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeInViewport({ratio:1});await page.keyboard.press('Tab');await expect(page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true})).toBeFocused();await expect(page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true})).toBeInViewport({ratio:1});});
test('persisted result page clears a settled status before any cached restoration',async({page})=>{const model=await setup(page);await open(page);await confirm(page);await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));await expect(page.getByRole('heading',{name:'Checking account status',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toHaveCount(0);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await expect(page.getByRole('heading',{name:'Account check unavailable',exact:true})).toBeVisible();expect(model.resultReads).toBe(1);expect(await stored(page)).toBeNull();});
test('persisted active result hides previous state while a new credential is checked',async({page})=>{const model=await setup(page,{lost:true,keepActive:true});await open(page);await confirm(page);await expect(page.getByRole('heading',{name:'Your account is currently active',exact:true})).toBeVisible();let release;model.resultDelay=new Promise(resolve=>release=resolve);model.owner=other;await page.evaluate(()=>{window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});await expect(page.getByRole('heading',{name:'Checking account status',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Your account is currently active',exact:true})).toHaveCount(0);release();await expect(page.getByRole('heading',{name:'Session changed',exact:true})).toBeVisible();expect(await stored(page)).toBeNull();expect(model.writes).toHaveLength(1);});
