const path=require('path');
const { enterSecondaryDocument } = require('../secondary-document-entry');
const { test, expect } = require('../../helpers/isolatedBrowserTest')('attorney-closure-real');
const start=require(path.resolve(__dirname,'../../../../docs/audits/completion-2026-09-09/closure/backend-browser-server.cjs'));
test.use({ baseURL: 'http://localhost:5297', storageState: { cookies: [], origins: [] } });
let server,owner;
test.beforeAll(async()=>{test.setTimeout(120000);server=await start({port:5297});});
test.afterAll(async()=>{await server?.close();});
test.beforeEach(async({context})=>{owner=await server.createUser();await context.addCookies([owner.cookie]);});
test.afterEach(()=>server?.release(owner?.id));
async function open(page){await enterSecondaryDocument(page, new URL('/attorney-v2.html#/settings?tab=closure', server.origin).href, { waitUntil: 'load' });await expect(page.locator('html')).toHaveAttribute('data-attorney-state','ready');await expect(page.locator('[data-closure-review]')).toHaveAttribute('aria-busy','false');}
async function confirm(page){await page.getByRole('button',{name:'Deactivate account',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true}).click();}
const receipts=()=>server.receipts().filter(item=>item.ownerId===owner.id);
const stored=page=>page.evaluate(()=>sessionStorage.getItem('lpc_account_closure_result'));
test('real closure atomically closes unfunded postings retains history and ends all managed sessions',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 const candidate=await server.createUser({role:'paralegal'});await server.cookieFor(owner.id);
 const matter=await server.createCase(owner.id,{paralegal:candidate.id,paralegalId:candidate.id,pendingParalegalId:candidate.id,applicants:[{paralegalId:candidate.id,status:'accepted'}],invites:[{paralegalId:candidate.id,status:'accepted',invitedAt:new Date()}]});const job=await server.createJob(owner.id,matter._id);
 const historic=await server.createCase(owner.id,{title:'Completed historical Matter',status:'completed',paymentReleased:true,paidOutAt:new Date(),escrowStatus:'released'});
 await open(page);await page.getByRole('button',{name:'Deactivate account',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();expect((await server.inspectUser(owner.id)).disabled).toBe(false);
 await confirm(page);await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();
 expect(await server.inspectUser(owner.id)).toMatchObject({disabled:true,deleted:true,status:'denied',authVersion:1});expect((await server.sessions(owner.id)).every(item=>item.revokedAt)).toBe(true);
 expect(await server.inspectCase(matter._id)).toMatchObject({status:'closed',archived:true,paymentStatus:'cancelled'});expect((await server.inspectCase(matter._id)).applicants[0].status).toBe('rejected');expect((await server.inspectCase(matter._id)).invites[0].status).toBe('expired');expect((await server.inspectJob(job._id)).status).toBe('closed');expect((await server.inspectCase(historic._id)).title).toBe('Completed historical Matter');expect(await server.audits(owner.id)).toHaveLength(1);expect(receipts()).toHaveLength(1);expect(await stored(page)).toBeNull();expect(errors).toEqual([]);
});
test('authoritative active Matter dispute funding and payout blockers prevent offering closure',async({page})=>{await server.createCase(owner.id,{status:'disputed',escrowStatus:'funded',paymentReleased:false});await server.createCase(owner.id,{status:'completed',paymentReleased:true,paidOutAt:null});await open(page);expect(await page.locator('[data-closure-blocker]').count()).toBeGreaterThanOrEqual(3);await expect(page.getByRole('button',{name:'Deactivate account',exact:true})).toHaveCount(0);expect(receipts()).toHaveLength(0);expect((await server.inspectUser(owner.id)).disabled).toBe(false);});
test('a new actual Matter invalidates the reviewed revision and cannot be silently closed',async({page})=>{await open(page);await page.getByRole('button',{name:'Deactivate account',exact:true}).click();const matter=await server.createCase(owner.id);await page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true}).click();await expect(page.getByText('Account closure changed. Review the current information before continuing.',{exact:true})).toBeVisible();expect((await server.inspectCase(matter._id)).status).toBe('open');expect((await server.inspectUser(owner.id)).disabled).toBe(false);expect(receipts()).toHaveLength(0);await confirm(page);await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect((await server.inspectCase(matter._id)).status).toBe('closed');});
test('a lost actual committed response uses the bounded status read after authentication ends',async({page})=>{await open(page);server.dropNextResponse(owner.id);await confirm(page);await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(receipts()).toHaveLength(1);expect((await server.inspectUser(owner.id)).disabled).toBe(true);});
test('failed actual outcome confirmation retains proof through refresh until deliberate check',async({page})=>{await open(page);let unavailable=true;await page.route('**/api/account/deactivate-result',route=>unavailable?route.fulfill({status:503,contentType:'application/json',body:'{}'}):route.continue());server.dropNextResponse(owner.id);await confirm(page);await expect(page.getByRole('heading',{name:'Account status could not be checked',exact:true})).toBeVisible();expect(receipts()).toHaveLength(1);expect(await stored(page)).toBeTruthy();await page.reload();await expect(page.getByRole('button',{name:'Check again',exact:true})).toBeVisible();unavailable=false;await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(receipts()).toHaveLength(1);expect(await stored(page)).toBeNull();});
test('actual cookie replacement after preflight cannot deactivate either account or erase new credentials',async({page,context})=>{await open(page);const replacement=await server.createUser();await page.route('**/api/csrf',async route=>{await context.addCookies([replacement.cookie]);await route.continue();});await confirm(page);await expect(page.getByRole('heading',{name:'Session changed',exact:true})).toBeVisible();expect((await server.inspectUser(owner.id)).disabled).toBe(false);expect((await server.inspectUser(replacement.id)).disabled).toBe(false);expect((await context.cookies(server.origin)).find(cookie=>cookie.name==='token').value).toBe(replacement.cookie.value);expect(await stored(page)).toBeNull();expect(receipts()).toHaveLength(0);});
test('actual delayed closure response cannot erase a newly signed-in account cookie',async({page,context})=>{await open(page);const replacement=await server.createUser();await page.route('**/api/account/deactivate',async route=>{const response=await route.fetch();expect(response.status()).toBe(200);expect(response.headers()['set-cookie']).toBeUndefined();await context.addCookies([replacement.cookie]);await route.fulfill({response});});await confirm(page);await expect(page.getByRole('heading',{name:'Session changed',exact:true})).toBeVisible();expect((await context.cookies(server.origin)).find(cookie=>cookie.name==='token').value).toBe(replacement.cookie.value);expect((await server.inspectUser(owner.id)).disabled).toBe(true);expect((await server.inspectUser(replacement.id)).disabled).toBe(false);});
test('actual in-flight request can remain active on reload and later confirms without another DELETE',async({page})=>{await open(page);server.holdNext(owner.id);await confirm(page);await expect.poll(()=>server.held(owner.id)).toBe(true);page.on('dialog',dialog=>dialog.accept());await page.evaluate(()=>{window.setTimeout(()=>location.reload(),0);});await expect(page).toHaveURL(/account-closure.html$/);await expect(page.getByRole('heading',{name:'Your account is currently active',exact:true})).toBeVisible();expect(await stored(page)).toBeTruthy();server.release(owner.id);await expect.poll(async()=>(await server.inspectUser(owner.id)).disabled).toBe(true);await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(receipts()).toHaveLength(1);});
test('same-owner route interruption immediately hands off a pending closure without exposing another protected pane',async({page})=>{await open(page);server.holdNext(owner.id);await confirm(page);await expect.poll(()=>server.held(owner.id)).toBe(true);await page.evaluate(()=>{location.hash='#/settings?tab=blocked';});await expect(page).toHaveURL(/account-closure.html$/);await expect(page.getByRole('heading',{name:'Your account is currently active',exact:true})).toBeVisible();await expect(page.locator('[data-av2-shell]')).toHaveCount(0);server.release(owner.id);await expect.poll(async()=>(await server.inspectUser(owner.id)).disabled).toBe(true);await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(receipts()).toHaveLength(1);});
test('unrelated profile and theme changes survive reviewed actual closure',async({page})=>{await open(page);await page.getByRole('button',{name:'Deactivate account',exact:true}).click();await server.updateUser(owner.id,{lawFirm:'Independent firm','preferences.theme':'dark'});await page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(await server.inspectUser(owner.id)).toMatchObject({lawFirm:'Independent firm',preferences:{theme:'dark'}});});
for(const phase of ['auth','csrf'])test(`actual ${phase} preflight failure sends no closure request and keeps explicit retry`,async({page})=>{await open(page);await page.getByRole('button',{name:'Deactivate account',exact:true}).click();await page.route(phase==='auth'?'**/api/auth/me':'**/api/csrf',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));await page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true}).click();await expect(page).toHaveURL(/attorney-v2.html/);await expect(page.getByText('Account closure could not start. Refresh the review and try again.',{exact:true})).toBeVisible();expect((await server.inspectUser(owner.id)).disabled).toBe(false);expect(receipts()).toHaveLength(0);expect(await stored(page)).toBeNull();});
test('actual pending closure survives an unverified storage signal without re-enabling protected UI',async({page})=>{await open(page);server.holdNext(owner.id);await confirm(page);await expect.poll(()=>server.held(owner.id)).toBe(true);await page.evaluate(()=>window.dispatchEvent(new StorageEvent('storage',{key:'lpc_user',newValue:null})));await expect(page.getByRole('heading',{name:'Your account is currently active',exact:true})).toBeVisible();expect(await stored(page)).toBeTruthy();await expect(page.locator('[data-av2-shell]')).toHaveCount(0);server.release(owner.id);await expect.poll(async()=>(await server.inspectUser(owner.id)).disabled).toBe(true);await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(receipts()).toHaveLength(1);});
test('Back after a settled account state cannot resurrect the cleared continuation or protected account',async({page})=>{await page.goto('/attorney-v2.html#/settings?tab=blocked');await expect(page.locator('html')).toHaveAttribute('data-attorney-state','ready');await page.getByRole('link',{name:'Account closure',exact:true}).click();await expect(page.getByRole('button',{name:'Deactivate account',exact:true})).toBeEnabled();await confirm(page);await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(await stored(page)).toBeNull();await page.goBack().catch(error=>{if(!/NS_BINDING_ABORTED|Frame load interrupted/.test(String(error.message)))throw error;});await expect(page).toHaveURL(/login.html/);expect(await stored(page)).toBeNull();await expect(page.locator('[data-av2-shell]')).toHaveCount(0);expect(receipts()).toHaveLength(1);});
test('a new same-owner credential requires a new review and retains the new session',async({page,context})=>{await open(page);const replacement=await server.cookieFor(owner.id);await page.route('**/api/csrf',async route=>{await context.addCookies([replacement]);await route.continue();});await confirm(page);await expect(page.getByRole('heading',{name:'Session changed',exact:true})).toBeVisible();expect((await server.inspectUser(owner.id)).disabled).toBe(false);expect((await context.cookies(server.origin)).find(cookie=>cookie.name==='token').value).toBe(replacement.value);expect(await stored(page)).toBeNull();expect(receipts()).toHaveLength(0);});
test('settled historical funding references do not prevent an actual eligible closure',async({page})=>{const historic=await server.createCase(owner.id,{title:'Settled historical Matter',status:'completed',completedAt:new Date(),paymentReleased:true,paidOutAt:new Date(),escrowStatus:'funded',fundingRequestKey:'synthetic-settled-funding-reference'});await open(page);await expect(page.getByRole('button',{name:'Deactivate account',exact:true})).toBeEnabled();await confirm(page);await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();const preserved=await server.inspectCase(historic._id);expect(preserved).toMatchObject({title:'Settled historical Matter',paymentReleased:true,fundingRequestKey:'synthetic-settled-funding-reference'});expect(preserved.paidOutAt).toBeTruthy();expect(receipts()).toHaveLength(1);});
