const { test, expect } = require("../support-session-fixture"), AxeBuilder = require("@axe-core/playwright").default;
const json = (route, value, status = 200) => route.fulfill({ status, contentType: "application/json", body: JSON.stringify(value) });
const panel = page => page.locator("[data-workspace-files]"), removal = page => page.locator("[data-file-removal]"), detail = page => panel(page).getByRole("region", { name: "Document review" });
const id = n => n.toString(16).padStart(24, "0");
const file = (n, patch = {}) => ({ id: id(n), name: `Lease exhibit ${n}.txt`, revision: "d".repeat(64), reviewRevision: "e".repeat(64), size: 40, version: 1, uploadedAt: null, securityStatus: "clean", status: "pending_review", uploadedByRole: "paralegal", notes: "", requestedAt: null, approvedAt: null, replacedAt: null, revisionOf: null, mimeType: "text/plain", canReview: true, ...patch });
async function fixture(page) {
  const user = (await (await page.request.get("/api/auth/me")).json()).user, ownerId = user.id || user._id;
  const csrf = await (await page.request.get("/api/csrf")).json(), fields = { title: "River Street lease — removal", practiceArea: "Contract Law", state: "New York", compAmount: "400.01", experience: "3+ years", deadline: "2027-03-14", description: "Review the lease and its exhibits.", tasks: [{ title: "Review the lease" }] };
  const draftResponse = await page.request.post("/api/case-drafts", { headers: { "X-CSRF-Token": csrf.csrfToken }, data: { ...fields, expectedOwnerId: ownerId } }); expect(draftResponse.ok()).toBeTruthy(); const draft = (await draftResponse.json()).draft;
  const posted = await page.request.post("/api/cases/posting/publications", { headers: { "X-CSRF-Token": csrf.csrfToken }, data: { draftId: draft.id, revision: draft.revision, requestId: require("crypto").randomUUID(), practiceArea: "contract law", expectedOwnerId: ownerId } }); expect(posted.ok()).toBeTruthy(); const caseId = (await posted.json()).publication.caseId;
  const state = { files: [file(100), file(99)], revision: "f".repeat(64), outcome: null, writes: [], lost: false, failure: false, held: false, canRemove: true, readError: false, cleanup: "pending" };
  await page.route(`**/api/cases/${caseId}/files/review?**`, route => {
    const query = new URL(route.request().url()).searchParams, target = query.get("fileId"), selectedFile = state.files.find(file => file.id === target) || null;
    return json(route, { caseId, ownerId, caseTitle: fields.title, access: "available", legacyAttachments: false, canUpload: true, files: state.files, nextCursor: null, selection: target ? selectedFile ? "found" : "unavailable" : "none", selectedFile });
  });
  await page.route(`**/api/uploads/case/${caseId}/upload-review?**`, route => json(route, { caseId, ownerId, revision: "f".repeat(64), canUpload: true, upload: null }));
  await page.route(`**/api/uploads/case/${caseId}/removal-review/*?**`, route => {
    if (state.readError) return json(route, {}, 503);
    const url = new URL(route.request().url()), selected = state.files.find(file => url.pathname.endsWith("/" + file.id)) || null;
    return json(route, { caseId, ownerId, revision: selected ? state.revision : null, file: selected, canRemove: state.canRemove && !!selected, removal: state.outcome });
  });
  state.record = fileId => { state.files = state.files.filter(file => file.id !== fileId); return state.outcome = { status: "removed", fileId, removedAt: "2026-09-08T12:00:00.000Z", exactRequest: true, cleanup: state.cleanup }; };
  await page.route(`**/api/uploads/case/${caseId}/reviewed-removal/*`, async route => {
    const body = route.request().postDataJSON(); state.writes.push(body);
    if (state.held) await new Promise(resolve => { state.release = resolve; });
    if (state.failure) return json(route, { code: "FILE_REMOVAL_CHANGED" }, 409);
    const result = state.record(new URL(route.request().url()).pathname.split("/").at(-1));
    return state.lost ? route.abort("failed") : json(route, { removal: result });
  });
  await page.goto(`/attorney-v2.html#/matters/${caseId}/files`, { waitUntil: "domcontentloaded" }); await expect(panel(page)).toHaveAttribute("data-state", "ready"); return { caseId, ownerId, state };
}
async function open(page) { await panel(page).locator("[data-download-file]").first().getByRole("button").click(); await detail(page).getByRole("button", { name: "Remove document", exact: true }).click(); await expect(removal(page)).toHaveAttribute("data-state", "ready"); }
const confirm = page => removal(page).getByRole("button", { name: "Confirm document removal", exact: true }).click();
test("removal names the document and retained copies before recording one reviewed request", async ({ page }) => {
  const { state, ownerId } = await fixture(page); await open(page); await expect(removal(page)).toContainText("“Lease exhibit 100.txt”, version 1"); await expect(removal(page)).toContainText("Copies still referenced in correspondence or document history remain"); expect(state.writes).toHaveLength(0);
  await confirm(page); await expect(removal(page)).toContainText("Document removed from Files."); await expect(removal(page)).toBeFocused(); await expect(removal(page)).toContainText("Storage cleanup is pending"); await expect(panel(page).locator("[data-download-file]")).toHaveCount(1); expect(state.writes).toHaveLength(1); expect(state.writes[0]).toEqual({ expectedOwnerId: ownerId, requestId: expect.stringMatching(/^[a-f0-9-]{36}$/), reviewedRevision: "f".repeat(64) });
});
test("closing the review leaves the document untouched and uses no native dialog", async ({ page }) => { const { state } = await fixture(page); const dialogs = []; page.on("dialog", dialog => { dialogs.push(dialog.type()); void dialog.dismiss(); }); await open(page); await removal(page).getByRole("button", { name: "Close removal review" }).click(); await expect(removal(page)).toBeHidden(); await expect(detail(page).getByRole("button", { name: "Remove document", exact: true })).toBeFocused(); expect(state.writes).toHaveLength(0); expect(dialogs).toEqual([]); await expect(panel(page).locator("[data-download-file]")).toHaveCount(2); });
test("a lost response recovers the recorded removal without another write", async ({ page }) => { const { state } = await fixture(page); state.lost = true; await open(page); await confirm(page); await expect(removal(page)).toContainText("could not be confirmed"); await removal(page).getByRole("button", { name: "Check removal result" }).click(); await expect(removal(page)).toContainText("Document removed from Files."); expect(state.writes).toHaveLength(1); await expect(panel(page).locator("[data-download-file]")).toHaveCount(1); });
test("an unrecorded removal requires an explicit same-request retry", async ({ page }) => { const { state } = await fixture(page); state.failure = true; await open(page); await confirm(page); await expect(removal(page)).toContainText("could not be confirmed"); state.failure = false; await removal(page).getByRole("button", { name: "Check removal result" }).click(); await expect(removal(page)).toContainText("No removal is recorded"); expect(state.writes).toHaveLength(1); await removal(page).getByRole("button", { name: "Confirm removal again" }).click(); await expect(removal(page)).toContainText("Document removed from Files."); expect(state.writes).toHaveLength(2); expect(state.writes[1]).toEqual(state.writes[0]); });
test("changed displayed contents require a fresh file review", async ({ page }) => { const { state } = await fixture(page); await panel(page).locator("[data-download-file]").first().getByRole("button").click(); state.files[0] = { ...state.files[0], name: "Changed lease.txt", reviewRevision: "a".repeat(64), version: 2 }; await detail(page).getByRole("button", { name: "Remove document", exact: true }).click(); await expect(removal(page)).toContainText("changed since you opened it"); await expect(removal(page).getByRole("button", { name: "Confirm document removal" })).toHaveCount(0); expect(state.writes).toHaveLength(0); });
test("a changed revision after an uncertain write cannot silently retry against current contents", async ({ page }) => { const { state } = await fixture(page); state.failure = true; await open(page); await confirm(page); await expect(removal(page)).toContainText("could not be confirmed"); state.revision = "a".repeat(64); await removal(page).getByRole("button", { name: "Check removal result" }).click(); await expect(removal(page)).toContainText("pending request cannot remove its current contents"); await expect(removal(page).getByRole("button", { name: "Confirm removal again" })).toHaveCount(0); await removal(page).getByRole("button", { name: "Keep current document" }).click(); await expect(removal(page)).toBeHidden(); expect(state.writes).toHaveLength(1); });
test("pending removal survives a Matter tab change and clears confidential memory on account loss", async ({ page }) => { const { state } = await fixture(page); state.lost = true; await open(page); await confirm(page); await expect(removal(page)).toContainText("could not be confirmed"); expect(await page.evaluate(() => [...Object.values(localStorage), ...Object.values(sessionStorage)].join(" "))).not.toContain("Lease exhibit 100.txt"); await page.getByRole("navigation", { name: "Matter sections" }).getByRole("link", { name: "Work", exact: true }).click(); await page.getByRole("navigation", { name: "Matter sections" }).getByRole("link", { name: "Files", exact: true }).click(); await expect(removal(page)).toContainText("Document removed from Files."); expect(state.writes).toHaveLength(1); await page.route("**/api/auth/me", route => json(route, { user: { id: "9".repeat(24), role: "attorney", status: "approved" } })); await panel(page).getByRole("button", { name: "Refresh files", exact: true }).click(); await expect(panel(page)).toHaveCount(0); });
test("Stop waiting keeps an in-flight removal uncertain until its result is checked", async ({ page }) => { const { state } = await fixture(page); state.held = true; await open(page); await confirm(page); await expect.poll(() => Boolean(state.release)).toBe(true); await removal(page).getByRole("button", { name: "Stop waiting" }).click(); await expect(removal(page)).toContainText("may still finish"); state.release(); await expect.poll(() => state.outcome?.status).toBe("removed"); await removal(page).getByRole("button", { name: "Check removal result" }).click(); await expect(removal(page)).toContainText("Document removed from Files."); expect(state.writes).toHaveLength(1); });
test("a storage reference hold is described without claiming that all copies were deleted", async ({ page }) => { const { state } = await fixture(page); state.cleanup = "retained"; await open(page); await confirm(page); await expect(removal(page)).toContainText("A stored copy remains because it is still referenced"); });
test("unavailable review and a changed account cannot remove the selected document", async ({ page }) => { const { state } = await fixture(page); state.canRemove = false; await panel(page).locator("[data-download-file]").first().getByRole("button").click(); await detail(page).getByRole("button", { name: "Remove document", exact: true }).click(); await expect(removal(page)).toContainText("cannot currently be removed"); state.canRemove = true; await removal(page).getByRole("button", { name: "Close removal review" }).click(); await detail(page).getByRole("button", { name: "Remove document", exact: true }).click(); await expect(removal(page)).toHaveAttribute("data-state", "ready"); await page.route("**/api/auth/me", route => json(route, { user: { id: "9".repeat(24), role: "attorney", status: "approved" } })); await confirm(page); await expect(panel(page)).toHaveCount(0); expect(state.writes).toHaveLength(0); });
test("the removal confirmation fits phone and desktop widths with accessible controls", async ({ page }, testInfo) => { await fixture(page); await open(page); for (const width of [320, 390, 768, 1366]) { await page.setViewportSize({ width, height: 900 }); await removal(page).scrollIntoViewIfNeeded(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); expect((await new AxeBuilder({ page }).include("[data-workspace-files]").withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]); await page.screenshot({ path: testInfo.outputPath(`removal-${width}.png`), fullPage: true }); } });
