const { test, expect } = require("../support-session-fixture"), AxeBuilder = require("@axe-core/playwright").default;
const json = (route, value, status = 200) => route.fulfill({ status, contentType: "application/json", body: JSON.stringify(value) });
const panel = page => page.locator("[data-workspace-files]"), detail = page => panel(page).getByRole("region", { name: "Document review" });
const id = n => n.toString(16).padStart(24, "0");
const file = (n, patch = {}) => ({ id: id(n), name: `Lease exhibit ${n}.txt`, revision: "d".repeat(64), reviewRevision: "e".repeat(64), size: 40, version: 1, uploadedAt: null, securityStatus: "clean", status: "pending_review", uploadedByRole: "paralegal", notes: "", requestedAt: null, approvedAt: null, replacedAt: null, revisionOf: null, mimeType: "text/plain", canReview: true, ...patch });
async function fixture(page) {
  const user = (await (await page.request.get("/api/auth/me")).json()).user, ownerId = user.id || user._id;
  const csrf = await (await page.request.get("/api/csrf")).json(), fields = { title: "River Street lease — files", practiceArea: "Contract Law", state: "New York", compAmount: "400.01", experience: "3+ years", deadline: "2027-03-14", description: "Review the lease and its exhibits.", tasks: [{ title: "Review the lease" }] };
  const draftResponse = await page.request.post("/api/case-drafts", { headers: { "X-CSRF-Token": csrf.csrfToken }, data: { ...fields, expectedOwnerId: ownerId } }); expect(draftResponse.ok()).toBeTruthy(); const draft = (await draftResponse.json()).draft;
  const posted = await page.request.post("/api/cases/posting/publications", { headers: { "X-CSRF-Token": csrf.csrfToken }, data: { draftId: draft.id, revision: draft.revision, requestId: require("crypto").randomUUID(), practiceArea: "contract law", expectedOwnerId: ownerId } }); expect(posted.ok()).toBeTruthy(); const caseId = (await posted.json()).publication.caseId;
  const state = { replaceOutcome: null, replaceWrites: [], replaceLost: false, replaceFailure: false, replaceHeld: false, canReplace: true, files: [file(100), file(99)], writes: [], error: false, lost: false, conflict: false, downloads: 0 };
  const pattern = `**/api/cases/${caseId}/files/review?**`;
  await page.route(pattern, route => {
    if (state.error) return json(route, {}, 503);
    const query = new URL(route.request().url()).searchParams, target = query.get("fileId"), cursor = query.get("cursor"), rows = state.files.filter(file => !cursor || file.id < cursor), files = rows.slice(0, 50), selectedFile = state.files.find(file => file.id === target) || null;
    return json(route, { caseId, ownerId, caseTitle: fields.title, access: "available", legacyAttachments: false, canUpload: true, files, nextCursor: rows.length > 50 ? files.at(-1).id : null, selection: target ? selectedFile ? "found" : "unavailable" : "none", selectedFile });
  });
  await page.route(`**/api/cases/${caseId}/files/*/review`, route => {
    const body = route.request().postDataJSON(); state.writes.push(body); const selected = state.files.find(file => route.request().url().includes(`/${file.id}/review`));
    if (state.conflict || body.reviewedRevision !== selected.reviewRevision) return json(route, { code: "DOCUMENT_CHANGED" }, 409);
    selected.status = body.status; selected.notes = body.notes; selected.reviewRevision = require("crypto").randomBytes(32).toString("hex"); selected.approvedAt = body.status === "approved" ? new Date().toISOString() : null; selected.requestedAt = body.status === "attorney_revision" ? new Date().toISOString() : null;
    return state.lost ? route.abort("failed") : json(route, { file: selected });
  });
  await page.route(`**/api/cases/${caseId}/downloads/*?**`, route => { state.downloads++; return route.fulfill({ contentType: "application/octet-stream", body: '<img src=x onerror="window.syntheticFileXss=true">\nExhibit B remains attached.' }); });
  await page.route(`**/api/uploads/case/${caseId}/upload-review?**`,route=>json(route,{caseId,ownerId,revision:"f".repeat(64),canUpload:true,upload:null}));
  await page.route(`**/api/uploads/case/${caseId}/replacement-review/*?**`,route=>{
    const url=new URL(route.request().url()),target=state.files.find(file=>url.pathname.endsWith('/'+file.id))||null;
    return json(route,{caseId,ownerId,revision:'f'.repeat(64),canUpload:state.canReplace&&!!target,target,upload:url.searchParams.get('requestId')?state.replaceOutcome||{status:'missing',file:null,retryAllowed:true}:null});
  });
  state.recordReplacement=()=>{const target=state.files[0];Object.assign(target,{name:'Replacement.txt',version:2,status:'attorney_revision',uploadedByRole:'attorney',canReview:false,reviewRevision:'c'.repeat(64),notes:'',approvedAt:null,requestedAt:null});return state.replaceOutcome={status:'recorded',file:target,retryAllowed:false};};
  await page.route(`**/api/uploads/case/${caseId}/reviewed-replacement/*`,async route=>{
    const body=route.request().postDataBuffer().toString('utf8'),part=key=>body.match(new RegExp('name="'+key+'"\\r\\n\\r\\n([^\\r]+)'))?.[1];state.replaceWrites.push({body,requestId:part('requestId'),revision:part('reviewedFileRevision')});
    if(state.replaceHeld)await new Promise(resolve=>{state.releaseReplacement=resolve;});
    if(state.replaceFailure){state.replaceOutcome={status:'unconfirmed',file:null,retryAllowed:true};return json(route,{code:'FILE_UPLOAD_TARGET_CHANGED'},409);}
    const outcome=state.recordReplacement();return state.replaceLost?route.abort('failed'):json(route,outcome);
  });
  await page.goto(`/attorney-v2.html#/matters/${caseId}/files`, { waitUntil: "domcontentloaded" }); await expect(panel(page)).toHaveAttribute("data-state", "ready"); return { caseId, ownerId, state, pattern };
}
const replacement=page=>page.locator('[data-file-replacement]');
async function openReplacement(page){await panel(page).locator('[data-download-file]').first().getByRole('button').click();await detail(page).getByRole('button',{name:'Replace document',exact:true}).click();await expect(replacement(page)).toHaveAttribute('data-state','ready');}
const selectReplacement=page=>replacement(page).getByLabel('Replacement document',{exact:true}).setInputFiles({name:'Replacement.txt',mimeType:'text/plain',buffer:Buffer.from('PRIVATE_REPLACEMENT_BYTES')});
const confirmReplacement=async page=>{await replacement(page).getByRole('button',{name:'Review selected document'}).click();await replacement(page).getByRole('button',{name:'Confirm replacement'}).click();};
test('replacement names the current version and verifies native bytes at the same-origin receiver',async({page})=>{
 const {caseId,ownerId,state}=await fixture(page),received=[],http=require('node:http');
 const server=http.createServer(async(req,res)=>{if(req.url!==`/api/uploads/case/${caseId}/reviewed-replacement/${id(100)}`){const upstream=http.request({hostname:'127.0.0.1',port:5051,path:req.url,method:req.method,headers:{...req.headers,host:'127.0.0.1:5051'},agent:false},result=>{res.writeHead(result.statusCode,result.headers);result.pipe(res);});upstream.on('error',()=>{if(!res.headersSent)res.writeHead(502);res.end();});res.on('close',()=>upstream.destroy());req.pipe(upstream);return;}const chunks=[];for await(const chunk of req)chunks.push(chunk);received.push(Buffer.concat(chunks).toString('utf8'));res.setHeader('Content-Type','application/json');res.end(JSON.stringify(state.recordReplacement()));});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{await page.unroute(`**/api/uploads/case/${caseId}/reviewed-replacement/*`);await page.goto('http://127.0.0.1:'+server.address().port+'/attorney-v2.html#/matters/'+caseId+'/files');await expect(panel(page)).toHaveAttribute('data-state','ready');await openReplacement(page);await selectReplacement(page);await replacement(page).getByRole('button',{name:'Review selected document'}).click();await expect(replacement(page)).toContainText('Replace “Lease exhibit 100.txt”, version 1, with “Replacement.txt”');await expect(replacement(page)).toContainText('Prior contents remain in document history');expect(received).toHaveLength(0);await replacement(page).getByRole('button',{name:'Confirm replacement'}).click();await expect(panel(page).locator('[data-file-feedback]')).toHaveText('Document replaced.');await expect(detail(page)).toContainText('Replacement.txt');expect(received).toHaveLength(1);expect(received[0]).toContain(ownerId);expect(received[0]).toContain('e'.repeat(64));expect(received[0]).toContain('PRIVATE_REPLACEMENT_BYTES');expect(state.files[1].name).toBe('Lease exhibit 99.txt');}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
});
test('lost replacement is checked without sending another document',async({page})=>{const {state}=await fixture(page);state.replaceLost=true;await openReplacement(page);await selectReplacement(page);await confirmReplacement(page);await expect(replacement(page)).toContainText('could not be confirmed');expect(state.replaceWrites).toHaveLength(1);await replacement(page).getByRole('button',{name:'Check saved upload'}).click();await expect(panel(page).locator('[data-file-feedback]')).toHaveText('Document replaced.');expect(state.replaceWrites).toHaveLength(1);await expect(detail(page)).toContainText('Replacement.txt');});
test('a conflicting replacement requires a fresh check and explicit retry with the same request',async({page})=>{const {state}=await fixture(page);state.replaceFailure=true;await openReplacement(page);await selectReplacement(page);await confirmReplacement(page);await expect(replacement(page)).toContainText('Matter or upload changed');state.replaceFailure=false;await replacement(page).getByRole('button',{name:'Check saved upload'}).click();await replacement(page).getByRole('button',{name:'Retry this file'}).click();await replacement(page).getByRole('button',{name:'Confirm replacement'}).click();await expect(panel(page).locator('[data-file-feedback]')).toHaveText('Document replaced.');expect(state.replaceWrites).toHaveLength(2);expect(state.replaceWrites[0].requestId).toBeTruthy();expect(state.replaceWrites[1].requestId).toBe(state.replaceWrites[0].requestId);});
test('a document changed since selection is named with its current version before confirmation',async({page})=>{const {state}=await fixture(page);await panel(page).locator('[data-download-file]').first().getByRole('button').click();state.files[0]={...state.files[0],name:'Current exhibit.txt',version:5,reviewRevision:'a'.repeat(64)};await detail(page).getByRole('button',{name:'Replace document',exact:true}).click();await expect(replacement(page)).toContainText('document changed since Files loaded');await selectReplacement(page);await replacement(page).getByRole('button',{name:'Review selected document'}).click();await expect(replacement(page)).toContainText('Replace “Current exhibit.txt”, version 5');await replacement(page).getByRole('button',{name:'Confirm replacement'}).click();await expect(panel(page).locator('[data-file-feedback]')).toHaveText('Document replaced.');expect(state.replaceWrites[0].revision).toBe('a'.repeat(64));});
test('selection survives another document and route while staying private to this tab',async({page})=>{await fixture(page);await openReplacement(page);await selectReplacement(page);await panel(page).locator('[data-download-file]').nth(1).getByRole('button').click();await openReplacement(page);await expect(replacement(page)).toContainText('Replacement.txt');await page.getByRole('navigation',{name:'Matter sections'}).getByRole('link',{name:'Work',exact:true}).click();await page.getByRole('navigation',{name:'Matter sections'}).getByRole('link',{name:'Files',exact:true}).click();await expect(panel(page)).toHaveAttribute('data-state','ready');await openReplacement(page);await expect(replacement(page)).toContainText('Replacement.txt');expect(await page.evaluate(()=>[...Object.values(localStorage),...Object.values(sessionStorage)].join(' '))).not.toMatch(/Replacement.txt|PRIVATE_REPLACEMENT_BYTES/);});
test('a recorded replacement superseded later is described as earlier evidence',async({page})=>{const {state}=await fixture(page);state.replaceLost=true;await openReplacement(page);await selectReplacement(page);await confirmReplacement(page);await expect(replacement(page)).toContainText('could not be confirmed');state.replaceOutcome={...state.replaceOutcome,changedSinceUpload:true};await replacement(page).getByRole('button',{name:'Check saved upload'}).click();await expect(panel(page).locator('[data-file-feedback]')).toContainText('earlier replacement was recorded');await expect(panel(page).locator('[data-file-feedback]')).toContainText('since changed again');expect(state.replaceWrites).toHaveLength(1);});
test('restricted replacement and changed account cannot send selected contents',async({page})=>{const {state}=await fixture(page);state.canReplace=false;await openReplacement(page);await expect(replacement(page)).toContainText('cannot currently be replaced');await expect(replacement(page).getByLabel('Replacement document',{exact:true})).toHaveCount(0);state.canReplace=true;await panel(page).getByRole('button',{name:'Refresh files',exact:true}).click();await openReplacement(page);await selectReplacement(page);await replacement(page).getByRole('button',{name:'Review selected document'}).click();await page.route('**/api/auth/me',route=>json(route,{user:{id:'9'.repeat(24),role:'attorney',status:'approved'}}));await replacement(page).getByRole('button',{name:'Confirm replacement'}).click();await expect(panel(page)).toHaveCount(0);expect(state.replaceWrites).toHaveLength(0);});
test('replacement confirmation has distinct labels and remains accessible on phone and desktop',async({page},testInfo)=>{await fixture(page);await openReplacement(page);await selectReplacement(page);await replacement(page).getByRole('button',{name:'Review selected document'}).click();for(const width of [320,390,768,1366]){await page.setViewportSize({width,height:900});await replacement(page).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect((await new AxeBuilder({page}).include('[data-workspace-files]').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);await page.screenshot({path:testInfo.outputPath('replacement-'+width+'.png'),fullPage:true});}});
test('leaving an active replacement retains its request and recovers without another send',async({page})=>{
 const {state}=await fixture(page);state.replaceHeld=true;await openReplacement(page);await selectReplacement(page);await confirmReplacement(page);await expect.poll(()=>Boolean(state.releaseReplacement)).toBe(true);await page.getByRole('navigation',{name:'Matter sections'}).getByRole('link',{name:'Work',exact:true}).click();state.releaseReplacement();await expect.poll(()=>state.replaceOutcome?.status).toBe('recorded');await page.getByRole('navigation',{name:'Matter sections'}).getByRole('link',{name:'Files',exact:true}).click();await expect(panel(page)).toHaveAttribute('data-state','ready');await panel(page).locator('[data-download-file]').first().getByRole('button').click();await detail(page).getByRole('button',{name:'Replace document',exact:true}).click();await expect(panel(page).locator('[data-file-feedback]')).toHaveText('Document replaced.');expect(state.replaceWrites).toHaveLength(1);
});
