const { test, expect } = require("../support-session-fixture"), AxeBuilder = require("@axe-core/playwright").default;
const json = (route, value, status = 200) => route.fulfill({ status, contentType: "application/json", body: JSON.stringify(value) });
const panel = page => page.locator("[data-workspace-files]"), detail = page => panel(page).getByRole("region", { name: "Document review" });
const id = n => n.toString(16).padStart(24, "0");
const file = (n, patch = {}) => ({ id: id(n), name: `Lease exhibit ${n}.txt`, revision: "d".repeat(64), reviewRevision: "e".repeat(64), size: 40, version: 1, uploadedAt: null, securityStatus: "clean", status: "pending_review", uploadedByRole: "paralegal", notes: "", requestedAt: null, approvedAt: null, replacedAt: null, revisionOf: null, mimeType: "text/plain", canReview: true, ...patch });
async function fixture(page) {
  const user = (await (await page.request.get("/api/auth/me")).json()).user, ownerId = user.id || user._id;
  const csrf = await (await page.request.get("/api/csrf")).json(), fields = { title: "River Street lease — files", practiceArea: "Contract Law", state: "New York", compAmount: "400.01", experience: "3+ years", deadline: "2027-03-14", description: "Review the lease and its exhibits.", tasks: [{ title: "Review the lease" }] };
  const draftResponse = await page.request.post("/api/case-drafts", { headers: { "X-CSRF-Token": csrf.csrfToken }, data: { ...fields, expectedOwnerId: ownerId } }); expect(draftResponse.ok()).toBeTruthy(); const draft = (await draftResponse.json()).draft;
  const posted = await page.request.post("/api/cases/posting/publications", { headers: { "X-CSRF-Token": csrf.csrfToken }, data: { draftId: draft.id, revision: draft.revision, requestId: require("crypto").randomUUID(), practiceArea: "contract law", expectedOwnerId: ownerId } }); expect(posted.ok()).toBeTruthy(); const caseId = (await posted.json()).publication.caseId;
  const state = { historyEntries: Array.from({length:31},(_,i)=>({index:30-i,retainedAt:new Date(1700000000000+i*1000).toISOString(),revision:'a'.repeat(64),hasStoredDocument:true})), responses: [], historyFailure: false, historyDownloads: 0, historyHeld: false, files: [file(100), file(99)], writes: [], error: false, lost: false, conflict: false, downloads: 0 };
  const pattern = `**/api/cases/${caseId}/files/review?**`;
  await page.route(pattern, route => {
    if (state.error) return json(route, {}, 503);
    const query = new URL(route.request().url()).searchParams, target = query.get("fileId"), cursor = query.get("cursor"), rows = state.files.filter(file => !cursor || file.id < cursor), files = rows.slice(0, 50), selectedFile = state.files.find(file => file.id === target) || null;
    return json(route, { caseId, ownerId, caseTitle: fields.title, access: "available", legacyAttachments: false, canUpload: true, files, nextCursor: rows.length > 50 ? files.at(-1).id : null, selection: target ? selectedFile ? "found" : "unavailable" : "none", selectedFile });
  });
  await page.route(`**/api/cases/${caseId}/files/*/review`, route => {
    const body = route.request().postDataJSON(); state.writes.push(body); const selected = state.files.find(file => route.request().url().includes(`/${file.id}/review`));
    if (state.conflict || body.reviewedRevision !== selected.reviewRevision) return json(route, { code: "DOCUMENT_CHANGED" }, 409);
    selected.status = body.status; selected.notes = body.notes; selected.reviewRevision = require("crypto").randomBytes(32).toString("hex"); selected.approvedAt = body.status === "approved" ? new Date().toISOString() : null; selected.requestedAt = body.status === "attorney_revision" ? new Date().toISOString() : null;
    return state.lost ? route.abort("failed") : json(route, { file: selected });
  });
  await page.route(`**/api/cases/${caseId}/downloads/*?**`, route => { state.downloads++; return route.fulfill({ contentType: "application/octet-stream", body: '<img src=x onerror="window.syntheticFileXss=true">\nExhibit B remains attached.' }); });
  await page.route(`**/api/cases/${caseId}/files/*/history?**`,async route=>{
    if(state.historyHeld)await new Promise(resolve=>{state.releaseHistory=resolve;});
    if(state.historyFailure)return json(route,{code:'DOCUMENT_HISTORY_CHANGED'},state.historyStatus||409);
    const query=new URL(route.request().url()).searchParams,offset=Number(query.get('cursor')||0),cursor=query.get('responseCursor'),responses=state.responses.filter(file=>!cursor||file.id<cursor),entries=state.historyEntries.slice(offset,offset+25),rows=responses.slice(0,25);
    return json(route,{caseId,ownerId,fileId:route.request().url().match(/files\/([a-f0-9]{24})\/history/)[1],revision:'b'.repeat(64),entries,nextCursor:offset+entries.length<state.historyEntries.length?String(offset+entries.length):null,responses:rows,nextResponseCursor:responses.length>25?rows.at(-1).id:null});
  });
  await page.route(`**/api/cases/${caseId}/files/*/history/*/download?**`,route=>{state.historyDownloads++;return route.fulfill({contentType:'application/octet-stream',headers:{'Content-Disposition':'attachment; filename="Earlier document"'},body:'Earlier legal document'});});
  await page.goto(`/attorney-v2.html#/matters/${caseId}/files`, { waitUntil: "domcontentloaded" }); await expect(panel(page)).toHaveAttribute("data-state", "ready"); return { caseId, ownerId, state, pattern };
}
const history=page=>page.locator('[data-file-history]');
async function open(page){await panel(page).locator('[data-download-file]').first().getByRole('button').click();await history(page).getByRole('button',{name:'Document history',exact:true}).click();await expect(history(page)).toContainText('Earlier contents');}
test('earlier contents paginate without invented version numbers and download exact selected bytes',async({page})=>{const {state}=await fixture(page);await open(page);await expect(history(page).getByRole('button',{name:'Download earlier contents'})).toHaveCount(25);await expect(history(page)).toContainText('original names, sizes and version numbers may not have been retained');await history(page).getByRole('button',{name:'More earlier contents'}).click();await expect(history(page).getByRole('button',{name:'Download earlier contents'})).toHaveCount(31);const promised=page.waitForEvent('download');await history(page).getByRole('button',{name:'Download earlier contents'}).first().click();const download=await promised;expect(download.suggestedFilename()).toBe('Earlier document');await expect(history(page)).toContainText('handed to your browser');expect(state.historyDownloads).toBe(1);});
test('linked responses preserve current review status and lead to the exact document',async({page})=>{const {caseId,state}=await fixture(page);state.responses=Array.from({length:28},(_,i)=>file(200-i,{name:'Lease response '+i+'.txt',revisionOf:{id:id(100),version:1,requestedAt:null},status:i===0?'approved':'pending_review'}));state.files.push(...state.responses);await open(page);await expect(history(page).getByRole('link')).toHaveCount(25);await history(page).getByRole('button',{name:'More responses'}).click();await expect(history(page).getByRole('link')).toHaveCount(28);await expect(history(page)).toContainText('Approved · In response to version 1');await history(page).getByRole('link',{name:'Lease response 0.txt',exact:true}).click();await expect(page).toHaveURL(new RegExp(caseId+'/files\\?fileId='+id(200)));await expect(detail(page)).toContainText('Lease response 0.txt');});
test('changed history is an explicit refresh state and cannot download an old selection',async({page})=>{const {state}=await fixture(page);state.historyFailure=true;await panel(page).locator('[data-download-file]').first().getByRole('button').click();await history(page).getByRole('button',{name:'Document history',exact:true}).click();await expect(history(page)).toContainText('document changed');await expect(history(page).getByRole('button',{name:'Download earlier contents'})).toHaveCount(0);expect(state.historyDownloads).toBe(0);});
test('late history responses are discarded when another document is selected',async({page})=>{const {state}=await fixture(page);state.historyHeld=true;await panel(page).locator('[data-download-file]').first().getByRole('button').click();await history(page).getByRole('button',{name:'Document history',exact:true}).click();await expect.poll(()=>Boolean(state.releaseHistory)).toBe(true);await panel(page).locator('[data-download-file]').nth(1).getByRole('button').click();state.releaseHistory();await expect(detail(page)).toContainText('Lease exhibit 99.txt');await expect(history(page).getByRole('button',{name:'Download earlier contents'})).toHaveCount(0);});
test('history remains readable on phone and desktop with accessible controls',async({page},testInfo)=>{const {state}=await fixture(page);state.historyEntries=state.historyEntries.slice(0,2);state.responses=[file(200,{name:'Lease revision in response to the missing exhibit.txt',revisionOf:{id:id(100),version:1,requestedAt:null}})];await open(page);for(const width of [320,390,768,1366]){await page.setViewportSize({width,height:900});await history(page).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect((await new AxeBuilder({page}).include('[data-file-history]').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);await page.screenshot({path:testInfo.outputPath('history-'+width+'.png'),fullPage:true});}});
test('history access loss clears the loaded document details and list',async({page})=>{const {state}=await fixture(page);state.historyFailure=true;state.historyStatus=403;await panel(page).locator('[data-download-file]').first().getByRole('button').click();await history(page).getByRole('button',{name:'Document history',exact:true}).click();await expect(panel(page)).toHaveAttribute('data-state','restricted');await expect(panel(page).locator('[data-download-file]')).toHaveCount(0);await expect(panel(page).locator('.av2-file-detail')).toBeEmpty();});
