const { test, expect } = require("../support-session-fixture"), AxeBuilder = require("@axe-core/playwright").default;
const id = n => n.toString(16).padStart(24, "0"), hash = n => n.toString(16).padStart(64, "0"), panel = page => page.locator("[data-financial-history]");
const fulfill = (route, body, status = 200) => route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) });
const row = (n, patch = {}) => ({ id: hash(n), caseId: id(n), caseTitle: `River Street lease ${n}`, type: "funding", state: "recorded", amount: 48800, currency: "USD", recordedAt: "2026-01-03T00:00:00.000Z", basis: "original_payment", receiptId: "payment", paralegalName: null, ...patch });
function summary(entries) {
  const groups = new Map();
  for (const item of entries) {
    if (!item.currency) continue;
    if (!groups.has(item.currency)) groups.set(item.currency, { currency: item.currency, originalFunding: 0, paralegalPayouts: 0, refunds: 0, refundRecords: 0, refundsUnverified: 0, fundingRecords: 0, payoutRecords: 0, fundingUnverified: 0, payoutsUnverified: 0 });
    const group = groups.get(item.currency);
    if (item.type === "funding") { if (item.state === "recorded") { group.originalFunding += item.amount; group.fundingRecords++; } else group.fundingUnverified++; }
    if (item.type === "refund") { if (item.state === "recorded") { group.refunds += item.amount; group.refundRecords++; } else group.refundsUnverified++; }
    if (item.type === "payout") { if (item.state === "recorded") { group.paralegalPayouts += item.amount; group.payoutRecords++; } else group.payoutsUnverified++; }
  }
  return { currencies: [...groups.values()], requiresReview: entries.filter(item => ["unconfirmed", "needs_review", "requires_action"].includes(item.state)).length, pending: entries.filter(item => item.state === "pending").length, undated: entries.filter(item => !item.recordedAt).length };
}
async function fixture(page, entries = [row(1), row(2, { type: "payout", amount: 8100, basis: "paralegal_payout", receiptId: hash(9), paralegalName: "Priya Ng" }), row(3, { type: "refund", state: "unconfirmed", basis: "refund_request" })]) {
  const user = (await (await page.request.get("/api/auth/me")).json()).user, ownerId = user.id || user._id;
  const state = { entries, reads: [], exports: [], status: 200, csvStatus: 200, revision: hash(999), invalidSummary: false, contentType: "text/csv", csvBody: null };
  const selected = query => state.entries.filter(item => (!query.get("caseId") || item.caseId === query.get("caseId")) && item.caseTitle.toLowerCase().includes((query.get("q") || "").toLowerCase()) && (!query.get("view") || query.get("view") === "all" || query.get("view") === "review" && ["unconfirmed", "needs_review", "requires_action"].includes(item.state) || item.type === query.get("view")));
  await page.route("**/api/payments/payment-method/default?**", route => fulfill(route, { hasDefault: false, paymentMethod: null }));
  await page.route("**/api/users/me/pending-hire?**", route => fulfill(route, { ownerId, revision: hash(1), pending: null }));
  await page.route("**/api/payments/attorney-records?**", route => { const q = new URL(route.request().url()).searchParams; return fulfill(route, { ownerId, view: q.get("view") || "all", q: q.get("q") || "", total: 0, items: [], nextCursor: null, selected: null, selection: q.has("caseId") ? "unavailable" : "none" }); });
  await page.route("**/api/payments/attorney-financial-history?**", route => {
    const q = new URL(route.request().url()).searchParams; state.reads.push(Object.fromEntries(q)); if (state.status !== 200) return fulfill(route, {}, state.status);
    const entries = selected(q), cursor = Number(q.get("cursor") || 0), totals = summary(entries); if (state.invalidSummary && totals.currencies.length) totals.currencies[0].originalFunding = 1;
    return fulfill(route, { ownerId, revision: state.revision, view: q.get("view") || "all", q: q.get("q") || "", caseId: q.get("caseId"), total: entries.length, entries: entries.slice(cursor, cursor + 50), nextCursor: cursor + 50 < entries.length ? String(cursor + 50) : null, summary: totals });
  });
  await page.route("**/api/payments/attorney-financial-history/csv?**", route => {
    const q = new URL(route.request().url()).searchParams; state.exports.push(Object.fromEntries(q)); if (state.csvStatus !== 200) return fulfill(route, {}, state.csvStatus);
    const quote = value => `"${String(value).replace(/"/g, '""')}"`, csv = '\uFEFF"Matter","Record","Status","Currency","Amount","Amount describes"\r\n' + selected(q).map(item => [item.caseTitle, item.type, item.state, item.currency || "", item.amount === null ? "" : (item.amount / 100).toFixed(2), item.basis].map(quote).join(",")).join("\r\n") + "\r\n";
    return route.fulfill({ status: 200, contentType: state.contentType, body: state.csvBody ?? csv });
  });
  await page.goto("/attorney-v2.html#/payments", { waitUntil: "domcontentloaded" }); await expect(panel(page)).toHaveAttribute("data-state", "ready"); return { state, ownerId };
}
test("history separates original funding, retained payouts and unconfirmed refunds with exact receipt links", async ({ page }) => {
  await fixture(page); const history = panel(page); await expect(page.locator(".av2-view-header")).not.toContainText("undefined"); await expect(page.locator('[aria-label="Payment card"]')).toContainText("No default payment card is saved"); await expect(history).toContainText("3 of 3 records shown"); await expect(history.locator("dl")).toContainText("$488.00"); await expect(history.locator("dl")).toContainText("$81.00"); await expect(history).toContainText("Requested refund; processing not confirmed"); await expect(history).not.toContainText("Refund processed");
  await expect(history.locator(`[data-financial-record="${hash(1)}"]`).getByRole("link", { name: "Review original funding receipt" })).toHaveAttribute("href", `#/matters/${id(1)}/receipt?receiptId=payment`);
  await expect(history.locator(`[data-financial-record="${hash(2)}"]`).getByRole("link", { name: "Review withdrawal receipt" })).toHaveAttribute("href", `#/matters/${id(2)}/receipt?receiptId=${hash(9)}`);
});
test("completed refunds have a separate total and each other refund outcome remains explicit", async ({ page }) => {
  const refunds = [["recorded", "refund_processed"], ["pending", "refund_pending"], ["requires_action", "refund_action"], ["failed", "refund_failed"], ["canceled", "refund_canceled"], ["unconfirmed", "refund_request"]].map(([state, basis], index) => row(index + 3, { type: "refund", state, basis, amount: 10000 + index, recordedAt: index === 0 ? null : "2026-01-04T00:00:00.000Z" }));
  await fixture(page, [row(1), row(2, { type: "payout", basis: "paralegal_payout", amount: 8100, receiptId: null }), ...refunds]);
  const history = panel(page); await expect(history.locator("dl")).toContainText("Original funding · USD"); await expect(history.locator("dl")).toContainText("$488.00"); await expect(history.locator("dl")).toContainText("$81.00"); await expect(history.locator("dl")).toContainText("Refunds recorded by Stripe · USD"); await expect(history.locator("dl")).toContainText("$100.00"); await expect(history.locator("dl")).toContainText("5 refund records not included");
  for (const text of ["Refund · Recorded", "Refund · Pending", "Refund · Action required", "Refund · Failed", "Refund · Canceled", "Current status not confirmed", "Date not recorded"]) await expect(history).toContainText(text);
  await history.getByLabel("Record type", { exact: true }).selectOption("review"); await history.getByRole("button", { name: "Apply filters" }).click(); await expect(history).toContainText("2 of 2 records shown"); await expect(history).toContainText("Refund requires action"); await expect(history).toContainText("Requested refund; processing not confirmed");
});
test("contradictory refund responses clear earlier amounts before CSV can be downloaded", async ({ page }) => {
  const { state } = await fixture(page, [row(1, { type: "refund", state: "recorded", basis: "refund_processed", amount: 10000 })]);
  await expect(panel(page).locator("dl")).toContainText("$100.00"); state.entries[0].basis = "refund_request";
  await panel(page).getByRole("button", { name: "Refresh financial history" }).click(); await expect(panel(page)).toHaveAttribute("data-state", "error"); await expect(panel(page).locator("dl")).toHaveCount(0); await expect(panel(page).locator("[data-financial-record]")).toHaveCount(0); await expect(panel(page).getByRole("button", { name: "Download CSV" })).toBeDisabled();
});
test("paging and CSV use the complete filtered history beyond five hundred records", async ({ page }) => {
  const { state, ownerId } = await fixture(page, Array.from({ length: 505 }, (_, i) => row(i + 1)));
  await expect(panel(page).locator("[data-financial-record]")).toHaveCount(50); await expect(panel(page)).toContainText("50 of 505"); await panel(page).getByRole("button", { name: "More records", exact: true }).click(); await expect(panel(page).locator("[data-financial-record]")).toHaveCount(100); expect(state.reads.at(-1)).toMatchObject({ cursor: "50", revision: hash(999) });
  const pending = page.waitForEvent("download"); await panel(page).getByRole("button", { name: "Download CSV" }).click(); const download = await pending, stream = await download.createReadStream(), chunks = []; for await (const chunk of stream) chunks.push(chunk); const csv = Buffer.concat(chunks).toString(); expect(csv.split("\r\n").filter(Boolean)).toHaveLength(506); expect(csv).toContain('"River Street lease 505"'); expect(download.suggestedFilename()).toBe("LPC-payment-history.csv"); expect(state.exports.at(-1)).toMatchObject({ expectedOwnerId: ownerId, view: "all", q: "", revision: hash(999) }); expect(state.exports.at(-1)).not.toHaveProperty("cursor");
});
test("filters recalculate actual counts and amounts, and exact Matter history survives refresh", async ({ page }) => {
  const { state } = await fixture(page); await panel(page).getByLabel("Record type", { exact: true }).selectOption("refund"); await panel(page).getByRole("button", { name: "Apply filters" }).click(); await expect(panel(page)).toContainText("1 of 1 records shown"); await expect(panel(page).locator("dl")).toContainText("No verified completed refund");
  await panel(page).getByLabel("Matter title", { exact: true }).fill("No matching title"); await panel(page).getByRole("button", { name: "Apply filters" }).click(); await expect(panel(page)).toContainText("No financial records match this selection");
  await page.goto(`/attorney-v2.html#/payments?highlightCase=${id(2)}`, { waitUntil: "domcontentloaded" }); await expect(panel(page)).toHaveAttribute("data-state", "ready"); await expect(panel(page)).toContainText("Financial history for the linked Matter"); await expect(panel(page)).toContainText("1 of 1"); expect(state.reads.at(-1).caseId).toBe(id(2)); await page.reload(); await expect(panel(page)).toHaveAttribute("data-state", "ready"); expect(state.reads.at(-1).caseId).toBe(id(2)); await expect(panel(page).getByRole("link", { name: "View financial history for all Matters" })).toHaveAttribute("href", "#/payments");
});
test("reversed payouts, missing currency and missing dates are never presented as verified totals", async ({ page }) => {
  await fixture(page, [row(1, { type: "payout", state: "reversed", basis: "paralegal_payout", receiptId: null }), row(2, { state: "needs_review", amount: null, currency: null, recordedAt: null, basis: "funding_to_verify" }), row(3, { currency: "EUR" })]);
  await expect(panel(page)).toContainText("Reversed"); await expect(panel(page)).toContainText("Amount not verified"); await expect(panel(page)).toContainText("Date not recorded"); await expect(panel(page).locator("dl")).toContainText("No verified payout amount"); await expect(panel(page).locator("dl")).toContainText("€488.00"); await expect(panel(page).locator("dl")).not.toContainText("$488.00");
});
test("changed snapshots, failed reads and invalid totals clear old amounts and never become empty history", async ({ page }) => {
  const { state } = await fixture(page, Array.from({ length: 55 }, (_, i) => row(i + 1))); state.revision = hash(1000); await panel(page).getByRole("button", { name: "More records", exact: true }).click(); await expect(panel(page)).toHaveAttribute("data-state", "error"); await expect(panel(page).locator("[data-financial-record]")).toHaveCount(0); await expect(panel(page).locator("dl")).toHaveCount(0);
  state.status = 503; await panel(page).getByRole("button", { name: "Refresh financial history" }).click(); await expect(panel(page)).toContainText("Financial history couldn’t load"); await expect(panel(page)).not.toContainText("No financial records match"); state.status = 200; state.invalidSummary = true; await panel(page).getByRole("button", { name: "Refresh financial history" }).click(); await expect(panel(page)).toHaveAttribute("data-state", "error"); await expect(panel(page).locator("dl")).toHaveCount(0);
});
test("stale exports and invalid CSV bytes produce no browser download", async ({ page }) => {
  const { state } = await fixture(page), downloads = []; page.on("download", value => downloads.push(value)); state.csvStatus = 409; await panel(page).getByRole("button", { name: "Download CSV" }).click(); await expect(panel(page)).toHaveAttribute("data-state", "error"); await expect(panel(page).getByRole("button", { name: "Download CSV" })).toBeDisabled();
  state.csvStatus = 200; state.csvBody = "PRIVATE_INVALID_CONTENT"; await panel(page).getByRole("button", { name: "Refresh financial history" }).click(); await expect(panel(page)).toHaveAttribute("data-state", "ready"); await panel(page).getByRole("button", { name: "Download CSV" }).click(); await expect(panel(page)).toHaveAttribute("data-state", "error"); expect(downloads).toEqual([]); await expect(page.locator("body")).not.toContainText("PRIVATE_INVALID_CONTENT");
});
test("cancellation discards a late financial response", async ({ page }) => {
  await fixture(page); let arrived, release; const waiting = new Promise(resolve => { arrived = resolve; }), gate = new Promise(resolve => { release = resolve; }); await page.route("**/api/payments/attorney-financial-history?**", async route => { arrived(); await gate; await fulfill(route, { privateData: "PRIVATE_LATE_HISTORY" }).catch(() => {}); });
  await panel(page).getByRole("button", { name: "Refresh financial history" }).click(); await waiting; await panel(page).getByRole("button", { name: "Cancel request" }).click(); await expect(panel(page)).toContainText("Financial-history request canceled"); release(); await expect(page.locator("body")).not.toContainText("PRIVATE_LATE_HISTORY");
});
test("an account change discards late CSV bytes before a browser download", async ({ page }) => {
  let csvArrived, csvRelease; const csvWaiting = new Promise(resolve => { csvArrived = resolve; }), csvGate = new Promise(resolve => { csvRelease = resolve; }); await fixture(page); const downloads = []; page.on("download", value => downloads.push(value)); await page.route("**/api/payments/attorney-financial-history/csv?**", async route => { csvArrived(); await csvGate; await route.fulfill({ status: 200, contentType: "text/csv", body: '"Matter","Record","Status","Currency","Amount",\r\n"PRIVATE_LATE_CSV"' }).catch(() => {}); });
  await panel(page).getByRole("button", { name: "Download CSV" }).click(); try { await csvWaiting; await page.route("**/api/auth/me", route => fulfill(route, { user: { id: id(777), role: "attorney", status: "approved" } })); await page.evaluate(() => window.dispatchEvent(new StorageEvent("storage", { key: "lpc_user" }))); await expect(page.locator("[data-payments-page]")).toHaveCount(0); } finally { csvRelease(); } expect(downloads).toEqual([]);
});
test("long financial records and filters are accessible and fit phone and desktop widths", async ({ page }, testInfo) => {
  await fixture(page, [row(1, { caseTitle: '<img src=x onerror="window.financialXss=true"> River Street lease '.repeat(4) }), row(2), row(3, { caseTitle: "River Street lease, recorded partial refund and remaining exhibits ".repeat(3), type: "refund", state: "recorded", basis: "refund_processed", amount: 10000, recordedAt: null }), row(4, { type: "refund", state: "requires_action", basis: "refund_action", amount: 1000 })]);
  for (const width of [320, 390, 768, 1366]) { await page.setViewportSize({ width, height: 900 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); expect(await page.evaluate(() => window.financialXss)).toBeUndefined(); expect((await new AxeBuilder({ page }).include("[data-payments-page]").withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]); await panel(page).getByLabel("Matter title", { exact: true }).focus(); await expect(panel(page).getByLabel("Matter title", { exact: true })).toBeFocused(); await panel(page).getByRole("heading", { name: "Financial history", exact: true }).scrollIntoViewIfNeeded(); await page.screenshot({ path: testInfo.outputPath(`financial-history-${width}.png`), fullPage: true }); await panel(page).locator("[data-financial-record]").last().scrollIntoViewIfNeeded(); await page.screenshot({ path: testInfo.outputPath(`financial-records-${width}.png`), fullPage: true }); }
});
