const { test, expect } = require("../support-session-fixture"), AxeBuilder = require("@axe-core/playwright").default;
const root = page => page.locator("[data-workspace-funding]"), fulfill = (route, body, status = 200) => route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) });
async function fixture(page) {
  const user = (await (await page.request.get("/api/auth/me")).json()).user, ownerId = user.id || user._id, csrf = (await (await page.request.get("/api/csrf")).json()).csrfToken;
  const send = async (path, data) => { const response = await page.request.post(path, { headers: { "X-CSRF-Token": csrf }, data: { ...data, expectedOwnerId: ownerId } }); expect(response.ok(), await response.text()).toBeTruthy(); return response.json(); };
  const draft = (await send("/api/case-drafts", { title: "River Street lease review", practiceArea: "Contract Law", state: "New York", compAmount: "1000.01", experience: "3+ years", deadline: "2027-03-14", description: "Review the lease and organize its exhibits.", tasks: [{ title: "Review the lease" }] })).draft;
  const published = await send("/api/cases/posting/publications", { draftId: draft.id, revision: draft.revision, requestId: require("crypto").randomUUID(), practiceArea: "contract law" }), caseId = published.publication.caseId;
  const state = { reads: [], writes: [], providerConfirmations: 0, status: 200, writeStatus: 200, outcome: null, view: { ownerId, caseId, caseTitle: "River Street lease review", revision: "d".repeat(64), state: "awaiting_payment", blockers: [], fundingVerified: false, verifiedAt: null, baseCents: 100001, feeCents: 22000, totalCents: 122001, currency: "USD", feePct: 22, paralegalName: "Priya Ng", canPrepare: true, canCheck: false, canEditAmount: false, closed: false, operation: null } };
  state.dto = requestId => ({ ...state.view, operation: requestId ? { requestId, status: state.outcome || "not_found", action: state.outcome ? state.writes.at(-1).action : null, at: state.outcome ? "2026-09-09T12:00:00Z" : null } : null });
  await page.route(`**/api/payments/matter/${caseId}/funding?**`, route => { const query = new URL(route.request().url()).searchParams; state.reads.push(Object.fromEntries(query)); return fulfill(route, state.status === 200 ? state.dto(query.get("requestId")) : {}, state.status); });
  await page.route(`**/api/payments/matter/${caseId}/funding`, route => { const body = route.request().postDataJSON(); state.writes.push(body); state.outcome = body.action === "prepare" ? "prepared" : "checked"; state.view = { ...state.view, revision: body.action === "prepare" ? "e".repeat(64) : "f".repeat(64), canCheck: true, ...(body.action === "check" ? { state: "verified", fundingVerified: true, verifiedAt: "2026-09-09T12:00:00Z", canPrepare: false } : { state: "unconfirmed" }) }; if (state.writeStatus === 0) return route.abort("failed"); if (state.writeStatus !== 200) return fulfill(route, {}, state.writeStatus); return fulfill(route, { funding: state.dto(body.requestId), payment: body.action === "prepare" ? { intentId: "pi_funding", clientSecret: "pi_funding_secret_SYNTHETIC_PRIVATE", status: "requires_payment_method" } : null }); });
  await page.route("**/api/payments/config", route => fulfill(route, { publishableKey: "pk_test_synthetic" }));
  await page.exposeFunction("observeSyntheticFundingConfirmation", () => { state.providerConfirmations++; });
  await page.addInitScript(() => {
    window.fundingProvider = { preparations: 0, confirmations: 0, destroyed: 0, fail: false, wait: false, release: null };
    window.Stripe = () => ({ elements: () => { window.fundingProvider.preparations++; return { create: () => { const handlers = {}; let input; return { on: (event, handler) => { handlers[event] = handler; }, mount: host => { input = document.createElement("input"); input.setAttribute("aria-label", "Synthetic payment details"); input.addEventListener("input", () => handlers.change?.({ complete: input.value === "4242", empty: !input.value })); host.append(input); queueMicrotask(() => handlers.ready?.()); }, destroy: () => { input?.remove(); window.fundingProvider.destroyed++; } }; } }; }, confirmPayment: async () => { await window.observeSyntheticFundingConfirmation(); const state = window.fundingProvider; state.confirmations++; if (state.wait) await new Promise(resolve => { state.release = resolve; }); return state.fail ? { error: { type: "card_error", message: "Synthetic decline" } } : { paymentIntent: { status: "succeeded" } }; } });
  });
  await page.goto(`/attorney-v2.html#/matters/${caseId}/financials`, { waitUntil: "domcontentloaded" }); await expect(root(page)).toHaveAttribute("data-state", "ready"); return { state, caseId, ownerId };
}
async function prepare(page) { await root(page).getByRole("button", { name: "Review payment details", exact: true }).click(); await expect(root(page).getByRole("heading", { name: "Payment for River Street lease review" })).toBeFocused(); await root(page).getByLabel("Synthetic payment details").fill("4242"); }
test("verified original payments omit future-funding guidance while preserving record concerns and provider checks", async ({ page }) => {
  const { state } = await fixture(page);
  state.view = { ...state.view, canPrepare: false, blockers: ["payment_review"] };
  await root(page).evaluate(section => section.sync());
  await expect(root(page)).toContainText("An open payment review must be resolved before funding.");
  state.view = { ...state.view, state: "verified", fundingVerified: true, verifiedAt: "2026-09-09T12:00:00Z", canCheck: true, revision: "a".repeat(64) };
  await root(page).evaluate(section => section.sync());
  await expect(root(page).locator("[data-funding-message]")).toHaveText(/^Verified .+/);
  await expect(root(page)).not.toContainText("before funding");
  await expect(root(page)).toContainText("$1,220.01");
  await expect(root(page).getByRole("button", { name: "Check Stripe payment", exact: true })).toBeEnabled();
  await expect(root(page).getByRole("button", { name: "Review payment details", exact: true })).toHaveCount(0);
  state.view = { ...state.view, blockers: ["payment_review", "payment_reference_needs_review"], revision: "b".repeat(64) };
  await root(page).evaluate(section => section.sync());
  await expect(root(page)).toContainText("The payment records need LPC review.");
  expect(state.writes).toEqual([]); expect(state.providerConfirmations).toBe(0);
});
test("funding shows the amount, fee, Matter and paralegal before an explicit payment confirmation", async ({ page }) => {
  const { state, ownerId } = await fixture(page); await expect(root(page)).toContainText("$1,000.01"); await expect(root(page)).toContainText("$220.00"); await expect(root(page)).toContainText("$1,220.01"); expect(state.writes).toEqual([]); await prepare(page); await expect(root(page)).toContainText("Assigned paralegal: Priya Ng"); expect(state.providerConfirmations).toBe(0); await root(page).getByRole("button", { name: "Fund Matter · $1,220.01", exact: true }).click(); await expect(root(page).locator("[data-funding-message]")).toHaveText(/^Verified .+/); expect(state.writes.map(body => body.action)).toEqual(["prepare", "check"]); expect(state.writes[0]).toMatchObject({ expectedOwnerId: ownerId, reviewedRevision: "d".repeat(64) }); expect(state.providerConfirmations).toBe(1); await expect(root(page).getByLabel("Synthetic payment details")).toHaveCount(0); expect(await page.evaluate(() => JSON.stringify({ local: localStorage, session: sessionStorage }) + document.documentElement.outerHTML + location.href)).not.toContain("SYNTHETIC_PRIVATE");
});
test("closing payment entry sends no confirmation and returns to the same funding review", async ({ page }) => { const { state } = await fixture(page); await prepare(page); await root(page).getByRole("button", { name: "Close payment form", exact: true }).click(); await expect(root(page)).toContainText("No confirmation was sent"); expect(state.providerConfirmations).toBe(0); expect(state.writes).toHaveLength(1); await expect(root(page).getByRole("button", { name: "Review payment details", exact: true })).toBeVisible(); });
test("a lost preparation response recovers its exact request without another preparation write", async ({ page }) => { const { state } = await fixture(page); state.writeStatus = 0; await root(page).getByRole("button", { name: "Review payment details", exact: true }).click(); await expect(root(page)).toContainText("payment request could not be confirmed"); await root(page).getByRole("button", { name: "Refresh funding details", exact: true }).click(); await expect(root(page).getByRole("button", { name: "Review payment details", exact: true })).toBeVisible(); expect(state.reads.at(-1).requestId).toBe(state.writes[0].requestId); expect(state.writes).toHaveLength(1); expect(state.providerConfirmations).toBe(0); });
test("a changed Matter amount removes the earlier form before any provider confirmation", async ({ page }) => { const { state } = await fixture(page); await prepare(page); state.view = { ...state.view, revision: "a".repeat(64), baseCents: 100100, feeCents: 22022, totalCents: 122122 }; await root(page).getByRole("button", { name: "Fund Matter · $1,220.01", exact: true }).click(); await expect(root(page)).toContainText("funding details changed"); expect(state.providerConfirmations).toBe(0); await expect(root(page).getByLabel("Synthetic payment details")).toHaveCount(0); });
test("a card error retains an unconfirmed payment until an explicit provider check", async ({ page }) => { const { state } = await fixture(page); await prepare(page); await page.evaluate(() => { window.fundingProvider.fail = true; }); await root(page).getByRole("button", { name: "Fund Matter · $1,220.01", exact: true }).click(); await expect(root(page)).toContainText("Stripe did not confirm the payment"); await expect(root(page).getByRole("button", { name: "Review payment details", exact: true })).toHaveCount(0); expect(state.writes).toHaveLength(1); await root(page).getByRole("button", { name: "Check Stripe payment", exact: true }).click(); await expect(root(page).locator("[data-funding-message]")).toHaveText(/^Verified .+/); expect(state.providerConfirmations).toBe(1); });
test("stopping an unfinished confirmation retains uncertainty across Matter tabs", async ({ page }) => { const { state } = await fixture(page); await prepare(page); await page.evaluate(() => { window.fundingProvider.wait = true; }); await root(page).getByRole("button", { name: "Fund Matter · $1,220.01", exact: true }).click(); await expect.poll(() => state.providerConfirmations).toBe(1); await root(page).getByRole("button", { name: "Stop waiting for payment", exact: true }).click(); await expect(root(page)).toContainText("payment request could not be confirmed"); await page.getByRole("navigation", { name: "Matter sections" }).getByRole("link", { name: "Overview", exact: true }).click(); await page.getByRole("navigation", { name: "Matter sections" }).getByRole("link", { name: "Financials", exact: true }).click(); await expect(root(page)).toContainText("Stopping the wait does not cancel a payment"); expect(state.writes).toHaveLength(1); await expect(root(page).getByRole("button", { name: "Review payment details", exact: true })).toHaveCount(0); await page.evaluate(() => window.fundingProvider.release?.()); });
test("an account change removes payment details before another charge can be confirmed", async ({ page }) => { const { state } = await fixture(page); await prepare(page); await page.route("**/api/auth/me", route => fulfill(route, { user: { id: "f".repeat(24), role: "attorney", status: "approved" } })); await root(page).getByRole("button", { name: "Fund Matter · $1,220.01", exact: true }).click(); await expect(root(page)).toHaveCount(0); expect(state.writes).toHaveLength(1); expect(state.providerConfirmations).toBe(0); });
test("unavailable reads clear payment controls and never appear as an empty funded queue", async ({ page }) => { const { state } = await fixture(page); state.status = 503; await root(page).getByRole("button", { name: "Refresh funding details", exact: true }).click(); await expect(root(page)).toContainText("Funding details couldn’t load"); await expect(root(page).getByRole("button", { name: "Review payment details", exact: true })).toHaveCount(0); expect(state.writes).toEqual([]); });
test("background refresh preserves entered payment details", async ({ page }) => { const { state } = await fixture(page); await prepare(page); await root(page).evaluate(element => element.sync()); await expect(root(page).getByLabel("Synthetic payment details")).toHaveValue("4242"); await expect(root(page).getByLabel("Synthetic payment details")).toBeFocused(); expect(state.providerConfirmations).toBe(0); });
test("the funding review stays readable and accessible on small and large screens", async ({ page }, testInfo) => { const { state } = await fixture(page); state.view.caseTitle = '<img src=x onerror="window.fundingXss=true"> River Street lease '.repeat(3); await root(page).getByRole("button", { name: "Refresh funding details", exact: true }).click(); await root(page).getByRole("button", { name: "Review payment details", exact: true }).click(); await expect(root(page).getByLabel("Synthetic payment details")).toBeVisible(); for (const width of [320, 390, 768, 1366]) { await page.setViewportSize({ width, height: 900 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); expect(await page.evaluate(() => window.fundingXss)).toBeUndefined(); expect((await new AxeBuilder({ page }).include("[data-workspace-funding]").withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]); await root(page).evaluate(element => element.scrollIntoView({ block: "start" })); await page.screenshot({ path: testInfo.outputPath(`funding-${width}.png`), fullPage: true }); } });
test("account loss during the payment request removes all private attorney content", async ({ page }) => { const { state, caseId } = await fixture(page); await page.route(`**/api/payments/matter/${caseId}/funding`, route => { state.writes.push(route.request().postDataJSON()); return fulfill(route, { code: "WORKSPACE_FUNDING_ACCOUNT_CHANGED" }, 403); }); await root(page).getByRole("button", { name: "Review payment details", exact: true }).click(); await expect(root(page)).toHaveCount(0); expect(state.writes).toHaveLength(1); expect(state.providerConfirmations).toBe(0); });
