const { test, expect } = require("../support-session-fixture"), AxeBuilder = require("@axe-core/playwright").default;
const fulfill = (route, value, status = 200) => route.fulfill({ status, contentType: "application/json", body: JSON.stringify(value) });
const id = n => n.toString(16).padStart(24, "0"), panel = page => page.locator("[data-workspace-messages]");
async function fixture(page, count = 3) {
  const user = (await (await page.request.get("/api/auth/me")).json()).user, ownerId = user.id || user._id, csrf = (await (await page.request.get("/api/csrf")).json()).csrfToken;
  const fields = { title: "River Street lease correspondence", practiceArea: "Contract Law", state: "New York", compAmount: "400.01", experience: "3+ years", deadline: "2027-03-14", description: "Review the lease and confirm the exhibits.", tasks: [{ title: "Review the lease" }] };
  const draftResult = await page.request.post("/api/case-drafts", { headers: { "X-CSRF-Token": csrf }, data: { ...fields, expectedOwnerId: ownerId } }); expect(draftResult.ok()).toBe(true); const draft = (await draftResult.json()).draft;
  const publication = await page.request.post("/api/cases/posting/publications", { headers: { "X-CSRF-Token": csrf }, data: { draftId: draft.id, revision: draft.revision, requestId: require("crypto").randomUUID(), practiceArea: "contract law", expectedOwnerId: ownerId } }); expect(publication.ok()).toBe(true); const caseId = (await publication.json()).publication.caseId;
  const value = await (await page.request.get(`/api/cases/${caseId}`)).json();
  await page.route(`**/api/cases/${caseId}?expectedOwnerId=*`, route => fulfill(route, { ...value, status: "completed", readOnly: true, completedAt: new Date().toISOString() }));
  const state = { reads: [], writes: [], requests: [], status: 200, attachmentStatus: 200, rows: [] };
  state.rows = Array.from({ length: count }, (_, n) => ({ _id: id(n + 1), caseId, senderId: { _id: n === 1 ? ownerId : id(900), firstName: "Priya", lastName: "Ng" }, senderRole: "paralegal", type: "text", text: `Retained instruction ${n + 1}`, createdAt: n === 0 ? null : new Date(Date.UTC(2026, 0, 2, 0, n)).toISOString(), revision: "d".repeat(64), reactions: { "👍": [ownerId] }, readBy: [], attachments: [] }));
  await page.route(`**/api/cases/${caseId}/retained-messages?**`, route => {
    const query = new URL(route.request().url()).searchParams; state.reads.push(Object.fromEntries(query)); if (state.status !== 200) return fulfill(route, { code: "WORKSPACE_HISTORY_EXPIRED" }, state.status);
    let rows = state.rows, targetMissing = false;
    if (query.get("messageId")) { const index = rows.findIndex(row => row._id === query.get("messageId")); if (index >= 0) rows = rows.slice(0, index + 1); else targetMissing = true; }
    else if (query.get("cursor")) rows = rows.slice(0, Number(query.get("cursor")));
    return fulfill(route, { caseId, ownerId, messages: rows.slice(-50), nextCursor: rows.length > 50 ? String(rows.length - 50) : null, targetMissing, writable: false, retained: true, retentionEndsAt: "2027-01-01T00:00:00.000Z" });
  });
  page.on("request", request => { if (request.method() !== "GET" && (/\/api\/messages\//.test(request.url()) || request.url().includes("workspace-presence"))) state.writes.push(request.url()); });
  await page.route(`**/api/cases/${caseId}/message-attachments/**`, route => {
    const query = new URL(route.request().url()).searchParams; state.requests.push(Object.fromEntries(query)); if (state.attachmentStatus !== 200) return fulfill(route, {}, state.attachmentStatus);
    return route.fulfill({ status: 200, contentType: query.get("play") ? "audio/wav" : "application/octet-stream", body: query.get("play") ? wave() : `EXACT_${query.get("attachmentId") || "primary"}` });
  });
  await page.goto(`/attorney-v2.html#/matters/${caseId}/messages`, { waitUntil: "domcontentloaded" }); await expect(panel(page)).toHaveAttribute("data-state", "ready"); return { state, caseId, ownerId };
}
function wave() { const samples = 8000 * 30, bytes = samples * 2, buffer = Buffer.alloc(44 + bytes); buffer.write("RIFF"); buffer.writeUInt32LE(36 + bytes, 4); buffer.write("WAVEfmt ", 8); buffer.writeUInt32LE(16, 16); buffer.writeUInt16LE(1, 20); buffer.writeUInt16LE(1, 22); buffer.writeUInt32LE(8000, 24); buffer.writeUInt32LE(16000, 28); buffer.writeUInt16LE(2, 32); buffer.writeUInt16LE(16, 34); buffer.write("data", 36); buffer.writeUInt32LE(bytes, 40); return buffer; }
async function refresh(page) { await page.locator("[data-matter-workspace]").evaluate(element => element.readiness); const response = page.waitForResponse(value => value.url().includes('/retained-messages?')); await page.evaluate(() => document.dispatchEvent(new Event("visibilitychange"))); await response; await expect(panel(page)).toHaveAttribute("data-state", "ready"); }
test("retained correspondence pages and exact undated links without composer, mutations, read acknowledgements or presence", async ({ page }) => {
  await page.clock.install(); const { state, caseId } = await fixture(page, 125); await expect(panel(page).locator("[data-message-id]")).toHaveCount(50); await panel(page).getByRole("button", { name: "Show earlier messages" }).click(); await expect(panel(page).locator("[data-message-id]")).toHaveCount(100); await panel(page).getByRole("button", { name: "Show earlier messages" }).click(); await expect(panel(page).locator("[data-message-id]")).toHaveCount(125);
  await expect(panel(page).locator("textarea,.av2-message-actions button")).toHaveCount(0); await expect(panel(page)).toContainText("Retained correspondence"); await page.clock.fastForward(16000); await expect(panel(page).locator("[data-message-id]")).toHaveCount(125); expect(state.writes).toEqual([]);
  await page.goto(`/attorney-v2.html#/matters/${caseId}/messages?messageId=${id(1)}`, { waitUntil: "domcontentloaded" }); const selected = panel(page).locator(`[data-message-id="${id(1)}"]`); await expect(selected).toBeFocused(); await expect(selected).toContainText("Date unavailable"); await expect(panel(page).locator("[data-message-id]")).toHaveCount(1); expect(state.writes).toEqual([]);
});
test("each earlier-format attachment downloads its selected bytes and filename", async ({ page }) => {
  const { state, ownerId } = await fixture(page); state.rows[0].attachments = [{ id: "primary", filename: "Original.txt", hasAttachment: true, audioMimeType: null }, { id: "file-0", filename: "Exhibit.txt", hasAttachment: true, audioMimeType: null }, { id: "file-1", filename: "Unverified reference", hasAttachment: false, audioMimeType: null }]; await refresh(page);
  const controls = panel(page).locator(`[data-message-id="${id(1)}"]`).getByRole("button", { name: "Download attachment" }); await expect(controls).toHaveCount(2);
  for (const [index, filename, token] of [[0, "Original.txt", "primary"], [1, "Exhibit.txt", "file-0"]]) { const event = page.waitForEvent("download"); await controls.nth(index).click(); const file = await event; expect(file.suggestedFilename()).toBe(filename); expect(require("fs").readFileSync(await file.path(), "utf8")).toBe(`EXACT_${token}`); expect(state.requests.at(-1)).toMatchObject({ expectedOwnerId: ownerId, retained: "true", revision: state.rows[0].revision }); }
  expect(state.requests[1].attachmentId).toBe("file-0"); await expect(panel(page)).toContainText("This attachment is unavailable."); expect(state.writes).toEqual([]);
});
test("retained audio plays only on request, survives refresh and stops when retention expires", async ({ page }) => {
  await page.clock.install(); const { state } = await fixture(page); state.rows[1] = { ...state.rows[1], type: "audio", transcript: "Original exhibit instructions.", attachments: [{ id: "primary", filename: "Instructions.wav", hasAttachment: true, audioMimeType: "audio/wav" }] }; await refresh(page); expect(state.requests).toEqual([]);
  await panel(page).getByRole("button", { name: "Load audio" }).click(); const audio = panel(page).locator("audio"); await expect(panel(page)).toContainText("Audio ready."); expect(await audio.evaluate(element => element.paused)).toBe(true); await audio.evaluate(async element => { window.retainedAudio = element; await element.play(); }); await expect.poll(() => audio.evaluate(element => element.currentTime)).toBeGreaterThan(0);
  await page.clock.fastForward(16000); expect(await audio.evaluate(element => element === window.retainedAudio && !element.paused)).toBe(true); state.status = 410; await page.clock.fastForward(16000); await expect(panel(page)).toHaveAttribute("data-state", "error"); await expect(audio).toHaveCount(0); expect(await page.evaluate(() => window.retainedAudio.paused && !window.retainedAudio.hasAttribute("src"))).toBe(true); await expect(panel(page)).not.toContainText("Original exhibit instructions"); expect(state.writes).toEqual([]);
});
test("missing links and unavailable history are distinct from an empty retained conversation", async ({ page }) => {
  const { state, caseId } = await fixture(page); await page.goto(`/attorney-v2.html#/matters/${caseId}/messages?messageId=${id(999)}`, { waitUntil: "domcontentloaded" }); await expect(panel(page)).toContainText("linked message is no longer available"); state.status = 503; await page.evaluate(() => document.dispatchEvent(new Event("visibilitychange"))); await expect(panel(page)).toHaveAttribute("data-state", "error"); await expect(panel(page)).toContainText("Retained messages couldn’t load"); await expect(panel(page)).not.toContainText("No messages have been recorded");
  state.status = 200; state.rows = []; await page.goto(`/attorney-v2.html#/matters/${caseId}/messages`, { waitUntil: "domcontentloaded" }); await expect(panel(page)).toContainText("No messages have been recorded"); expect(state.writes).toEqual([]);
});
test("a late retained attachment cannot download into a different Matter section", async ({ page }) => {
  const { state, caseId } = await fixture(page); state.rows[0].attachments = [{ id: "primary", filename: "Private.txt", hasAttachment: true, audioMimeType: null }]; await refresh(page);
  let arrived, release; const waiting = new Promise(resolve => { arrived = resolve; }), gate = new Promise(resolve => { release = resolve; }); let downloads = 0; page.on("download", () => { downloads++; });
  await page.route(`**/api/cases/${caseId}/message-attachments/**`, async route => { arrived(); await gate; await route.fulfill({ status: 200, contentType: "application/octet-stream", body: "PRIVATE_LATE_ATTACHMENT" }).catch(() => {}); });
  await panel(page).getByRole("button", { name: "Download attachment" }).click(); try { await waiting; await page.getByRole("link", {name:"View Matter",exact:true}).click(); await expect(panel(page)).toHaveCount(0); } finally { release(); } await expect(page.getByRole("region", { name: "Matter overview" })).toBeVisible(); expect(downloads).toBe(0);
});
test("long retained correspondence stays readable and safe across phone and desktop widths", async ({ page }, testInfo) => {
  const { state } = await fixture(page); state.rows[0].text = '<img src=x onerror="window.retainedXss=true">\nOriginal correspondence '.repeat(8); await refresh(page);
  for (const width of [320, 390, 768, 1366]) { await page.setViewportSize({ width, height: 900 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); expect(await page.evaluate(() => window.retainedXss)).toBeUndefined(); expect((await new AxeBuilder({ page }).include("[data-workspace-messages]").withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]); await page.screenshot({ path: testInfo.outputPath(`retained-${width}.png`), fullPage: true }); }
});
