const {test,expect}=require('../support-session-fixture');
const AxeBuilder=require('@axe-core/playwright').default;
const id='a'.repeat(24),other='b'.repeat(24),revision='a'.repeat(64);
const json=(route,value,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});
const session=(id,current=false)=>({id,current,ua:current?'Mozilla/5.0 Chrome Mac OS':'Mozilla/5.0 Firefox Windows',createdAt:'2026-09-08T10:00:00Z',lastSeenAt:'2026-09-09T10:00:00Z',expiresAt:'2026-09-09T12:00:00Z',ip:'192.0.2.1'});
async function setup(page,overrides={}) {
 const model={owner:id,revision,enabled:false,method:'email',hasBackupCodes:false,sessionManaged:true,disabled:false,passkeys:[],sessions:[session('this-session',true),session('other-session')],writes:[],stateFail:false,passkeysFail:false,sessionsFail:false,...overrides};
 await page.route('**/api/**',async route=>{
  const req=route.request(),url=new URL(req.url()),path=url.pathname,method=req.method();
  if(path==='/api/auth/me')return json(route,{user:model.owner?{id:model.owner,role:'attorney',status:'approved',firstName:'Morgan',lastName:'Ellis',preferences:{theme:model.theme||'light',fontSize:model.fontSize||'md'}}:null});
  if(path==='/api/csrf'){if(model.switchAfterPreflight)model.owner=other;return json(route,{csrfToken:'synthetic-security-token'});}
  if(method==='GET'&&path==='/api/account/2fa'){if(model.stateDelay)await model.stateDelay;return model.stateFail?json(route,{},503):json(route,{enabled:model.enabled,method:model.method,hasBackupCodes:model.hasBackupCodes,sessionManaged:model.sessionManaged,disabled:model.disabled,securityRevision:model.revision});}
  if(method==='GET'&&path==='/api/account/passkeys')return model.passkeysFail?json(route,{},503):json(route,{passkeys:model.passkeys});
  if(method==='GET'&&path==='/api/account/sessions'){if(model.sessionsFail)return json(route,{},503);if(url.searchParams.has('cursor')){if(model.pageFail)return json(route,{},503);return json(route,{sessions:[session('later-session')],currentSession:model.sessions.find(item=>item.current)||null,nextCursor:null,total:3});}return json(route,{sessions:model.sessions,currentSession:model.sessions.find(item=>item.current)||null,nextCursor:model.more?'synthetic-cursor':null,total:model.more?3:model.sessions.length});}
  if(method!=='GET'&&path.startsWith('/api/account/')){
   const body=req.postDataJSON();model.writes.push({path,body,method});if(model.delay)await model.delay;
   if(body.expectedOwnerId!==model.owner)return json(route,{code:'ACCOUNT_CHANGED'},403);
   if(model.reject)return json(route,model.reject.body,model.reject.status);if(model.malformed)return json(route,{});
   if(!path.includes('/sessions')&&body.expectedSecurityRevision!==model.revision)return json(route,{code:'ACCOUNT_CONFLICT'},409);
   if(path.endsWith('/update-password')){model.owner=null;if(model.lost)return route.abort('failed');return json(route,{ok:true,reauthenticationRequired:true});}
   if(path.endsWith('/2fa-toggle')){model.enabled=body.enabled;model.method=body.method||model.method;model.revision='b'.repeat(64);if(model.lost)return route.abort('failed');return json(route,{enabled:model.enabled,method:model.method});}
   if(path.endsWith('/2fa/authenticator/setup'))return json(route,{challengeId:'synthetic-challenge-'.repeat(3),manualSecret:'ABCDEFGHIJKLMNOPQRSTUVWXY234567A',qrDataUrl:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jh5cAAAAASUVORK5CYII=',expiresInSeconds:model.expiry||600});
   if(path.endsWith('/2fa/authenticator/confirm')){model.enabled=true;model.method='authenticator';model.hasBackupCodes=true;model.revision='b'.repeat(64);return json(route,{enabled:true,method:'authenticator',backupCodes:['ABCD123456','EFGH123456']});}
   if(path.endsWith('/2fa-backup-codes')){model.hasBackupCodes=true;model.revision='c'.repeat(64);if(model.lost)return route.abort('failed');return json(route,{codes:['ABCD123456','EFGH123456']});}
   if(path.endsWith('/passkeys/registration-options'))return json(route,{challengeId:'synthetic-passkey-'.repeat(3),options:{challenge:'challenge'}});
   if(path.endsWith('/passkeys/register')){model.passkeys.push({id:'c'.repeat(24),name:body.name,createdAt:'2026-09-09T10:00:00Z'});return json(route,{id:'c'.repeat(24),name:body.name});}
   if(method==='DELETE'&&path.includes('/passkeys/')){model.passkeys=model.passkeys.filter(item=>item.id!==path.split('/').at(-1));return json(route,{ok:true});}
   if(path.endsWith('/sessions/revoke-others')){model.sessions=model.sessions.filter(item=>item.current);return json(route,{ok:true,revokedCount:1});}
   if(method==='DELETE'&&path.includes('/sessions/')){const target=model.sessions.find(item=>item.id===path.split('/').at(-1));model.sessions=model.sessions.filter(item=>item!==target);if(target?.current)model.owner=null;return json(route,{ok:true,currentSessionRevoked:Boolean(target?.current)});}
  }
  if(path==='/api/notifications/stream')return route.fulfill({status:200,contentType:'text/event-stream',body:': ready\n\n'});
  if(path==='/api/notifications/page')return json(route,{items:[],hasMore:false,nextCursor:null});
  if(path==='/api/notifications/unread-count')return json(route,{count:0});
  if(path==='/api/notifications')return json(route,[]);
  return json(route,{});
 });return model;
}
async function open(page){await page.goto('/attorney-v2.html#/settings?tab=security');await expect(page.locator('html')).toHaveAttribute('data-attorney-state','ready');await expect(page.locator('[data-security-content]')).toHaveAttribute('aria-busy','false');}
async function password(page){await page.getByRole('dialog').getByLabel('Current password',{exact:true}).fill('A secure current passphrase');}

for (const retained of [false, true]) test(`security refresh failure describes ${retained ? 'retained rows' : 'an empty prior result'} accurately`, async ({page}, info) => {
 const model = await setup(page, {theme:'dark', passkeys:retained ? [{id:'c'.repeat(24),name:'Work device',createdAt:'2026-09-09T10:00:00Z'}] : [], sessions:retained ? [session('this-session',true)] : []});
 await page.setViewportSize({width:320,height:844});
 await open(page);
 model.passkeysFail = model.sessionsFail = true;
 await page.getByRole('button',{name:'Refresh security',exact:true}).click();
 const suffix = retained ? ' The previous list is shown below.' : '';
 for (const label of ['Passkeys','Sessions']) await expect(page.getByText(`${label} could not be refreshed.${suffix}`,{exact:true})).toBeVisible();
 await expect(page.getByText('No passkeys added.',{exact:true})).toHaveCount(0);
 await expect(page.locator('[data-security-session]')).toHaveCount(retained ? 1 : 0);
 await expect(page.getByRole('button',{name:'Add passkey',exact:true})).toBeDisabled();
 if (retained) await expect(page.getByRole('button',{name:'Remove Work device'})).toBeDisabled();
 else await expect(page.getByText(/previous list/)).toHaveCount(0);
 await page.getByText(`Passkeys could not be refreshed.${suffix}`,{exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:info.outputPath('security-read-failure.png')});
 const report = await new AxeBuilder({page}).include('.av2-security').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
 expect(report.violations).toEqual([]);
 model.passkeysFail = model.sessionsFail = false;
 await page.getByRole('button',{name:'Refresh security',exact:true}).click();
 await expect(page.locator('[data-security-content]')).toHaveAttribute('aria-busy','false');
 await expect(page.getByText(/could not be refreshed/)).toHaveCount(0);
 if (retained) await expect(page.getByRole('button',{name:'Remove Work device'})).toBeEnabled();
 else await expect(page.getByText('No passkeys added.',{exact:true})).toBeVisible();
 expect(model.writes).toEqual([]);
});

test('Security mounts real controls and vendor capability without writes or repeated placeholders',async({page})=>{const model=await setup(page);await open(page);await expect(page.getByRole('navigation',{name:'Profile settings'}).getByRole('link',{name:'Security'})).toHaveAttribute('aria-current','page');expect(model.writes).toEqual([]);expect(await page.evaluate(()=>typeof window.SimpleWebAuthnBrowser?.startRegistration)).toBe('function');await expect(page.getByText(/navigation preview/i)).toHaveCount(0);await expect(page.locator('[data-security-content] [placeholder]')).toHaveCount(0);});
test('password manager fields validate before one write and explicit success signs out current session',async({page})=>{const model=await setup(page);await open(page);await page.getByRole('button',{name:'Change password',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Current password',{exact:true})).toHaveAttribute('autocomplete','current-password');await expect(dialog.getByLabel('New password',{exact:true})).toHaveAttribute('autocomplete','new-password');await password(page);await dialog.getByLabel('New password',{exact:true}).fill('A newer secure test passphrase');await dialog.getByLabel('Confirm new password',{exact:true}).fill('Different passphrase');await dialog.getByRole('button',{name:'Change password and sign out'}).click();expect(model.writes).toHaveLength(0);await dialog.getByLabel('Confirm new password',{exact:true}).fill('A newer secure test passphrase');await dialog.getByRole('button',{name:'Change password and sign out'}).click();await expect(page).toHaveURL(/login.html/);expect(model.writes).toHaveLength(1);expect(model.writes[0].body.expectedOwnerId).toBe(id);expect(model.writes[0].body.expectedSecurityRevision).toBe(revision);});
test('MFA switches only on deliberate confirmed action and refreshes actual method',async({page})=>{const model=await setup(page);await open(page);await page.getByRole('button',{name:'Enable email codes'}).click();await page.getByRole('dialog').getByRole('button',{name:'Cancel'}).click();expect(model.writes).toEqual([]);await page.getByRole('button',{name:'Enable email codes'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(page.getByText('Email sign-in codes enabled.',{exact:true})).toBeVisible();expect(model.enabled).toBe(true);await expect(page.getByRole('button',{name:'Enabled',exact:true})).toBeDisabled();});
test('rejected password stays recoverable without secret storage or unsafe server copy',async({page})=>{const model=await setup(page,{reject:{status:400,body:{error:'Current password is incorrect.'}}});await open(page);await page.getByRole('button',{name:'Enable email codes'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(page.getByText('Current password is incorrect.',{exact:true})).toBeVisible();expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain('secure current');model.reject=null;await password(page);await page.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(model.writes).toHaveLength(2);});
test('authenticator setup cancellation clears its secret without enabling MFA',async({page})=>{const model=await setup(page);await open(page);await page.getByRole('button',{name:'Set up authenticator'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('dialog',{name:'Connect your authenticator app'})).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Cancel'}).click();expect(model.enabled).toBe(false);await expect(page.locator('[data-security-secret]')).toHaveCount(0);expect(model.writes.map(item=>item.path)).toEqual(['/api/account/2fa/authenticator/setup']);});
test('authenticator confirmation presents one-time codes and clears them on close',async({page},info)=>{const model=await setup(page);await open(page);await page.getByRole('button',{name:'Set up authenticator'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Six-digit code').fill('123456');await page.getByRole('button',{name:'Confirm authenticator'}).click();await expect(page.getByRole('dialog',{name:'Save your backup codes'})).toBeVisible();await expect(page.getByText(/ABCD123456/)).toBeVisible();expect((await new AxeBuilder({page}).include('dialog').analyze()).violations).toEqual([]);await page.screenshot({path:info.outputPath('backup-codes.png')});await page.getByRole('button',{name:'Done',exact:true}).click();await expect(page.locator('[data-security-secret]')).toHaveCount(0);expect(model.method).toBe('authenticator');});
test('authenticator expiry disables confirmation and clears QR/manual secret',async({page})=>{const model=await setup(page,{expiry:1});await open(page);await page.getByRole('button',{name:'Set up authenticator'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByText(/Authenticator setup expired/)).toBeVisible();await expect(page.getByRole('button',{name:'Confirm authenticator'})).toBeDisabled();await expect(page.getByRole('img',{name:'Authenticator setup QR code'})).not.toHaveAttribute('src',/data:/);expect(model.writes).toHaveLength(1);});
test('lost code rotation does not repeat and directs an explicit fresh generation',async({page})=>{const model=await setup(page,{enabled:true,hasBackupCodes:true,lost:true});await open(page);await page.getByRole('button',{name:'Generate new backup codes'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Generate codes'}).click();await expect(page.getByText(/Backup codes may have changed/)).toBeVisible();expect(model.writes).toHaveLength(1);await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Generate new backup codes'})).toBeEnabled();});
test('stale MFA state refreshes before another explicit action',async({page})=>{const model=await setup(page);await open(page);model.revision='b'.repeat(64);model.enabled=true;await page.getByRole('button',{name:'Enable email codes'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(page.getByText('Your security settings changed. Review the current settings before trying again.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Enabled',exact:true})).toBeDisabled();expect(model.writes).toHaveLength(1);});
test('passkey cancellation and successful registration preserve deliberate retry',async({page})=>{const model=await setup(page);await open(page);await page.evaluate(()=>{window.SimpleWebAuthnBrowser.browserSupportsWebAuthn=()=>true;window.SimpleWebAuthnBrowser.startRegistration=async()=>{throw new DOMException('Canceled','NotAllowedError');};});await page.getByRole('button',{name:'Add passkey',exact:true}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Continue on this device'}).click();await expect(page.getByText('Passkey setup was canceled. You can try again.',{exact:true})).toBeVisible();expect(model.writes).toHaveLength(1);await page.evaluate(()=>{window.SimpleWebAuthnBrowser.startRegistration=async()=>({id:'synthetic-credential'});});await password(page);await page.getByLabel('Name (optional)',{exact:true}).fill('Work device');await page.getByRole('dialog').getByRole('button',{name:'Continue on this device'}).click();await expect(page.getByRole('heading',{name:'Work device'})).toBeVisible();expect(model.writes.map(item=>item.path).filter(path=>path.endsWith('/register'))).toHaveLength(1);});
test('session paging shows current device once and preserves keyboard focus for added records',async({page})=>{const model=await setup(page,{more:true});await open(page);await expect(page.locator('[data-security-session="this-session"]')).toHaveCount(1);await page.getByRole('button',{name:'Load more devices'}).click();await expect(page.locator('[data-security-session="later-session"]')).toBeVisible();await expect(page.locator('[data-security-session="later-session"] button')).toBeFocused();await expect(page.getByRole('button',{name:'Load more devices'})).toHaveCount(0);expect(model.writes).toEqual([]);});
test('revoke other sessions keeps current and current sign-out honors the explicit response',async({page})=>{const model=await setup(page);await open(page);await page.getByRole('button',{name:'Sign out other devices',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Sign out other devices',exact:true}).click();await expect(page.getByText('Other devices signed out.',{exact:true})).toBeVisible();expect(model.sessions).toHaveLength(1);await page.locator('[data-security-session="this-session"]').getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Sign out',exact:true}).click();await expect(page).toHaveURL(/login.html/);});
test('account replacement after preflight clears secrets and cannot change replacement',async({page})=>{const model=await setup(page,{switchAfterPreflight:true});await open(page);await page.getByRole('button',{name:'Enable email codes'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(page).toHaveURL(/login.html|dashboard-attorney.html/);expect(model.enabled).toBe(false);await expect(page.getByRole('dialog')).toHaveCount(0);});
test('failed reads stay unavailable and retry restores controls without showing false empty lists',async({page})=>{const model=await setup(page,{stateFail:true,passkeysFail:true,sessionsFail:true});await open(page);await expect(page.getByRole('button',{name:'Change password',exact:true})).toBeDisabled();await expect(page.getByText('No passkeys added.',{exact:true})).toHaveCount(0);await expect(page.getByText('Sessions could not be loaded.',{exact:true})).toBeVisible();model.stateFail=model.passkeysFail=model.sessionsFail=false;await page.getByRole('button',{name:'Refresh security'}).click();await expect(page.getByRole('button',{name:'Change password',exact:true})).toBeEnabled();});
test('Security and password dialog remain accessible on desktop mobile dark and enlarged text',async({page},info)=>{await setup(page);await open(page);for(const [width,height,dark,large]of[[1366,768,false,false],[390,844,false,false],[320,844,true,true]]){await page.setViewportSize({width,height});await page.evaluate(({dark,large})=>{document.documentElement.classList.toggle('theme-dark',dark);document.documentElement.style.fontSize=large?'125%':'100%';},{dark,large});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect((await new AxeBuilder({page}).include('[data-security-content]').analyze()).violations).toEqual([]);await page.screenshot({path:info.outputPath(`security-${width}-${dark?'dark':'light'}.png`)});await page.locator('main').evaluate(el=>{el.scrollTop=el.scrollHeight;});await page.screenshot({path:info.outputPath(`security-lower-${width}-${dark?'dark':'light'}.png`)});await page.locator('main').evaluate(el=>{el.scrollTop=0;});}await page.getByRole('button',{name:'Change password',exact:true}).click();expect((await new AxeBuilder({page}).include('dialog').analyze()).violations).toEqual([]);await page.screenshot({path:info.outputPath('password-mobile-dark.png')});});


test('unmanaged sessions require sign-in before guarded MFA/passkey actions',async({page})=>{await setup(page,{sessionManaged:false,sessions:[]});await open(page);await expect(page.getByRole('button',{name:'Enable email codes'})).toBeDisabled();await expect(page.getByRole('button',{name:'Set up authenticator'})).toBeDisabled();await expect(page.getByRole('button',{name:'Add passkey',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Change password',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'Sign out other devices',exact:true})).toHaveCount(0);});
test('unsupported passkey capability and disabled MFA do not invent working controls',async({page})=>{await page.addInitScript(()=>{Object.defineProperty(window,'PublicKeyCredential',{value:undefined,configurable:true});});await setup(page,{disabled:true});await open(page);await expect(page.getByRole('button',{name:'Enable email codes'})).toBeDisabled();await expect(page.getByRole('button',{name:'Add passkey',exact:true})).toBeDisabled();await expect(page.getByText(/Passkey setup is unavailable/)).toBeVisible();await expect(page.getByRole('button',{name:'Change password',exact:true})).toBeEnabled();});
test('replacing an authenticator keeps the current method until setup is confirmed',async({page})=>{const model=await setup(page,{enabled:true,method:'authenticator',hasBackupCodes:true});await open(page);await page.getByRole('button',{name:'Replace authenticator'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('dialog',{name:'Connect your authenticator app'})).toBeVisible();expect(model.method).toBe('authenticator');expect(model.enabled).toBe(true);await page.getByRole('button',{name:'Cancel',exact:true}).click();expect(model.writes).toHaveLength(1);});
test('invalid authenticator codes remain retryable and too many attempts clear the secret',async({page})=>{const model=await setup(page);await open(page);await page.getByRole('button',{name:'Set up authenticator'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('dialog',{name:'Connect your authenticator app'})).toBeVisible();model.reject={status:400,body:{error:'That code is not valid. Try the current code from your app.'}};await page.getByLabel('Six-digit code').fill('123456');await page.getByRole('button',{name:'Confirm authenticator'}).click();await expect(page.getByText('That code is not valid. Enter the current code from your app.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Confirm authenticator'})).toBeEnabled();model.reject={status:429,body:{error:'Too many attempts. Start setup again.'}};await page.getByLabel('Six-digit code').fill('123456');await page.getByRole('button',{name:'Confirm authenticator'}).click();await expect(page.getByText('Too many attempts. Start setup again.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Confirm authenticator'})).toBeDisabled();await expect(page.getByRole('img',{name:'Authenticator setup QR code'})).not.toHaveAttribute('src',/data:/);});
test('navigation clears password and enrollment secrets instead of restoring them as drafts',async({page})=>{await setup(page);await open(page);await page.getByRole('button',{name:'Set up authenticator'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByRole('dialog',{name:'Connect your authenticator app'})).toBeVisible();await page.evaluate(()=>{location.hash='/home';});await expect(page.getByRole('dialog')).toHaveCount(0);await page.evaluate(()=>{location.hash='/settings?tab=security';});await expect(page.locator('[data-security-content]')).toHaveAttribute('aria-busy','false');await expect(page.locator('[data-security-secret]')).toHaveCount(0);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toMatch(/ABCDEFGHIJKLMNOP|secure current/);});
test('lost password response clears fields and offers sign-in without another mutation',async({page})=>{const model=await setup(page,{lost:true});await open(page);await page.getByRole('button',{name:'Change password',exact:true}).click();await password(page);await page.getByLabel('New password',{exact:true}).fill('A newer secure test passphrase');await page.getByLabel('Confirm new password',{exact:true}).fill('A newer secure test passphrase');await page.getByRole('button',{name:'Change password and sign out'}).click();await expect(page.getByText(/The password change could not be confirmed/)).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);expect(model.writes).toHaveLength(1);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/login.html/);});
test('passkey removal requires password confirmation and reads back the remaining list',async({page})=>{const model=await setup(page,{passkeys:[{id:'c'.repeat(24),name:'Work device',createdAt:'2026-09-09T10:00:00Z'}]});await open(page);await page.getByRole('button',{name:'Remove Work device'}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();expect(model.writes).toHaveLength(0);await page.getByRole('button',{name:'Remove Work device'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Remove passkey'}).click();await expect(page.getByText('No passkeys added.',{exact:true})).toBeVisible();expect(model.passkeys).toHaveLength(0);});

test('email verification prerequisites explain the actual requirement instead of a false conflict',async({page})=>{await setup(page,{reject:{status:409,body:{error:'Verify your email before enabling two-step verification.'}}});await open(page);await page.getByRole('button',{name:'Enable email codes'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(page.getByText('Verify your email before enabling email sign-in codes.',{exact:true})).toBeVisible();await expect(page.getByText(/security settings changed/i)).toHaveCount(0);});

test('security shortcuts focus an enabled relevant control even when the first method is active',async({page})=>{await setup(page,{enabled:true,method:'email'});await page.goto('/attorney-v2.html#/settings?panel=security:verification');await expect(page.getByRole('button',{name:'Set up authenticator'})).toBeFocused();await page.evaluate(()=>{location.hash='/settings?settingsTarget=security:password';});await expect(page.getByRole('button',{name:'Change password',exact:true})).toBeFocused();});
test('failed later device pages preserve existing rows and deliberate retry loads the rest',async({page})=>{const model=await setup(page,{more:true,pageFail:true});await open(page);await page.getByRole('button',{name:'Load more devices'}).click();await expect(page.getByText('More devices could not be loaded. Try again.',{exact:true})).toBeVisible();await expect(page.locator('[data-security-session]')).toHaveCount(2);model.pageFail=false;await page.getByRole('button',{name:'Load more devices'}).click();await expect(page.locator('[data-security-session]')).toHaveCount(3);});
test('failed refresh labels retained passkeys and disables stale actions until a fresh read',async({page})=>{const model=await setup(page,{passkeys:[{id:'c'.repeat(24),name:'Work device',createdAt:'2026-09-09T10:00:00Z'}]});await open(page);model.passkeysFail=true;await page.getByRole('button',{name:'Refresh security'}).click();await expect(page.getByText('Passkeys could not be refreshed. The previous list is shown below.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Remove Work device'})).toBeDisabled();model.passkeysFail=false;await page.getByRole('button',{name:'Refresh security'}).click();await expect(page.getByRole('button',{name:'Remove Work device'})).toBeEnabled();});
test('backup codes download only on request and their text clears on dismissal',async({page})=>{await setup(page,{enabled:true});await open(page);await page.getByRole('button',{name:'Generate backup codes',exact:true}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Generate codes'}).click();await expect(page.getByRole('dialog',{name:'Save your backup codes'})).toBeVisible();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download codes'}).click();expect((await download).suggestedFilename()).toBe('lpc-backup-codes.txt');await page.getByRole('button',{name:'Done',exact:true}).click();await expect(page.getByText(/ABCD123456/)).toHaveCount(0);});


test('malformed success cannot claim that an unconfirmed MFA mutation completed',async({page})=>{const model=await setup(page,{malformed:true});await open(page);await page.getByRole('button',{name:'Enable email codes'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(page.getByText(/two-step verification result could not be confirmed/)).toBeVisible();await expect(page.getByText('Email sign-in codes enabled.',{exact:true})).toHaveCount(0);expect(model.enabled).toBe(false);expect(model.writes).toHaveLength(1);});
test('refresh disables existing security actions until every current read settles',async({page})=>{const model=await setup(page);await open(page);let release;model.stateDelay=new Promise(resolve=>{release=resolve;});await page.getByRole('button',{name:'Refresh security'}).click();await expect(page.getByRole('button',{name:'Enable email codes'})).toBeDisabled();await expect(page.getByRole('button',{name:'Change password',exact:true})).toBeDisabled();model.stateDelay=null;release();await expect(page.getByRole('button',{name:'Enable email codes'})).toBeEnabled();});
test('a confirmation retains the reviewed security revision if a background read completes later',async({page})=>{const model=await setup(page);await open(page);await page.getByRole('button',{name:'Enable email codes'}).click();await password(page);model.revision='b'.repeat(64);await page.evaluate(()=>document.querySelector('.av2-security .av2-refresh').click());await expect(page.locator('[data-security-content]')).toHaveAttribute('aria-busy','false');await page.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(page.getByText('Your security settings changed. Review the current settings before trying again.',{exact:true})).toBeVisible();expect(model.writes[0].body.expectedSecurityRevision).toBe(revision);expect(model.enabled).toBe(false);});
test('closing backup codes restores focus to the refreshed code action',async({page})=>{await setup(page,{enabled:true});await open(page);await page.getByRole('button',{name:'Generate backup codes',exact:true}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Generate codes'}).click();await expect(page.getByRole('dialog',{name:'Save your backup codes'})).toBeVisible();await expect(page.locator('[data-security-content]')).toHaveAttribute('aria-busy','false');await page.getByRole('button',{name:'Done',exact:true}).click();await expect(page.getByRole('button',{name:'Generate new backup codes'})).toBeFocused();});
test('a successful refresh restores safe section focus when the confirmed action disappears',async({page})=>{await setup(page);await open(page);await page.getByRole('button',{name:'Enable email codes'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(page.getByText('Email sign-in codes enabled.',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Two-step verification',exact:true})).toBeFocused();});

test('Security controls and restored focus remain usable with doubled text at narrow width',async({page},info)=>{await setup(page,{enabled:true});await open(page);await page.setViewportSize({width:320,height:844});await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});const overflow=selector=>page.locator(selector).evaluateAll(elements=>elements.map(element=>{const bounds=element.getBoundingClientRect();return {label:element.textContent.slice(0,80),left:bounds.left,right:bounds.right,scrollWidth:element.scrollWidth,clientWidth:element.clientWidth};}).filter(bounds=>bounds.left< -1||bounds.right>innerWidth+1||bounds.scrollWidth>bounds.clientWidth+1));expect(await overflow('[data-security-content] button')).toEqual([]);await page.getByRole('button',{name:'Generate backup codes',exact:true}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Generate codes'}).click();await expect(page.getByRole('dialog',{name:'Save your backup codes'})).toBeVisible();expect(await overflow('dialog')).toEqual([]);await page.screenshot({path:info.outputPath('backup-codes-mobile-200.png')});await page.getByRole('button',{name:'Done',exact:true}).click();const restored=page.getByRole('button',{name:'Generate new backup codes'});await expect(restored).toBeFocused();await expect(restored).toBeInViewport();});
