const path=require('path');
const { test, expect } = require('../../helpers/isolatedBrowserTest')('attorney-security-real');
const start=require(path.resolve(__dirname,'../../../../docs/audits/completion-2026-09-09/security/backend-browser-server.cjs'));
const SECURITY_BASE_URL='http://localhost:5289';
test.use({ baseURL: SECURITY_BASE_URL, storageState: { cookies: [], origins: [] } });
let server,owner,pageErrors,consoleErrors;
test.beforeAll(async()=>{test.setTimeout(120000);server=await start({port:5289});});
test.afterAll(async()=>{await server?.close();});
test.beforeEach(async({context})=>{
 pageErrors=[];consoleErrors=[];
 const observe=page=>{page.on('pageerror',error=>pageErrors.push(error.message));page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});};
 context.pages().forEach(observe);context.on('page',observe);
 await context.addInitScript(()=>{window.__securityLoadEvidence={domContentLoaded:false,load:false};document.addEventListener('DOMContentLoaded',()=>{window.__securityLoadEvidence.domContentLoaded=true;},{once:true});window.addEventListener('load',()=>{window.__securityLoadEvidence.load=true;},{once:true});});
 owner=await server.createUser();await context.addCookies([owner.cookie]);
});
test.afterEach(async({context},info)=>{
 const pages=await Promise.all(context.pages().map(page=>page.evaluate(()=>({path:location.pathname,readyState:document.readyState,appState:document.documentElement.dataset.attorneyState,...window.__securityLoadEvidence})).catch(error=>({unavailable:error.message}))));
 await info.attach('security-runtime',{body:JSON.stringify({pages,pageErrors,consoleErrors},null,2),contentType:'application/json'});
 expect(pageErrors).toEqual([]);
});
async function open(page){
 const destination=new URL('/attorney-v2.html#/settings?tab=security',SECURITY_BASE_URL);
 await page.evaluate(url=>{setTimeout(()=>location.assign(url),0);},destination.href);
 await expect(page).toHaveURL(destination.href);
 await expect(page.locator('html')).toHaveAttribute('data-attorney-state','ready');
 await expect(page.locator('[data-security-content]')).toHaveAttribute('aria-busy','false');
 await expect(page.getByRole('button',{name:'Change password',exact:true})).toBeEnabled();
}
async function password(page){await page.getByRole('dialog').getByLabel('Current password',{exact:true}).fill(server.password);}
async function enableEmail(page){await page.getByRole('button',{name:'Enable email codes'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(page.getByText('Email sign-in codes enabled.',{exact:true})).toBeVisible();}

test('actual password change revokes every managed session and the new password signs in',async({page,context})=>{
 await server.cookieFor(owner.id);await open(page);await page.getByRole('button',{name:'Change password',exact:true}).click();await password(page);await page.getByLabel('New password',{exact:true}).fill('An entirely newer security passphrase');await page.getByLabel('Confirm new password',{exact:true}).fill('An entirely newer security passphrase');await page.getByRole('button',{name:'Change password and sign out'}).click();await expect(page).toHaveURL(/login.html/);expect((await server.sessions(owner.id)).every(item=>item.revokedAt)).toBe(true);
 const old=await context.request.post('/api/auth/login',{data:{email:owner.email,password:server.password}});expect(old.status()).toBe(401);const valid=await context.request.post('/api/auth/login',{data:{email:owner.email,password:'An entirely newer security passphrase'}});expect(valid.status()).toBe(200);expect((await valid.json()).twoFactorRequired).not.toBe(true);
});
test('actual email MFA keeps the current session and backup-code rotation invalidates the previous set',async({page})=>{
 await server.cookieFor(owner.id);await open(page);await enableEmail(page);expect((await server.inspectUser(owner.id)).twoFactorEnabled).toBe(true);expect((await server.sessions(owner.id)).filter(item=>!item.revokedAt)).toHaveLength(1);
 await page.getByRole('button',{name:'Generate backup codes',exact:true}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Generate codes'}).click();await expect(page.getByRole('dialog',{name:'Save your backup codes'})).toBeVisible();const first=await page.locator('.av2-security-codes').innerText();const hashes=(await server.inspectUser(owner.id)).twoFactorBackupCodes;await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Generate new backup codes'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Generate codes'}).click();const second=await page.locator('.av2-security-codes').innerText();expect(second).not.toBe(first);expect((await server.inspectUser(owner.id)).twoFactorBackupCodes).not.toEqual(hashes);await page.getByRole('button',{name:'Done',exact:true}).click();
 const challenged=await page.request.post('/api/auth/login',{data:{email:owner.email,password:server.password}});const challenge=(await challenged.json()).challengeToken;const rejected=await page.request.post('/api/auth/2fa-backup',{data:{challengeToken:challenge,code:first.split('\n')[0]}});expect(rejected.status()).toBe(400);const accepted=await page.request.post('/api/auth/2fa-backup',{data:{challengeToken:challenge,code:second.split('\n')[0]}});expect(accepted.status()).toBe(200);
});
test('actual authenticator enrollment confirms real TOTP and returns one-time backup codes',async({page})=>{
 await open(page);await page.getByRole('button',{name:'Set up authenticator'}).click();await password(page);const setupReply=page.waitForResponse(response=>response.url().endsWith('/api/account/2fa/authenticator/setup')&&response.request().method()==='POST');await page.getByRole('dialog').getByRole('button',{name:'Continue',exact:true}).click();const enrollment=await(await setupReply).json();await page.getByLabel('Six-digit code').fill(server.totp(enrollment.manualSecret));await page.getByRole('button',{name:'Confirm authenticator'}).click();await expect(page.getByRole('dialog',{name:'Save your backup codes'})).toBeVisible();expect((await server.inspectUser(owner.id)).twoFactorMethod).toBe('authenticator');expect((await page.locator('.av2-security-codes').innerText()).split('\n')).toHaveLength(8);await page.getByRole('button',{name:'Done',exact:true}).click();await expect(page.getByRole('button',{name:'Replace authenticator'})).toBeEnabled();
});
test('actual expired authenticator challenge stays recoverable without enabling MFA',async({page})=>{
 await open(page);await page.getByRole('button',{name:'Set up authenticator'}).click();await password(page);const setupReply=page.waitForResponse(response=>response.url().endsWith('/api/account/2fa/authenticator/setup')&&response.request().method()==='POST');await page.getByRole('dialog').getByRole('button',{name:'Continue',exact:true}).click();const enrollment=await(await setupReply).json();await server.expireChallenge(enrollment.challengeId);await page.getByLabel('Six-digit code').fill(server.totp(enrollment.manualSecret));await page.getByRole('button',{name:'Confirm authenticator'}).click();await expect(page.getByText(/setup expired/i)).toBeVisible();expect((await server.inspectUser(owner.id)).twoFactorEnabled).toBe(false);await expect(page.getByRole('button',{name:'Confirm authenticator'})).toBeDisabled();
});
test('two real tabs detect security changes and preserve unrelated profile edits',async({page,context})=>{
 await open(page);const second=await context.newPage();await open(second);await server.updateUser(owner.id,{lawFirm:'Preserved independent firm'});await enableEmail(page);await second.getByRole('button',{name:'Enable email codes'}).click();await password(second);await second.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(second.getByText('Your security settings changed. Review the current settings before trying again.',{exact:true})).toBeVisible();expect(await server.inspectUser(owner.id)).toMatchObject({twoFactorEnabled:true,lawFirm:'Preserved independent firm'});await second.close();
});
test('actual account replacement after preflight cannot write into the replacement',async({page,context})=>{
 await open(page);const replacement=await server.createUser();let switched=false;await page.route('**/api/csrf',async route=>{if(!switched){switched=true;await context.addCookies([replacement.cookie]);}await route.continue();});await page.getByRole('button',{name:'Enable email codes'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(page).toHaveURL(/login.html|dashboard-attorney.html/);expect((await server.inspectUser(owner.id)).twoFactorEnabled).toBe(false);expect((await server.inspectUser(replacement.id)).twoFactorEnabled).toBe(false);
});
test('real paged device list retains the current session beyond the first fifty and signs out all others',async({page})=>{
 const current=(await server.sessions(owner.id))[0].sessionId;for(let index=0;index<55;index++)await server.cookieFor(owner.id,{ua:`Synthetic Firefox Windows ${index}`});await open(page);await expect(page.locator(`[data-security-session="${current}"]`)).toHaveCount(1);await expect(page.getByRole('button',{name:'Load more devices'})).toBeVisible();await page.getByRole('button',{name:'Load more devices'}).click();await expect(page.locator('[data-security-session]')).toHaveCount(56);await expect(page.getByRole('button',{name:'Load more devices'})).toHaveCount(0);await page.getByRole('button',{name:'Sign out other devices',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Sign out other devices',exact:true}).click();await expect(page.getByText('Other devices signed out.',{exact:true})).toBeVisible();const active=(await server.sessions(owner.id)).filter(item=>!item.revokedAt);expect(active).toHaveLength(1);expect(active[0].sessionId).toBe(current);
});
test('actual committed backup-code response loss is reviewed without repeating the rotation',async({page})=>{
 await open(page);await enableEmail(page);let writes=0;await page.route('**/api/account/2fa-backup-codes',async route=>{writes++;await route.fetch();await route.abort('failed');});await page.getByRole('button',{name:'Generate backup codes',exact:true}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Generate codes'}).click();await expect(page.getByText(/Backup codes may have changed/)).toBeVisible();expect(writes).toBe(1);expect((await server.inspectUser(owner.id)).twoFactorBackupCodes).toHaveLength(8);await expect(page.getByRole('button',{name:'Generate new backup codes'})).toBeEnabled();
});
for(const operation of ['mfa','backup','sessions'])test(`post-write owner failure recovers actual ${operation} without replay`,async({page})=>{
 if(operation==='sessions')await server.cookieFor(owner.id);await open(page);if(operation==='backup')await enableEmail(page);const endpoint=operation==='mfa'?'/api/account/2fa-toggle':operation==='backup'?'/api/account/2fa-backup-codes':'/api/account/sessions/revoke-others';let writes=0,fail=false;await page.route('**'+endpoint,async route=>{writes++;const response=await route.fetch();expect(response.status()).toBe(200);fail=true;await route.fulfill({response});});await page.route('**/api/auth/me',async route=>{if(fail){fail=false;return route.fulfill({status:503,contentType:'application/json',body:'{}'});}return route.continue();});
 if(operation==='mfa'){await page.getByRole('button',{name:'Enable email codes'}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Enable email codes'}).click();await expect(page.getByRole('button',{name:'Enabled',exact:true})).toBeVisible();expect((await server.inspectUser(owner.id)).twoFactorEnabled).toBe(true);}else if(operation==='backup'){await page.getByRole('button',{name:'Generate backup codes',exact:true}).click();await password(page);await page.getByRole('dialog').getByRole('button',{name:'Generate codes'}).click();await expect(page.getByText(/Backup codes may have changed/)).toBeVisible();expect((await server.inspectUser(owner.id)).twoFactorBackupCodes).toHaveLength(8);}else{await page.getByRole('button',{name:'Sign out other devices',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Sign out other devices',exact:true}).click();await expect(page.locator('[data-security-session]')).toHaveCount(1);expect((await server.sessions(owner.id)).filter(item=>!item.revokedAt)).toHaveLength(1);}await expect(page.getByRole('dialog')).toHaveCount(0);expect(writes).toBe(1);
});
