const { test, expect } = require("../support-session-fixture"), AxeBuilder = require("@axe-core/playwright").default;
const root = page => page.locator("[data-workspace-withdrawal]"), id = n => n.toString(16).padStart(24, "0");
const fulfill = (route, value, status = 200) => route.fulfill({ status, contentType: "application/json", body: JSON.stringify(value) });
async function fixture(page) {
  const user = (await (await page.request.get("/api/auth/me")).json()).user, ownerId = user.id || user._id, csrf = (await (await page.request.get("/api/csrf")).json()).csrfToken;
  const send = async (path, data) => { const response = await page.request.post(path, { headers: { "X-CSRF-Token": csrf }, data: { ...data, expectedOwnerId: ownerId } }); expect(response.ok(), await response.text()).toBeTruthy(); return response.json(); };
  const draft = (await send("/api/case-drafts", { title: "River Street lease review", practiceArea: "Contract Law", state: "New York", compAmount: "1000.00", experience: "3+ years", deadline: "2027-03-14", description: "Review the lease and organize its exhibits.", tasks: [{ title: "Review the lease" }] })).draft;
  const published = await send("/api/cases/posting/publications", { draftId: draft.id, revision: draft.revision, requestId: require("crypto").randomUUID(), practiceArea: "contract law" }), caseId = published.publication.caseId;
  const state = { reads: [], writes: [], status: 200, writeStatus: 200, outcome: null, view: { ownerId, caseId, caseTitle: "River Street lease review", revision: "d".repeat(64), applicable: true, state: "decision_required", blockers: [], paralegalId: id(100), paralegalName: "Priya Ng", withdrawnAt: "2026-09-01T12:00:00Z", originalCents: 100001, remainingCents: 100001, balanceVerified: true, currency: "USD", feePct: 18, maximumPayoutCents: 70001, work: { complete: 1, total: 2 }, canDecide: true, canPay: true, canRelist: false, fundingReady: true, payoutSetupReady: true, reviewDeadline: null, adminDeadline: null, decision: null, relistedAt: null, operation: null } };
  state.dto = requestId => ({ ...state.view, operation: requestId ? { requestId, status: state.outcome || "not_found", action: state.outcome ? state.writes.at(-1)?.action || "partial" : null, amountCents: state.outcome ? state.writes.at(-1)?.amountCents ?? null : null, at: state.outcome ? "2026-09-09T12:00:00Z" : null } : null });
  await page.route(`**/api/cases/${caseId}/withdrawal-review?**`, route => { const query = new URL(route.request().url()).searchParams; state.reads.push(Object.fromEntries(query)); return fulfill(route, state.status === 200 ? state.dto(query.get("requestId")) : {}, state.status); });
  state.record = body => { state.outcome = "recorded"; state.view = { ...state.view, canDecide: false, canPay: false, canRelist: false, revision: "e".repeat(64), state: body.action === "reject" ? "review_window" : "finalized", ...(body.action === "reject" ? { reviewDeadline: "2027-03-14T12:00:00Z" } : { relistedAt: "2026-09-09T12:00:00Z" }), ...(body.action === "partial" ? { remainingCents: state.view.remainingCents - body.amountCents, decision: { type: "partial_attorney", amountCents: body.amountCents, netCents: body.amountCents ? body.amountCents - Math.round(body.amountCents * 18 / 100) : null, payoutState: body.amountCents ? "recorded" : "none", at: "2026-09-09T12:00:00Z" } } : {}) }; };
  await page.route(`**/api/cases/${caseId}/withdrawal-decision`, route => { const body = route.request().postDataJSON(); state.writes.push(body); if (state.writeStatus === 0) { state.record(body); return route.abort("failed"); } if (state.writeStatus !== 200) return fulfill(route, {}, state.writeStatus); state.record(body); return fulfill(route, state.dto(body.requestId)); });
  await page.goto(`/attorney-v2.html#/matters/${caseId}/financials`, { waitUntil: "domcontentloaded" }); await expect(root(page)).toHaveAttribute("data-state", "ready"); return { state, caseId, ownerId };
}
async function reviewAmount(page, amount = "200.01") { await root(page).getByLabel("Withdrawal amount before the paralegal fee · USD", { exact: true }).fill(amount); await root(page).getByRole("button", { name: "Review payout amount", exact: true }).click(); }
for (const outcome of ["unchanged", "changed", "failed", "canceled"]) test(`withdrawal review survives a background read during its click: ${outcome}`, async ({ page }) => {
  const { state, caseId } = await fixture(page);
  await root(page).getByLabel("Withdrawal amount before the paralegal fee · USD", { exact: true }).fill("200.01");
  let arrived, release;
  const waiting = new Promise(resolve => { arrived = resolve; }), gate = new Promise(resolve => { release = resolve; });
  await page.route(`**/api/cases/${caseId}/withdrawal-review?**`, async route => { arrived(); await gate; await route.fallback(); }, { times: 1 });
  await root(page).evaluate(section => section.querySelector('button[type="submit"]').addEventListener("pointerdown", () => { void section.sync(); }, { once: true }));
  try {
    await root(page).getByRole("button", { name: "Review payout amount", exact: true }).click(); await waiting;
    await expect(root(page).locator("[data-withdrawal-confirmation]")).toBeVisible();
    await expect(root(page).getByRole("button", { name: "Record decision and pay $164.01", exact: true })).toBeDisabled();
    expect(state.writes).toEqual([]);
    if (outcome === "changed") state.view = { ...state.view, revision: "a".repeat(64), remainingCents: 10000, maximumPayoutCents: 10000 };
    if (outcome === "failed") state.status = 503;
    if (outcome === "canceled") {
      await root(page).getByRole("button", { name: "Keep reviewing", exact: true }).click();
      await expect(root(page).getByLabel("Withdrawal amount before the paralegal fee · USD", { exact: true })).toBeFocused();
    }
    release();
    if (outcome === "unchanged") {
      await root(page).getByRole("button", { name: "Record decision and pay $164.01", exact: true }).click();
      await expect(root(page)).toContainText("Withdrawal decision recorded");
      expect(state.writes).toHaveLength(1); expect(state.writes[0]).toMatchObject({ amountCents: 20001, reviewedRevision: "d".repeat(64) });
    } else {
      await expect(root(page).getByRole("button", { name: "Refresh withdrawal details", exact: true })).toBeEnabled();
      await expect(root(page).locator("[data-withdrawal-confirmation]")).toHaveCount(0);
      if (outcome !== "canceled") await expect(root(page)).toContainText(outcome === "changed" ? "Withdrawal details changed" : "Withdrawal details couldn’t load");
      expect(state.writes).toEqual([]);
    }
  } finally { release(); }
});
test("the amount, fee, payee and remaining work are shown before the decision is sent", async ({ page }) => {
  const { state, ownerId, caseId } = await fixture(page); await expect(root(page)).toContainText("1 of 2 work items"); await reviewAmount(page); await expect(root(page).locator("[data-withdrawal-confirmation]")).toBeFocused(); await expect(root(page)).toContainText("$36.00"); await expect(root(page)).toContainText("$164.01"); await expect(root(page)).toContainText("$800.00"); expect(state.writes).toEqual([]); await root(page).getByRole("button", { name: "Keep reviewing", exact: true }).click(); await expect(root(page).getByLabel("Withdrawal amount before the paralegal fee · USD", { exact: true })).toBeFocused();
  await reviewAmount(page); await root(page).getByRole("button", { name: "Record decision and pay $164.01", exact: true }).click(); await expect(root(page)).toContainText("Withdrawal decision recorded"); expect(state.writes).toHaveLength(1); expect(state.writes[0]).toMatchObject({ expectedOwnerId: ownerId, action: "partial", amountCents: 20001, reviewedRevision: "d".repeat(64) }); expect(Object.keys(state.writes[0]).sort()).toEqual(["action", "amountCents", "expectedOwnerId", "requestId", "reviewedRevision"]); await expect(root(page).getByRole("link", { name: "Review replacement applications" })).toHaveAttribute("href", `#/matters/${caseId}/applications`);
});
test("zero payout and declining release explain their different relisting and review outcomes", async ({ page }) => {
  const { state } = await fixture(page); await reviewAmount(page, "0"); await expect(root(page)).toContainText("It does not start a payment-review window"); await root(page).getByRole("button", { name: "Keep reviewing", exact: true }).click(); await root(page).getByRole("button", { name: "Review decline of payment", exact: true }).click(); await expect(root(page)).toContainText("24-hour window"); await root(page).getByRole("button", { name: "Decline release and start review window", exact: true }).click(); await expect(root(page)).toContainText("Payment-review window ends"); expect(state.writes[0].action).toBe("reject"); expect(state.writes[0].amountCents).toBeUndefined(); await expect(root(page).getByRole("button", { name: "Review payout amount", exact: true })).toHaveCount(0);
});
test("a zero decision records no payout and makes the remaining work available", async ({ page }) => {
  const { state } = await fixture(page); await reviewAmount(page, "0"); await root(page).getByRole("button", { name: "Record no payout and relist", exact: true }).click(); await expect(root(page)).toContainText("No payout was issued"); await expect(root(page)).toContainText("Relisting request recorded"); expect(state.writes[0].amountCents).toBe(0); await expect(root(page)).not.toContainText("Recorded paralegal payout");
});
test("a finalized decision can relist without changing its amount or requesting another payout", async ({ page }) => {
  const { state } = await fixture(page); state.view = { ...state.view, state: "finalized", canDecide: false, canPay: false, canRelist: true, decision: { type: "expired_zero", amountCents: 0, netCents: null, payoutState: "none", at: "2026-09-02T12:00:00Z" } }; await root(page).getByRole("button", { name: "Refresh withdrawal details" }).click(); await root(page).getByRole("button", { name: "Review relisting", exact: true }).click(); await root(page).getByRole("button", { name: "Relist remaining work", exact: true }).click(); await expect(root(page)).toContainText("Relisting request recorded"); expect(state.writes[0].action).toBe("relist"); expect(state.writes[0].amountCents).toBeUndefined();
});
test("input rejects rounded, negative and over-limit amounts and incomplete payout setup", async ({ page }) => {
  const { state } = await fixture(page); for (const amount of ["1.001", "-1", "1e3", "700.02"]) { await reviewAmount(page, amount); await expect(root(page).locator("[data-withdrawal-confirmation]")).toHaveCount(0); } state.view = { ...state.view, canPay: false, payoutSetupReady: false }; await root(page).getByRole("button", { name: "Refresh withdrawal details" }).click(); await expect(root(page).getByRole("button", { name: "Refresh withdrawal details", exact: true })).toBeEnabled(); await reviewAmount(page); await expect(root(page)).toContainText("positive payout is not available"); expect(state.writes).toEqual([]);
});
test("a lost response recovers the same decision without resending the payout", async ({ page }) => {
  const { state } = await fixture(page); state.writeStatus = 0; await reviewAmount(page); await root(page).getByRole("button", { name: "Record decision and pay $164.01", exact: true }).click(); await expect(root(page)).toContainText("decision could not be confirmed"); await root(page).getByRole("button", { name: "Check withdrawal decision", exact: true }).click(); await expect(root(page)).toContainText("Withdrawal decision recorded"); expect(state.reads.at(-1).requestId).toBe(state.writes[0].requestId); expect(state.writes).toHaveLength(1);
});
test("stopping the wait retains an uncertain decision across Matter tabs", async ({ page }) => {
  const { state, caseId } = await fixture(page); let arrived, release; const waiting = new Promise(resolve => { arrived = resolve; }), gate = new Promise(resolve => { release = resolve; }); await page.route(`**/api/cases/${caseId}/withdrawal-decision`, async route => { state.writes.push(route.request().postDataJSON()); state.outcome = "processing"; arrived(); await gate; await fulfill(route, {}).catch(() => {}); });
  await reviewAmount(page); await root(page).getByRole("button", { name: "Record decision and pay $164.01", exact: true }).click(); try { await waiting; await root(page).getByRole("button", { name: "Stop waiting for the withdrawal decision", exact: true }).click(); await expect(root(page)).toContainText("Stopping the wait does not cancel a transfer"); await page.getByRole("navigation", { name: "Matter sections" }).getByRole("link", { name: "Overview", exact: true }).click(); await page.getByRole("navigation", { name: "Matter sections" }).getByRole("link", { name: "Financials", exact: true }).click(); await expect(root(page)).toContainText("decision is still being processed"); expect(state.reads.at(-1).requestId).toBe(state.writes[0].requestId); expect(state.writes).toHaveLength(1); } finally { release(); }
});
test("a changed amount clears the earlier confirmation and a failed read clears permission", async ({ page }) => {
  const { state } = await fixture(page); await reviewAmount(page); state.view = { ...state.view, revision: "a".repeat(64), remainingCents: 10000, maximumPayoutCents: 10000 }; await root(page).getByRole("button", { name: "Refresh withdrawal details" }).click(); await expect(root(page).locator("[data-withdrawal-confirmation]")).toHaveCount(0); await reviewAmount(page); await expect(root(page)).toContainText("exceeds the available attorney payout"); state.status = 503; await root(page).getByRole("button", { name: "Refresh withdrawal details" }).click(); await expect(root(page)).toContainText("Withdrawal details couldn’t load"); await expect(root(page).getByRole("button", { name: "Review payout amount", exact: true })).toHaveCount(0); expect(state.writes).toEqual([]);
});
test("review windows, administrative review and reversed payments keep their actual meaning", async ({ page }) => {
  const { state } = await fixture(page); state.view = { ...state.view, canDecide: false, canPay: false, state: "review_overdue", reviewDeadline: "2026-09-02T12:00:00Z" }; await root(page).getByRole("button", { name: "Refresh withdrawal details" }).click(); await expect(root(page)).toContainText("no final outcome is recorded yet"); state.view = { ...state.view, state: "admin_review", blockers: ["dispute_open"], adminDeadline: "2026-09-10T12:00:00Z" }; await root(page).getByRole("button", { name: "Refresh withdrawal details" }).click(); await expect(root(page)).toContainText("LPC is reviewing the dispute"); state.view = { ...state.view, state: "finalized", blockers: ["payout_needs_review"], decision: { type: "partial_attorney", amountCents: 20001, netCents: null, payoutState: "reversed", at: "2026-09-09T12:00:00Z" } }; await root(page).getByRole("button", { name: "Refresh withdrawal details" }).click(); await expect(root(page)).toContainText("payout has been reversed"); await expect(root(page).getByRole("button", { name: "Review relisting", exact: true })).toHaveCount(0); expect(state.writes).toEqual([]);
});
test("an account change removes the private confirmation before any payout request", async ({ page }) => {
  const { state } = await fixture(page); await reviewAmount(page); await page.route("**/api/auth/me", route => fulfill(route, { user: { id: id(777), role: "attorney", status: "approved" } })); await root(page).getByRole("button", { name: "Record decision and pay $164.01", exact: true }).click(); await expect(root(page)).toHaveCount(0); expect(state.writes).toEqual([]);
});
test("long Matter names and decision controls remain readable, keyboard accessible and within the page", async ({ page }, testInfo) => {
  const { state } = await fixture(page); state.view.caseTitle = '<img src=x onerror="window.withdrawalXss=true"> River Street lease exhibits '.repeat(3); await root(page).getByRole("button", { name: "Refresh withdrawal details" }).click(); await expect(root(page).getByRole("button", { name: "Refresh withdrawal details", exact: true })).toBeEnabled(); await reviewAmount(page);
  for (const width of [320, 390, 768, 1366]) { await page.setViewportSize({ width, height: 900 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); expect(await page.evaluate(() => window.withdrawalXss)).toBeUndefined(); expect((await new AxeBuilder({ page }).include("[data-workspace-withdrawal]").withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]); await root(page).getByRole("button", { name: "Keep reviewing", exact: true }).focus(); await expect(root(page).getByRole("button", { name: "Keep reviewing", exact: true })).toBeFocused(); await root(page).evaluate(element => element.scrollIntoView({ block: "start" })); await page.screenshot({ path: testInfo.outputPath(`withdrawal-top-${width}.png`), fullPage: true }); await root(page).getByRole("button", { name: "Record decision and pay $164.01", exact: true }).scrollIntoViewIfNeeded(); await page.screenshot({ path: testInfo.outputPath(`withdrawal-decision-${width}.png`), fullPage: true }); }
});

test("a background refresh preserves the typed amount and cursor until the decision is no longer available", async ({ page }) => {
  const { state } = await fixture(page), input = root(page).getByLabel("Withdrawal amount before the paralegal fee · USD", { exact: true }); await input.fill("200.01"); await input.evaluate(element => element.setSelectionRange(3, 3)); state.view = { ...state.view, revision: "a".repeat(64), payoutSetupReady: false, canPay: false }; await root(page).evaluate(element => element.sync()); await expect(input).toHaveValue("200.01"); await expect(input).toBeFocused(); expect(await input.evaluate(element => element.selectionStart)).toBe(3); expect(state.writes).toEqual([]);
});

test("an outcome from another request cannot clear an uncertain payout", async ({ page }) => {
  const { state, caseId } = await fixture(page); state.writeStatus = 0; await reviewAmount(page); await root(page).getByRole("button", { name: "Record decision and pay $164.01", exact: true }).click(); await expect(root(page)).toContainText("decision could not be confirmed"); await page.route(`**/api/cases/${caseId}/withdrawal-review?**`, route => fulfill(route, state.dto("b1b2c3d4-1234-4567-8123-abcdefabcdef"))); await root(page).getByRole("button", { name: "Check withdrawal decision", exact: true }).click(); await expect(root(page)).toContainText("Withdrawal details couldn’t load"); await expect(root(page)).not.toContainText("Withdrawal decision recorded"); expect(state.writes).toHaveLength(1); await expect(root(page).getByRole("button", { name: "Check withdrawal decision", exact: true })).toBeVisible();
});
