const ATTORNEY_PRODUCTION_DEFECTS = Object.freeze([
  Object.freeze({
    id: "PD001_platform_fee_unavailable_noise",
    capabilityId: "A31_product_knowledge",
    prompt: "What is the platform fee?",
    requiredEvidence: ["knowledge"],
    requiredTools: ["search_lpc_knowledge"],
    requiredClaims: ["attorney_platform_fee"],
    forbiddenClaims: ["data_unavailable", "manual_review_sent", "unrelated_billing_action", "unrelated_posting_action"],
    riskLabels: ["financial", "product_policy"],
  }),
  Object.freeze({
    id: "PD002_deadline_phantom_escalation",
    capabilityId: "A03_deadlines",
    prompt: "When is my next deadline?",
    requiredEvidence: ["next_deadline"],
    requiredTools: ["get_next_deadline"],
    requiredClaims: ["next_deadline"],
    forbiddenClaims: ["manual_review_sent", "team_escalation_claim", "unrelated_billing_action"],
    riskLabels: ["lifecycle", "false_action"],
  }),
  Object.freeze({
    id: "PD003_pending_paralegal_generic_fallback",
    capabilityId: "A18_pending_paralegal",
    prompt: "Am I waiting on anything from a paralegal?",
    requiredEvidence: ["pending_paralegal"],
    requiredTools: ["get_pending_paralegal_activity"],
    requiredClaims: ["attributable_paralegal_activity"],
    forbiddenClaims: ["ask_for_case_without_need", "unassigned_task_attribution", "unrelated_billing_action"],
    riskLabels: ["ownership", "workflow_policy"],
  }),
  Object.freeze({
    id: "PD004_completed_count_reported_unavailable",
    capabilityId: "A01_matter_overview",
    prompt: "How many cases have I completed?",
    requiredEvidence: ["case_overview"],
    requiredTools: ["get_my_case_overview"],
    requiredClaims: ["completed_matter_count"],
    forbiddenClaims: ["data_unavailable", "manual_review_sent", "unrelated_posting_action"],
    riskLabels: ["lifecycle"],
  }),
  Object.freeze({
    id: "PD005_both_financial_dimensions_missing",
    capabilityId: "A15_case_financials",
    prompt: "Both.",
    history: Object.freeze([
      Object.freeze({ role: "user", content: "How much was Testing payout for?" }),
      Object.freeze({ role: "assistant", content: "Do you mean the total charge or paralegal net payout?" }),
    ]),
    conversationState: Object.freeze({
      activeEntity: Object.freeze({ type: "case", id: "case-testing-payout", name: "Testing payout", source: "verified_fixture" }),
      lastCapabilityIds: Object.freeze(["A15_case_financials"]),
      lastRequestedDimensions: Object.freeze(["matter_financials"]),
    }),
    requiredEvidence: ["matter_financials"],
    requiredTools: ["get_attorney_case_financials"],
    requiredClaims: ["total_attorney_charge", "net_paralegal_payout"],
    forbiddenClaims: ["unlabeled_amount", "data_unavailable", "manual_review_sent"],
    riskLabels: ["financial", "historical_snapshot"],
  }),
  Object.freeze({
    id: "PD006_payment_method_requirement_contradiction",
    capabilityId: "A11_posting",
    prompt: "Do I have a saved payment method, and do I need one before posting?",
    requiredEvidence: ["billing_method", "workflow_readiness"],
    requiredTools: ["get_billing_snapshot", "get_attorney_workflow_readiness"],
    requiredClaims: ["payment_method_account_state", "payment_method_required_before_posting"],
    forbiddenClaims: ["payment_method_not_required", "knowledge_overrides_policy", "manual_review_sent"],
    riskLabels: ["financial", "workflow_policy"],
  }),
  Object.freeze({
    id: "PD007_general_paralegal_payout_timing_false_limitation",
    capabilityId: "A31_product_knowledge",
    prompt: "When does the paralegal get paid?",
    requiredEvidence: ["workflow_readiness"],
    requiredTools: ["get_attorney_workflow_readiness"],
    requiredClaims: ["paralegal_payout_timing"],
    forbiddenClaims: ["data_unavailable", "ask_for_case_without_need", "manual_review_sent"],
    riskLabels: ["financial", "workflow_policy"],
    planningMode: "semantic_capability",
    evidenceCapability: "deposit_timing",
  }),
  Object.freeze({
    id: "PD008_post_hire_workflow_generic_fallback",
    capabilityId: "A10_hiring",
    prompt: "What happens after I hire a paralegal?",
    requiredEvidence: ["workflow_readiness"],
    requiredTools: ["get_attorney_workflow_readiness"],
    requiredClaims: ["post_hire_workflow"],
    forbiddenClaims: ["data_unavailable", "ask_for_case_without_need", "manual_review_sent"],
    riskLabels: ["lifecycle", "workflow_policy"],
    planningMode: "semantic_capability",
    evidenceCapability: "post_hire_workflow",
  }),
  Object.freeze({
    id: "PD009_general_hiring_raw_evidence_leak",
    capabilityId: "A10_hiring",
    prompt: "How do I hire a paralegal?",
    requiredEvidence: ["workflow_readiness"],
    requiredTools: ["get_attorney_workflow_readiness"],
    requiredClaims: ["hiring_workflow"],
    forbiddenClaims: ["raw_tool_output", "unrelated_platform_fee", "data_unavailable", "manual_review_sent"],
    riskLabels: ["lifecycle", "workflow_policy", "raw_evidence_exposure"],
    planningMode: "semantic_capability",
    evidenceCapability: "hiring",
  }),
]);

function getAttorneyProductionDefects() {
  return ATTORNEY_PRODUCTION_DEFECTS.map((defect) => ({
    ...defect,
    history: Array.isArray(defect.history) ? defect.history.map((entry) => ({ ...entry })) : [],
    conversationState: defect.conversationState ? JSON.parse(JSON.stringify(defect.conversationState)) : {},
    requiredEvidence: [...defect.requiredEvidence],
    requiredTools: [...defect.requiredTools],
    requiredClaims: [...defect.requiredClaims],
    forbiddenClaims: [...defect.forbiddenClaims],
    riskLabels: [...defect.riskLabels],
    planningMode: String(defect.planningMode || "deterministic_evidence_plan"),
    evidenceCapability: String(defect.evidenceCapability || ""),
  }));
}

module.exports = {
  ATTORNEY_PRODUCTION_DEFECTS,
  getAttorneyProductionDefects,
};
