const express = require('express');
const cookieParser = require('cookie-parser');
const jwt = require('jsonwebtoken');
const request = require('supertest');
jest.mock('../utils/email', () => Object.assign(jest.fn(async () => ({ok:true})), {sendAccountDeactivatedEmail:jest.fn(async () => ({ok:true}))}));
const User = require('../models/User');
const AuthSession = require('../models/AuthSession');
const {connect,clearDatabase,closeDatabase} = require('./helpers/db');
const app=express();app.use(cookieParser());app.use(express.json());app.use('/api/account',require('../routes/account'));
let owner,other,cookie;
const token=user=>`token=${jwt.sign({id:String(user._id),role:user.role,status:'approved',av:0},process.env.JWT_SECRET,{expiresIn:'1h'})}`;
const review=(query={})=>request(app).get('/api/account/deactivate-status').query({expectedOwnerId:String(owner._id),...query}).set('Cookie',cookie);
const remove=(value,extra={})=>request(app).delete('/api/account/deactivate').set('Cookie',cookie).send({expectedOwnerId:String(owner._id),expectedClosureRevision:value?.closureRevision,resultProof:value?.resultProof,...extra});
const result=(proof,{credential=cookie}={})=>{const req=request(app).get('/api/account/deactivate-result').set('X-LPC-Closure-Proof',proof||'missing');return credential?req.set('Cookie',credential):req;};
beforeAll(connect);afterAll(closeDatabase);
beforeEach(async()=>{await clearDatabase();const create=label=>User.create({firstName:label,lastName:'Fixture',role:'attorney',email:`${label.toLowerCase()}@closure.invalid`,password:'A synthetic closure test passphrase',status:'approved',state:'CA'});owner=await create('Owner');other=await create('Other');cookie=token(owner);});
afterEach(()=>jest.restoreAllMocks());

test('guarded review gives a private purpose-limited capability and preserves legacy eligibility',async()=>{
 const current=await review();expect(current.status).toBe(200);expect(current.headers['cache-control']).toMatch(/private.*no-store/);expect(current.body).toMatchObject({ownerId:String(owner._id),canDeactivate:true,blockers:[]});expect(current.body.closureRevision).toMatch(/^[a-f0-9]{64}$/);expect(current.body.resultProof).toMatch(/^[A-Za-z0-9_-]+\.[a-f0-9]{64}$/);expect(new Date(current.body.proofExpiresAt).getTime()).toBeGreaterThan(Date.now());expect(JSON.stringify(current.body)).not.toContain(owner.email);expect(JSON.stringify(current.body)).not.toContain(cookie.slice(6));const legacy=await request(app).get('/api/account/deactivate-status').set('Cookie',cookie);expect(legacy.body).toEqual({canDeactivate:true,blockers:[]});
});
test('wrong owner cannot review or deactivate the signed-in replacement',async()=>{
 expect((await review({expectedOwnerId:String(other._id)})).status).toBe(403);const changed=await remove(null,{expectedOwnerId:String(other._id),expectedClosureRevision:'a'.repeat(64),resultProof:'invalid'});expect(changed.status).toBe(403);expect(changed.body.code).toBe('ACCOUNT_CHANGED');expect((await User.findById(owner._id)).disabled).not.toBe(true);
});
test.each(['expectedOwnerId=bad','expectedOwnerId[]=bad','expectedOwnerId.foo=bad'])('malformed owner review rejects %s',async query=>{const res=await request(app).get(`/api/account/deactivate-status?${query}`).set('Cookie',cookie);expect(res.status).toBe(400);expect(res.body.code).toBe('ACCOUNT_GUARD_INVALID');});
test('guarded deactivation requires an exact reviewed revision and proof',async()=>{const res=await remove(null);expect(res.status).toBe(400);expect((await User.findById(owner._id)).disabled).not.toBe(true);});
test.each(['expectedOwnerId.foo','expectedClosureRevision.foo','resultProof.foo'])('malformed guard field cannot fall through to legacy deactivation: %s',async key=>{const res=await request(app).delete('/api/account/deactivate').set('Cookie',cookie).send({[key]:'value'});expect(res.status).toBe(400);expect((await User.findById(owner._id)).disabled).not.toBe(true);});
test('proof read reports active status with no private identity or mutation',async()=>{const current=await review();const status=await result(current.body.resultProof);expect(status.status).toBe(200);expect(status.body).toEqual({state:'active'});expect(status.headers['cache-control']).toMatch(/private.*no-store/);expect((await User.findById(owner._id)).disabled).not.toBe(true);});
test('proof read supports absent credentials but refuses a different present account',async()=>{const current=await review();expect((await result(current.body.resultProof,{credential:null})).body).toEqual({state:'active'});const replacement=await result(current.body.resultProof,{credential:token(other)});expect(replacement.status).toBe(403);expect(replacement.body.code).toBe('ACCOUNT_CHANGED');expect(replacement.body.state).toBeUndefined();});
test('guarded completion revokes access, retains the account and supports readback without clearing a future cookie',async()=>{await AuthSession.create({userId:owner._id,sessionId:'closure-other-device',expiresAt:new Date(Date.now()+60000)});const current=await review();const res=await remove(current.body);expect(res.status).toBe(200);expect(res.body).toEqual({ok:true,deactivated:true});expect(res.headers['set-cookie']).toBeUndefined();const saved=await User.findById(owner._id).select('+authVersion');expect(saved).toMatchObject({disabled:true,deleted:true,status:'denied',authVersion:1});expect(await AuthSession.countDocuments({userId:owner._id,revokedAt:null})).toBe(0);expect((await result(current.body.resultProof)).body).toEqual({state:'deactivated'});expect((await result(current.body.resultProof,{credential:null})).body).toEqual({state:'deactivated'});expect((await review()).status).toBe(403);});
test('invalid result proof is rejected before account lookup or a success projection',async()=>{const find=jest.spyOn(User,'findById');const res=await result('invalid');expect(res.status).toBe(400);expect(res.body.code).toBe('ACCOUNT_CLOSURE_PROOF_INVALID');expect(res.body.state).toBeUndefined();expect(find).not.toHaveBeenCalled();});
test('a tampered result capability cannot read account state',async()=>{const current=await review();const proof=String(current.body.resultProof||'');const res=await result(proof+'x');expect(res.status).toBe(400);expect(res.body.state).toBeUndefined();});
test('proof bound to another review or credential cannot authorize deactivation',async()=>{const current=await review();const wrongRevision=await remove(current.body,{expectedClosureRevision:'b'.repeat(64)});expect(wrongRevision.status).toBe(409);const replaced=await request(app).delete('/api/account/deactivate').set('Cookie',token(other)).send({expectedOwnerId:String(other._id),expectedClosureRevision:current.body.closureRevision,resultProof:current.body.resultProof});expect(replaced.status).toBe(403);expect((await User.findById(other._id)).disabled).not.toBe(true);});

test('expired signed result proof is refused without an account lookup',async()=>{const guard=require('../utils/accountClosureGuard');const value=guard.issue({user:{id:String(owner._id),role:'attorney'},auth:{token:cookie.slice(6)}},'a'.repeat(64),Date.now()-guard.PROOF_LIFETIME_MS-1);const find=jest.spyOn(User,'findById');const res=await result(value.resultProof);expect(res.status).toBe(410);expect(res.body.code).toBe('ACCOUNT_CLOSURE_PROOF_EXPIRED');expect(find).not.toHaveBeenCalled();});
test.each(['purpose','audience','role','ownerId','issuedAt'])('signed proof with malformed %s is not a valid result capability',async field=>{const current=await review();const payload=JSON.parse(Buffer.from(current.body.resultProof.split('.')[0],'base64url').toString());payload[field]=field==='issuedAt'?Date.now()+60000:'invalid';const encoded=Buffer.from(JSON.stringify(payload)).toString('base64url');const signature=require('crypto').createHmac('sha256',Buffer.from(process.env.DATA_ENCRYPTION_KEY,'hex')).update(`lpc:account-closure:result:v1\0${encoded}`).digest('hex');const find=jest.spyOn(User,'findById');const res=await result(`${encoded}.${signature}`);expect(res.status).toBe(400);expect(find).not.toHaveBeenCalled();});
test('result capability is never accepted through URL query parameters',async()=>{const current=await review();const res=await request(app).get('/api/account/deactivate-result').query({proof:current.body.resultProof});expect(res.status).toBe(400);expect(res.body.state).toBeUndefined();});
test('missing or inconsistent account state stays unavailable without claiming deactivation',async()=>{const current=await review();await User.collection.updateOne({_id:owner._id},{$set:{disabled:true,deleted:false}});expect((await result(current.body.resultProof,{credential:null})).body).toEqual({state:'unavailable'});await User.collection.deleteOne({_id:owner._id});expect((await result(current.body.resultProof,{credential:null})).body).toEqual({state:'unavailable'});});
test('an existing but unapproved account is unavailable through result check',async()=>{const current=await review();await User.collection.updateOne({_id:owner._id},{$set:{status:'pending'}});expect((await result(current.body.resultProof,{credential:null})).body).toEqual({state:'unavailable'});});
test('guarded compatibility alias uses the same deliberate proof and does not clear cookies',async()=>{const current=await review();const response=await request(app).delete('/api/account/delete').set('Cookie',cookie).send({expectedOwnerId:String(owner._id),expectedClosureRevision:current.body.closureRevision,resultProof:current.body.resultProof});expect(response.status).toBe(200);expect(response.headers['set-cookie']).toBeUndefined();expect((await result(current.body.resultProof)).body).toEqual({state:'deactivated'});});
test('a new credential for the same owner cannot reuse the initiating credential capability',async()=>{const current=await review();const replacement=`token=${jwt.sign({id:String(owner._id),role:owner.role,status:'approved',av:0,sid:'a-new-synthetic-session'},process.env.JWT_SECRET,{expiresIn:'1h'})}`;const find=jest.spyOn(User,'findById');const response=await result(current.body.resultProof,{credential:replacement});expect(response.status).toBe(403);expect(response.body.code).toBe('ACCOUNT_CHANGED');expect(find).not.toHaveBeenCalled();});
