const {Types}=require('mongoose');const Case=require('../models/Case'),Job=require('../models/Job'),Application=require('../models/Application');const {connect,clearDatabase,closeDatabase}=require('./helpers/db');const service=require('../services/applicationMirrorRepair');
beforeAll(connect);afterAll(closeDatabase);beforeEach(clearDatabase);
async function fixture(status){const ownerId=new Types.ObjectId(),personId=new Types.ObjectId(),caseId=new Types.ObjectId(),jobId=new Types.ObjectId(),applicationId=new Types.ObjectId();
 const application={_id:applicationId,jobId,paralegalId:personId,status,coverLetter:'Organize the supplied exhibits.',resumeURL:'',linkedInURL:'',profileSnapshot:{location:'California'},requirementConfirmations:[],createdAt:new Date('2026-02-16T15:49:50.548Z'),statusHistory:[{to:status,at:new Date('2026-02-16T15:49:50.548Z')}]};
 await Case.collection.insertOne({_id:caseId,jobId,attorney:ownerId,attorneyId:ownerId,status:status==='accepted'?'in progress':'open',...(status==='accepted'?{paralegal:personId,paralegalId:personId}:{}),applicants:[]});
 await Job.collection.insertOne({_id:jobId,caseId,attorneyId:ownerId,applicantsCount:0});await Application.collection.insertOne(application);return {input:{applicationId:String(applicationId),caseId:String(caseId),ownerId:String(ownerId)},application,caseId,jobId,personId};}
test.each(['accepted','submitted','viewed','shortlisted','rejected'])('%s canonical record repairs exactly one mirror and repeated repair is a no-op',async status=>{const f=await fixture(status),before=await service.inspect(f.input);const result=await service.repair(f.input,before.revision);expect(result.changed).toBe(true);const c=await Case.collection.findOne({_id:f.caseId}),a=await Application.collection.findOne({_id:f.application._id});expect(c.applicants).toHaveLength(1);expect(c.applicants[0]).toMatchObject({paralegalId:f.personId,note:f.application.coverLetter,status:status==='submitted'?'pending':status,appliedAt:f.application.createdAt});expect(a.status).toBe(status);expect(a.statusHistory).toEqual(f.application.statusHistory);expect(a.syncStatus).toBe('synced');expect(await Application.countDocuments({jobId:f.jobId})).toBe(1);const fresh=await service.inspect(f.input);expect((await service.repair(f.input,fresh.revision)).changed).toBe(false);expect((await Case.collection.findOne({_id:f.caseId})).applicants).toHaveLength(1);expect((await Job.collection.findOne({_id:f.jobId})).applicantsCount).toBe(['submitted','viewed','shortlisted'].includes(status)?1:0);});
test('withdrawn canonical record removes its stale mirror and does not recreate it',async()=>{const f=await fixture('withdrawn');await Case.collection.updateOne({_id:f.caseId},{$push:{applicants:{paralegalId:f.personId,status:'pending',note:'Old submission'}}});const before=await service.inspect(f.input);await service.repair(f.input,before.revision);expect((await Case.collection.findOne({_id:f.caseId})).applicants).toEqual([]);expect((await Application.collection.findOne({_id:f.application._id})).status).toBe('withdrawn');expect((await service.inspect(f.input)).needed).toBe(false);});
test('mismatched reciprocal Job/Matter link is rejected without a write',async()=>{const f=await fixture('accepted');await Job.collection.updateOne({_id:f.jobId},{$set:{caseId:new Types.ObjectId()}});await expect(service.inspect(f.input)).rejects.toMatchObject({code:'APPLICATION_REPAIR_UNSAFE'});expect((await Case.collection.findOne({_id:f.caseId})).applicants).toEqual([]);});
test('ambiguous embedded duplicates are rejected rather than silently merged',async()=>{const f=await fixture('submitted');await Case.collection.updateOne({_id:f.caseId},{$set:{applicants:[{paralegalId:f.personId,status:'pending'},{paralegalId:f.personId,status:'pending'}]}});await expect(service.inspect(f.input)).rejects.toMatchObject({code:'APPLICATION_REPAIR_UNSAFE'});});
test('a stale review cannot overwrite a newer canonical status',async()=>{const f=await fixture('submitted'),before=await service.inspect(f.input);await Application.collection.updateOne({_id:f.application._id},{$set:{status:'withdrawn'}});await expect(service.repair(f.input,before.revision)).rejects.toMatchObject({code:'APPLICATION_REPAIR_UNSAFE'});expect((await Case.collection.findOne({_id:f.caseId})).applicants).toEqual([]);});
