const { execFileSync } = require("child_process"), { pathToFileURL } = require("url"), path = require("path");
const url = name => pathToFileURL(path.resolve(__dirname, `../../frontend/assets/scripts/attorney-v2/${name}.mjs`)).href;
const check = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict'; import * as m from ${JSON.stringify(url("files-model"))}; import {createApiClient} from ${JSON.stringify(url("api-client"))}; import {createPrivateState} from ${JSON.stringify(url("private-state"))}; const ownerId='a'.repeat(24),caseId='b'.repeat(24),fileId='c'.repeat(24); const file={id:fileId,name:'Agreement.pdf',revision:'d'.repeat(64),reviewRevision:'e'.repeat(64),mimeType:'application/pdf',size:40,version:1,uploadedAt:null,securityStatus:'clean',status:'pending_review',uploadedByRole:'paralegal',notes:'',requestedAt:null,approvedAt:null,replacedAt:null,revisionOf:null,canReview:true};const value={ownerId,caseId,caseTitle:'Matter',access:'available',legacyAttachments:false,files:[file],nextCursor:null,canUpload:true,selection:'none',selectedFile:null}; ${source}`], { stdio: "pipe" }); };
test("file and exact-selection metadata fail closed for contradictory or malformed actions", () => check(`
assert.equal(m.readFiles(value,caseId,ownerId),value);for(const patch of [{canReview:true,securityStatus:'blocked'},{reviewRevision:'bad'},{requestedAt:'bad'},{revisionOf:{id:'bad'}},{uploadedByRole:'attorney',canReview:true}])assert.throws(()=>m.readFiles({...value,files:[{...file,...patch}]},caseId,ownerId));assert.throws(()=>m.readFiles({...value,selection:'found'},caseId,ownerId));assert.throws(()=>m.readFiles({...value,selectedFile:file},caseId,ownerId));assert.equal(m.previewType(file),'pdf');assert.equal(m.previewType({...file,mimeType:'text/html'}),null);
`));
test("document decisions bind the displayed revision, account and selected file without automatic retry", () => check(`
const calls=[];const api=createApiClient({fetchImpl:async(path,options)=>{calls.push({path,...options});if(path==='/api/auth/me')return new Response(JSON.stringify({user:{id:ownerId,role:'attorney',status:'approved'}}));if(path==='/api/csrf')return new Response(JSON.stringify({csrfToken:'synthetic'}));throw new Error('lost response');}});const selection={reviewedRevision:file.reviewRevision,status:'attorney_revision',notes:'Keep exhibit B.'};await assert.rejects(api.updateWorkspaceFile(caseId,fileId,selection,{ownerId}));const writes=calls.filter(call=>call.method==='POST');assert.equal(writes.length,1);assert.equal(writes[0].path,'/api/cases/'+caseId+'/files/'+fileId+'/review');assert.deepEqual(JSON.parse(writes[0].body),{...selection,expectedOwnerId:ownerId});
`));
test("file selections validate IDs and private review state is cleared by account protection", () => check(`
const api=createApiClient({fetchImpl:async()=>new Response('{}')});assert.throws(()=>api.readWorkspaceFiles(caseId,{ownerId,fileId:'bad'}));const state=createPrivateState();state.fileReviews.set(caseId,{drafts:{[fileId]:'Private instructions'},pending:{id:fileId,status:'approved'}});assert.equal(state.hasUnsaved(),true);state.clear();assert.equal(state.hasUnsaved(),false);assert.equal(state.fileReviews.size,0);
`));
