const { execFileSync } = require("node:child_process"), { pathToFileURL } = require("node:url"), path = require("node:path");
const url = name => pathToFileURL(path.resolve(__dirname, `../../frontend/assets/scripts/attorney-v2/${name}.mjs`)).href;
const check = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict';import {createApiClient} from ${JSON.stringify(url("api-client"))};import {readPaymentRecords,paymentAmount,billingUrl} from ${JSON.stringify(url("payment-records-model"))};const ownerId='a'.repeat(24),caseId='b'.repeat(24);${source}`], { stdio: "pipe" }); };
test("payment list rejects fabricated cents, unsupported currencies and inconsistent selection", () => check(`
const item={id:caseId,title:'Original Matter',matterStatus:'completed',archived:false,paralegalName:'Priya Ng',currency:'USD',matterAmount:60001,funding:'recorded',release:'not_recorded',createdAt:null,updatedAt:null,fundingVerifiedAt:null,releasedAt:null,withdrawal:null};const value={ownerId,view:'all',q:'',total:1,items:[item],nextCursor:null,selected:null,selection:'none'};assert.equal(readPaymentRecords(value,ownerId).items[0].matterAmount,60001);assert.match(paymentAmount(60001,'USD'),/600.01/);assert.equal(paymentAmount(null,'USD'),'Amount needs review');for(const patch of [{matterAmount:1.5},{matterAmount:'60001'},{currency:'JPY'},{release:'paid_in_full'},{releasedAt:'invalid'}])assert.throws(()=>readPaymentRecords({...value,items:[{...item,...patch}]},ownerId));assert.throws(()=>readPaymentRecords({...value,selection:'found'},ownerId));assert.throws(()=>readPaymentRecords({...value,items:[item,item]},ownerId));
`));
test("billing accepts only the current owner's exact trusted provider destination", () => check(`
assert.equal(billingUrl({ownerId,url:'https://billing.stripe.com/p/session/test_value'},ownerId),'https://billing.stripe.com/p/session/test_value');for(const url of ['https://outside.test/p/session/x','https://billing.stripe.com.evil.test/p/session/x','https://billing.stripe.com/p/session/x#token','https://user@billing.stripe.com/p/session/x'])assert.throws(()=>billingUrl({ownerId,url},ownerId));assert.throws(()=>billingUrl({ownerId:caseId,url:'https://billing.stripe.com/p/session/x'},ownerId));
`));
test("list and portal requests preserve the current owner, exact filters and same retry identity", () => check(`
const requests=[];const api=createApiClient({fetchImpl:async(path,options={})=>{requests.push({path,options});if(path==='/api/auth/me')return new Response(JSON.stringify({user:{id:ownerId,role:'attorney',status:'approved'}}));if(path==='/api/csrf')return new Response(JSON.stringify({csrfToken:'synthetic-csrf'}));return new Response('{}');}});await api.readPaymentRecords({ownerId,view:'released',q:'Lease [original]',caseId,cursor:caseId});const query=new URL(requests.find(r=>r.path.includes('/attorney-records')).path,'https://local.test').searchParams;assert.equal(query.get('q'),'Lease [original]');assert.equal(query.get('expectedOwnerId'),ownerId);assert.equal(query.get('caseId'),caseId);const requestId='c1111111-1111-4111-8111-111111111111';await api.openAttorneyBilling(requestId,{ownerId});const portal=requests.find(r=>r.path.includes('/portal/attorney'));assert.equal(portal.options.method,'POST');assert.deepEqual(JSON.parse(portal.options.body),{requestId,expectedOwnerId:ownerId});
`));
