const { execFileSync } = require("child_process"), { pathToFileURL } = require("url"), path = require("path");
const url = name => pathToFileURL(path.resolve(__dirname, `../../frontend/assets/scripts/attorney-v2/${name}.mjs`)).href;
const check = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict'; import * as m from ${JSON.stringify(url("upload-model"))}; import {createApiClient} from ${JSON.stringify(url("api-client"))}; import {createPrivateState} from ${JSON.stringify(url("private-state"))}; const ownerId='a'.repeat(24),caseId='b'.repeat(24),fileId='c'.repeat(24); const file={id:fileId,name:'Agreement.pdf',revision:'d'.repeat(64),reviewRevision:'e'.repeat(64),mimeType:'application/pdf',size:40,version:1,uploadedAt:null,securityStatus:'clean',status:'pending_review',uploadedByRole:'paralegal',notes:'',requestedAt:null,approvedAt:null,replacedAt:null,revisionOf:null,canReview:true};const value={ownerId,caseId,caseTitle:'Matter',access:'available',legacyAttachments:false,files:[file],nextCursor:null,canUpload:true,selection:'none',selectedFile:null}; ${source}`], { stdio: "pipe" }); };
test("upload selection and outcome validation preserve uncertainty",()=>check(`
assert.equal(m.selectionError({name:'Lease.pdf',size:20*1024*1024}),'');assert.match(m.selectionError({name:'Lease.pdf',size:20*1024*1024+1}),/20 MB/);assert.match(m.selectionError({name:'Lease.html',size:10}),/supported/);assert.match(m.selectionError({name:'Empty.txt',size:0}),/byte/);assert.throws(()=>m.readUpload({status:'recorded',file:null,retryAllowed:true}));assert.throws(()=>m.readUpload({status:'failed',file,retryAllowed:true}));assert.equal(m.readUploadReview({caseId,ownerId,canUpload:true,revision:'a'.repeat(64),upload:null},caseId,ownerId).canUpload,true);assert.throws(()=>m.readUploadReview({caseId,ownerId:'wrong',canUpload:true,revision:'a'.repeat(64),upload:null},caseId,ownerId));
`));
test("multipart writes preserve selected bytes and never replay a dropped request",()=>check(`
const calls=[];const api=createApiClient({fetchImpl:async(path,options)=>{calls.push({path,...options});if(path==='/api/auth/me')return new Response(JSON.stringify({user:{id:ownerId,role:'attorney',status:'approved'}}));if(path==='/api/csrf')return new Response(JSON.stringify({csrfToken:'synthetic'}));throw new Error('lost response');}});const upload=new File(['PRIVATE_FILE_CONTENT'],'Lease.txt',{type:'text/plain'});await assert.rejects(api.uploadWorkspaceFile(caseId,{file:upload,requestId:'unique-synthetic-request',reviewedRevision:'a'.repeat(64)},{ownerId}));const writes=calls.filter(call=>call.method==='POST');assert.equal(writes.length,1);assert.equal(writes[0].body.get('requestId'),'unique-synthetic-request');assert.equal(writes[0].body.get('expectedOwnerId'),ownerId);assert.equal(await writes[0].body.get('file').text(),'PRIVATE_FILE_CONTENT');assert.equal(writes[0].headers['Content-Type'],undefined);const state=createPrivateState();state.fileReviews.set(caseId,{upload:{file:upload,pending:true}});assert.equal(state.hasUnsaved(),true);state.clear();assert.equal(state.fileReviews.size,0);assert.equal(state.hasUnsaved(),false);
`));
