const { execFileSync } = require("child_process"), { pathToFileURL } = require("url"), path = require("path");
const url = name => pathToFileURL(path.resolve(__dirname, `../../frontend/assets/scripts/attorney-v2/${name}.mjs`)).href;
const check = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict'; import * as m from ${JSON.stringify(url("upload-model"))}; import {createApiClient} from ${JSON.stringify(url("api-client"))}; import {createPrivateState} from ${JSON.stringify(url("private-state"))}; const ownerId='a'.repeat(24),caseId='b'.repeat(24),fileId='c'.repeat(24); const file={id:fileId,name:'Agreement.pdf',revision:'d'.repeat(64),reviewRevision:'e'.repeat(64),mimeType:'application/pdf',size:40,version:1,uploadedAt:null,securityStatus:'clean',status:'pending_review',uploadedByRole:'paralegal',notes:'',requestedAt:null,approvedAt:null,replacedAt:null,revisionOf:null,canReview:true};const value={ownerId,caseId,caseTitle:'Matter',access:'available',legacyAttachments:false,files:[file],nextCursor:null,canUpload:true,selection:'none',selectedFile:null}; ${source}`], { stdio: "pipe" }); };
test("replacement review cannot substitute another target or claim current bytes after a later replacement",()=>check(`
const review={caseId,ownerId,revision:'a'.repeat(64),canUpload:true,target:file,upload:null};assert.equal(m.readReplacementReview(review,caseId,ownerId,fileId),review);for(const target of [null,{...file,id:'f'.repeat(24)},{}])assert.throws(()=>m.readReplacementReview({...review,target},caseId,ownerId,fileId));assert.throws(()=>m.readUpload({status:'recorded',retryAllowed:false}));assert.throws(()=>m.readUpload({status:'recorded',file:null,retryAllowed:false,changedSinceUpload:true}));assert.equal(m.readUpload({status:'recorded',file,retryAllowed:false,changedSinceUpload:true}).changedSinceUpload,true);
`));
test("replacement sends the displayed file revision, exact target and retained bytes only once",()=>check(`
const calls=[];const api=createApiClient({fetchImpl:async(path,options)=>{calls.push({path,...options});if(path==='/api/auth/me')return new Response(JSON.stringify({user:{id:ownerId,role:'attorney',status:'approved'}}));if(path==='/api/csrf')return new Response(JSON.stringify({csrfToken:'synthetic'}));throw new Error('lost response');}});const selected=new File(['PRIVATE_REPLACEMENT'],'Lease revised.txt',{type:'text/plain'});await assert.rejects(api.replaceWorkspaceFile(caseId,fileId,{file:selected,requestId:'synthetic-replacement-id',reviewedRevision:'a'.repeat(64),reviewedFileRevision:file.reviewRevision},{ownerId}));const writes=calls.filter(call=>call.method==='POST');assert.equal(writes.length,1);assert.ok(writes[0].path.endsWith('/reviewed-replacement/'+fileId));assert.equal(writes[0].body.get('reviewedFileRevision'),file.reviewRevision);assert.equal(writes[0].body.get('expectedOwnerId'),ownerId);assert.equal(await writes[0].body.get('file').text(),'PRIVATE_REPLACEMENT');const state=createPrivateState();state.fileReviews.set(caseId,{replacements:{[fileId]:{file:selected,pending:true}}});assert.equal(state.hasUnsaved(),true);state.clear();assert.equal(state.hasUnsaved(),false);
`));
