const { execFileSync } = require("child_process"), path = require("path");
const run = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict';import {readWithdrawal,payoutInput,withdrawalAmounts} from './frontend/assets/scripts/attorney-v2/withdrawal-model.mjs';import {createPrivateState} from './frontend/assets/scripts/attorney-v2/private-state.mjs';import {createApiClient} from './frontend/assets/scripts/attorney-v2/api-client.mjs';${source}`], { cwd: path.resolve(__dirname, "../.."), encoding: "utf8", timeout: 10000 }); };
const fixture = `const owner='a'.repeat(24),caseId='b'.repeat(24),revision='c'.repeat(64),requestId='a1b2c3d4-1234-4567-8123-abcdefabcdef',value={ownerId:owner,caseId,caseTitle:'River Street lease',revision,applicable:true,state:'decision_required',blockers:[],paralegalId:'d'.repeat(24),paralegalName:'Priya Ng',withdrawnAt:'2026-09-01T00:00:00Z',originalCents:100001,remainingCents:100001,balanceVerified:true,currency:'USD',feePct:18,maximumPayoutCents:70001,work:{complete:1,total:2},canDecide:true,canPay:true,canRelist:false,fundingReady:true,payoutSetupReady:true,reviewDeadline:null,adminDeadline:null,decision:null,relistedAt:null,operation:null,privateSource:'PRIVATE'};`;
test("withdrawal presentation validates actionable facts and strips unrendered data", () => run(fixture + `
  const read=input=>readWithdrawal(input,caseId,owner);assert.equal(JSON.stringify(read(value)).includes('PRIVATE'),false);
  for(const patch of [{ownerId:'f'.repeat(24)},{caseId:'e'.repeat(24)},{state:'approved'},{remainingCents:100002},{balanceVerified:false},{currency:'JPY'},{feePct:100},{maximumPayoutCents:1.2},{canDecide:false},{payoutSetupReady:false},{blockers:['invented']},{work:{complete:3,total:2}},{reviewDeadline:'2026-09-02T00:00:00Z'},{decision:{type:'admin',amountCents:20000,netCents:30000,payoutState:'recorded',at:null}}])assert.throws(()=>read({...value,...patch}));
  assert.equal(read({...value,state:'review_window',canDecide:false,canPay:false,reviewDeadline:'2026-09-02T00:00:00Z'}).state,'review_window');
`));
test("payout entry preserves exact cents, zero decisions, cap and fee arithmetic without accepting rounded or negative input", () => run(fixture + `
  assert.equal(payoutInput('200.01'),20001);assert.equal(payoutInput('0'),0);assert.equal(payoutInput('0.09'),9);
  for(const input of ['-1','1e3','1.001','1,000','$10','','Infinity','0x10'])assert.equal(payoutInput(input),null);
  assert.deepEqual(withdrawalAmounts(value,20001),{grossCents:20001,feeCents:3600,netCents:16401,remainingCents:80000});assert.equal(withdrawalAmounts(value,70002),null);assert.equal(withdrawalAmounts({...value,canPay:false},100),null);assert.equal(withdrawalAmounts({...value,canPay:false},0).netCents,0);
`));
test("private withdrawal drafts and uncertain requests survive route changes but clear on account loss", () => run(fixture + `
  const state=createPrivateState();assert.equal(state.hasUnsaved(),false);state.withdrawals.set(caseId,{amountText:'200.01',pending:{requestId}});assert.equal(state.hasUnsaved(),true);assert.equal(state.withdrawals.get(caseId).pending.requestId,requestId);state.clear();assert.equal(state.withdrawals.size,0);assert.equal(state.hasUnsaved(),false);
`));
test("withdrawal API sends only the exact reviewed request once and discards a result after account change", () => run(fixture + `
  const body={requestId,reviewedRevision:revision,action:'partial',amountCents:20001};
  for(const changed of [false,true]){const calls=[];let identities=0;const api=createApiClient({fetchImpl:async(url,opts)=>{calls.push({url,...opts});return {ok:true,status:200,json:async()=>url==='/api/auth/me'?{user:{id:++identities>1&&changed?'f'.repeat(24):owner,role:'attorney',status:'approved'}}:url==='/api/csrf'?{csrfToken:'synthetic'}:value};}});const response=api.writeWithdrawal(caseId,body,{ownerId:owner});if(changed)await assert.rejects(response,error=>error.kind==='authentication');else assert.equal((await response).caseId,caseId);const writes=calls.filter(call=>call.method==='POST');assert.equal(writes.length,1);assert.equal(writes[0].url,'/api/cases/'+caseId+'/withdrawal-decision');assert.deepEqual(JSON.parse(writes[0].body),{...body,expectedOwnerId:owner});assert.equal(writes[0].headers['X-CSRF-Token'],'synthetic');}
`));
