const { execFileSync } = require("child_process"), { pathToFileURL } = require("url"), path = require("path");
const url = name => pathToFileURL(path.resolve(__dirname, `../../frontend/assets/scripts/attorney-v2/${name}.mjs`)).href;
const check = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict'; import * as m from ${JSON.stringify(url("file-removal-model"))}; import {createApiClient} from ${JSON.stringify(url("api-client"))}; import {createPrivateState} from ${JSON.stringify(url("private-state"))}; const ownerId='a'.repeat(24),caseId='b'.repeat(24),fileId='c'.repeat(24),revision='d'.repeat(64); const file={id:fileId,name:'Lease.txt',version:1,reviewRevision:'e'.repeat(64)};const value={ownerId,caseId,file,revision,canRemove:true,removal:null};const removed={status:'removed',fileId,removedAt:'2026-09-08T12:00:00.000Z',cleanup:'pending',exactRequest:true}; ${source}`], { stdio: "pipe" }); };
test("removal review validates its exact account, document, revision and explicit outcome", () => check(`
assert.deepEqual(m.readRemovalReview({...value,privateData:'hidden',file:{...file,storageKey:'hidden'}},caseId,ownerId,fileId),value);for(const patch of [{ownerId:'other'},{file:{...file,id:'other'}},{revision:'bad'},{canRemove:'yes'},{file:null},{removal:removed}])assert.throws(()=>m.readRemovalReview({...value,...patch},caseId,ownerId,fileId));assert.deepEqual(m.readRemovalReview({...value,file:null,revision:null,canRemove:false,removal:removed},caseId,ownerId,fileId).removal,removed);assert.throws(()=>m.readRemoval({...removed,exactRequest:'yes'},fileId));assert.match(m.removalNotice(removed),/cleanup is pending/);assert.match(m.removalNotice({...removed,cleanup:'retained'}),/still referenced/);
`));
test("dropped removal requests are sent once with the owner, UUID and reviewed revision", () => check(`
const calls=[];const api=createApiClient({fetchImpl:async(path,options)=>{calls.push({path,...options});if(path==='/api/auth/me')return new Response(JSON.stringify({user:{id:ownerId,role:'attorney',status:'approved'}}));if(path==='/api/csrf')return new Response(JSON.stringify({csrfToken:'synthetic'}));throw new Error('lost response');}});const requestId=crypto.randomUUID();await assert.rejects(api.removeWorkspaceFile(caseId,fileId,{requestId,reviewedRevision:revision},{ownerId}));const writes=calls.filter(call=>call.method==='POST');assert.equal(writes.length,1);assert.deepEqual(JSON.parse(writes[0].body),{requestId,reviewedRevision:revision,expectedOwnerId:ownerId});const state=createPrivateState();state.fileReviews.set(caseId,{removal:{target:file,pending:{requestId,reviewedRevision:revision}}});assert.equal(state.hasUnsaved(),true);state.fileReviews.get(caseId).removal.pending=null;state.fileReviews.get(caseId).removal.outcome=removed;assert.equal(state.hasUnsaved(),false);state.clear();assert.equal(state.hasUnsaved(),false);
`));
