const { execFileSync } = require("node:child_process"), { pathToFileURL } = require("node:url"), path = require("node:path");
const url = name => pathToFileURL(path.resolve(__dirname, `../../frontend/assets/scripts/attorney-v2/${name}.mjs`)).href;
const check = source => void execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict';import {createApiClient} from ${JSON.stringify(url("api-client"))};import {readDisputes,disputeNotice,disputeAmount,disputeLink} from ${JSON.stringify(url("disputes-model"))};import {createPrivateState} from ${JSON.stringify(url("private-state"))};const ownerId='a'.repeat(24),caseId='b'.repeat(24),person={id:ownerId,name:'Morgan Lee'},record={id:'earlier-dispute:1',status:'resolved',message:'Exhibit review',raisedBy:person,createdAt:null,updatedAt:null,requestedAmount:null,commentCount:1},selected={...record,revision:'c'.repeat(64),canComment:true,comments:[{id:'d'.repeat(24),by:person,text:'Reviewed exhibit B',createdAt:null}],nextCommentCursor:null,selectedComment:null,commentSelection:'none',decision:null},value={ownerId,caseId,caseTitle:'Lease review',revision:'d'.repeat(64),reason:'ready',canOpen:true,total:1,items:[record],nextCursor:null,selection:'automatic',selected,currency:'USD',operation:null};${source}`], { stdio: "pipe" });
test("dispute review validates permission, page bounds and exact earlier references", () => check(`
assert.equal(readDisputes(value,caseId,ownerId).selected.id,'earlier-dispute:1');assert.equal(disputeNotice('ready'),'');assert.match(disputeAmount(82001,'USD'),/820.01/);assert.match(disputeLink(caseId,record.id,'d'.repeat(24)),/disputeId=earlier-dispute%3A1&commentId=/);for(const patch of [{ownerId:caseId},{canOpen:false},{total:0},{items:Array(26).fill(record),total:26},{nextCursor:'../bad'},{revision:'bad'},{selected:{...selected,commentCount:0}},{selected:{...selected,id:null}},{selected:{...selected,decision:{action:'paid',grossCents:100,payoutCents:100,refundCents:0,at:null}}},{operation:{status:'sent',changedSinceSave:false}}])assert.throws(()=>readDisputes({...value,...patch},caseId,ownerId));assert.equal(readDisputes({...value,currency:'ZZZ'},caseId,ownerId).currency,null);assert.equal(readDisputes({...value,currency:'JPY'},caseId,ownerId).currency,null);
`));
test("the dispute client keeps only public records, including nested people and saved outcomes", () => check(`
const v=readDisputes({...value,adminNotes:'PRIVATE',items:[{...record,adminNotes:'PRIVATE',raisedBy:{...person,email:'PRIVATE'}}],selected:{...selected,adminNotes:'PRIVATE',raisedBy:{...person,email:'PRIVATE'},comments:[{...selected.comments[0],adminNotes:'PRIVATE',by:{...person,email:'PRIVATE'}}]},operation:{status:'recorded',action:'comment',disputeId:record.id,commentId:'d'.repeat(24),changedSinceSave:false,privateKey:'PRIVATE'}},caseId,ownerId);assert.equal(JSON.stringify(v).includes('PRIVATE'),false);assert.equal(v.selected.createdAt,null);assert.equal(v.operation.action,'comment');
`));
test("dispute reads keep exact paging and links; writes bind the current account without resubmission", () => check(`
const calls=[];const api=createApiClient({fetchImpl:async(path,options={})=>{calls.push({path,options});if(path==='/api/auth/me')return new Response(JSON.stringify({user:{id:ownerId,role:'attorney',status:'approved'}}));if(path==='/api/csrf')return new Response(JSON.stringify({csrfToken:'synthetic'}));return new Response('{}');}});const requestId='a1111111-1111-4111-8111-111111111111';await api.readDisputes(caseId,{ownerId,requestId,disputeId:record.id,commentId:'d'.repeat(24),cursor:'page_25',commentCursor:'comments_25'});const read=calls.find(call=>call.path.includes('/attorney-review'));assert.deepEqual(Object.fromEntries(new URL(read.path,'https://local.test').searchParams),{expectedOwnerId:ownerId,cursor:'page_25',disputeId:record.id,commentCursor:'comments_25',commentId:'d'.repeat(24),requestId});const input={requestId,action:'comment',text:'Reviewed exhibit B',reviewedRevision:value.revision,disputeId:record.id,reviewedDisputeRevision:selected.revision};await api.recordDispute(caseId,input,{ownerId});const writes=calls.filter(call=>call.options.method==='POST');assert.equal(writes.length,1);assert.deepEqual(JSON.parse(writes[0].options.body),{...input,expectedOwnerId:ownerId});
`));
test("dispute drafts and unconfirmed requests remain private to the tab and are cleared with the account", () => check(`
const state=createPrivateState();state.disputes.set(caseId,{opening:'Private disagreement',comments:{[record.id]:'Private reply'},pending:{requestId:'synthetic'}});assert.equal(state.hasUnsaved(),true);state.clear();assert.equal(state.disputes.size,0);assert.equal(state.hasUnsaved(),false);state.disputes.set(caseId,{comments:{[record.id]:'Unsaved reply'}});assert.equal(state.hasUnsaved(),true);
`));
