const { execFileSync } = require("child_process"), { pathToFileURL } = require("url"), path = require("path");
const url = name => pathToFileURL(path.resolve(__dirname, `../../frontend/assets/scripts/attorney-v2/${name}.mjs`)).href;
const run = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict';import * as m from ${JSON.stringify(url("export-model"))};import {createApiClient} from ${JSON.stringify(url("api-client"))};import {parseRoute} from ${JSON.stringify(url("routes"))};${source}`], { stdio: "pipe" }); };
const fixture = `const owner='a'.repeat(24),caseId='b'.repeat(24),revision='c'.repeat(64),value={ownerId:owner,caseId,caseTitle:'Agreement',access:'available',revision,retentionEndsAt:null,filename:'Agreement-archive.zip',counts:{messages:2,documents:3,priorVersions:1,confidentialityDocuments:1}};const zip=Buffer.concat([Buffer.from([80,75,3,4]),Buffer.from('synthetic'),Buffer.from([80,75,5,6]),Buffer.alloc(18)]),bytes=new Blob([zip]);const identity={ok:true,json:async()=>({user:{id:owner,role:'attorney',status:'approved'}})};`;
test("archive projections reject foreign identities, invalid counts and unavailable download data", () => run(fixture+`
  assert.equal(m.readExport(value,caseId,owner),value);assert.equal(parseRoute('#/matters/'+caseId+'/export').name,'matter-export');
  for(const change of [{ownerId:'other'},{caseId:'other'},{access:'expired'},{revision:''},{retentionEndsAt:'invalid'},{counts:{...value.counts,documents:-1}},{counts:{...value.counts,priorVersions:4}},{filename:'../archive.zip'}])assert.throws(()=>m.readExport({...value,...change},caseId,owner));
  for(const access of Object.keys(m.exportReasons))assert.equal(m.readExport({...value,access,counts:null,revision:null},caseId,owner).access,access);
`));
test("review and ZIP requests verify identity and use GET only", () => run(fixture+`
  const calls=[];const api=createApiClient({fetchImpl:async(path,options)=>{calls.push({path,...options});return path==='/api/auth/me'?identity:{ok:true,status:200,headers:new Headers({'content-type':'application/zip'}),blob:async()=>bytes,json:async()=>value};}});
  assert.equal(await api.readMatterExport(caseId,{ownerId:owner}),value);assert.equal(await api.downloadMatterExport(caseId,revision,{ownerId:owner}),bytes);assert.equal(calls.length,5);assert.ok(calls.every(call=>call.method==='GET'));assert.equal(calls[3].headers.Accept,'application/zip');assert.ok(calls[3].path.includes('revision='+revision));assert.equal(calls[4].path,'/api/auth/me');
`));
test("HTTP failures, HTML, truncated ZIPs and oversize archives never become downloads", () => run(fixture+`
  for(const mode of ['http','html','fake','truncated','oversize']){let gets=0;const body=mode==='oversize'?{size:271*1024*1024,slice:(...args)=>bytes.slice(...args)}:mode==='fake'?new Blob(['<html>Error</html>']):mode==='truncated'?new Blob([zip.subarray(0,-1)]):bytes;const api=createApiClient({fetchImpl:async(path)=>path==='/api/auth/me'?identity:(gets++,{ok:mode!=='http',status:409,headers:new Headers({'content-type':mode==='html'?'text/html':'application/zip'}),json:async()=>({code:'EXPORT_CHANGED'}),blob:async()=>body})});await assert.rejects(api.downloadMatterExport(caseId,revision,{ownerId:owner}));assert.equal(gets,1);}
`));
test("account changes after bytes arrive discard the old archive", () => run(fixture+`
  let identities=0,lost=0;const api=createApiClient({onAuthenticationLost:()=>lost++,fetchImpl:async(path)=>path==='/api/auth/me'?{ok:true,json:async()=>({user:{id:++identities===1?owner:'f'.repeat(24),role:'attorney',status:'approved'}})}:{ok:true,status:200,headers:new Headers({'content-type':'application/zip'}),blob:async()=>bytes}});await assert.rejects(api.downloadMatterExport(caseId,revision,{ownerId:owner}),e=>e.kind==='authentication');assert.equal(lost,1);
`));
test("clearing the API or canceling discards delayed archive bytes", () => run(fixture+`
  for(const mode of ['clear','cancel']){let release,started;const ready=new Promise(r=>started=r),gate=new Promise(r=>release=r),controller=new AbortController();const api=createApiClient({fetchImpl:async(path)=>path==='/api/auth/me'?identity:{ok:true,status:200,headers:new Headers({'content-type':'application/zip'}),blob:async()=>{started();await gate;return bytes;}}});const result=api.downloadMatterExport(caseId,revision,{ownerId:owner,signal:controller.signal});await ready;if(mode==='clear')api.clear();else controller.abort();release();await assert.rejects(result,e=>e.name==='AbortError');}
`));
