process.env.STRIPE_SECRET_KEY = "sk_test_synthetic_removal"; process.env.S3_BUCKET = "synthetic-removal"; process.env.S3_MALWARE_SCAN_REQUIRED = "false";
const express = require("express"), cookieParser = require("cookie-parser"), request = require("supertest"), mongoose = require("mongoose"), crypto = require("crypto"), { Readable } = require("stream");
const mockStorage = jest.fn();
jest.mock("../utils/s3Client", () => ({ createS3Client: () => ({ send: mockStorage }) }));
jest.mock("../utils/email", () => jest.fn(async () => ({ ok: true })));
jest.mock("../services/lpcEvents/publishEventService", () => ({ publishEventSafe: jest.fn(async () => ({ ok: true })) }));
const User = require("../models/User"), Case = require("../models/Case"), CaseFile = require("../models/CaseFile"), Upload = require("../models/MatterFileUpload"), Removal = require("../models/MatterFileRemoval"), Retirement = require("../models/MatterStorageRetirement"), Message = require("../models/Message"), AuditLog = require("../models/AuditLog"), Notification = require("../models/Notification");
const storage = require("../services/matterStorageRetirement"), writes = require("../services/matterFileWrites"), { decryptCaseFilePayload } = require("../utils/dataEncryption"), { connect, clearDatabase, closeDatabase } = require("./helpers/db");
const app = express(); app.use(cookieParser(), express.json()); for (const route of ["uploads", "cases", "messages"]) app.use(`/api/${route}`, require(`../routes/${route}`)); app.use((error, _req, res, _next) => res.status(error.status || 500).json({ error: error.message }));
const cookie = user => `token=${require("jsonwebtoken").sign({ id: String(user._id), role: user.role, av: user.authVersion || 0 }, process.env.JWT_SECRET, { expiresIn: "1h" })}`;
let owner, para, other, matter, file, key;
beforeAll(async () => { await connect(); await Promise.all([User.init(), Case.init(), CaseFile.init(), Upload.init(), Removal.init(), Retirement.init(), Message.init(), AuditLog.init(), Notification.init()]); }); afterAll(closeDatabase); afterEach(() => jest.restoreAllMocks());
beforeEach(async () => {
  await clearDatabase(); jest.clearAllMocks();
  mockStorage.mockImplementation(async command => command.constructor.name === "HeadObjectCommand" ? { ContentLength: 9, ContentType: "text/plain" } : command.constructor.name === "GetObjectCommand" ? { Body: Readable.from(["new lease"]) } : {});
  [owner, para, other] = await User.create(["owner", "para", "other"].map(name => ({ firstName: "Synthetic", lastName: name, email: `${name}@file-removal.test`, password: "Synthetic123!", role: name === "para" ? "paralegal" : "attorney", status: "approved" })));
  matter = await Case.create({ title: "River Street lease", details: "Review the lease", attorney: owner._id, attorneyId: owner._id, paralegal: para._id, paralegalId: para._id, status: "in progress", escrowStatus: "funded", escrowIntentId: "pi_synthetic_removal", totalAmount: 100000 }); key = `cases/${matter._id}/documents/lease.txt`;
  file = await CaseFile.create({ caseId: matter._id, userId: para._id, originalName: "Lease.txt", storageKey: key, mimeType: "text/plain", size: 9, uploadedByRole: "paralegal", securityStatus: "not_required" });
});
const read = (query = {}, user = owner, fileId = file._id) => request(app).get(`/api/uploads/case/${matter._id}/removal-review/${fileId}`).set("Cookie", cookie(user)).query({ expectedOwnerId: String(user._id), ...query });
const review = async () => { const result = await read(); expect(result.status).toBe(200); return result.body; };
const remove = (value, requestId = crypto.randomUUID(), user = owner, fileId = file._id) => request(app).post(`/api/uploads/case/${matter._id}/reviewed-removal/${fileId}`).set("Cookie", cookie(user)).send({ expectedOwnerId: String(user._id), requestId, reviewedRevision: value.revision });
const stored = () => CaseFile.collection.findOne({ _id: file._id });
const share = () => request(app).post(`/api/messages/${matter._id}/file`).set("Cookie", cookie(para)).send({ fileKey: key, fileName: "Lease.txt", mimeType: "text/plain", fileSize: 9 });
test("removal commits evidence and matching mirrors before any storage call, retaining unknown metadata", async () => {
  const mirror = { key, original: "Lease.txt", futureEvidence: "MIRROR" }, mismatch = { key, original: "Different.txt", fileId: new mongoose.Types.ObjectId() };
  await Case.collection.updateOne({ _id: matter._id }, { $set: { files: [mirror, mismatch] } }); await CaseFile.collection.updateOne({ _id: file._id }, { $set: { futureEvidence: "PRIVATE", history: [{ storageKey: `cases/${matter._id}/documents/prior.txt`, futureVersion: "PRESERVE" }] } });
  const value = await review(), requestId = crypto.randomUUID(), result = await remove(value, requestId); expect(result.status).toBe(200); expect(result.body.removal).toMatchObject({ exactRequest: true, status: "removed", cleanup: "pending" }); expect(await stored()).toBeNull(); expect(mockStorage).not.toHaveBeenCalled();
  const record = await Removal.collection.findOne({ requestId }); expect(record.snapshot.futureEvidence).toBe("PRIVATE"); expect(record.snapshot.history[0].futureVersion).toBe("PRESERVE"); expect(record.removedMirrors).toEqual([mirror]); expect((await Case.collection.findOne({ _id: matter._id })).files).toEqual([mismatch]);
  const recovered = await read({ requestId }); expect(recovered.status).toBe(200); expect(recovered.body.removal.exactRequest).toBe(true); expect(JSON.stringify(recovered.body)).not.toMatch(/PRIVATE|MIRROR|documents\/|snapshot|futureEvidence/); expect((await remove(value, requestId)).status).toBe(200); expect(await Removal.countDocuments()).toBe(1); expect(await AuditLog.countDocuments({ action: "case.file.remove" })).toBe(1);
});
test.each(["paralegal", "other"])("%s cannot read or remove the attorney document", async role => { const user = role === "paralegal" ? para : other; expect((await read({}, user)).status).toBe(403); expect((await remove(await review(), crypto.randomUUID(), user)).status).toBe(403); expect(await stored()).toBeTruthy(); });
test.each([{ completionClaimStatus: "claimed" }, { completionClaimToken: "claimed" }, { hiringClaimToken: "claimed" }, { status: "paused" }, { archived: true }, { readOnly: true }, { purgedAt: new Date() }])("lifecycle state %j prevents removal", async patch => { const value = await review(); await Case.collection.updateOne({ _id: matter._id }, { $set: patch }); expect([403, 409]).toContain((await remove(value)).status); expect(await stored()).toBeTruthy(); expect(await Removal.countDocuments()).toBe(0); });
test("completed and purged removal reviews do not bypass the file-access policy", async () => { for (const patch of [{ status: "completed" }, { purgedAt: new Date() }]) { await Case.collection.updateOne({ _id: matter._id }, { $set: patch }); const result = await read(); expect(result.status).toBe(200); expect(result.body.file).toBeNull(); expect(result.body.revision).toBeNull(); expect(result.body.canRemove).toBe(false); } });
test.each([{ version: 8 }, { previewKey: "changed-preview" }, { futureMetadata: "new evidence" }])("a changed document %j invalidates its reviewed removal", async patch => { const value = await review(); await CaseFile.collection.updateOne({ _id: file._id }, { $set: patch }); expect((await remove(value)).status).toBe(409); expect(await stored()).toBeTruthy(); });
test("changed expected account and original request inputs cannot adopt a removal", async () => { expect((await read({ expectedOwnerId: String(other._id) })).status).toBe(403); const value = await review(), requestId = crypto.randomUUID(); expect((await remove(value, requestId)).status).toBe(200); expect((await remove({ revision: "f".repeat(64) }, requestId)).status).toBe(409); expect((await remove(value)).status).toBe(409); expect(await Removal.countDocuments()).toBe(1); });
test("the original legacy upload receipt survives removal and cannot create the document again", async () => { const requestId = crypto.randomUUID(); await CaseFile.collection.updateOne({ _id: file._id }, { $set: { clientUploadId: requestId } }); expect((await remove(await review())).status).toBe(200); const receipt = await Upload.collection.findOne({ requestId }); expect(receipt.fingerprint).toBe("legacy-unverified"); expect(String(receipt.ownerId)).toBe(String(para._id)); });
test("a lost commit acknowledgement recovers the exact removal without deleting again", async () => { const value = await review(), original = mongoose.startSession.bind(mongoose); jest.spyOn(mongoose, "startSession").mockImplementation(async (...args) => { const session = await original(...args), commit = session.commitTransaction.bind(session); session.commitTransaction = async () => { await commit(); throw new Error("Synthetic lost acknowledgement"); }; return session; }); const requestId = crypto.randomUUID(); expect((await remove(value, requestId)).status).toBe(200); expect(await stored()).toBeNull(); expect(await Removal.countDocuments()).toBe(1); expect(mockStorage).not.toHaveBeenCalled(); });
test("failure before commit rolls back the document, mirror and retirement together", async () => { const value = await review(); jest.spyOn(Removal, "create").mockRejectedValueOnce(new Error("Synthetic unavailable evidence")); expect((await remove(value)).status).toBe(503); expect(await stored()).toBeTruthy(); expect(await Retirement.countDocuments()).toBe(0); });
test("completion winning the Case guard stops removal", async () => { const value = await review(), original = Case.collection.updateOne.bind(Case.collection); let once = false; jest.spyOn(Case.collection, "updateOne").mockImplementation(async (...args) => { if (args[2]?.session && !once) { once = true; await original({ _id: matter._id }, { $set: { completionClaimToken: "winner" } }); } return original(...args); }); expect((await remove(value)).status).toBe(409); expect(await stored()).toBeTruthy(); expect(await Retirement.countDocuments()).toBe(0); });
test("account revocation at the final write guard rolls back removal", async () => { const value = await review(), original = Removal.create.bind(Removal); jest.spyOn(Removal, "create").mockImplementation(async (...args) => { const result = await original(...args); await User.collection.updateOne({ _id: owner._id }, { $inc: { authVersion: 1 } }); return result; }); expect((await remove(value)).status).toBe(403); expect(await stored()).toBeTruthy(); expect(await Retirement.countDocuments()).toBe(0); });
test("both earlier deletion routes use the retained removal and reject the paralegal role", async () => { expect((await request(app).delete(`/api/cases/${matter._id}/files`).set("Cookie", cookie(para)).send({ key })).status).toBe(403); expect((await request(app).delete(`/api/uploads/case/${matter._id}/${file._id}`).set("Cookie", cookie(para))).status).toBe(403); expect((await request(app).delete(`/api/cases/${matter._id}/files`).set("Cookie", cookie(owner)).send({ key })).status).toBe(200); expect(await Removal.countDocuments()).toBe(1); expect(mockStorage).not.toHaveBeenCalled(); });
test("an existing file message retains its copy after removal, while a later message cannot reattach it", async () => { const shared = await share(); expect(shared.status).toBe(201); expect((await remove(await review())).status).toBe(200); expect(await storage.referenced(matter._id, key)).toBe(true); expect((await share()).status).toBe(400); expect(await Message.countDocuments({ caseId: matter._id })).toBe(1); });
test("removal winning after the message file read prevents its late attachment", async () => { const value = await review(), original = writes.run; let once = false; jest.spyOn(writes, "run").mockImplementation(async (req, ...args) => { if (req.user.role === "paralegal" && !once) { once = true; expect((await remove(value)).status).toBe(200); } return original(req, ...args); }); expect((await share()).status).toBe(409); expect(await Message.countDocuments()).toBe(0); });
test("retired storage keys cannot be attached or used for replacement", async () => { expect((await remove(await review())).status).toBe(200); const attach = await request(app).post(`/api/cases/${matter._id}/files`).set("Cookie", cookie(owner)).send({ key, original: "Lease.txt", mime: "text/plain", size: 9 }); expect(attach.status).toBe(409); expect(attach.body.code).toBe("FILE_WRITE_RETIRED"); expect(await CaseFile.countDocuments()).toBe(0); });
test("earlier replacement clears the old preview and schedules its retirement atomically", async () => { const previewKey = `cases/${matter._id}/previews/lease.pdf`; await CaseFile.collection.updateOne({ _id: file._id }, { $set: { previewKey, previewMimeType: "application/pdf", previewSize: 15 } }); const result = await request(app).post(`/api/cases/${matter._id}/files/${file._id}/replace`).set("Cookie", cookie(owner)).send({ key: `cases/${matter._id}/documents/new.txt`, original: "New.txt", mime: "text/plain", size: 9 }); expect(result.status).toBe(200); expect(decryptCaseFilePayload(await stored())).toMatchObject({ previewKey: "", previewMimeType: "", previewSize: 0 }); expect(await Retirement.countDocuments({ reason: "preview_replaced" })).toBe(1); expect(mockStorage.mock.calls.some(([command]) => command.constructor.name === "DeleteObjectCommand")).toBe(false); });
test("a recorded acknowledged upload completes removal cleanup without deleting another document", async () => {
  const result = await request(app).post(`/api/uploads/case/${matter._id}?presentation=matter`).set("Cookie", cookie(para)).field("clientUploadId", crypto.randomUUID()).attach("file", Buffer.from("Acknowledged document"), { filename: "Acknowledged.txt", contentType: "text/plain" }); expect(result.status).toBe(201);
  file = await CaseFile.findById(result.body.file.id); const value = await review(), requestId = crypto.randomUUID(); expect((await remove(value, requestId)).status).toBe(200);
  const outcome = await storage.processMatterStorageRetirements({}, { s3: { send: mockStorage }, env: process.env }); expect(outcome.deleted).toBe(1); const after = await read({ requestId }); expect(after.body.removal.cleanup).toBe("deleted"); expect(await CaseFile.countDocuments()).toBe(1); expect(decryptCaseFilePayload(await CaseFile.findOne()).storageKey).toBe(key);
});
test("an expired upload cannot attach after its original storage call returns late", async () => {
  let arrived, release; const waiting = new Promise(resolve => { arrived = resolve; }), gate = new Promise(resolve => { release = resolve; }); const requestId = crypto.randomUUID();
  mockStorage.mockImplementationOnce(async () => { arrived(); await gate; return {}; });
  const upload = request(app).post(`/api/uploads/case/${matter._id}?presentation=matter`).set("Cookie", cookie(para)).field("clientUploadId", requestId).attach("file", Buffer.from("Late document"), { filename: "Late.txt", contentType: "text/plain" }).then(value => value);
  try { await waiting; await Upload.collection.updateOne({ requestId }, { $set: { leaseUntil: new Date(Date.now() - 1000) } }); expect((await storage.sweepUploads()).failed).toBe(0); } finally { release(); }
  expect((await upload).status).toBe(409); expect(await CaseFile.countDocuments()).toBe(1); expect((await Upload.collection.findOne({ requestId })).status).toBe("unconfirmed"); expect((await Retirement.collection.findOne()).putOutcome).toBe("uploaded");
});
test("the same request UUID cannot remove another document", async () => {
  const value = await review(), requestId = crypto.randomUUID(); expect((await remove(value, requestId)).status).toBe(200);
  file = await CaseFile.create({ caseId: matter._id, userId: para._id, originalName: "Other.txt", storageKey: `cases/${matter._id}/documents/other.txt`, mimeType: "text/plain", size: 9, uploadedByRole: "paralegal", securityStatus: "not_required" });
  expect((await remove(await review(), requestId)).status).toBe(409); expect(await stored()).toBeTruthy(); expect(await Removal.countDocuments()).toBe(1);
});

test("an unavailable audit cannot leave a document removed without its recorded activity", async () => { const value = await review(); jest.spyOn(AuditLog, "create").mockRejectedValueOnce(new Error("Synthetic audit unavailable")); expect((await remove(value)).status).toBe(503); expect(await stored()).toBeTruthy(); expect(await Removal.countDocuments()).toBe(0); expect(await Retirement.countDocuments()).toBe(0); });
