const express = require("express"), cookieParser = require("cookie-parser"), request = require("supertest"), mongoose = require("mongoose"), crypto = require("crypto");
jest.mock("../utils/email", () => jest.fn(async () => ({ ok: true })));
jest.mock("../services/lpcEvents/publishEventService", () => ({ publishEventSafe: jest.fn(async () => ({ ok: true })) }));
const mockStripe = { paymentIntents: { retrieve: jest.fn(), create: jest.fn() }, charges: { retrieve: jest.fn() }, checkout: { sessions: { create: jest.fn(), retrieve: jest.fn() } } };
jest.mock("../utils/stripe", () => mockStripe);
const User = require("../models/User"), Case = require("../models/Case"), Job = require("../models/Job"), Operation = require("../models/PaymentOperation"), Payout = require("../models/Payout"), Audit = require("../models/AuditLog");
const { connect, clearDatabase, closeDatabase } = require("./helpers/db"), { ensureFundingRequestKey } = require("../utils/funding");
const app = express(); app.use(cookieParser(), express.json()); app.use("/api/payments", require("../routes/payments")); app.use("/api/cases", require("../routes/cases"));
let owner, other, para, admin, matter;
const cookie = user => `token=${require("jsonwebtoken").sign({ id: String(user._id), role: user.role, av: user.authVersion || 0 }, process.env.JWT_SECRET, { expiresIn: "1h" })}`;
const read = (query = {}, user = owner) => request(app).get(`/api/payments/matter/${matter._id}/funding`).query({ expectedOwnerId: String(user._id), ...query }).set("Cookie", cookie(user));
const send = (body, user = owner) => request(app).post(`/api/payments/matter/${matter._id}/funding`).set("Cookie", cookie(user)).send({ expectedOwnerId: String(user._id), ...body });
const legacy = (action, body = {}, user = owner) => request(app).post(`/api/payments/${action}/${matter._id}`).set("Cookie", cookie(user)).send(body);
const budget = (body, user = owner) => request(app).patch(`/api/payments/${matter._id}/budget`).set("Cookie", cookie(user)).send(body);
const raw = () => Case.collection.findOne({ _id: matter._id }), change = patch => Case.collection.updateOne({ _id: matter._id }, { $set: patch });
async function command(action = "prepare") { const review = await read(); expect({ status: review.status, body: review.body }).toMatchObject({ status: 200 }); return { action, requestId: crypto.randomUUID(), reviewedRevision: review.body.revision }; }
const intent = (patch = {}) => ({ id: "pi_funding", object: "payment_intent", amount: 122001, amount_received: 0, currency: "usd", livemode: false, status: "requires_payment_method", client_secret: "pi_funding_secret_synthetic", transfer_group: `case_${matter._id}`, metadata: { caseId: String(matter._id), attorneyId: String(owner._id) }, ...patch });
const paid = (patch = {}) => intent({ status: "succeeded", amount_received: 122001, latest_charge: { id: "ch_funding", amount: 122001, amount_captured: 122001, amount_refunded: 0, paid: true, captured: true, refunded: false, disputed: false, status: "succeeded", currency: "usd", livemode: false, payment_intent: "pi_funding", balance_transaction: { id: "txn_funding", type: "charge", amount: 122001, fee: 3500, net: 118501, currency: "usd", source: "ch_funding" } }, ...patch });
beforeAll(async () => { await connect(); await Promise.all([User.init(), Case.init(), Job.init(), Operation.init(), Payout.init(), Audit.init()]); }); afterAll(closeDatabase); afterEach(() => jest.restoreAllMocks());
beforeEach(async () => {
  await clearDatabase(); jest.clearAllMocks(); mockStripe.paymentIntents.create.mockReset(); mockStripe.paymentIntents.retrieve.mockReset();
  [owner, other, para, admin] = await User.create(["owner", "other", "para", "admin"].map(name => ({ firstName: "Synthetic", lastName: name, email: `${name}@funding.test`, password: "Synthetic123!", role: name === "para" ? "paralegal" : name === "admin" ? "admin" : "attorney", status: "approved" })));
  matter = await Case.create({ title: "River Street lease review", practiceArea: "Real Estate Law", details: "Review the retained lease exhibits.", attorney: owner._id, attorneyId: owner._id, paralegal: para._id, paralegalId: para._id, status: "open", totalAmount: 100001, lockedTotalAmount: 100001, remainingAmount: 100001, feeAttorneyPct: 22, feeAttorneyAmount: 22000, currency: "usd", stripeMode: "test" });
  mockStripe.paymentIntents.create.mockImplementation(async () => intent()); mockStripe.paymentIntents.retrieve.mockImplementation(async () => intent());
});
async function interruptedCapture() {
  await change({ paymentIntentId: "pi_funding", escrowIntentId: "pi_funding" });
  await require("../services/fundingEvidenceBackfillService").reconcileFundingEvidence({
    caseDoc: await raw(), paymentIntent: paid({ latest_charge: "ch_funding" }), PaymentOperation: Operation,
    stripeClient: { charges: { retrieve: async () => { throw Error("Synthetic charge lookup unavailable"); } } },
  });
  mockStripe.paymentIntents.retrieve.mockResolvedValue(paid());
  return Operation.findOne({ caseId: matter._id, kind: "funding" }).lean();
}
test.each([39999, 40000, 40001])("funding review applies the Matter minimum to the recorded %i-cent amount before any provider request", async amount => {
  await change({ totalAmount: amount, lockedTotalAmount: amount, remainingAmount: amount, feeAttorneyAmount: Math.round(amount * 0.22) });
  const before = await raw(), response = await read();
  expect(response.status).toBe(200);
  expect(response.body.canPrepare).toBe(amount >= 40000);
  expect(await raw()).toEqual(before);
  expect(mockStripe.paymentIntents.create).not.toHaveBeenCalled();
  expect(mockStripe.paymentIntents.retrieve).not.toHaveBeenCalled();
});
test.each(["attorney", "admin"])("an explicit %s funding check finishes an interrupted capture without another charge", async role => {
  const before = await interruptedCapture();
  const response = role === "admin" ? await legacy("reconcile", {}, admin) : await send(await command("check"));
  expect({ status: response.status, body: response.body }).toMatchObject({ status: 200 });
  expect(await Operation.findById(before._id).lean()).toMatchObject({ status: "succeeded", lastError: "", grossAmount: 122001, processingFeeAmount: 3500, netAmount: 118501, stripeMode: "test", livemode: false });
  expect((await Operation.collection.findOne({ _id: before._id })).caseId).toEqual(before.caseId);
  expect((await read()).body.fundingVerified).toBe(true);
  expect(await Operation.countDocuments()).toBe(1);
  expect(mockStripe.paymentIntents.create).not.toHaveBeenCalled();
});
test("an explicit check preserves a quarantined interrupted capture", async () => {
  const operation = await interruptedCapture(); await Operation.collection.updateOne({ _id: operation._id }, { $set: { evidenceStatus: "quarantined" } });
  const before = await Operation.findById(operation._id).lean(), beforeMatter = await raw();
  expect((await send(await command("check"))).status).toBe(409);
  expect(await Operation.findById(operation._id).lean()).toEqual(before); expect(await raw()).toEqual(beforeMatter);
});
test("an interrupted capture cannot be recovered if the explicit check loses its audit", async () => {
  const before = await interruptedCapture(), beforeMatter = await raw(), body = await command("check");
  jest.spyOn(Audit, "create").mockRejectedValueOnce(new Error("Synthetic recovery audit unavailable"));
  expect((await send(body)).status).toBe(503);
  expect(await Operation.findById(before._id).lean()).toEqual(before); expect(await raw()).toEqual(beforeMatter);
  expect((await send(body)).status).toBe(200); expect(await Operation.countDocuments()).toBe(1);
});
test("read shows exact original amounts and exposes no provider identifiers or read side effects", async () => {
  const before = await raw(), value = await read(); expect({ status: value.status, body: value.body }).toMatchObject({ status: 200, body: { baseCents: 100001, feeCents: 22000, totalCents: 122001, currency: "USD", fundingVerified: false, canPrepare: true, canCheck: false, canEditAmount: false } }); expect(value.headers["cache-control"]).toBe("private, no-store"); expect(JSON.stringify(value.body)).not.toMatch(/pi_|clientSecret|fundingRequest|stripeCustomer/); expect(await raw()).toEqual(before); expect(mockStripe.paymentIntents.create).not.toHaveBeenCalled(); expect(mockStripe.paymentIntents.retrieve).not.toHaveBeenCalled();
});
test("preparation durably claims one unconfirmed intent and exact replay never creates or exposes a second form", async () => {
  const body = await command(), sent = await send(body); expect({ status: sent.status, body: sent.body }).toMatchObject({ status: 200, body: { payment: { intentId: "pi_funding", clientSecret: "pi_funding_secret_synthetic" }, funding: { fundingVerified: false, operation: { status: "prepared", requestId: body.requestId } } } });
  expect(mockStripe.paymentIntents.create).toHaveBeenCalledTimes(1); const [payload, options] = mockStripe.paymentIntents.create.mock.calls[0]; expect(payload).toMatchObject({ amount: 122001, currency: "usd", transfer_group: `case_${matter._id}` }); expect(payload.confirm).toBeUndefined(); expect((await raw()).fundingRequestKey).toBe(options.idempotencyKey); expect((await raw()).status).toBe("open"); expect(await Operation.countDocuments()).toBe(0);
  expect((await send(body)).body.payment).toBeNull(); expect((await read({ requestId: body.requestId })).body.operation.status).toBe("prepared"); expect(mockStripe.paymentIntents.create).toHaveBeenCalledTimes(1); expect((await send({ ...body, reviewedRevision: "a".repeat(64) })).status).toBe(409);
});
test("unknown preparation stays claimed past provider key expiry and is never resent", async () => {
  mockStripe.paymentIntents.create.mockRejectedValueOnce(new Error("Synthetic unknown provider result")); const body = await command(); expect((await send(body)).status).toBe(503); await Audit.collection.updateMany({ action: "case.funding.started" }, { $set: { createdAt: new Date(Date.now() - 172800000) } }); expect((await read({ requestId: body.requestId })).body).toMatchObject({ canPrepare: false, operation: { status: "needs_review" } }); expect((await send(body)).body.payment).toBeNull(); expect((await send(await command())).status).toBe(409); expect(mockStripe.paymentIntents.create).toHaveBeenCalledTimes(1);
});
test("competing tabs cannot create a second intent while provider preparation is in flight", async () => {
  const body = await command(); let release, arrived; const waiting = new Promise(resolve => { arrived = resolve; }), gate = new Promise(resolve => { release = resolve; }); mockStripe.paymentIntents.create.mockImplementationOnce(async () => { arrived(); await gate; return intent(); }); const running = send(body).then(value => value);
  try { await waiting; expect((await send(body)).body.funding.operation.status).toBe("processing"); expect((await legacy("intent")).status).toBe(409); expect((await budget({ amountUsd: "1100" })).status).toBe(409); } finally { release(); } expect((await running).status).toBe(200); expect(mockStripe.paymentIntents.create).toHaveBeenCalledTimes(1);
});
test("known provider ID survives account loss after preparation without exposing the secret", async () => {
  mockStripe.paymentIntents.create.mockImplementationOnce(async () => { await User.collection.updateOne({ _id: owner._id }, { $inc: { authVersion: 1 } }); return intent(); }); const value = await send(await command()); expect(value.status).toBe(403); expect(JSON.stringify(value.body)).not.toContain("secret"); expect((await raw()).escrowIntentId).toBe("pi_funding"); expect((await raw()).status).toBe("open");
});
test.each([{ status: "completed" }, { archived: true }, { readOnly: true }, { paralegal: null, paralegalId: null }, { completionClaimToken: "busy" }, { withdrawalClaimStatus: "needs_reconciliation" }, { hiringClaimToken: "busy" }, { lockedTotalAmount: null }, { paymentReleased: true }, { totalAmount: 1, lockedTotalAmount: 1 }])("preparation respects current Matter state %j", async patch => { await change(patch); expect((await read()).body.canPrepare).toBe(false); expect((await send(await command())).status).toBe(409); expect((await legacy("intent")).status).toBe(409); expect(mockStripe.paymentIntents.create).not.toHaveBeenCalled(); });
test.each([{ currency: "eur" }, { amount: 122002 }, { livemode: true }, { customer: "cus_wrong" }, { metadata: { caseId: "a".repeat(24) } }, { transfer_group: "case_other" }])("an existing intent with conflicting evidence %j is not reused or confirmed", async patch => { await change({ escrowIntentId: "pi_funding" }); mockStripe.paymentIntents.retrieve.mockResolvedValue(intent(patch)); expect((await send(await command())).status).toBe(409); expect((await send(await command("check"))).status).toBe(409); expect(await Operation.countDocuments()).toBe(0); expect(mockStripe.paymentIntents.create).not.toHaveBeenCalled(); });
test("a canceled intent can be replaced only after confirming no received or captured payment", async () => {
  await change({ escrowIntentId: "pi_old", paymentIntentId: "pi_old", fundingRequestKey: "old-key", fundingRequestFingerprint: "old" }); mockStripe.paymentIntents.retrieve.mockResolvedValue(intent({ id: "pi_old", status: "canceled", amount_received: 0 })); expect((await send(await command())).status).toBe(200); expect((await raw()).fundingRequestKey).not.toBe("old-key"); expect((await raw()).paymentIntentId).toBe("pi_funding");
});
test("a canceled intent with earlier charge evidence cannot be replaced", async () => { await change({ escrowIntentId: "pi_funding" }); mockStripe.paymentIntents.retrieve.mockResolvedValue(intent({ status: "canceled", latest_charge: "ch_prior" })); const response = await send(await command()); expect({ status: response.status, body: response.body }).toMatchObject({ status: 409 }); expect(mockStripe.paymentIntents.create).not.toHaveBeenCalled(); });
test("checking a successful payment records exact funding evidence and activates only the assigned open Matter", async () => {
  await change({ escrowIntentId: "pi_funding" }); mockStripe.paymentIntents.retrieve.mockResolvedValue(paid()); const body = await command("check"), sent = await send(body); expect({ status: sent.status, body: sent.body }).toMatchObject({ status: 200, body: { funding: { fundingVerified: true, state: "verified", canPrepare: false, operation: { status: "checked" } }, payment: null } }); const saved = await raw(); expect(saved.status).toBe("in progress"); expect(saved.remainingAmount).toBe(100001); expect(saved.escrowStatus).toBe("funded"); const op = await Operation.findOne().lean(); expect(op).toMatchObject({ operationKey: `funding:${matter._id}:pi_funding`, stripePaymentIntentId: "pi_funding", stripeChargeId: "ch_funding", stripeBalanceTransactionId: "txn_funding", amount: 122001, processingFeeAmount: 3500, netAmount: 118501 }); expect((await send(body)).status).toBe(200); expect(await Operation.countDocuments()).toBe(1);
});
test.each(["completed", "paused", "disputed", "closed"])("checking original funding preserves historical %s state and remaining amount", async status => { await change({ status, escrowIntentId: "pi_funding", escrowStatus: "released", remainingAmount: 12345 }); mockStripe.paymentIntents.retrieve.mockResolvedValue(paid()); expect((await send(await command("check"))).status).toBe(200); const saved = await raw(); expect(saved.status).toBe(status); expect(saved.remainingAmount).toBe(12345); expect(saved.escrowStatus).toBe("released"); expect(saved.hiredAt).toBeFalsy(); });
test.each(["refunded", "partially_refunded", "refund_failed", "chargeback"])("checking original capture preserves the later %s payment status", async paymentStatus => { await change({ status: "closed", escrowIntentId: "pi_funding", escrowStatus: "released", paymentStatus }); mockStripe.paymentIntents.retrieve.mockResolvedValue(paid()); expect((await send(await command("check"))).status).toBe(200); expect((await raw()).paymentStatus).toBe(paymentStatus); });
test("processing is not funded and later verified completion can activate the Matter", async () => { await change({ escrowIntentId: "pi_funding" }); mockStripe.paymentIntents.retrieve.mockResolvedValue(intent({ status: "processing" })); expect((await send(await command("check"))).body.funding).toMatchObject({ fundingVerified: false, canPrepare: false }); mockStripe.paymentIntents.retrieve.mockResolvedValue(paid()); expect((await send(await command("check"))).body.funding.fundingVerified).toBe(true); expect((await raw()).status).toBe("in progress"); });
test("a Case funded flag alone never certifies payment and duplicate evidence stays unverified", async () => { await change({ escrowStatus: "funded", escrowIntentId: "pi_funding", fundingIntegrityStatus: "verified" }); expect((await read()).body.fundingVerified).toBe(false); await Case.collection.insertOne({ attorney: other._id, paymentIntentId: "pi_funding" }); mockStripe.paymentIntents.retrieve.mockResolvedValue(paid()); expect((await send(await command("check"))).status).toBe(409); expect(await Operation.countDocuments()).toBe(0); });
test("an audit failure rolls back funding and ledger writes together", async () => { await change({ escrowIntentId: "pi_funding" }); mockStripe.paymentIntents.retrieve.mockResolvedValue(paid()); const before = await raw(); jest.spyOn(Audit, "create").mockRejectedValueOnce(new Error("Synthetic audit unavailable")); expect((await send(await command("check"))).status).toBe(503); expect(await raw()).toEqual(before); expect(await Operation.countDocuments()).toBe(0); });
test("a changed Matter during provider verification is not overwritten", async () => { await change({ escrowIntentId: "pi_funding" }); mockStripe.paymentIntents.retrieve.mockImplementationOnce(async () => { await change({ status: "closed" }); return paid(); }); expect((await send(await command("check"))).status).toBe(409); expect((await raw()).status).toBe("closed"); expect(await Operation.countDocuments()).toBe(0); });
test("owner aliases, session changes, and unknown request fields fail before a provider call", async () => { expect((await read({}, other)).status).toBe(403); expect((await read({ expectedOwnerId: String(other._id) })).status).toBe(403); expect((await send({ ...await command(), amount: 1 })).status).toBe(400); await change({ attorney: null, attorneyId: null }); expect((await legacy("intent")).status).toBe(403); expect(mockStripe.paymentIntents.create).not.toHaveBeenCalled(); });
test("admin compatibility checks funding without pretending to be the attorney", async () => { await change({ escrowIntentId: "pi_funding" }); mockStripe.paymentIntents.retrieve.mockResolvedValue(paid()); expect((await legacy("confirm", {}, admin)).body.ok).toBe(true); expect((await Audit.findOne({ action: "case.funding.checked" })).actorRole).toBe("admin"); expect((await read({}, admin)).status).toBe(403); });
test("pending payments read links to the explicit Matter review without making a checkout session", async () => { const before = await raw(); const value = await request(app).get("/api/payments/escrow/pending").set("Cookie", cookie(owner)); expect(value.status).toBe(200); expect(value.body.items[0].checkoutUrl).toBe(`/attorney-v2.html#/matters/${matter._id}/financials`); expect(mockStripe.checkout.sessions.create).not.toHaveBeenCalled(); expect(await raw()).toEqual(before); });
test("eligible budget updates keep exact cents and the public Job amount together", async () => {
  const job = await Job.create({ caseId: matter._id, attorneyId: owner._id, title: matter.title, description: matter.details, practiceArea: matter.practiceArea, budget: 1000.01, status: "open" }); await change({ paralegal: null, paralegalId: null, lockedTotalAmount: null, jobId: job._id }); expect((await read()).body.canEditAmount).toBe(true); expect((await budget({ amountUsd: "1000.03", currency: "USD" })).body).toMatchObject({ totalAmount: 100003 }); expect((await Job.findById(job._id)).budget).toBe(1000.03); expect((await raw()).totalAmount).toBe(100003);
  for (const amount of ["1.001", "1e3", "399.99", "-1"]) expect((await budget({ amountUsd: amount })).status).toBe(400);
});
test.each([{ fundingRequestKey: "uncertain" }, { escrowSessionId: "cs_existing" }, { paymentIntentId: "pi_existing" }, { applicants: [{ paralegalId: "a".repeat(24), status: "pending" }] }, { archived: true }])("budget and the posted editor preserve financial locks %j", async patch => { await change({ paralegal: null, paralegalId: null, lockedTotalAmount: null, ...patch }); expect((await budget({ amountUsd: "1100" })).status).toBe(409); const current = await request(app).get(`/api/cases/posting/${matter._id}`).set("Cookie", cookie(owner)); expect(current.status).toBe(200); expect(current.body.posting.permissions.amountLocked || !current.body.posting.permissions.canEdit).toBe(true); });
test("funding key changes cannot replace an unresolved request even when forceNew is supplied", async () => { const key = await ensureFundingRequestKey(matter._id, "initial"); expect(await ensureFundingRequestKey(matter._id, "initial")).toBe(key); await expect(ensureFundingRequestKey(matter._id, "changed")).rejects.toMatchObject({ status: 409 }); await expect(ensureFundingRequestKey(matter._id, "initial", { forceNew: true })).rejects.toMatchObject({ status: 409 }); expect((await raw()).fundingRequestKey).toBe(key); });
test.each([{ payment_intent: "pi_other" }, { paid: false }, { status: "failed" }, { amount_captured: 1000 }, { livemode: true }, { transfer_group: "case_other" }, { amount_refunded: 100 }, { disputed: true }])("charge evidence %j cannot certify a succeeded PaymentIntent", async patch => { await change({ escrowIntentId: "pi_funding" }); const value = paid(); Object.assign(value.latest_charge, patch); mockStripe.paymentIntents.retrieve.mockResolvedValue(value); expect((await send(await command("check"))).status).toBe(409); expect(await Operation.countDocuments()).toBe(0); expect((await raw()).escrowStatus).not.toBe("funded"); });
test("a balance transaction for another charge cannot certify funding", async () => { await change({ escrowIntentId: "pi_funding" }); const value = paid(); value.latest_charge.balance_transaction.source = "ch_other"; mockStripe.paymentIntents.retrieve.mockResolvedValue(value); expect((await send(await command("check"))).status).toBe(409); expect(await Operation.countDocuments()).toBe(0); });
test("an existing open checkout blocks a competing PaymentIntent and amount change", async () => { await change({ escrowSessionId: "cs_open_checkout", fundingRequestKey: "checkout-key", fundingRequestFingerprint: "checkout:original" }); expect((await send(await command())).status).toBe(409); expect((await budget({ amountUsd: "1100" })).status).toBe(409); expect(mockStripe.paymentIntents.create).not.toHaveBeenCalled(); });
test("a changed fee during preparation is retained and the earlier form is withheld", async () => { mockStripe.paymentIntents.create.mockImplementationOnce(async () => { await change({ feeAttorneyPct: 22.00001 }); return intent(); }); expect((await send(await command())).status).toBe(409); expect((await raw()).feeAttorneyPct).toBe(22.00001); expect((await raw()).paymentIntentId).toBe("pi_funding"); });
test("a customer change during preparation cannot expose a form for the prior customer", async () => { await User.collection.updateOne({ _id: owner._id }, { $set: { stripeCustomerId: "cus_original" } }); mockStripe.paymentIntents.create.mockImplementationOnce(async () => { await User.collection.updateOne({ _id: owner._id }, { $set: { stripeCustomerId: "cus_changed" } }); return intent({ customer: "cus_original" }); }); expect((await send(await command())).status).toBe(409); expect((await raw()).paymentIntentId).toBe("pi_funding"); expect((await User.findById(owner._id)).stripeCustomerId).toBe("cus_changed"); });
test("duplicated intent references block opening a payment form before any charge", async () => { await change({ escrowIntentId: "pi_funding" }); await Case.collection.insertOne({ attorney: other._id, paymentIntentId: "pi_funding" }); expect((await read()).body.canPrepare).toBe(false); expect((await send(await command())).status).toBe(409); expect(mockStripe.paymentIntents.retrieve).not.toHaveBeenCalled(); });
test("legacy confirmation and administrator checks retain their distinct pending-payment responses", async () => { await change({ escrowIntentId: "pi_funding" }); expect((await legacy("confirm")).status).toBe(402); const value = await legacy("reconcile", {}, admin); expect(value.status).toBe(200); expect(value.body).toMatchObject({ ok: true, fundingVerified: false, paymentStatus: "requires_payment_method", paymentIntentStatus: "requires_payment_method" }); });
