const { execFileSync } = require("child_process"), path = require("path");
const run = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict';import {readFinancialHistory} from './frontend/assets/scripts/attorney-v2/financial-history-model.mjs';import {createApiClient} from './frontend/assets/scripts/attorney-v2/api-client.mjs';${source}`], { cwd: path.resolve(__dirname, "../.."), encoding: "utf8", timeout: 10000 }); };
const fixture = `const owner='a'.repeat(24),caseId='b'.repeat(24),revision='c'.repeat(64),entry={id:'d'.repeat(64),caseId,caseTitle:'River Street lease',type:'funding',state:'recorded',amount:48801,currency:'USD',recordedAt:null,basis:'original_payment',receiptId:'payment',paralegalName:null,privateNote:'PRIVATE'},summary={currencies:[{currency:'USD',originalFunding:48801,paralegalPayouts:0,refunds:0,refundRecords:0,refundsUnverified:0,fundingRecords:1,payoutRecords:0,fundingUnverified:0,payoutsUnverified:0}],requiresReview:0,pending:0,undated:1},value={ownerId:owner,revision,view:'all',q:'',caseId:null,total:1,entries:[entry],nextCursor:null,summary,privateSource:'PRIVATE'},filters={view:'all',q:''};`;
test("financial presentation validates owner, scope, exact cents and summary consistency while excluding private fields", () => run(fixture + `
  const read=input=>readFinancialHistory(input,owner,filters);assert.equal(JSON.stringify(read(value)).includes('PRIVATE'),false);
  for(const patch of [{ownerId:'f'.repeat(24)},{view:'refund'},{caseId},{total:0},{entries:[entry,entry],total:2},{entries:[{...entry,currency:'JPY'}]},{entries:[{...entry,amount:1.2}]},{entries:[{...entry,basis:'refund_request'}]},{entries:[{...entry,receiptId:'f'.repeat(64)}]},{summary:{...summary,currencies:[]}},{summary:{...summary,currencies:[{...summary.currencies[0],originalFunding:48800}]}},{nextCursor:'1'}])assert.throws(()=>read({...value,...patch}));
  assert.equal(read({...value,total:0,entries:[],summary:{currencies:[],requiresReview:0,pending:0,undated:0}}).total,0);
`));
test("CSV download sends the reviewed filters and rejects HTTP, HTML and falsely labelled CSV responses", () => run(fixture + `
  const csv='"Matter","Record","Status","Currency","Amount","Amount describes"\\r\\n"River Street","Matter funding","Recorded","USD","488.01","Original payment before refunds"\\r\\n';
  for(const mode of ['valid','http','html','fake']){const calls=[];const api=createApiClient({fetchImpl:async(url,options)=>{calls.push({url,...options});return url==='/api/auth/me'?{ok:true,json:async()=>({user:{id:owner,role:'attorney',status:'approved'}})}:{ok:mode!=='http',status:mode==='http'?409:200,headers:new Headers({'content-type':mode==='html'?'text/html':'text/csv; charset=utf-8'}),json:async()=>({code:'FINANCIAL_HISTORY_CHANGED'}),blob:async()=>new Blob([mode==='fake'?'<h1>Error</h1>':csv])};}});const result=api.downloadFinancialCsv(revision,{ownerId:owner,...filters,q:'Lease & exhibits',caseId});if(mode==='valid'){assert.equal(await(await result).text(),csv);const query=new URL(calls.find(call=>call.url.includes('/csv?')).url,'https://example.test').searchParams;assert.equal(query.get('q'),'Lease & exhibits');assert.equal(query.get('revision'),revision);assert.equal(query.get('caseId'),caseId);}else await assert.rejects(result);assert.ok(calls.every(call=>call.method==='GET'));assert.equal(calls.filter(call=>call.url.includes('/csv?')).length,1);}
`));
test("financial JSON and CSV are discarded if the account changes after their response", () => run(fixture + `
  for(const mode of ['json','csv']){let identities=0;const api=createApiClient({fetchImpl:async(url)=>url==='/api/auth/me'?{ok:true,json:async()=>({user:{id:++identities===1?owner:'f'.repeat(24),role:'attorney',status:'approved'}})}:{ok:true,status:200,headers:new Headers({'content-type':'text/csv'}),json:async()=>value,blob:async()=>new Blob(['"Matter","Record","Status","Currency","Amount",'])}});await assert.rejects(mode==='json'?api.readFinancialHistory({ownerId:owner,...filters}):api.downloadFinancialCsv(revision,{ownerId:owner,...filters}),error=>error.kind==='authentication');}
`));
test("refund presentation rejects contradictory outcomes and totals while retaining exact verified amounts", () => run(fixture + `
  const refund={...entry,type:'refund',basis:'refund_processed',state:'recorded',amount:10000};
  const group={...summary.currencies[0],originalFunding:0,fundingRecords:0,refunds:10000,refundRecords:1};
  const input={...value,entries:[refund],summary:{...summary,currencies:[group]}};
  const read=input=>readFinancialHistory(input,owner,filters);assert.equal(read(input).summary.currencies[0].refunds,10000);
  for(const entryPatch of [{basis:'refund_request'},{basis:'refund_failed'},{amount:null},{currency:null},{amount:0}])assert.throws(()=>read({...input,entries:[{...refund,...entryPatch}]}));
  for(const groupPatch of [{refunds:9999},{refundRecords:0},{refunds:undefined},{refundsUnverified:-1}])assert.throws(()=>read({...input,summary:{...input.summary,currencies:[{...group,...groupPatch}]}}));
`));
