const { execFileSync } = require("node:child_process"), { pathToFileURL } = require("node:url"), path = require("node:path");
const url = name => pathToFileURL(path.resolve(__dirname, `../../frontend/assets/scripts/attorney-v2/${name}.mjs`)).href;
const check = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict';import {createApiClient} from ${JSON.stringify(url("api-client"))};import {readConversation,mergeMessages} from ${JSON.stringify(url("conversation-model"))};const ownerId='a'.repeat(24),caseId='b'.repeat(24),messageId='c'.repeat(24),revision='d'.repeat(64);${source}`], { stdio: "pipe" }); };
test("undated retained messages stay undated and retained responses cannot authorize writes", () => check(`
const message={_id:messageId,caseId,senderId:ownerId,type:'system',createdAt:null,revision,reactions:{},readBy:[],attachments:[]};const value={caseId,messages:[message],nextCursor:null,writable:false,retained:true,targetMissing:false};assert.equal(readConversation(value,caseId).messages[0].createdAt,null);assert.throws(()=>readConversation({...value,writable:true},caseId));assert.throws(()=>readConversation({...value,retained:false},caseId));const rows=mergeMessages([{id:'1',createdAt:null}],[{id:'2',createdAt:'2026-01-01'}]);assert.equal(rows[0].id,'1');
`));
test("attachment selection accepts only exact safe tokens and projected metadata", () => check(`
const attachment={id:'file-0',filename:'Original.txt',hasAttachment:true,audioMimeType:null,storageKey:'private-key'};const message={_id:messageId,caseId,type:'text',createdAt:null,revision,reactions:{},readBy:[],attachments:[attachment]};const value={caseId,messages:[message],nextCursor:null,writable:false,retained:true,targetMissing:false};assert.equal(readConversation(value,caseId).messages[0].attachments[0].storageKey,undefined);for(const patch of [{id:'../file'},{audioMimeType:'text/html'},{hasAttachment:'yes'}])assert.throws(()=>readConversation({...value,messages:[{...message,attachments:[{...attachment,...patch}]}]},caseId));assert.throws(()=>readConversation({...value,messages:[{...message,attachments:[attachment,attachment]}]},caseId));
`));
test("retained page and attachment requests carry the owner, exact link and explicit retained boundary", () => check(`
const paths=[];const api=createApiClient({fetchImpl:async path=>{paths.push(path);if(path==='/api/auth/me')return new Response(JSON.stringify({user:{id:ownerId,role:'attorney',status:'approved'}}));return new Response('{}');}});await api.readRetainedMessages(caseId,{ownerId,messageId});const query=new URL(paths.find(p=>p.includes('/retained-messages')),'https://local.test').searchParams;assert.equal(query.get('messageId'),messageId);assert.equal(query.get('expectedOwnerId'),ownerId);const src=await api.prepareMessageAudio(caseId,messageId,revision,{ownerId,retained:true,attachmentId:'file-0'});const audio=new URL(src,'https://local.test').searchParams;assert.equal(audio.get('retained'),'true');assert.equal(audio.get('attachmentId'),'file-0');await assert.rejects(api.prepareMessageAudio(caseId,messageId,revision,{ownerId,attachmentId:'../bad'}));
`));
