const { execFileSync } = require("child_process"), path = require("path");
const run = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict';import {readReceiptHistory} from './frontend/assets/scripts/attorney-v2/receipt-history-model.mjs';import {readReceipt} from './frontend/assets/scripts/attorney-v2/receipt-model.mjs';import {createApiClient} from './frontend/assets/scripts/attorney-v2/api-client.mjs';${source}`], { cwd: path.resolve(__dirname, "../.."), encoding: "utf8", timeout: 10000 }); };
const fixture = `const owner='a'.repeat(24),caseId='b'.repeat(24),selection='c'.repeat(64),entry={id:selection,type:'withdrawal',at:null,amount:0,decision:'zero_auto',paralegalName:'Earlier paralegal',needsReview:false,privatePointer:'PRIVATE_VALUE'},value={caseId,ownerId:owner,currency:'USD',revision:'d'.repeat(64),total:1,entries:[entry],nextCursor:null,selected:entry,selection:'found',privateNotes:'PRIVATE_NOTES'};`;
test("history presentation binds exact selection and strips private fields without inventing valid money or dates", () => run(fixture + `
  const read=input=>readReceiptHistory(input,caseId,owner,selection);assert.equal(JSON.stringify(read(value)).includes('PRIVATE'),false);
  for(const patch of [{ownerId:'e'.repeat(24)},{caseId:'e'.repeat(24)},{currency:'ZZZ'},{currency:'JPY'},{total:0},{entries:[]},{entries:[entry,entry],total:2},{selected:{...entry,id:'f'.repeat(64)}},{selection:'none',selected:null},{entries:[{...entry,amount:-1}]},{entries:[{...entry,at:'invalid'}]},{nextCursor:'1'}])assert.throws(()=>read({...value,...patch}));
  assert.equal(read({...value,selected:null,selection:'unavailable'}).selection,'unavailable');assert.throws(()=>readReceipt({ownerId:owner,selectionId:'payment'},caseId,owner,selection));
`));
test("history, review and PDF requests retain the chosen record and use only account-checked reads", () => run(fixture + `
  const calls=[],pdf=new Blob(['%PDF-1.4 receipt']);const api=createApiClient({fetchImpl:async(url,options)=>{calls.push({url,...options});return {ok:true,status:200,headers:new Headers({'content-type':'application/pdf'}),json:async()=>url==='/api/auth/me'?{user:{id:owner,role:'attorney',status:'approved'}}:value,blob:async()=>pdf};}});
  await api.readReceiptHistory(caseId,{ownerId:owner,receiptId:selection,cursor:'25',revision:'d'.repeat(64)});await api.readMatterReceipt(caseId,{ownerId:owner,receiptId:selection});await api.downloadMatterReceipt(caseId,'d'.repeat(64),{ownerId:owner,receiptId:selection});
  assert.ok(calls.every(call=>call.method==='GET'));const requests=calls.filter(call=>call.url!=='/api/auth/me');assert.equal(requests.length,3);for(const request of requests)assert.equal(new URL(request.url,'https://example.test').searchParams.get('receiptId'),selection);assert.equal(new URL(requests[0].url,'https://example.test').searchParams.get('cursor'),'25');
`));
test("an account switch after receipt or history JSON arrives prevents the prior account's result from being adopted", () => run(fixture + `
  for(const kind of ['history','receipt']){let identities=0;const api=createApiClient({fetchImpl:async(url)=>({ok:true,status:200,json:async()=>url==='/api/auth/me'?{user:{id:++identities===1?owner:'f'.repeat(24),role:'attorney',status:'approved'}}:value})});await assert.rejects(kind==='history'?api.readReceiptHistory(caseId,{ownerId:owner}):api.readMatterReceipt(caseId,{ownerId:owner}),error=>error.kind==='authentication');}
`));
