const { execFileSync } = require("child_process"), path = require("path");
const run = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict';import {readFunding,readFundingResult,fundingMoney,consumeFundingReturn} from './frontend/assets/scripts/attorney-v2/funding-model.mjs';import {createPrivateState} from './frontend/assets/scripts/attorney-v2/private-state.mjs';import {createApiClient} from './frontend/assets/scripts/attorney-v2/api-client.mjs';${source}`], { cwd: path.resolve(__dirname, "../.."), encoding: "utf8", timeout: 10000 }); };
const fixture = `const owner='a'.repeat(24),caseId='b'.repeat(24),revision='c'.repeat(64),requestId='a1b2c3d4-1234-4567-8123-abcdefabcdef',value={ownerId:owner,caseId,caseTitle:'River Street lease',revision,state:'awaiting_payment',blockers:[],fundingVerified:false,verifiedAt:null,baseCents:100001,feeCents:22000,totalCents:122001,currency:'USD',feePct:22,paralegalName:'Priya Ng',canPrepare:true,canCheck:false,canEditAmount:false,closed:false,operation:null,privateSource:'PRIVATE'};`;
test("funding presentation preserves exact amounts and rejects false verification and contradictory permissions", () => run(fixture + `
  const read=input=>readFunding(input,caseId,owner);assert.equal(JSON.stringify(read(value)).includes('PRIVATE'),false);assert.equal(fundingMoney(value.totalCents,'USD'),'$1,220.01');
  for(const patch of [{ownerId:'d'.repeat(24)},{caseId:'f'.repeat(24)},{revision:'changed'},{state:'paid'},{fundingVerified:true},{totalCents:122000},{feeCents:22001},{baseCents:100001.1},{currency:'JPY'},{currency:null},{feePct:null},{blockers:['invented']},{closed:true},{paralegalName:null},{canEditAmount:true}])assert.throws(()=>read({...value,...patch}));
  const verified={...value,state:'verified',fundingVerified:true,canPrepare:false,verifiedAt:'2026-09-09T12:00:00Z'};assert.equal(read(verified).fundingVerified,true);assert.throws(()=>read({...verified,verifiedAt:null}));
`));
test("only the exact reviewed prepare request may expose an approved payment form", () => run(fixture + `
  const request={requestId,action:'prepare'},funding={...value,operation:{requestId,action:'prepare',status:'prepared',at:'2026-09-09T12:00:00Z'}},payment={intentId:'pi_test',clientSecret:'pi_test_secret_synthetic',status:'requires_payment_method',privateSource:'PRIVATE'};
  assert.equal(JSON.stringify(readFundingResult({funding,payment},caseId,owner,request)).includes('PRIVATE'),false);
  for(const patch of [{intentId:'pi_other'},{clientSecret:'wrong'},{status:'succeeded'}])assert.throws(()=>readFundingResult({funding,payment:{...payment,...patch}},caseId,owner,request));
  assert.throws(()=>readFundingResult({funding:{...funding,canPrepare:false},payment},caseId,owner,request));assert.throws(()=>readFundingResult({funding,payment},caseId,owner,{...request,requestId:'b1b2c3d4-1234-4567-8123-abcdefabcdef'}));
`));
test("uncertain funding stays in page memory across routes and is erased on account protection", () => run(fixture + `const state=createPrivateState();state.funding.set(caseId,{pending:{requestId,action:'prepare'}});assert.equal(state.hasUnsaved(),true);assert.equal(state.funding.get(caseId).pending.requestId,requestId);state.clear();assert.equal(state.funding.size,0);assert.equal(state.hasUnsaved(),false);`));
test("provider return data is removed before review and cannot dictate Matter funding status", () => run(fixture + `const returned=consumeFundingReturn('https://example.test/attorney-v2.html?payment_intent=pi_test&payment_intent_client_secret=PRIVATE&redirect_status=succeeded#/matters/'+caseId+'/financials');assert.equal(returned.present,true);assert.equal(returned.caseId,caseId);assert.equal(returned.cleanUrl,'/attorney-v2.html#/matters/'+caseId+'/financials');assert.equal(JSON.stringify(returned).includes('PRIVATE'),false);assert.equal(consumeFundingReturn('https://example.test/attorney-v2.html?payment_intent=pi_other#/payments').caseId,null);`));
test("funding API verifies the owner before and after a single reviewed write", () => run(fixture + `
  const body={requestId,reviewedRevision:revision,action:'prepare'};
  for(const changed of [false,true]){const calls=[];let identities=0;const api=createApiClient({fetchImpl:async(url,opts)=>{calls.push({url,...opts});return {ok:true,status:200,json:async()=>url==='/api/auth/me'?{user:{id:++identities>1&&changed?'f'.repeat(24):owner,role:'attorney',status:'approved'}}:url==='/api/csrf'?{csrfToken:'synthetic'}:value};}});const response=api.writeFunding(caseId,body,{ownerId:owner});if(changed)await assert.rejects(response,error=>error.kind==='authentication');else assert.equal((await response).caseId,caseId);const writes=calls.filter(call=>call.method==='POST');assert.equal(writes.length,1);assert.equal(writes[0].url,'/api/payments/matter/'+caseId+'/funding');assert.deepEqual(JSON.parse(writes[0].body),{...body,expectedOwnerId:owner});assert.equal(writes[0].headers['X-CSRF-Token'],'synthetic');}
`));
test("account loss reported by the funding handler clears the whole private session", () => run(fixture + `let lost=0;const api=createApiClient({onAuthenticationLost:()=>lost++,fetchImpl:async(url)=>({ok:!url.includes('/matter/'),status:url.includes('/matter/')?403:200,json:async()=>url==='/api/auth/me'?{user:{id:owner,role:'attorney',status:'approved'}}:url==='/api/csrf'?{csrfToken:'synthetic'}:{code:'WORKSPACE_FUNDING_ACCOUNT_CHANGED'}})});await assert.rejects(api.writeFunding(caseId,{requestId,reviewedRevision:revision,action:'prepare'},{ownerId:owner}),error=>error.kind==='authentication');assert.equal(lost,1);`));
