const { execFileSync } = require("node:child_process"), { pathToFileURL } = require("node:url"), path = require("node:path");
const url = name => pathToFileURL(path.resolve(__dirname, `../../frontend/assets/scripts/attorney-v2/${name}.mjs`)).href;
const check = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict';import {createApiClient} from ${JSON.stringify(url("api-client"))};import {readCompletion,completionMoney,completionConfirmation,outcomeText} from ${JSON.stringify(url("completion-model"))};import {createPrivateState} from ${JSON.stringify(url("private-state"))};const ownerId='a'.repeat(24),caseId='b'.repeat(24),value={ownerId,caseId,caseTitle:'Lease review',paralegalId:'c'.repeat(24),paralegalName:'Priya Ng',revision:'d'.repeat(64),canComplete:true,blockers:[],mode:'complete_and_release',payoutState:'none',grossCents:100001,feeCents:18000,payoutCents:82001,currency:'USD',work:{total:1,complete:1},documents:{total:0,approved:0,awaitingReview:0,revisions:0,securityPending:0},completedAt:null,purgeAt:null,archiveReady:false,operation:null,retentionMonths:6};${source}`], { stdio: "pipe" }); };
test("completion rejects invented amounts, unavailable records and contradictory permission", () => check(`
assert.equal(readCompletion(value,caseId,ownerId).payoutCents,82001);assert.match(completionMoney(82001,'USD'),/820.01/);for(const patch of [{withdrawalActive:true},{withdrawalActive:"true"},{closed:true},{closed:"true"},{payoutCents:82000},{payoutCents:'82001'},{currency:'JPY'},{currency:'ZZZ'},{ownerId:caseId},{work:{total:1,complete:0}},{blockers:['open_dispute']},{payoutState:'needs_review'},{mode:'finish_completion'},{retentionMonths:0},{documents:{total:2,approved:0,awaitingReview:0,revisions:0,securityPending:0}}])assert.throws(()=>readCompletion({...value,...patch},caseId,ownerId));assert.equal(readCompletion({...value,canComplete:false,blockers:['amount_unavailable'],currency:null,payoutCents:null,feeCents:null},caseId,ownerId).canComplete,false);
`));
test("completion confirmation contains the exact reviewed Matter, recipient and cents", () => check(`
assert.deepEqual(completionConfirmation(value),{caseId,paralegalId:value.paralegalId,reviewedRevision:value.revision,mode:value.mode,grossCents:100001,payoutCents:82001,currency:'USD'});assert.match(outcomeText({status:'recorded_needs_review'}),/current Matter or payment records need administrative review/);assert.throws(()=>readCompletion({...value,operation:{status:'paid_in_full',at:null}},caseId,ownerId));assert.equal(readCompletion({...value,unexpectedStorageKey:'PRIVATE'},caseId,ownerId).unexpectedStorageKey,undefined);
`));
test("completion uses guarded reads and one explicit write without automatic resubmission", () => check(`
const calls=[];const api=createApiClient({fetchImpl:async(path,options={})=>{calls.push({path,options});if(path==='/api/auth/me')return new Response(JSON.stringify({user:{id:ownerId,role:'attorney',status:'approved'}}));if(path==='/api/csrf')return new Response(JSON.stringify({csrfToken:'synthetic'}));return new Response('{}');}});const requestId='a1111111-1111-4111-8111-111111111111';await api.readCompletion(caseId,{ownerId,requestId});const read=calls.find(call=>call.path.includes('/completion-review'));assert.equal(new URL(read.path,'https://local.test').searchParams.get('requestId'),requestId);await api.completeMatter(caseId,{requestId,confirmation:completionConfirmation(value)},{ownerId});const writes=calls.filter(call=>call.options.method==='POST');assert.equal(writes.length,1);assert.deepEqual(JSON.parse(writes[0].options.body),{requestId,confirmation:completionConfirmation(value),expectedOwnerId:ownerId});
`));
test("pending completion stays in tab memory and account clearing removes its private context", () => check(`
const state=createPrivateState();state.completions.set(caseId,{pending:{requestId:'synthetic',confirmation:completionConfirmation(value)}});assert.equal(state.hasUnsaved(),true);state.clear();assert.equal(state.completions.size,0);assert.equal(state.hasUnsaved(),false);
`));
