const { execFileSync } = require("child_process"), path = require("path");
test("an exact earlier-file link cannot adopt a different selected record", () => {
  const source = `import assert from 'node:assert/strict';import {readEarlierFiles} from './frontend/assets/scripts/attorney-v2/earlier-files-model.mjs';const entry={id:'a'.repeat(64),revision:'b'.repeat(64),name:'Earlier exhibit.txt',kind:'earlier_attachment',recordedAt:null,size:null,version:null,available:true};const value={caseId:'c'.repeat(24),ownerId:'d'.repeat(24),access:'available',revision:'e'.repeat(64),total:1,entries:[entry],nextCursor:null,selected:entry,selection:'found'};const read=input=>readEarlierFiles(input,value.caseId,value.ownerId,entry.id);assert.equal(read(value).selected.id,entry.id);assert.throws(()=>read({...value,selected:{...entry,id:'f'.repeat(64)}}));assert.throws(()=>read({...value,selected:null,selection:'none'}));assert.throws(()=>read({...value,total:0,entries:[]}));assert.equal(read({...value,selected:null,selection:'unavailable'}).selection,'unavailable');process.stdout.write('exact earlier-file selection verified');`;
  expect(execFileSync(process.execPath, ["--input-type=module", "--eval", source], { cwd: path.resolve(__dirname, "../.."), encoding: "utf8", timeout: 10000 })).toBe("exact earlier-file selection verified");
});
test("earlier-file presentation rejects mixed identities, repeated pages and invented history metadata while stripping private fields", () => {
  const source = `import assert from 'node:assert/strict';import {readEarlierFiles} from './frontend/assets/scripts/attorney-v2/earlier-files-model.mjs';const entry={id:'a'.repeat(64),revision:'b'.repeat(64),name:'Earlier exhibit.txt',kind:'earlier_version',recordedAt:null,size:null,version:null,available:true,key:'PRIVATE_KEY'};const value={caseId:'c'.repeat(24),ownerId:'d'.repeat(24),access:'available',revision:'e'.repeat(64),total:1,entries:[entry],nextCursor:null,selected:null,selection:'none',privateSnapshot:'PRIVATE_SNAPSHOT'};const read=input=>readEarlierFiles(input,value.caseId,value.ownerId);assert.equal(JSON.stringify(read(value)).includes('PRIVATE'),false);for(const patch of [{ownerId:'f'.repeat(24)},{caseId:'f'.repeat(24)},{entries:[entry,entry],total:2},{entries:[{...entry,version:2}]},{access:'purged'},{nextCursor:'1'},{selected:entry},{total:5000}])assert.throws(()=>read({...value,...patch}));assert.equal(read({...value,access:'purged',total:0,entries:[]}).entries.length,0);process.stdout.write('earlier-file model verified');`;
  expect(execFileSync(process.execPath, ["--input-type=module", "--eval", source], { cwd: path.resolve(__dirname, "../.."), encoding: "utf8", timeout: 10000 })).toBe("earlier-file model verified");
});
