const path=require('path');
const {execFileSync}=require('child_process');
const {pathToFileURL}=require('url');
const moduleUrl=pathToFileURL(path.resolve(__dirname,'../../frontend/assets/scripts/attorney-v2/security-api.mjs')).href;
function check(source){execFileSync(process.execPath,['--input-type=module','--eval',`import assert from 'node:assert/strict'; import {createSecurityApi,securityState} from ${JSON.stringify(moduleUrl)}; const id='a'.repeat(24), revision='a'.repeat(64); const identity=()=>new Response(JSON.stringify({user:{id,role:'attorney',status:'approved'}})); const csrf=()=>new Response(JSON.stringify({csrfToken:'synthetic-token'})); ${source}`],{stdio:'pipe'});}
test('post-write owner verification failures retain uncertain results for every non-signout mutation',()=>check(`
 const cases=[['changeMfa',[{enabled:true,method:'email'}],{enabled:true,method:'email'}],['beginAuthenticator',[{}],{challengeId:'a'.repeat(24),qrDataUrl:'data:image/png;base64,AAAA',manualSecret:'A'.repeat(32),expiresInSeconds:300}],['confirmAuthenticator',[{}],{enabled:true,method:'authenticator',backupCodes:['ABCD123456']}],['rotateBackupCodes',[{}],{codes:['ABCD123456']}],['beginPasskey',[{}],{challengeId:'a'.repeat(24),options:{}}],['registerPasskey',[{}],{id:'b'.repeat(24),name:'Work device'}],['removePasskey',['b'.repeat(24),{}],{ok:true}],['revokeSession',['other-session'],{ok:true,currentSessionRevoked:false}],['revokeOthers',[],{ok:true,revokedCount:1}]];
 for(const [method,args,payload] of cases)for(const failure of ['503','network','malformed','account']){let writes=0,verifies=0,lost=0;const api=createSecurityApi({onAuthenticationLost:()=>lost++,fetchImpl:async(path)=>{if(path==='/api/auth/me'){if(++verifies===1)return identity();if(failure==='network')throw new Error('offline');if(failure==='account')return new Response(JSON.stringify({user:{id:'b'.repeat(24),role:'attorney',status:'approved'}}));return new Response(JSON.stringify(failure==='malformed'?null:{}),{status:failure==='503'?503:200});}if(path==='/api/csrf')return csrf();writes++;return new Response(JSON.stringify(payload));}});await assert.rejects(api[method](...args,{ownerId:id,securityRevision:revision}),error=>error.kind===(failure==='account'?'authentication':'uncertain'));assert.equal(writes,1);assert.equal(lost,failure==='account'?1:0);}
`));
test('successful password/current-session logout is honored before any post-write owner verification',()=>check(`
 for(const operation of ['password','session']){const calls=[];let lost=0;const api=createSecurityApi({onAuthenticationLost:()=>lost++,fetchImpl:async(path,options)=>{calls.push({path,...options});if(path==='/api/auth/me')return identity();if(path==='/api/csrf')return csrf();return new Response(JSON.stringify(operation==='password'?{ok:true,reauthenticationRequired:true}:{ok:true,currentSessionRevoked:true}));}});
 const result=operation==='password'?await api.changePassword({currentPassword:'synthetic old',newPassword:'synthetic new'},{ownerId:id,securityRevision:revision}):await api.revokeSession('session-id',{ownerId:id});assert.equal(calls.length,3);assert.equal(lost,0);assert.equal(calls[2].headers['X-CSRF-Token'],'synthetic-token');assert.equal(calls[2].credentials,'include');assert.equal(calls[2].redirect,'error');assert.equal(JSON.parse(calls[2].body).expectedOwnerId,id);assert.ok(result.reauthenticationRequired||result.currentSessionRevoked);}
`));
test('clearing the security API discards a delayed one-time-code response even if fetch ignores abort',()=>check(`
 let release,calls=0;const api=createSecurityApi({fetchImpl:async(path)=>{calls++;if(path==='/api/auth/me')return identity();if(path==='/api/csrf')return csrf();return new Promise(resolve=>{release=resolve;});}});
 const pending=api.rotateBackupCodes({currentPassword:'synthetic proof'},{ownerId:id,securityRevision:revision});while(!release)await new Promise(resolve=>setTimeout(resolve,0));api.clear();release(new Response(JSON.stringify({codes:['ABCD123456']})));await assert.rejects(pending,error=>error.name==='AbortError');assert.equal(calls,3);
`));
test('known email prerequisites stay distinct from conflicts and ambiguous writes never retry',()=>check(`
 for(const status of [409,503]){let calls=0;const api=createSecurityApi({fetchImpl:async(path)=>{calls++;if(path==='/api/auth/me')return identity();if(path==='/api/csrf')return csrf();return new Response(JSON.stringify(status===409?{error:'Verify your email before enabling two-step verification.'}:{error:'Private database path and credentials'}),{status});}});
 await assert.rejects(api.changeMfa({enabled:true,method:'email',currentPassword:'synthetic proof'},{ownerId:id,securityRevision:revision}),error=>status===409?error.kind==='request'&&error.message==='Verify your email before enabling email sign-in codes.':error.kind==='uncertain'&&!error.message.includes('Private'));assert.equal(calls,3);}
`));
test('paged session reads retain the exact owner and cursor and validate the full envelope',()=>check(`
 const calls=[];const api=createSecurityApi({fetchImpl:async(path)=>{calls.push(path);if(path==='/api/auth/me')return identity();return new Response(JSON.stringify({sessions:[],currentSession:null,nextCursor:null,total:0}));}});const result=await api.readSessions({ownerId:id,cursor:'opaque+/cursor'});assert.equal(result.total,0);assert.equal(calls.length,3);const url=new URL(calls[1],'https://lpc.test');assert.equal(url.searchParams.get('expectedOwnerId'),id);assert.equal(url.searchParams.get('cursor'),'opaque+/cursor');
`));
test('security state projections exclude extra secrets and reject incomplete readback',()=>check(`
 const result=securityState({enabled:true,method:'email',hasBackupCodes:true,sessionManaged:true,securityRevision:revision,password:'never project',totpSecretEncrypted:'never project'});assert.equal(Object.keys(result).length,6);assert.equal(result.password,undefined);assert.equal(result.totpSecretEncrypted,undefined);assert.throws(()=>securityState({enabled:true,method:'email'}));
`));


test('every mutation validates its exact success before accepting confirmation or skipping owner verification',()=>check(`
 const cases=[['changePassword',[{currentPassword:'old',newPassword:'new'}],{reauthenticationRequired:true}],['changeMfa',[{enabled:true,method:'email'}],{}],['beginAuthenticator',[{}],{}],['confirmAuthenticator',[{}],{backupCodes:['ABCD123456']}],['rotateBackupCodes',[{}],{codes:[]}],['beginPasskey',[{}],{}],['registerPasskey',[{}],{}],['removePasskey',['b'.repeat(24),{}],{}],['revokeSession',['session-id'],{currentSessionRevoked:true}],['revokeOthers',[],{}]];
 for(const [method,args,payload] of cases){let calls=0,lost=0;const api=createSecurityApi({onAuthenticationLost:()=>lost++,fetchImpl:async(path)=>{calls++;if(path==='/api/auth/me')return identity();if(path==='/api/csrf')return csrf();return new Response(JSON.stringify(payload));}});await assert.rejects(api[method](...args,{ownerId:id,securityRevision:revision}),error=>error.kind==='uncertain');assert.equal(calls,3);assert.equal(lost,0);}
`));
