const { execFileSync } = require("node:child_process"), { pathToFileURL } = require("node:url"), path = require("node:path");
const url = name => pathToFileURL(path.resolve(__dirname, `../../frontend/assets/scripts/attorney-v2/${name}.mjs`)).href;
const check = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict';import * as m from ${JSON.stringify(url("dates-model"))};import {createApiClient} from ${JSON.stringify(url("api-client"))};import {createPrivateState} from ${JSON.stringify(url("private-state"))};const ownerId='a'.repeat(24),caseId='b'.repeat(24),eventId='c'.repeat(24),revision='d'.repeat(64);const entry={id:eventId,caseId,revision,title:'Exhibit meeting',type:'meeting',start:'2027-03-14T16:00:15.123Z',end:'2027-03-14T17:00:20.456Z',isAllDay:false,timezone:'America/New_York',where:'Conference room',notes:'Original notes',rrule:'',attendees:[],reminders:[]};${source}`], { stdio: "pipe" }); };
test("DST gaps and repeated times are explicit, including half-hour changes and a skipped date", () => check(`
assert.deepEqual(m.wallInstants('2027-03-14','02:30','America/New_York'),[]);assert.deepEqual(m.wallInstants('2027-11-07','01:30','America/New_York'),['2027-11-07T05:30:00.000Z','2027-11-07T06:30:00.000Z']);assert.deepEqual(m.wallInstants('2027-04-04','01:45','Australia/Lord_Howe'),['2027-04-03T14:45:00.000Z','2027-04-03T15:15:00.000Z']);assert.deepEqual(m.wallInstants('2011-12-30','12:00','Pacific/Apia'),[]);assert.deepEqual(m.wallInstants('2027-03-14','10:00','Asia/Kathmandu'),['2027-03-14T04:15:00.000Z']);assert.deepEqual(m.wallInstants('2027-02-30','10:00','UTC'),[]);assert.deepEqual(m.wallInstants('2027-03-14','10:00','Invalid/Zone'),[]);
`));
test("a repeated wall time requires a chosen occurrence and never silently selects the first", () => check(`
const fields={...m.dateFields(null),title:'Court appearance',isAllDay:false,timezone:'America/New_York',startDate:'2027-11-07',startTime:'01:30'};assert.throws(()=>m.dateChanges(fields,null),/occurs twice/);fields.startOccurrence='2027-11-07T06:30:00.000Z';assert.equal(m.dateChanges(fields,null).start,fields.startOccurrence);fields.startDate='2027-03-14';fields.startTime='02:30';assert.throws(()=>m.dateChanges(fields,null),/does not exist/);
`));
test("partial changes preserve original instants and unknown time zones when time fields are untouched", () => check(`
const fields=m.dateFields(entry);fields.title='Updated title';assert.deepEqual(m.dateChanges(fields,entry),{title:'Updated title'});const changedEnd={...m.dateFields(entry),endTime:'14:00'};const update=m.dateChanges(changedEnd,entry);assert.equal(update.start,undefined);assert.equal(update.end,'2027-03-14T18:00:00.000Z');const legacy={...entry,timezone:'Earlier/Zone'};const legacyFields=m.dateFields(legacy);legacyFields.notes='Revised notes';assert.deepEqual(m.dateChanges(legacyFields,legacy),{notes:'Revised notes'});
`));
test("all-day entries preserve the recorded business date and use the existing noon-UTC convention for new dates", () => check(`
const earlier={...entry,isAllDay:true,start:'2027-03-14T00:00:00.000Z',end:'2027-03-14T23:59:59.000Z',timezone:'Pacific/Kiritimati'};const fields=m.dateFields(earlier);assert.equal(fields.startDate,'2027-03-14');fields.notes='Keep the original dates';assert.deepEqual(m.dateChanges(fields,earlier),{notes:'Keep the original dates'});const created=m.dateChanges({...m.dateFields(null),title:'Matter preparation',startDate:'2027-03-14',endDate:'2027-03-15'},null);assert.equal(created.start,'2027-03-14T12:00:00.000Z');assert.equal(created.end,'2027-03-15T12:00:00.000Z');assert.match(m.calendarLabel(earlier),/Mar 14, 2027/);
`));
test("calendar reads and action acknowledgements cannot substitute another account, Matter or entry", () => check(`
const review={ownerId,caseId,revision,items:[entry],total:1,nextCursor:null,selection:'found',selectedEvent:entry,operation:null};assert.equal(m.readDates(review,caseId,ownerId),review);for(const patch of [{ownerId:'f'.repeat(24)},{items:[entry,entry]},{selectedEvent:null},{total:-1}])assert.throws(()=>m.readDates({...review,...patch},caseId,ownerId));assert.throws(()=>m.readDateOperation({status:'recorded',action:'create',eventId:'e'.repeat(24),event:entry,changedSinceSave:false},caseId));assert.equal(m.readDateOperation({status:'recorded',action:'create',eventId,event:null,changedSinceSave:true},caseId).changedSinceSave,true);
`));
test("calendar writes retain their exact request and draft context without automatic retry or browser storage", () => check(`
const calls=[];const api=createApiClient({fetchImpl:async(path,options)=>{calls.push({path,...options});if(path==='/api/auth/me')return new Response(JSON.stringify({user:{id:ownerId,role:'attorney',status:'approved'}}));if(path==='/api/csrf')return new Response(JSON.stringify({csrfToken:'synthetic'}));throw new Error('unknown response');}});const command={requestId:'synthetic-calendar-request',action:'update',eventId,reviewedRevision:revision,reviewedMatterRevision:revision,values:{notes:'PRIVATE_CALENDAR_NOTES'}};await assert.rejects(api.saveWorkspaceDate(caseId,command,{ownerId}));const writes=calls.filter(value=>value.method==='POST');assert.equal(writes.length,1);assert.equal(JSON.parse(writes[0].body).requestId,command.requestId);assert.equal(JSON.parse(writes[0].body).expectedOwnerId,ownerId);const state=createPrivateState();state.dateReviews.set(caseId,{draft:{fields:{notes:'PRIVATE_CALENDAR_NOTES'}},pending:command});assert.equal(state.hasUnsaved(),true);state.clear();assert.equal(state.hasUnsaved(),false);assert.equal(state.dateReviews.size,0);
`));
