const { execFileSync } = require("child_process"), { pathToFileURL } = require("url"), path = require("path");
const url = name => pathToFileURL(path.resolve(__dirname, `../../frontend/assets/scripts/attorney-v2/${name}.mjs`)).href;
const check = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict'; import * as m from ${JSON.stringify(url("workspace-file-history"))}; import {createApiClient} from ${JSON.stringify(url("api-client"))}; import {createPrivateState} from ${JSON.stringify(url("private-state"))}; const ownerId='a'.repeat(24),caseId='b'.repeat(24),fileId='c'.repeat(24); const file={id:fileId,name:'Agreement.pdf',revision:'d'.repeat(64),reviewRevision:'e'.repeat(64),mimeType:'application/pdf',size:40,version:1,uploadedAt:null,securityStatus:'clean',status:'pending_review',uploadedByRole:'paralegal',notes:'',requestedAt:null,approvedAt:null,replacedAt:null,revisionOf:null,canReview:true};const value={ownerId,caseId,caseTitle:'Matter',access:'available',legacyAttachments:false,files:[file],nextCursor:null,canUpload:true,selection:'none',selectedFile:null}; ${source}`], { stdio: "pipe" }); };
test("history validates record boundaries, duplicate entries and malformed response links",()=>check(`
const entry={index:0,retainedAt:null,revision:'a'.repeat(64),hasStoredDocument:true};const history={caseId,ownerId,fileId,revision:'b'.repeat(64),entries:[entry],responses:[file],nextCursor:null,nextResponseCursor:null};assert.equal(m.readHistory(history,caseId,ownerId,fileId),history);for(const patch of [{ownerId:'wrong'},{fileId:'wrong'},{entries:[entry,entry]},{entries:[{...entry,index:-1}]},{entries:[{...entry,retainedAt:'bad'}]},{responses:[file,file]},{nextResponseCursor:'bad'}])assert.throws(()=>m.readHistory({...history,...patch},caseId,ownerId,fileId));
`));
test("history downloads bind the exact historical entry and verify the account around its bytes",()=>check(`
const calls=[];const api=createApiClient({fetchImpl:async(path,options)=>{calls.push({path,...options});return path==='/api/auth/me'?new Response(JSON.stringify({user:{id:ownerId,role:'attorney',status:'approved'}})):new Response('Earlier document',{headers:{'Content-Type':'application/octet-stream'}});}});const blob=await api.downloadWorkspaceFileHistory(caseId,fileId,3,'e'.repeat(64),{ownerId});assert.equal(await blob.text(),'Earlier document');assert.equal(calls.filter(call=>call.path==='/api/auth/me').length,2);assert.ok(calls[1].path.includes('/history/3/download?'));assert.ok(calls[1].path.includes('expectedOwnerId='+ownerId));assert.ok(calls[1].path.includes('revision='+'e'.repeat(64)));await assert.rejects(api.downloadWorkspaceFileHistory(caseId,fileId,-1,'e'.repeat(64),{ownerId}));
`));
