const { execFileSync } = require("node:child_process"), { pathToFileURL } = require("node:url"), path = require("node:path");
const url = name => pathToFileURL(path.resolve(__dirname, `../../frontend/assets/scripts/attorney-v2/${name}.mjs`)).href;
const check = source => { execFileSync(process.execPath, ["--input-type=module", "--eval", `import assert from 'node:assert/strict';import {createApiClient} from ${JSON.stringify(url("api-client"))};import {readConversation} from ${JSON.stringify(url("conversation-model"))};const ownerId='a'.repeat(24),caseId='b'.repeat(24),messageId='c'.repeat(24),revision='d'.repeat(64);${source}`], { stdio: "pipe" }); };
test("attachment capabilities cannot turn arbitrary metadata into playable content", () => check(`
const message={_id:messageId,caseId,senderId:ownerId,type:'audio',createdAt:new Date().toISOString(),revision,reactions:{},readBy:[],hasAttachment:true,audioMimeType:'audio/wav'};const value={caseId,messages:[message],nextCursor:null,writable:true,targetMissing:false};assert.equal(readConversation(value,caseId).messages[0].audioMimeType,'audio/wav');for(const patch of [{audioMimeType:'text/html'},{hasAttachment:false},{type:'text'},{hasAttachment:'yes'}])assert.throws(()=>readConversation({...value,messages:[{...message,...patch}]},caseId));
`));
test("binary delivery checks both sides of the account boundary and never accepts a sign-in page", () => check(`
let reads=0,calls=[];const api=createApiClient({fetchImpl:async(path)=>{calls.push(path);if(path==='/api/auth/me'){reads++;return new Response(JSON.stringify({user:{id:reads===2?'e'.repeat(24):ownerId,role:'attorney',status:'approved'}}));}return new Response('PRIVATE_CONTENTS',{headers:{'content-type':'application/octet-stream'}});}});await assert.rejects(api.downloadMessageAttachment(caseId,messageId,revision,{ownerId}));assert.equal(reads,2);assert.equal(calls.filter(value=>value.includes('/message-attachments/')).length,1);
const wrong=createApiClient({fetchImpl:async(path)=>path==='/api/auth/me'?new Response(JSON.stringify({user:{id:ownerId,role:'attorney',status:'approved'}})):new Response('<html>Sign in</html>',{headers:{'content-type':'text/html'}})});await assert.rejects(wrong.downloadMessageAttachment(caseId,messageId,revision,{ownerId}));
`));
test("audio preparation uses the exact same-origin message route and cancellation cannot return a URL", () => check(`
const api=createApiClient({fetchImpl:async()=>new Response(JSON.stringify({user:{id:ownerId,role:'attorney',status:'approved'}}))});const src=await api.prepareMessageAudio(caseId,messageId,revision,{ownerId});assert.ok(src.startsWith('/api/cases/'+caseId+'/message-attachments/'+messageId+'?'));const query=new URL(src,'https://local.test').searchParams;assert.equal(query.get('play'),'true');assert.equal(query.get('revision'),revision);assert.equal(query.get('expectedOwnerId'),ownerId);const controller=new AbortController();controller.abort();await assert.rejects(api.prepareMessageAudio(caseId,messageId,revision,{ownerId,signal:controller.signal}));
`));
