const express = require('express');
const cookieParser = require('cookie-parser');
const jwt = require('jsonwebtoken');
const request = require('supertest');
const mongoose = require('mongoose');
jest.mock('../utils/email', () => jest.fn(async () => ({ ok: true })));
const User = require('../models/User');
const Block = require('../models/Block');
const AuthSession = require('../models/AuthSession');
const { connect, clearDatabase, closeDatabase } = require('./helpers/db');
const app = express(); app.use(cookieParser()); app.use(express.json()); app.use('/api/blocks', require('../routes/blocks'));
let owner, target, other, cookie;
const ownerId = () => String(owner._id);
const targetId = () => String(target._id);
function token(user, sid = '') { return `token=${jwt.sign({ id:String(user._id),role:user.role,status:'approved',av:0,...(sid?{sid}:{}) },process.env.JWT_SECRET,{expiresIn:'1h'})}`; }
async function user(role, label) { return User.create({firstName:label,lastName:'Fixture',role,email:`${label.toLowerCase()}@blocks.invalid`,password:'A bounded synthetic passphrase',status:'approved',state:'CA'}); }
async function block(values={}) { return Block.create({blockerId:owner._id,blockedId:target._id,blockerRole:'attorney',blockedRole:'paralegal',reason:'Private fixture note',...values}); }
const list = (query={}) => request(app).get('/api/blocks').query({expectedOwnerId:ownerId(),...query}).set('Cookie',cookie);
const status = () => request(app).get(`/api/blocks/${targetId()}`).query({expectedOwnerId:ownerId()}).set('Cookie',cookie);
const remove = revision => request(app).delete(`/api/blocks/${targetId()}`).set('Cookie',cookie).send({expectedOwnerId:ownerId(),expectedBlockRevision:revision});
beforeAll(connect); afterAll(closeDatabase);
beforeEach(async()=>{await clearDatabase();owner=await user('attorney','Owner');target=await user('paralegal','Target');other=await user('attorney','Other');cookie=token(owner);});
afterEach(()=>jest.restoreAllMocks());

test('guarded list gives private complete envelope and retains legacy array callers',async()=>{await block();const value=await list();expect(value.status).toBe(200);expect(value.headers['cache-control']).toMatch(/private.*no-store/);expect(value.body.total).toBe(1);expect(value.body.nextCursor).toBeNull();expect(value.body.items).toHaveLength(1);expect(value.body.items[0]).toMatchObject({blockedId:targetId(),name:'Target Fixture',role:'paralegal',reason:'Private fixture note'});expect(value.body.items[0].revision).toMatch(/^[a-f0-9]{64}$/);const legacy=await request(app).get('/api/blocks').set('Cookie',cookie);expect(Array.isArray(legacy.body)).toBe(true);});
test('wrong owner cannot list another account or unblock its record',async()=>{await block();const read=await list({expectedOwnerId:String(other._id)});expect(read.status).toBe(403);expect(read.body.code).toBe('ACCOUNT_CHANGED');const change=await request(app).delete(`/api/blocks/${targetId()}`).set('Cookie',cookie).send({expectedOwnerId:String(other._id),expectedBlockRevision:'a'.repeat(64)});expect(change.status).toBe(403);expect(await Block.countDocuments({active:true})).toBe(1);});
test.each(['expectedOwnerId[]=bad','expectedOwnerId=bad','cursor=bare','expectedOwnerId.foo=bad','cursor.foo=bad'])('malformed guarded list input rejects %s',async query=>{const result=await request(app).get(`/api/blocks?${query}`).set('Cookie',cookie);expect(result.status).toBe(400);expect(result.body.code).toBe('ACCOUNT_GUARD_INVALID');});
test('guarded unblock requires a valid reviewed revision',async()=>{await block();const result=await remove(undefined);expect(result.status).toBe(400);expect(await Block.countDocuments({active:true})).toBe(1);});
test('status read confirms only the owner direct block, never the reciprocal block',async()=>{await block({blockerId:target._id,blockedId:owner._id});const value=await status();expect(value.status).toBe(200);expect(value.body).toEqual({blockedId:targetId(),blocked:false,revision:null});});
test('a confirmed unblock retains history and leaves a reciprocal block active',async()=>{await block();await block({blockerId:target._id,blockedId:owner._id});const current=await list();const result=await remove(current.body.items?.[0]?.revision);expect(result.status).toBe(200);expect(result.body).toEqual({ok:true,blocked:false,blockedId:targetId()});expect((await status()).body.blocked).toBe(false);expect(await Block.countDocuments()).toBe(2);expect(await Block.countDocuments({blockerId:target._id,active:true})).toBe(1);});
test('an old review cannot remove a reactivated block',async()=>{const saved=await block();const current=await list();await Block.collection.updateOne({_id:saved._id},{$set:{active:false,deactivatedAt:new Date(),updatedAt:new Date(Date.now()+10)}});await Block.collection.updateOne({_id:saved._id},{$set:{active:true,deactivatedAt:null,updatedAt:new Date(Date.now()+20)}});const result=await remove(current.body.items?.[0]?.revision);expect(result.status).toBe(409);expect(result.body.code).toBe('ACCOUNT_CONFLICT');expect(await Block.countDocuments({active:true})).toBe(1);});
test('another tab removal cannot masquerade as this review succeeding',async()=>{const saved=await block();const current=await list();await Block.collection.updateOne({_id:saved._id},{$set:{active:false,deactivatedAt:new Date()}});const result=await remove(current.body.items?.[0]?.revision);expect(result.status).toBe(409);expect((await status()).body.blocked).toBe(false);});
test('missing referenced users remain visible and removable without inventing a profile',async()=>{const missing=new mongoose.Types.ObjectId();await block({blockedId:missing});const current=await list();expect(current.body.total).toBe(1);expect(current.body.items?.[0]).toMatchObject({blockedId:String(missing),name:'Account unavailable',role:'paralegal'});const result=await request(app).delete(`/api/blocks/${missing}`).set('Cookie',cookie).send({expectedOwnerId:ownerId(),expectedBlockRevision:current.body.items[0].revision});expect(result.status).toBe(200);expect(await Block.countDocuments({active:true})).toBe(0);});
test('more than two pages retain tied dates and missing dates exactly once',async()=>{const date=new Date('2026-09-01');const records=Array.from({length:124},(_,i)=>({_id:new mongoose.Types.ObjectId(),blockerId:owner._id,blockedId:new mongoose.Types.ObjectId(),blockedRole:'paralegal',active:true,...(i<122?{createdAt:date}:i===122?{createdAt:null}:{})}));await Block.collection.insertMany(records);const ids=[];let cursor='';let pages=0;do{const result=await list(cursor?{cursor}:{});expect(result.status).toBe(200);expect(result.body.total).toBe(124);expect(result.body.items.length).toBeLessThanOrEqual(50);ids.push(...result.body.items.map(item=>item.blockedId));cursor=result.body.nextCursor;pages++;expect(pages).toBeLessThan(5);}while(cursor);expect(ids).toHaveLength(124);expect(new Set(ids).size).toBe(124);expect(pages).toBe(3);});
test('cursor rejects tampering and reuse by another owner',async()=>{await Block.collection.insertMany(Array.from({length:51},()=>({blockerId:owner._id,blockedId:new mongoose.Types.ObjectId(),createdAt:new Date(),active:true})));const first=await list();expect(first.body.nextCursor).toEqual(expect.any(String));const bad=await list({cursor:first.body.nextCursor+'x'});expect(bad.status).toBe(400);const changed=await request(app).get('/api/blocks').query({expectedOwnerId:String(other._id),cursor:first.body.nextCursor}).set('Cookie',token(other));expect(changed.status).toBe(400);});
test('independent profile changes do not invalidate a block review',async()=>{await block();const current=await list();await User.updateOne({_id:owner._id},{$set:{lawFirm:'New independent firm','preferences.theme':'dark'}});const result=await remove(current.body.items?.[0]?.revision);expect(result.status).toBe(200);const saved=await User.findById(owner._id);expect(saved.lawFirm).toBe('New independent firm');expect(saved.preferences.theme).toBe('dark');});
test('revoked managed sessions cannot list or remove block records',async()=>{await block();const sid='blocks-managed-fixture';await AuthSession.create({userId:owner._id,sessionId:sid,expiresAt:new Date(Date.now()+60000),revokedAt:new Date()});cookie=token(owner,sid);expect((await list()).status).toBe(403);expect((await remove('a'.repeat(64))).status).toBe(403);expect(await Block.countDocuments({active:true})).toBe(1);});

test('legacy deactivate/reactivate increments the existing version even if timestamps match',async()=>{const saved=await block();const {deactivateBlock,createOrActivateBlock}=require('../utils/blocks');await deactivateBlock({blockerId:owner._id,blockedId:target._id});await createOrActivateBlock({blockerId:owner._id,blockedId:target._id,blockerRole:'attorney',blockedRole:'paralegal',reason:saved.reason});await Block.collection.updateOne({_id:saved._id},{$set:{updatedAt:saved.updatedAt}});const current=await Block.findById(saved._id);expect(current.__v).toBeGreaterThan(saved.__v);expect(current.active).toBe(true);});
test('a changed block between read and write cannot be removed by a stale request',async()=>{const saved=await block();const current=await list();const update=Block.collection.updateOne.bind(Block.collection);jest.spyOn(Block.collection,'updateOne').mockImplementationOnce(async(...args)=>{await update({_id:saved._id},{$inc:{__v:1}});return update(...args);});const result=await remove(current.body.items[0].revision);expect(result.status).toBe(409);expect(await Block.countDocuments({active:true})).toBe(1);});
test('session loss between authentication and the guarded transaction prevents unblocking',async()=>{await block();const sid='blocks-race-session';const managed=await AuthSession.create({userId:owner._id,sessionId:sid,expiresAt:new Date(Date.now()+60000)});cookie=token(owner,sid);const current=await list();const update=AuthSession.updateOne.bind(AuthSession);jest.spyOn(AuthSession,'updateOne').mockImplementationOnce(async(...args)=>{await AuthSession.collection.updateOne({_id:managed._id},{$set:{revokedAt:new Date()}});return update(...args);});const result=await remove(current.body.items[0].revision);expect(result.status).toBe(403);expect(result.body.code).toBe('ACCOUNT_CHANGED');expect(await Block.countDocuments({active:true})).toBe(1);});
test('account deactivation after authentication cannot commit an unblock',async()=>{await block();const current=await list();const update=User.collection.updateOne.bind(User.collection);jest.spyOn(User.collection,'updateOne').mockImplementationOnce(async(...args)=>{await update({_id:owner._id},{$set:{disabled:true}});return update(...args);});const result=await remove(current.body.items[0].revision);expect(result.status).toBe(403);expect(await Block.countDocuments({active:true})).toBe(1);});
test('status read is private and rejects mismatched owner before projecting a block',async()=>{await block();const result=await request(app).get(`/api/blocks/${targetId()}`).query({expectedOwnerId:String(other._id)}).set('Cookie',cookie);expect(result.status).toBe(403);expect(result.headers['cache-control']).toMatch(/private.*no-store/);expect(result.body.blocked).toBeUndefined();});
test('paralegal guarded list and unblocking use the same direct-owner boundary',async()=>{const original=owner;owner=target;target=original;cookie=token(owner);await block({blockerRole:'paralegal',blockedRole:'attorney'});const current=await list();expect(current.body.items[0].role).toBe('attorney');expect((await remove(current.body.items[0].revision)).status).toBe(200);expect((await status()).body.blocked).toBe(false);});
test('malformed dotted owner cannot fall through to a legacy unblock',async()=>{await block();const result=await request(app).delete(`/api/blocks/${targetId()}`).set('Cookie',cookie).send({'expectedOwnerId.foo':String(other._id)});expect(result.status).toBe(400);expect(await Block.countDocuments({active:true})).toBe(1);});
test('an array revision is invalid input rather than a coerced conflict',async()=>{await block();const current=await list();const result=await remove([current.body.items[0].revision]);expect(result.status).toBe(400);expect(result.body.code).toBe('ACCOUNT_GUARD_INVALID');expect(await Block.countDocuments({active:true})).toBe(1);});
test('a malformed revision key cannot fall through to a legacy unblock',async()=>{await block();const result=await request(app).delete(`/api/blocks/${targetId()}`).set('Cookie',cookie).send({'expectedBlockRevision.foo':'a'.repeat(64)});expect(result.status).toBe(400);expect(await Block.countDocuments({active:true})).toBe(1);});
