const path=require('path');
const {execFileSync}=require('child_process');
const {pathToFileURL}=require('url');
const moduleUrl=pathToFileURL(path.resolve(__dirname,'../../frontend/assets/scripts/paralegal-v2/closure-api.mjs')).href;
const storageUrl=pathToFileURL(path.resolve(__dirname,'../../frontend/assets/scripts/utils/account-closure-state.mjs')).href;
function check(source){execFileSync(process.execPath,['--input-type=module','--eval',`import assert from 'node:assert/strict';import {createClosureApi,closureReview,closureResult} from ${JSON.stringify(moduleUrl)};import {readClosureProof,storeClosureProof,clearClosureProof} from ${JSON.stringify(storageUrl)};const owner='a'.repeat(24),other='b'.repeat(24),revision='a'.repeat(64),proof='YWJj.'+'b'.repeat(64),review={ownerId:owner,canDeactivate:true,blockers:[],closureRevision:revision,resultProof:proof,proofExpiresAt:new Date(Date.now()+600000).toISOString()};const json=(value,status=200)=>new Response(JSON.stringify(value),{status});const identity=id=>json({user:{id:id||owner,role:'paralegal',status:'approved'}});${source}`],{stdio:'pipe'});}
test('review validates exact owner, blockers and capability without accepting false eligibility',()=>check(`assert.deepEqual(closureReview({...review,email:'private'},owner),review);for(const value of [{...review,ownerId:other},{...review,blockers:[{code:'active_matters',message:'Resolve active work.',count:1}]},{...review,closureRevision:[]},{...review,resultProof:'invalid'},{...review,canDeactivate:false,blockers:[]},{...review,canDeactivate:false,blockers:[{code:'invented_policy',message:'No.',count:1}]}])assert.throws(()=>closureReview(value,owner));`));
test('deactivation pins owner reviewed revision and proof with CSRF and no invalid post-logout authentication',()=>check(`const calls=[];const api=createClosureApi({fetchImpl:async(path,opts)=>{calls.push({path,...opts});return path==='/api/auth/me'?identity():path==='/api/csrf'?json({csrfToken:'fixture'}):json({ok:true,deactivated:true});}});assert.deepEqual(await api.deactivate(review,{ownerId:owner}),{ok:true,deactivated:true});assert.equal(calls.length,3);assert.deepEqual(JSON.parse(calls[2].body),{expectedOwnerId:owner,expectedClosureRevision:revision,resultProof:proof});assert.equal(calls[2].headers['X-CSRF-Token'],'fixture');assert.equal(calls[2].cache,'no-store');assert.equal(calls[2].redirect,'error');`));
test('unknown response remains uncertain and never replays deletion',()=>check(`for(const mode of ['network','503','empty','false']){let writes=0;const api=createClosureApi({fetchImpl:async(path)=>{if(path==='/api/auth/me')return identity();if(path==='/api/csrf')return json({csrfToken:'fixture'});writes++;if(mode==='network')throw new Error('offline');return json(mode==='false'?{ok:true,deactivated:false}:{},mode==='503'?503:200);}});await assert.rejects(api.deactivate(review,{ownerId:owner}),e=>e.kind==='uncertain');assert.equal(writes,1);}`));
test('replacement on either review boundary rejects protected data and prevents a mutation before review',()=>check(`let reads=0,lost=0;const api=createClosureApi({onAuthenticationLost:()=>lost++,fetchImpl:async(path)=>path==='/api/auth/me'?identity(++reads===1?owner:other):json(review)});await assert.rejects(api.readReview({ownerId:owner}),e=>e.kind==='authentication');assert.equal(lost,1);await assert.rejects(api.deactivate(review,{ownerId:owner}),e=>e.kind==='authentication');assert.equal(reads,3);`));
test('result check is read only and keeps proof out of URLs, with only current state projected',()=>check(`const calls=[];const api=createClosureApi({fetchImpl:async(path,opts)=>{calls.push({path,...opts});return json({state:'deactivated',email:'private'});}});assert.deepEqual(await api.readResult(proof),{state:'deactivated'});assert.equal(calls.length,1);assert.equal(calls[0].method,'GET');assert.equal(calls[0].path,'/api/account/deactivate-result');assert.equal(calls[0].headers['X-LPC-Closure-Proof'],proof);assert.equal(calls[0].body,undefined);for(const value of [{},{state:true},{state:'completed'},null])assert.throws(()=>closureResult(value));`));
test('proof expiry invalid proof account replacement and transient errors have distinct result contracts',()=>check(`for(const [status,code,kind] of [[410,'ACCOUNT_CLOSURE_PROOF_EXPIRED','expired'],[400,'ACCOUNT_CLOSURE_PROOF_INVALID','invalid_proof'],[403,'ACCOUNT_CHANGED','authentication'],[503,'','request']]){const api=createClosureApi({fetchImpl:async()=>json({code},status)});await assert.rejects(api.readResult(proof),e=>e.kind===kind);}`));
test('cleared request cannot install a late review even when transport ignores abort',()=>check(`let release;const api=createClosureApi({fetchImpl:async path=>path==='/api/auth/me'?identity():new Promise(resolve=>release=resolve)});const pending=api.readReview({ownerId:owner});while(!release)await new Promise(r=>setTimeout(r,0));api.clear();release(json(review));await assert.rejects(pending,e=>e.name==='AbortError');`));
test('tab storage contains only valid capability and refuses unavailable retention',()=>check(`const values=new Map();const storage={getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};storeClosureProof(proof,storage);assert.equal(values.size,1);assert.equal(readClosureProof(storage),proof);clearClosureProof(storage);assert.equal(values.size,0);storage.setItem('lpc_account_closure_result','invalid');assert.equal(readClosureProof(storage),null);assert.equal(values.size,0);assert.throws(()=>storeClosureProof(proof,{setItem(){},getItem(){return null}}));assert.equal(readClosureProof({getItem(){throw new Error('denied')}}),null);`));
test('preflight failures never retain a pending capability or claim dispatch',()=>check(`for(const mode of ['identity','csrf','storage']){let dispatches=0,writes=0;const api=createClosureApi({fetchImpl:async(path)=>{if(path==='/api/auth/me')return mode==='identity'?json({},503):identity();if(path==='/api/csrf')return mode==='csrf'?json({},503):json({csrfToken:'fixture'});writes++;return json({ok:true,deactivated:true});}});await assert.rejects(api.deactivate(review,{ownerId:owner,beforeDispatch(){dispatches++;if(mode==='storage')throw new Error('denied');}}),e=>e.dispatched===false);assert.equal(writes,0);assert.equal(dispatches,mode==='storage'?1:0);}`));

test('protected paralegal closure calls reject wrong role unapproved disabled and missing identities before DELETE',()=>check(`for(const user of [{id:owner,role:'attorney',status:'approved'},{id:owner,role:'paralegal',status:'pending'},{id:owner,role:'paralegal',status:'approved',disabled:true},{id:owner,role:'paralegal',status:'approved',deleted:true},null]){let writes=0;const api=createClosureApi({fetchImpl:async(path,opts)=>{if(opts.method==='DELETE')writes++;return json({user});}});await assert.rejects(api.deactivate(review,{ownerId:owner}),error=>error.kind==='authentication'&&error.dispatched===false);assert.equal(writes,0);}`));
