const express=require('express'),cookieParser=require('cookie-parser'),jwt=require('jsonwebtoken'),request=require('supertest');
process.env.S3_BUCKET='personal-document-test';process.env.S3_REGION='us-east-1';process.env.S3_MALWARE_SCAN_REQUIRED='true';
const mockSend=jest.fn(),mockSigned=jest.fn(async()=> 'https://synthetic.invalid/document.pdf');
jest.mock('../utils/s3Client',()=>({createS3Client:()=>({send:mockSend})}));
jest.mock('@aws-sdk/s3-request-presigner',()=>({getSignedUrl:(...args)=>mockSigned(...args)}));
jest.mock('../utils/email',()=>jest.fn(async()=>({ok:true})));
const User=require('../models/User'),Application=require('../models/Application'),Case=require('../models/Case'),StorageDeletionTask=require('../models/StorageDeletionTask');
const {connect,clearDatabase,closeDatabase}=require('./helpers/db');
const app=express();app.use(cookieParser(),express.json());app.use('/api/users',require('../routes/users'));app.use('/api/uploads',require('../routes/uploads'));app.use((error,_req,res,_next)=>res.status(500).json({error:error.message}));
const types=[['resumeURL','paralegal-resume','paralegal-resumes','resume'],['certificateURL','paralegal-certificate','paralegal-certificates','certificate'],['writingSampleURL','paralegal-writing-sample','paralegal-writing-samples','writing-sample']];
const bytes=Buffer.from('%PDF-1.7\nSynthetic private profile document\n%%EOF\n');
const cookie=user=>`token=${jwt.sign({id:String(user._id),role:user.role,status:user.status,email:user.email},process.env.JWT_SECRET,{expiresIn:'1h'})}`;
let owner,other,attorney,oldKey;
const upload=(type=types[0],expectedKey=oldKey,actor=owner,expectedOwner=String(owner._id))=>request(app).post(`/api/uploads/${type[1]}`).set('Cookie',cookie(actor)).field('expectedOwnerId',expectedOwner).field('expectedDocumentKey',expectedKey).attach('file',bytes,{filename:'document.pdf',contentType:'application/pdf'});
const clear=(type=types[0],expectedKey=oldKey)=>request(app).patch('/api/users/me').set('Cookie',cookie(owner)).send({expectedOwnerId:String(owner._id),expectedValues:{[type[0]]:expectedKey},[type[0]]:''});
const view=(path='view',actor=owner,key=oldKey,expectedOwner=String(actor._id))=>request(app).get(`/api/uploads/${path}`).query({key,expectedOwnerId:expectedOwner}).set('Cookie',cookie(actor));
beforeAll(connect,90000);afterAll(closeDatabase);afterEach(()=>jest.restoreAllMocks());
beforeEach(async()=>{await clearDatabase();mockSend.mockReset().mockImplementation(async command=>command.constructor.name==='GetObjectTaggingCommand'?{TagSet:[{Key:'GuardDutyMalwareScanStatus',Value:'NO_THREATS_FOUND'}]}:{});mockSigned.mockClear();[owner,other,attorney]=await User.create(['owner','other','attorney'].map(name=>({firstName:'Dana',lastName:name,email:`doc-${name}@example.test`,password:'Password123!',role:name==='attorney'?'attorney':'paralegal',status:'approved',bio:'Profile biography',skills:['Research'],practiceAreas:['Litigation'],profilePhotoStatus:'approved',profileImage:'existing',preferences:{hideProfile:false}})));oldKey=`paralegal-resumes/${owner._id}/resume-1700000000000.pdf`;await User.updateOne({_id:owner._id},{$set:{resumeURL:oldKey}});});
test.each(types)('%s upload rejects a replaced account before storage access',async(...type)=>{const result=await upload(type,'',other,String(owner._id));expect(result.status).toBe(403);expect(result.body.code).toBe('ACCOUNT_CHANGED');expect(mockSend).not.toHaveBeenCalled();});
test.each(types)('%s upload rejects an obsolete document snapshot',async(...type)=>{const current=`${type[2]}/${owner._id}/${type[3]}-1700000000001.pdf`;await User.updateOne({_id:owner._id},{$set:{[type[0]]:current}});const result=await upload(type,'');expect(result.status).toBe(409);expect(mockSend).not.toHaveBeenCalled();expect((await User.findById(owner._id))[type[0]]).toBe(current);});
test('upload cannot restore a document removed while storage is pending',async()=>{let release,entered;const started=new Promise(r=>entered=r),gate=new Promise(r=>release=r);mockSend.mockImplementationOnce(async()=>{entered();await gate;return {};});const pending=upload().then(r=>r);await started;try{expect((await clear()).status).toBe(200);}finally{release();}expect((await pending).status).toBe(409);expect((await User.findById(owner._id)).resumeURL).toBe('');expect(await StorageDeletionTask.countDocuments({reason:'resume_replaced_upload_compensation',status:'pending'})).toBe(1);});
test('atomic document comparison refuses a concurrent replacement',async()=>{const update=User.collection.updateOne.bind(User.collection),next=`paralegal-resumes/${owner._id}/resume-1700000000002.pdf`;jest.spyOn(User.collection,'updateOne').mockImplementationOnce(async(...args)=>{await update({_id:owner._id},{$set:{resumeURL:next}});return update(...args);});expect((await upload()).status).toBe(409);expect((await User.findById(owner._id)).resumeURL).toBe(next);});
test('independent document replacement merges with profile edits',async()=>{const update=User.collection.updateOne.bind(User.collection);jest.spyOn(User.collection,'updateOne').mockImplementationOnce(async(...args)=>{await update({_id:owner._id},{$set:{bio:'Concurrent biography',certificateURL:`paralegal-certificates/${owner._id}/certificate-1700000000002.pdf`}});return update(...args);});const result=await upload();expect(result.status).toBe(200);const current=await User.findById(owner._id);expect(current.bio).toBe('Concurrent biography');expect(current.certificateURL).toContain('/certificate-1700000000002.pdf');expect(current.resumeURL).toBe(result.body.url);});
test.each(['view','download','signed-get'])('%s rejects stale cookie identity before signing or storage',async path=>{const result=await view(path,attorney,oldKey,String(owner._id));expect(result.status).toBe(403);expect(result.body.code).toBe('ACCOUNT_CHANGED');expect(mockSend).not.toHaveBeenCalled();expect(mockSigned).not.toHaveBeenCalled();});
test.each([['',423],['THREATS_FOUND',422],['FAILED',503]])('scan %s prevents document delivery',async(scan,status)=>{mockSend.mockImplementation(async command=>command.constructor.name==='GetObjectTaggingCommand'?{TagSet:[{Key:'GuardDutyMalwareScanStatus',Value:scan}]}:{});expect((await view()).status).toBe(status);expect(mockSigned).not.toHaveBeenCalled();});
test('existing owner and eligible attorney can view current documents, another paralegal cannot',async()=>{expect((await view()).status).toBe(302);expect((await view('download',attorney)).status).toBe(200);expect((await view('view',other)).status).toBe(403);});
test('stale removal rejects the changed current document without queuing its deletion',async()=>{const next=`paralegal-resumes/${owner._id}/resume-1700000000003.pdf`;await User.updateOne({_id:owner._id},{$set:{resumeURL:next}});expect((await clear()).status).toBe(409);expect((await User.findById(owner._id)).resumeURL).toBe(next);expect(await StorageDeletionTask.countDocuments()).toBe(0);});

test.each(types)('%s current document reads reject a replaced key',async(...type)=>{
 const original=`${type[2]}/${owner._id}/${type[3]}-1700000000000.pdf`,next=`${type[2]}/${owner._id}/${type[3]}-1700000000001.pdf`;await User.updateOne({_id:owner._id},{$set:{[type[0]]:next}});
 const result=await request(app).get('/api/uploads/download').query({key:original,expectedOwnerId:String(owner._id),documentField:type[0],expectedDocumentKey:original}).set('Cookie',cookie(owner));expect(result.status).toBe(409);expect(mockSend).not.toHaveBeenCalled();expect(mockSigned).not.toHaveBeenCalled();
});
test('document replaced during scanning never receives a usable current-owner link',async()=>{
 const next=`paralegal-resumes/${owner._id}/resume-1700000000004.pdf`;mockSend.mockImplementation(async command=>{if(command.constructor.name==='GetObjectTaggingCommand'){await User.updateOne({_id:owner._id},{$set:{resumeURL:next}});return {TagSet:[{Key:'GuardDutyMalwareScanStatus',Value:'NO_THREATS_FOUND'}]};}return {};});
 const result=await request(app).get('/api/uploads/download').query({key:oldKey,expectedOwnerId:String(owner._id),documentField:'resumeURL',expectedDocumentKey:oldKey}).set('Cookie',cookie(owner));expect(result.status).toBe(409);expect(result.body.url).toBeUndefined();
});
test('removed or superseded unreferenced keys are unavailable even while cleanup is pending',async()=>{await User.updateOne({_id:owner._id},{$set:{resumeURL:''}});for(const actor of [owner,attorney,other])expect((await view('download',actor)).status).toBe(403);expect(mockSend).not.toHaveBeenCalled();});
test('recorded historical résumé access follows actual Matter ownership and canonical selection',async()=>{
 const {Types}=require('mongoose'),jobId=new Types.ObjectId(),caseId=new Types.ObjectId(),next=`paralegal-resumes/${owner._id}/current.pdf`;
 await require('../models/Job').collection.insertOne({_id:jobId,caseId,attorneyId:attorney._id});await Case.collection.insertOne({_id:caseId,attorneyId:attorney._id,attorney:attorney._id,jobId,status:'completed',applicants:[{paralegalId:owner._id,resumeURL:oldKey,status:'rejected'}]});await Application.collection.insertOne({jobId,paralegalId:owner._id,resumeURL:`https://personal-document-test.s3.us-east-1.amazonaws.com/${oldKey}`,status:'withdrawn'});await User.updateOne({_id:owner._id},{$set:{resumeURL:next,'preferences.hideProfile':true}});
 expect((await view('download',attorney)).status).toBe(200);expect((await view()).status).toBe(302);
 const unrelated=await User.create({firstName:'Other',lastName:'Attorney',email:'unrelated-doc@example.test',password:'Password123!',role:'attorney',status:'approved'});expect((await view('download',unrelated)).status).toBe(403);
 await Application.updateMany({jobId},{$set:{resumeURL:next}});expect((await view('download',attorney)).status).toBe(403);
 await Application.deleteMany({jobId});expect((await view('download',attorney)).status).toBe(200);
});
test('a guarded attachment request keeps its fixed filename and short signed-link lifetime',async()=>{const result=await request(app).get('/api/uploads/download').query({key:oldKey,expectedOwnerId:String(owner._id),documentField:'resumeURL',expectedDocumentKey:oldKey,download:'true'}).set('Cookie',cookie(owner));expect(result.status).toBe(200);expect(mockSigned.mock.calls[0][1].input.ResponseContentDisposition).toBe('attachment; filename="Resume.pdf"');expect(mockSigned.mock.calls[0][2]).toMatchObject({expiresIn:60});expect(result.headers['cache-control']).toBe('private, no-store');});
