const fs = require("fs");
const path = require("path");
const {
  PRODUCTION_ORIGIN,
  NOT_FOUND_ROUTE,
  SURFACES,
  sha256,
  validateCandidateManifest,
  verifyProductionSurface,
  writeEvidence,
} = require("../scripts/verify-production-surface");
const { REQUIRED_CANDIDATE_FILES } = require("../scripts/check-release-candidate");
const { collectInlineScriptHashes } = require("../utils/contentSecurityPolicy");

const repositoryRoot = path.resolve(__dirname, "../..");
const COMMIT = "b".repeat(40);
const inlineScriptHashes = collectInlineScriptHashes(path.join(repositoryRoot, "frontend"));
const CSP = [
  "default-src 'self'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'self'",
  "object-src 'none'",
  `script-src 'self' ${inlineScriptHashes.join(" ")} https://js.stripe.com https://challenges.cloudflare.com`,
  "script-src-attr 'none'",
  "upgrade-insecure-requests",
].join("; ");

function candidateForCurrentFiles() {
  return {
    schemaVersion: 1,
    generatedAt: "2026-08-15T12:00:00.000Z",
    commit: COMMIT,
    files: Object.fromEntries(
      REQUIRED_CANDIDATE_FILES.map((candidateFile) => [
        candidateFile,
        sha256(fs.readFileSync(path.join(repositoryRoot, candidateFile))),
      ])
    ),
  };
}

function response(body, { status = 200, headers = {} } = {}) {
  const buffer = Buffer.isBuffer(body) ? body : Buffer.from(String(body), "utf8");
  return {
    status,
    headers: new Headers(headers),
    async arrayBuffer() {
      return buffer;
    },
  };
}

function successfulFetch(candidate, overrides = {}) {
  return jest.fn(async (url) => {
    const route = new URL(url).pathname;
    if (overrides[route]) return overrides[route];
    const common = { "X-LPC-Release-Commit": candidate.commit };
    if (route === "/api/health") {
      return response(JSON.stringify({ ok: true, db: "connected" }), {
        headers: {
          ...common,
          "Content-Type": "application/json; charset=utf-8",
          "Cache-Control": "no-store",
        },
      });
    }
    if (route === NOT_FOUND_ROUTE) {
      return response(fs.readFileSync(path.join(repositoryRoot, "frontend/404.html")), {
        status: 404,
        headers: {
          ...common,
          "Content-Type": "text/html; charset=utf-8",
          "Cache-Control": "no-store",
          "X-Robots-Tag": "noindex, nofollow",
        },
      });
    }
    const surface = SURFACES.find((entry) => entry.route === route);
    const body = fs.readFileSync(path.join(repositoryRoot, surface.candidateFile));
    const isHtml = surface.candidateFile.endsWith(".html");
    const contentType = surface.route === "/robots.txt"
      ? "text/plain; charset=utf-8"
      : surface.route === "/sitemap.xml"
        ? "application/xml"
        : "text/html; charset=utf-8";
    return response(body, {
      headers: {
        ...common,
        "Content-Type": contentType,
        "Cache-Control": isHtml ? "no-store" : "public, max-age=0, must-revalidate",
        ...(surface.canonical ? { Link: `<${surface.canonical}>; rel="canonical"` } : {}),
        ...(route === "/" ? {
          "Content-Security-Policy": CSP,
          "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
          "Cross-Origin-Opener-Policy": "same-origin",
          "Cross-Origin-Resource-Policy": "same-origin",
          "Origin-Agent-Cluster": "?1",
          "Referrer-Policy": "no-referrer",
          "X-Content-Type-Options": "nosniff",
          "X-Frame-Options": "SAMEORIGIN",
        } : {}),
      },
    });
  });
}

describe("production surface verification", () => {
  test("binds the public origin, legal pages, discovery files, headers, and health to one candidate", async () => {
    const candidate = candidateForCurrentFiles();
    expect(validateCandidateManifest(candidate, {
      expectedCommit: COMMIT,
      workingTreeStatus: "",
    })).toMatchObject({ commit: COMMIT });
    const fetchFn = successfulFetch(candidate);
    const evidence = await verifyProductionSurface({
      candidate,
      fetchFn,
      now: () => new Date("2026-08-15T13:00:00.000Z"),
    });

    expect(evidence).toMatchObject({
      schemaVersion: 1,
      verifiedAt: "2026-08-15T13:00:00.000Z",
      origin: PRODUCTION_ORIGIN,
      commit: COMMIT,
      health: { ok: true, db: "connected" },
    });
    expect(Object.keys(evidence.surfaces)).toEqual(SURFACES.map(({ route }) => route));
    expect(evidence.notFound).toMatchObject({ status: 404, candidateFile: "frontend/404.html" });
    expect(fetchFn).toHaveBeenCalledTimes(SURFACES.length + 2);
  });

  test("rejects post-deploy evidence generated by a dirty checkout", () => {
    const candidate = candidateForCurrentFiles();
    expect(() => validateCandidateManifest(candidate, {
      expectedCommit: COMMIT,
      workingTreeStatus: " M backend/index.js",
    })).toThrow(/clean checkout/);
  });

  test("rejects a stale deploy even when health is green", async () => {
    const candidate = candidateForCurrentFiles();
    const staleCommit = "c".repeat(40);
    const fetchFn = successfulFetch(candidate, {
      "/api/health": response(JSON.stringify({ ok: true, db: "connected" }), {
        headers: {
          "X-LPC-Release-Commit": staleCommit,
          "Content-Type": "application/json",
          "Cache-Control": "no-store",
        },
      }),
    });
    await expect(verifyProductionSurface({ candidate, fetchFn })).rejects.toThrow(/reports release/);
  });

  test("rejects homepage fallbacks for robots and sitemap by byte hash", async () => {
    const candidate = candidateForCurrentFiles();
    const homepage = fs.readFileSync(path.join(repositoryRoot, "frontend/index.html"));
    const fetchFn = successfulFetch(candidate, {
      "/robots.txt": response(homepage, {
        headers: {
          "X-LPC-Release-Commit": COMMIT,
          "Content-Type": "text/plain; charset=utf-8",
          "Cache-Control": "public, max-age=0, must-revalidate",
        },
      }),
    });
    await expect(verifyProductionSurface({ candidate, fetchFn })).rejects.toThrow(/does not match candidate/);
  });

  test("rejects a stale legal document even when its route and content type look valid", async () => {
    const candidate = candidateForCurrentFiles();
    const fetchFn = successfulFetch(candidate, {
      "/terms.html": response("<html>older terms</html>", {
        headers: {
          "X-LPC-Release-Commit": COMMIT,
          "Content-Type": "text/html; charset=utf-8",
          "Cache-Control": "no-store",
          Link: '<https://www.lets-paraconnect.com/terms.html>; rel="canonical"',
        },
      }),
    });
    await expect(verifyProductionSurface({ candidate, fetchFn })).rejects.toThrow(/terms\.html SHA-256/);
  });

  test("rejects a weakened production script policy", async () => {
    const candidate = candidateForCurrentFiles();
    const homepage = fs.readFileSync(path.join(repositoryRoot, "frontend/index.html"));
    const fetchFn = successfulFetch(candidate, {
      "/": response(homepage, {
        headers: {
          "X-LPC-Release-Commit": COMMIT,
          "Content-Type": "text/html; charset=utf-8",
          "Cache-Control": "no-store",
          Link: '<https://www.lets-paraconnect.com/>; rel="canonical"',
          "Content-Security-Policy": CSP.replace(
            " https://js.stripe.com",
            " https://cdn.jsdelivr.net 'unsafe-inline' https://js.stripe.com"
          ),
          "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
          "Cross-Origin-Opener-Policy": "same-origin",
          "Cross-Origin-Resource-Policy": "same-origin",
          "Origin-Agent-Cluster": "?1",
          "Referrer-Policy": "no-referrer",
          "X-Content-Type-Options": "nosniff",
          "X-Frame-Options": "SAMEORIGIN",
        },
      }),
    });
    await expect(verifyProductionSurface({ candidate, fetchFn })).rejects.toThrow(/script-src must be exactly/);
  });

  test("rejects missing modern cross-origin isolation headers", async () => {
    const candidate = candidateForCurrentFiles();
    const homepage = fs.readFileSync(path.join(repositoryRoot, "frontend/index.html"));
    const fetchFn = successfulFetch(candidate, {
      "/": response(homepage, {
        headers: {
          "X-LPC-Release-Commit": COMMIT,
          "Content-Type": "text/html; charset=utf-8",
          "Cache-Control": "no-store",
          Link: '<https://www.lets-paraconnect.com/>; rel="canonical"',
          "Content-Security-Policy": CSP,
          "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
          "Referrer-Policy": "no-referrer",
          "X-Content-Type-Options": "nosniff",
          "X-Frame-Options": "SAMEORIGIN",
        },
      }),
    });
    await expect(verifyProductionSurface({ candidate, fetchFn })).rejects.toThrow(
      /cross-origin-opener-policy must be same-origin, received missing/i
    );
  });

  test("rejects ambiguous duplicate CSP directives", async () => {
    const candidate = candidateForCurrentFiles();
    const homepage = fs.readFileSync(path.join(repositoryRoot, "frontend/index.html"));
    const fetchFn = successfulFetch(candidate, {
      "/": response(homepage, {
        headers: {
          "X-LPC-Release-Commit": COMMIT,
          "Content-Type": "text/html; charset=utf-8",
          "Cache-Control": "no-store",
          Link: '<https://www.lets-paraconnect.com/>; rel="canonical"',
          "Content-Security-Policy": `${CSP}; script-src *`,
          "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
          "Cross-Origin-Opener-Policy": "same-origin",
          "Cross-Origin-Resource-Policy": "same-origin",
          "Origin-Agent-Cluster": "?1",
          "Referrer-Policy": "no-referrer",
          "X-Content-Type-Options": "nosniff",
          "X-Frame-Options": "SAMEORIGIN",
        },
      }),
    });
    await expect(verifyProductionSurface({ candidate, fetchFn })).rejects.toThrow(
      /repeats script-src; duplicate directives are ambiguous/i
    );
  });

  test("writes successful production evidence atomically with owner-only permissions", () => {
    const outputPath = path.resolve(
      __dirname,
      `../test-results/release/production-surface-test-${process.pid}.json`
    );
    try {
      expect(writeEvidence({ schemaVersion: 1 }, outputPath)).toBe(outputPath);
      expect(fs.statSync(outputPath).mode & 0o777).toBe(0o600);
      expect(JSON.parse(fs.readFileSync(outputPath, "utf8"))).toEqual({ schemaVersion: 1 });
    } finally {
      fs.rmSync(outputPath, { force: true });
    }
  });
});
