const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { pathToFileURL } = require('node:url');
const moduleUrl = pathToFileURL(path.resolve(__dirname, '../../frontend/assets/scripts/utils/support-transport.mjs')).href;
function check(source) {
  execFileSync(process.execPath, ['--input-type=module', '--eval', `import assert from 'node:assert/strict'; import {createSupportTransport,SupportError,SUPPORT_MUTATION_TIMEOUT_MS} from ${JSON.stringify(moduleUrl)}; const ownerId='a'.repeat(24),role='attorney',other='b'.repeat(24),conv='c'.repeat(24),opts={ownerId,role}; const reply=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}}); const session=(extra={})=>reply({user:{id:ownerId,role,status:'approved',...extra}}); const csrf=()=>reply({csrfToken:'synthetic-csrf'}); ${source}`], { stdio: 'pipe', timeout: 10000 });
}
test('reads bind the expected owner and role, verify twice, and preserve the existing users/me contract', () => check(`
 for(const path of ['/api/support/conversation?caseId='+conv,'/api/users/me']){const calls=[];const api=createSupportTransport({fetchImpl:async(url,options)=>{calls.push({url,options});return url==='/api/auth/me'?session():reply({ok:true});}});const result=await api.request(path,opts);assert.equal(result.ok,true);assert.deepEqual(await result.json(),{ok:true});assert.equal(calls.length,3);const u=new URL(calls[1].url,'https://lpc.test');assert.equal(u.searchParams.get('expectedOwnerId'),ownerId);assert.equal(u.searchParams.get('expectedRole'),path==='/api/users/me'?null:role);assert.equal(calls[1].options.credentials,'include');assert.equal(calls[1].options.cache,'no-store');assert.equal(calls[1].options.redirect,'error');}
 const api=createSupportTransport();const events=new URL(api.boundEventsUrl('/api/support/conversation/'+conv+'/events',opts),'https://lpc.test');assert.equal(events.searchParams.get('expectedOwnerId'),ownerId);assert.equal(events.searchParams.get('expectedRole'),role);assert.throws(()=>api.boundEventsUrl('https://foreign.test/events',opts));
`));
test('writes acquire CSRF, bind a copied body and never use implicit session refresh or replay', () => check(`
 const calls=[],body={text:'A private question'};const api=createSupportTransport({fetchImpl:async(url,options)=>{calls.push({url,options});return url==='/api/auth/me'?session():url==='/api/csrf'?csrf():reply({ok:true},201);}});const result=await api.request('/api/support/conversation/'+conv+'/messages',{...opts,method:'POST',body});assert.equal(result.status,201);assert.equal(calls.length,4);assert.deepEqual(body,{text:'A private question'});assert.deepEqual(JSON.parse(calls[2].options.body),{...body,expectedOwnerId:ownerId,expectedRole:role});assert.equal(calls[2].options.headers.get('x-csrf-token'),'synthetic-csrf');assert.equal(calls[2].options.headers.get('content-type'),'application/json');
`));
test('verified owner role and access loss before dispatch invokes one callback and sends nothing', () => check(`
 for(const extra of [{id:other},{role:'paralegal'},{status:'pending'},{disabled:true},{deleted:true}]){let calls=0,lost=0;const api=createSupportTransport({onAuthenticationLost:()=>lost++,fetchImpl:async()=>{calls++;return session(extra);}});await assert.rejects(api.request('/api/support/conversation',{...opts,method:'POST',body:{}}),e=>e.kind==='authentication'&&!e.dispatched);assert.equal(calls,1);assert.equal(lost,1);}
`));
test('unavailable and incomplete preflight responses preserve identity and do not dispatch', () => check(`
 for(const response of [()=>reply({},503),()=>reply({user:{id:ownerId}}),()=>reply({user:{id:ownerId,_id:other,role,status:'approved'}}),()=>{throw new Error('offline');}]){let calls=0,lost=0;const api=createSupportTransport({onAuthenticationLost:()=>lost++,fetchImpl:async()=>{calls++;return response();}});await assert.rejects(api.request('/api/support/conversation',{...opts,method:'POST',body:{}}),e=>e.kind==='unavailable'&&!e.dispatched);assert.equal(calls,1);assert.equal(lost,0);}
`));
test('every successful read message feedback and reset response checks the authoritative account after JSON', () => check(`
 for(const [path,method] of [['/api/support/conversation','GET'],['/api/support/conversation/'+conv+'/messages','POST'],['/api/support/conversation/'+conv+'/messages/'+conv+'/feedback','POST'],['/api/auth/request-password-reset','POST']]){let endpointCalls=0,lost=0;const api=createSupportTransport({onAuthenticationLost:()=>lost++,fetchImpl:async(url)=>url==='/api/auth/me'?session(endpointCalls?{id:other}:{}):url==='/api/csrf'?csrf():(endpointCalls++,reply({ok:true}))});await assert.rejects(api.request(path,{...opts,method,body:{email:'synthetic@example.test'}}),e=>e.kind==='authentication');assert.equal(endpointCalls,1);assert.equal(lost,1);}
`));
test('rejected malformed and lost requests recheck identity before presenting an error', () => check(`
 for(const method of ['GET','POST'])for(const outcome of [400,404,500,'malformed','lost']){let requested=0,lost=0;const api=createSupportTransport({onAuthenticationLost:()=>lost++,fetchImpl:async(url)=>{if(url==='/api/auth/me')return session(requested?{id:other}:{});if(url==='/api/csrf')return csrf();requested++;if(outcome==='lost')throw new Error('lost response');return outcome==='malformed'?new Response('not json'):reply({error:'refused'},outcome);}});await assert.rejects(api.request('/api/support/conversation',{...opts,method,body:{}}),e=>e.kind==='authentication');assert.equal(requested,1);assert.equal(lost,1);}
`));
test('same-owner known HTTP rejections keep their status without automatic replay', () => check(`
 for(const status of [400,403,404,409]){let requested=0;const api=createSupportTransport({fetchImpl:async(url)=>url==='/api/auth/me'?session():url==='/api/csrf'?csrf():(requested++,reply({error:'Refused',code:status===403?'CSRF_INVALID':'REJECTED'},status))});const result=await api.request('/api/support/conversation',{...opts,method:'POST',body:{}});assert.equal(result.ok,false);assert.equal(result.status,status);assert.equal((await result.json()).error,'Refused');assert.equal(requested,1);}
`));
test('same-owner 5xx malformed or lost writes stay uncertain and are not replayed', () => check(`
 for(const outcome of [503,'malformed','lost']){let requested=0,lost=0;const api=createSupportTransport({onAuthenticationLost:()=>lost++,fetchImpl:async(url)=>{if(url==='/api/auth/me')return session();if(url==='/api/csrf')return csrf();requested++;if(outcome==='lost')throw new Error('offline');return outcome==='malformed'?new Response('bad'):reply({error:'unavailable'},503);}});await assert.rejects(api.request('/api/support/conversation',{...opts,method:'POST',body:{}}),e=>e.kind==='uncertain'&&e.dispatched);assert.equal(requested,1);assert.equal(lost,0);}
`));
test('failed post-response verification retains the actual request status and uncertainty', () => check(`
 for(const method of ['GET','POST'])for(const failure of ['network','malformed','503']){let requested=0,lost=0;const status=method==='GET'?200:201;const api=createSupportTransport({onAuthenticationLost:()=>lost++,fetchImpl:async(url)=>{if(url==='/api/auth/me'){if(!requested)return session();if(failure==='network')throw new Error('offline');return failure==='503'?reply({},503):reply(null);}if(url==='/api/csrf')return csrf();requested++;return reply({ok:true},status);}});await assert.rejects(api.request('/api/support/conversation',{...opts,method,body:{}}),e=>e.kind===(method==='GET'?'unavailable':'uncertain')&&e.status===status&&e.dispatched===(method==='POST'));assert.equal(requested,1);assert.equal(lost,0);}
`));
test('generation clearing and caller cancellation discard late JSON even when fetch ignores abort', () => check(`
 for(const action of ['clear','abort']){let held,started=false;const controller=new AbortController();const api=createSupportTransport({fetchImpl:async(url)=>{if(url==='/api/auth/me')return session();return {ok:true,status:200,headers:new Headers(),json:async()=>{started=true;await new Promise(r=>held=r);return{private:'old'};}};}});const pending=api.request('/api/support/conversation',{...opts,signal:controller.signal});while(!started)await new Promise(r=>setTimeout(r,0));if(action==='clear')api.clear();else controller.abort();await assert.rejects(pending,e=>e.name==='AbortError'&&!e.dispatched);held();}
`));
test('a returned response cannot reveal JSON after the owning generation is cleared', () => check(`
 const api=createSupportTransport({fetchImpl:async(url)=>url==='/api/auth/me'?session():reply({private:'old'})});const response=await api.request('/api/support/conversation',opts);api.clear();await assert.rejects(response.json(),e=>e.name==='AbortError');
`));
test('manual cancellation remains usable during a model POST and does not claim rollback', () => check(`
 let writes=0;const controller=new AbortController();const api=createSupportTransport({fetchImpl:async(url)=>{if(url==='/api/auth/me')return session();if(url==='/api/csrf')return csrf();writes++;return new Promise(()=>{});}});const pending=api.request('/api/support/conversation/'+conv+'/messages',{...opts,signal:controller.signal,method:'POST',body:{text:'private'},timeoutMs:600000});while(!writes)await new Promise(r=>setTimeout(r,0));controller.abort();await assert.rejects(pending,e=>e.name==='AbortError'&&e.dispatched);assert.equal(writes,1);
`));
test('bounded deadlines distinguish undispatched checks from unknown writes without replay', () => check(`
 for(const afterDispatch of [false,true]){let writes=0;const api=createSupportTransport({fetchImpl:async(url)=>{if(afterDispatch&&url==='/api/auth/me')return session();if(url==='/api/csrf')return csrf();if(url.startsWith('/api/support/'))writes++;return new Promise(()=>{});}});await assert.rejects(api.request('/api/support/conversation',{...opts,method:'POST',body:{},timeoutMs:10}),e=>e.kind===(afterDispatch?'uncertain':'unavailable')&&e.dispatched===afterDispatch);assert.equal(writes,afterDispatch?1:0);}
`));
test('auth and CSRF stages retain a separate twelve-second maximum within the model budget', () => check(`
 for(const hold of ['auth','csrf']){const durations=[],original=setTimeout;globalThis.setTimeout=(fn,ms)=>{durations.push(ms);return original(fn,ms===12000?5:ms);};try{const api=createSupportTransport({fetchImpl:async(url)=>url==='/api/auth/me'&&hold!=='auth'?session():new Promise(()=>{})});await assert.rejects(api.request('/api/support/conversation',{...opts,method:'POST',body:{}}),e=>e.kind==='unavailable'&&!e.dispatched);assert.equal(durations[0],SUPPORT_MUTATION_TIMEOUT_MS);assert.ok(durations.includes(12000));}finally{globalThis.setTimeout=original;}}
`));
test('invalid ownership request and timeout options cannot reach fetch', () => check(`
 let calls=0;const api=createSupportTransport({fetchImpl:async()=>{calls++;throw new Error('must not fetch');}});for(const options of [{ownerId:'bad',role},{ownerId,role:'Attorney'},{...opts,timeoutMs:0},{...opts,timeoutMs:600001},{...opts,method:'PUT'},{...opts,method:'POST',body:null}])await assert.rejects(api.request('/api/support/conversation',options),e=>e.kind==='invalid_request');await assert.rejects(api.request('https://foreign.test/api/support/conversation',opts));assert.equal(calls,0);
`));
test('a confirmed-loss callback may clear transport without changing authentication into a generic cancel', () => check(`
 let lost=0;let api;api=createSupportTransport({onAuthenticationLost:()=>{lost++;api.clear();},fetchImpl:async()=>session({id:other})});await assert.rejects(api.request('/api/support/conversation',opts),e=>e.kind==='authentication');assert.equal(lost,1);
`));
