const {test,expect}=require('playwright/test'),path=require('node:path'),fs=require('node:fs/promises'),start=require('./real-server.cjs');
let server,cleanup;
test.beforeEach(async({context})=>{server=await start({frontendRoot:path.join(process.env.LPC_HELP_SOURCE_ROOT||path.resolve(__dirname,'../../../..'),'frontend'),onStartupCleanup:close=>cleanup=close});await context.route('**/*',route=>new URL(route.request().url()).origin===server.origin?route.continue():route.abort('blockedbyclient'));});
test.afterEach(async({page})=>{await page.close();await(server?.close||cleanup)?.();server=null;cleanup=null;});
test('managed-session browser recovery reviews and resumes only the retained provider Session; uncertainty and account changes block payment',async({page,context},testInfo)=>{
 const owner=await server.createUser(),matter=await server.seedCheckout(owner.id);await context.addCookies([owner.cookie]);
 // Ancillary Matter presentation is synthetic; funding, Checkout, authentication,
 // CSRF and financial history below use actual mounted application routes.
 await page.route(`**/api/cases/${matter.id}?**`,route=>route.fulfill({contentType:'application/json',body:JSON.stringify({_id:matter.id,title:'River Street original Checkout',status:'open',tasks:[],matterExperience:{version:1,header:{relationship:'Matter owner',status:{label:'Posted'}},sections:['overview','applications','work','files','messages','deadlines','activity','financials'].map(id=>({id})),overview:{},work:{},activity:[]}})}));
 await page.route('**/api/payments/payment-method/default?**',route=>route.fulfill({contentType:'application/json',body:'{"hasDefault":false,"paymentMethod":null}'}));
 const address=`${server.origin}/attorney-v2.html#/matters/${matter.id}/financials`,panel=page.locator('[data-workspace-funding]'),posts=[];
 page.on('request',req=>{if(req.method()!=='GET'&&req.url().includes('/api/payments/'))posts.push(req.url());});
 const before=await server.checkoutEvidence(owner.id);await page.goto(address);await expect(panel).toHaveAttribute('data-state','ready');await expect(panel).toContainText('$488.00');expect(server.providerCalls).toEqual([]);
 await panel.getByRole('button',{name:'Review original Checkout',exact:true}).click();await expect(panel.getByRole('button',{name:'Continue with Stripe',exact:true})).toBeVisible();
 const review=await(await page.request.get(`${server.origin}/api/payments/matter/${matter.id}/checkout?expectedOwnerId=${owner.id}`)).json();
 const noCsrf=await page.request.post(`${server.origin}/api/payments/matter/${matter.id}/checkout/resume`,{data:{expectedOwnerId:owner.id,reviewedRevision:review.revision}});expect(noCsrf.status()).toBe(403);
 await page.route('https://checkout.stripe.com/**',route=>route.fulfill({contentType:'text/html',body:'<title>Private synthetic Stripe destination</title>'}));await panel.getByRole('button',{name:'Continue with Stripe',exact:true}).click();await expect(page).toHaveURL(matter.session.url);expect(await server.checkoutEvidence(owner.id)).toEqual(before);
 Object.assign(matter.session,{status:'complete',payment_status:'paid',payment_intent:matter.intent.id,url:null});await page.goto(address);await expect(panel).toHaveAttribute('data-state','ready');await panel.getByRole('button',{name:'Review original Checkout',exact:true}).click();await expect(panel).toContainText('funding record has not been verified');await expect(panel.getByRole('button',{name:'Continue with Stripe',exact:true})).toHaveCount(0);expect(await server.checkoutEvidence(owner.id)).toEqual(before);
 Object.assign(matter.session,{status:'expired',payment_status:'unpaid',payment_intent:null});await panel.getByRole('button',{name:'Refresh payment status',exact:true}).click();await expect(panel).toContainText('Checkout has expired');await expect(panel.getByRole('link',{name:'Request a payment review',exact:true})).toHaveAttribute('href',`#/help?caseId=${matter.id}`);
 await server.changeMatter(matter.id,{archived:true});const changed=await server.checkoutEvidence(owner.id);await panel.getByRole('button',{name:'Refresh payment status',exact:true}).click();await expect(panel).toHaveAttribute('data-state','ready');await expect(panel.getByRole('button',{name:'Continue with Stripe',exact:true})).toHaveCount(0);
 const other=await server.createUser();await context.addCookies([other.cookie]);const denied=await page.request.get(`${server.origin}/api/payments/matter/${matter.id}/checkout?expectedOwnerId=${other.id}`);expect(denied.status()).toBe(403);await page.evaluate(()=>document.querySelector('[data-workspace-funding]')?.sync());await expect(page).toHaveURL(/\/login.html/);expect(await server.checkoutEvidence(owner.id)).toEqual(changed);
 expect(posts).toEqual([`${server.origin}/api/payments/matter/${matter.id}/checkout/resume`]);expect(server.providerCalls.every(call=>['checkout.sessions.retrieve','paymentIntents.retrieve'].includes(call))).toBe(true);
 await fs.writeFile(testInfo.outputPath('actual-checkout-recovery.json'),JSON.stringify({managedAuthentication:true,csrfMissingStatus:noCsrf.status(),foreignOwnerStatus:denied.status(),retainedSessionResumed:true,paidNotInventedAsFunding:true,expiredCannotResume:true,accountReplacementClears:true,databaseUnchangedByReviewAndResume:true,providerCalls:server.providerCalls,financialPosts:posts},null,2));
});
