const path = require('node:path');
const { test, expect } = require('../support-session-fixture');
const AxeBuilder = require('@axe-core/playwright').default;
const owner = 'a'.repeat(24), other = 'b'.repeat(24), revision = 'a'.repeat(64), proof = 'YWJj.' + 'b'.repeat(64);
const json = (route, value, status = 200) => route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});
async function setup(page, overrides = {}) {
 const model = {owner,blockers:[],writes:[],state:'active',...overrides};
 await page.route('**/api/**', async route => {
  const req = route.request(), url = new URL(req.url()), path = url.pathname;
  if (path === '/api/auth/me' && model.authFail) return json(route,{},503);
  if (path === '/api/auth/me') return json(route,{user:{id:model.owner,role:model.role||'paralegal',status:'approved',firstName:'Morgan',lastName:'Counsel',preferences:{theme:model.theme||'light',fontSize:model.fontSize||'md'},onboarding:{paralegalTourCompleted:true,paralegalProfileTourCompleted:true}}});
  if (path === '/api/users/me' && req.method()==='PATCH') {if(model.profileDelay)await model.profileDelay;model.bio=req.postDataJSON().bio||model.bio;}
  if (path === '/api/users/me') return json(route,{_id:model.owner,bio:model.bio||'',firstName:'Morgan',lastName:'Counsel',email:'synthetic@example.test',role:model.role||'paralegal',status:'approved',state:'NY',profilePhotoRevision:revision,preferences:{theme:model.theme||'light',fontSize:model.fontSize||'md'},onboarding:{paralegalTourCompleted:true,paralegalProfileTourCompleted:true}});
  if (path === '/api/account/preferences') {if(req.method()==='POST'){const value=req.postDataJSON();if(value.theme)model.theme=value.theme;if(value.fontSize)model.fontSize=value.fontSize;}return json(route,{theme:model.theme||'light',fontSize:model.fontSize||'md'});}
  if (path === '/api/payments/connect/status') return json(route,{readiness:{ready:true}});
  if (path === '/api/account/deactivate-status') return model.reviewFail ? json(route,{},503) : json(route,{ownerId:model.owner,canDeactivate:!model.blockers.length,blockers:model.blockers,closureRevision:model.revision||revision,resultProof:proof,proofExpiresAt:new Date(Date.now()+600000).toISOString()});
  if (path === '/api/csrf') {if(model.csrfFail)return json(route,{},503);if(model.switchAfterPreflight)model.owner=other;return json(route,{csrfToken:'synthetic-closure-token'});}
  if (path === '/api/account/deactivate') {
   const body = req.postData() ? req.postDataJSON() : null;model.writes.push(body);
   if (model.removeDelay) await model.removeDelay;
   if (body && body.expectedOwnerId !== model.owner) return json(route,{code:'ACCOUNT_CHANGED'},403);
   if (body && body.expectedClosureRevision !== (model.revision||revision)) return json(route,{code:'ACCOUNT_CLOSURE_CHANGED'},409);
   if(!model.keepActive)model.state = 'deactivated';if(model.lost)return route.abort('failed');return json(route,{ok:true,deactivated:true});
  }
  if (path === '/api/account/deactivate-result' && model.owner!==owner) return json(route,{code:'ACCOUNT_CHANGED'},403);
  if (path === '/api/account/deactivate-result') return model.resultFail ? json(route,{},503) : json(route,{state:model.state});
  if (path === '/api/blocks') return json(route,{items:[],nextCursor:null,total:0});
  if (path === '/api/account/2fa') return json(route,{enabled:false,method:'email',hasBackupCodes:false,sessionManaged:true,securityRevision:revision});
  if (path === '/api/account/passkeys') return json(route,{passkeys:[]});
  if (path === '/api/account/sessions') return json(route,{sessions:[],currentSession:null,nextCursor:null,total:0});
  if (['/api/notifications/stream','/api/jobs/stream'].includes(path)) return route.fulfill({status:204});
  return json(route,path==='/api/notifications/page'?{items:[],hasMore:false,nextCursor:null}:path==='/api/notifications'?[]:path.endsWith('unread-count')?{count:0}:{});
 });return model;
}
async function open(page) {await page.goto('/paralegal-v2.html#/settings?section=closure');await expect(page.locator('#v2-settings-closure')).toBeVisible();}
async function confirm(page) {await page.getByRole('button',{name:'Deactivate account',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true}).click();}
const stored = page => page.evaluate(()=>sessionStorage.getItem('lpc_account_closure_result'));
test('unavailable review cannot offer a consequential action',async({page})=>{const model=await setup(page,{reviewFail:true});await open(page);await expect(page.getByText('Account closure could not be checked. Refresh to try again.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Deactivate account',exact:true})).toHaveCount(0);model.reviewFail=false;await page.getByRole('button',{name:'Refresh closure review',exact:true}).click();await expect(page.getByRole('button',{name:'Deactivate account',exact:true})).toBeEnabled();});
test('authoritative blockers are distinct and prevent offering closure',async({page})=>{await setup(page,{blockers:[{code:'active_matters',count:1,message:'Complete your active Matter first.'},{code:'pending_payouts',count:1,message:'Wait for the pending payout.'}]});await open(page);await expect(page.getByRole('button',{name:'Deactivate account',exact:true})).toHaveCount(0);await expect(page.locator('[data-closure-blocker]')).toHaveCount(2);});
test('a lost submitted response keeps the guarded current-state check',async({page})=>{const model=await setup(page,{lost:true});await open(page);await confirm(page);await expect.poll(()=>model.writes.length).toBe(1);expect(model.writes[0]).toEqual({expectedOwnerId:owner,expectedClosureRevision:revision,resultProof:proof});await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(await stored(page)).toBeNull();});

for (const role of ['paralegal','attorney']) {
 test(`${role} pending handoff storage failure closes review and cannot replay an uncertain mutation`,async({page})=>{
  let release;const model=await setup(page,{role,lost:true,keepActive:true,removeDelay:new Promise(resolve=>release=resolve)});
  await page.goto(role==='paralegal'?'/paralegal-v2.html#/settings?section=closure':'/attorney-v2.html#/settings?tab=closure');
  await confirm(page);await expect.poll(()=>model.writes.length).toBe(1);
  await page.evaluate(()=>{window.__closureSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new Error('synthetic unavailable tab retention');};});
  release();await expect(page.getByText('The account check could not be opened. Keep this page open and try again.',{exact:true})).toBeAttached();
  await page.evaluate(()=>{Storage.prototype.setItem=window.__closureSetItem;});
  const dialog=page.getByRole('dialog');if(await dialog.count()) {const submit=dialog.getByRole('button',{name:'Deactivate account',exact:true});if(await submit.isEnabled())await submit.click();}
  await expect(dialog).toHaveCount(0);expect(model.writes).toHaveLength(1);
  const check=page.getByRole('button',{name:'Check account status',exact:true});await expect(check).toBeFocused();await expect(check).toBeInViewport();
  model.state='deactivated';await check.click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(model.writes).toHaveLength(1);
 });
 test(`${role} pending hash navigation immediately hands off without exposing another workspace route`,async({page})=>{
  let release;const model=await setup(page,{role,removeDelay:new Promise(resolve=>release=resolve)});
  await page.goto(role==='paralegal'?'/paralegal-v2.html#/settings?section=closure':'/attorney-v2.html#/settings?tab=closure');await confirm(page);await expect.poll(()=>model.writes.length).toBe(1);
  await page.evaluate(()=>{location.hash='#/home';});await expect(page).toHaveURL(/account-closure.html$/);await expect(page.getByRole('heading',{name:'Your account is currently active',exact:true})).toBeVisible();
  expect(await stored(page)).toBe(proof);release();await expect.poll(()=>model.state).toBe('deactivated');await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(model.writes).toHaveLength(1);
 });
}

test('cancel and Escape restore visible focus without retaining proof or sending closure',async({page})=>{const model=await setup(page);await open(page);const launcher=page.getByRole('button',{name:'Deactivate account',exact:true});await launcher.click();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(launcher).toBeFocused();await expect(launcher).toBeInViewport();expect(model.writes).toEqual([]);expect(await stored(page)).toBeNull();});
for(const phase of ['auth','csrf'])test(`${phase} preflight failure stays in Settings with explicit retry and no pending proof`,async({page})=>{const model=await setup(page);await open(page);await page.getByRole('button',{name:'Deactivate account',exact:true}).click();model[phase+'Fail']=true;await page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true}).click();await expect(page.getByText('Account closure could not start. Refresh the review and try again.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Refresh closure review'})).toBeFocused();expect(model.writes).toEqual([]);expect(await stored(page)).toBeNull();model[phase+'Fail']=false;await page.getByRole('button',{name:'Refresh closure review'}).click();await expect(page.getByRole('button',{name:'Deactivate account',exact:true})).toBeEnabled();});
test('unavailable initial tab retention prevents DELETE and retains a cancelable review',async({page})=>{const model=await setup(page);await open(page);await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new Error('synthetic denied storage');};});await confirm(page);await expect(page.getByRole('alert')).toHaveText('This browser could not retain the account check. Allow session storage and try again.');expect(model.writes).toEqual([]);await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeEnabled();});
test('a changed review preserves current work and requires another deliberate review',async({page})=>{const model=await setup(page);await open(page);await page.getByRole('button',{name:'Deactivate account',exact:true}).click();model.revision='b'.repeat(64);model.blockers=[{code:'active_matters',count:1,message:'Complete the newly active Matter.'}];await page.getByRole('dialog').getByRole('button',{name:'Deactivate account',exact:true}).click();await expect(page.getByText('Complete the newly active Matter.',{exact:true})).toBeVisible();expect(model.writes[0].expectedClosureRevision).toBe(revision);expect(model.state).toBe('active');expect(await stored(page)).toBeNull();await expect(page.getByRole('button',{name:'Refresh closure review'})).toBeFocused();});
test('post-preflight account replacement never exposes the earlier account outcome',async({page})=>{const model=await setup(page);await open(page);model.switchAfterPreflight=true;await confirm(page);await expect(page.getByRole('heading',{name:'Session changed',exact:true})).toBeVisible();expect(model.state).toBe('active');expect(await stored(page)).toBeNull();});
test('failed outcome confirmation retains the proof through refresh and deliberate checking',async({page})=>{const model=await setup(page,{lost:true,resultFail:true});await open(page);await confirm(page);await expect(page.getByRole('heading',{name:'Account status could not be checked',exact:true})).toBeVisible();expect(await stored(page)).toBe(proof);await page.reload();await expect(page.getByRole('button',{name:'Check again',exact:true})).toBeVisible();model.resultFail=false;await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeFocused();expect(model.writes).toHaveLength(1);expect(await stored(page)).toBeNull();});
test('pending closure survives actual document reload before the normal protected bootstrap',async({page})=>{let release;const model=await setup(page,{removeDelay:new Promise(resolve=>release=resolve)});await open(page);await confirm(page);await expect.poll(()=>model.writes.length).toBe(1);page.on('dialog',dialog=>dialog.accept());await page.evaluate(()=>{setTimeout(()=>location.reload(),0);});await expect(page).toHaveURL(/account-closure.html$/);await expect(page.getByRole('heading',{name:'Your account is currently active',exact:true})).toBeVisible();expect(await stored(page)).toBe(proof);release();await expect.poll(()=>model.state).toBe('deactivated');await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(model.writes).toHaveLength(1);});
test('an unverified storage signal hands off a pending closure without exposing the workspace',async({page})=>{let release;const model=await setup(page,{removeDelay:new Promise(resolve=>release=resolve)});await open(page);await confirm(page);await expect.poll(()=>model.writes.length).toBe(1);await page.evaluate(()=>window.dispatchEvent(new StorageEvent('storage',{key:'lpc_user',newValue:null,oldValue:'synthetic prior hint'})));await expect(page.getByRole('heading',{name:'Your account is currently active',exact:true})).toBeVisible();expect(await stored(page)).toBe(proof);await expect(page.locator('[data-v2-route-outlet]')).toHaveCount(0);release();await expect.poll(()=>model.state).toBe('deactivated');await page.getByRole('button',{name:'Check again',exact:true}).click();await expect(page.getByRole('heading',{name:'Account deactivated',exact:true})).toBeVisible();expect(model.writes).toHaveLength(1);});
test('visiting and canceling closure preserves a neighboring profile draft and existing blocked settings',async({page})=>{let release;const model=await setup(page,{profileDelay:new Promise(resolve=>release=resolve)});await page.goto('/paralegal-v2.html#/settings?tab=profile');const bio=page.getByRole('textbox',{name:'Bio',exact:true});await bio.fill('A retained profile draft while reviewing closure.');await page.evaluate(()=>{location.hash='#/settings?section=closure';});await page.getByRole('button',{name:'Deactivate account',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('heading',{name:'Blocked users',exact:true})).toBeVisible();await page.getByRole('tab',{name:'Profile',exact:true}).click();await expect(bio).toHaveValue('A retained profile draft while reviewing closure.');release();expect(model.writes).toEqual([]);});

test('closure content and confirmation remain usable in actual dark XL preferences narrow layout and doubled text',async({page},info)=>{
 await setup(page);await open(page);await page.getByRole('tab',{name:'Preferences',exact:true}).click();await page.getByRole('radio',{name:'Dark',exact:true}).click();await expect(page.locator('[data-preference-status]')).toContainText('Appearance saved');await page.getByLabel('Font size',{exact:true}).selectOption('xl');await expect(page.locator('[data-preference-status]')).toContainText('Reading size saved');await page.evaluate(()=>{location.hash='#/settings?section=closure';});
 const card=page.locator('.pv2-closure');await expect(card.getByRole('button',{name:'Deactivate account',exact:true})).toBeEnabled();const measurements=[];
 for(const width of [1366,390,320]) {
  await page.setViewportSize({width,height:900});if(width===320)await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});
  await card.scrollIntoViewIfNeeded();expect(await card.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);expect((await new AxeBuilder({page}).include('.pv2-closure').analyze()).violations).toEqual([]);await page.screenshot({path:info.outputPath(`closure-dark-xl-${width}.png`)});
  const launcher=card.getByRole('button',{name:'Deactivate account',exact:true});await launcher.focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog');const cancel=dialog.getByRole('button',{name:'Cancel',exact:true}),submit=dialog.getByRole('button',{name:'Deactivate account',exact:true});await expect(cancel).toBeFocused();await expect(cancel).toBeInViewport();await page.keyboard.press('Tab');await expect(submit).toBeFocused();await expect(submit).toBeInViewport();await page.keyboard.press('Tab');await expect(cancel).toBeFocused();
  const geometry=await dialog.evaluate(el=>{const r=el.getBoundingClientRect(),target=document.activeElement.getBoundingClientRect();return {width:innerWidth,left:r.left,right:r.right,overflow:el.scrollWidth>el.clientWidth+1,focusLeft:target.left,focusRight:target.right,paragraphFont:getComputedStyle(el.querySelector('p')).fontSize};});measurements.push(geometry);expect(geometry.left).toBeGreaterThanOrEqual(0);expect(geometry.right).toBeLessThanOrEqual(width);expect(geometry.overflow).toBe(false);expect(geometry.focusLeft).toBeGreaterThanOrEqual(0);expect(geometry.focusRight).toBeLessThanOrEqual(width);expect((await new AxeBuilder({page}).include('dialog').analyze()).violations).toEqual([]);await page.screenshot({path:info.outputPath(`closure-confirm-dark-xl-${width}.png`)});await page.keyboard.press('Escape');await expect(launcher).toBeFocused();await expect(launcher).toBeInViewport();
 }
 await info.attach('closure-geometry',{body:JSON.stringify(measurements,null,2),contentType:'application/json'});
});

test('Attorney close returns visible focus after an offscreen doubled-text confirmation',async({page},info)=>{
 await setup(page,{role:'attorney',theme:'dark',fontSize:'xl'});await page.goto('/attorney-v2.html#/settings?tab=closure');await expect(page.getByRole('button',{name:'Deactivate account',exact:true})).toBeEnabled();await page.setViewportSize({width:320,height:600});await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});const launcher=page.getByRole('button',{name:'Deactivate account',exact:true});await launcher.click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeInViewport();await page.keyboard.press('Escape');await expect(launcher).toBeFocused();await expect(launcher).toBeInViewport();expect(await launcher.evaluate(el=>{const r=el.getBoundingClientRect();return document.elementFromPoint(r.left+r.width/2,r.top+r.height/2)===el;})).toBe(true);await page.screenshot({path:info.outputPath('attorney-closure-focus-dark-320-200.png')});
});
